### ISSUE TITLE
Incorrectly typed code compiles without error (deleting record field)

### ISSUE THREAD

**Issue by Dobiasd** [elm-lang/elm-compiler#1000]
The following code should not compile, but it does (for example on http://elm-lang.org/try).

    import Graphics.Element

    type alias Thing = {
        foo : Int
      , bar : String
      }

    main : Graphics.Element.Element
    main = scene (Thing 0 "")

    scene : Thing -> Graphics.Element.Element
    scene thing =
        let notAThing = { thing - foo }
            barFromThing = thing.bar
            brokenFoo = getFooFromThing notAThing -- This should not compile.
        in  Graphics.Element.show brokenFoo

    getFooFromThing : Thing -> Int
    getFooFromThing thing = thing.foo

**Comment by evancz** [comment]
This should go away if #985 happens. But I would assume this is a problem with the constraint generation for this syntactic construct.

**Comment by evancz** [comment]
Okay, this is removed in the master branch, so it should be solved by no longer existing :)
