### ISSUE TITLE
Touches positions are Floats on Android

### ISSUE THREAD

**Issue by robertjlooby** [elm-lang/elm-compiler#1001]
If I write a small program that just shows `Touch.touches`, it displays `x`/`y`/`x0`/`y0` as `Int`s on my laptop (Chrome browser, OSX) (as they are in [the documentation](http://package.elm-lang.org/packages/elm-lang/core/2.1.0/Touch)). I had someone try with an iPhone with Safari and Chrome and they reported `Int`s as well. However, when I view it on my phone (Chrome browser, Android) they display as `Float`s.

Here is an example [http://share-elm.com/sprout/55b299bee4b06aacf0e8b6f4](http://share-elm.com/sprout/55b299bee4b06aacf0e8b6f4)

**Comment by mgold** [comment]
Well, we could change the API... or liberally sprinkle `Math.round` in [this file](https://github.com/elm-lang/core/blob/master/src/Native/Touch.js).

**Comment by evancz** [comment]
Is there a W3C spec that says what it really should be? If so, are there issues open about Chrome on Android about becoming compliant? Or on the other browsers about getting more accurate?

**Comment by TheSeamau5** [comment]
From the [W3C spec](http://www.w3.org/TR/touch-events/#touch-interface):

```webidl
interface Touch {
      readonly    attribute long        identifier;
      readonly    attribute EventTarget target;
      readonly    attribute long        screenX;
      readonly    attribute long        screenY;
      readonly    attribute long        clientX;
      readonly    attribute long        clientY;
      readonly    attribute long        pageX;
      readonly    attribute long        pageY;
  };
```

No floats or doubles to be seen. Only longs. So, yeah, probably a Chrome bug.

**Comment by doshitan** [comment]
A draft of the v1-errata ([which will not be published](https://github.com/w3c/touch-events/issues/24#issue-97751613)) for touch events changed them to doubles. The current draft for [v2 of touch events](https://w3c.github.io/touch-events/touchevents.html#touch-interface) incorporates the changes from v1-errata and looks like:

```webidl
interface Touch {
    readonly    attribute long        identifier;
    readonly    attribute EventTarget target;
    readonly    attribute double      screenX;
    readonly    attribute double      screenY;
    readonly    attribute double      clientX;
    readonly    attribute double      clientY;
    readonly    attribute double      pageX;
    readonly    attribute double      pageY;
    readonly    attribute float       radiusX;
    readonly    attribute float       radiusY;
    readonly    attribute float       rotationAngle;
    readonly    attribute float       force;
};
```

See the [Chromium issue where they implemented the change](https://code.google.com/p/chromium/issues/detail?id=379150) for some links and discussion about the change. [Announcement of Chrome switching](https://plus.google.com/+RickByers/posts/FEnpGkqjE8x).

I did a little searching on Mozilla's Bugzilla, but couldn't find anything related to sub-pixel touch events, the errata or v2 of the spec.

**Comment by evancz** [comment]
Alright, moving to https://github.com/elm-lang/core/issues/322, thanks for reporting this!

**Comment by RByers** [comment]
As the one that drove that change to Touch Events (and an API owner in Blink reviewing/approving other API changes), I'd love to hear details of how this change caused problems for you.  The compatibility of web API changes is typically evaluated almost entirely in the context of JavaScript.  I personally worry about the impact on strongly-typed programming languages of such thinking.  Hopefully web programming isn't destined to mostly be weakly typed forever ;-)
