### ISSUE TITLE
Delay introduces gliches:

### ISSUE THREAD

**Issue by phadej** [elm-lang/elm-compiler#1003]
Example code:

```elm
import Graphics.Element exposing (..)
import Mouse
import Time

f : () -> () -> ()
f a b = ()

b : Signal ()
b = Time.delay 200 Mouse.clicks

c : Signal ()
c = Time.delay 100 (Time.delay 100 Mouse.clicks)

foo : Signal ()
foo = Signal.map2 f c b

bar : Signal Int
bar =
  Signal.foldp (\click total -> total + 1) 0 foo

main : Signal Element
main =
  Signal.map show bar
```

`b` and `c` are semantically equivalent. Yet this code distinguish them: `bar` is updated by two each click.

**Comment by staltz** [comment]
I guess the glitch culprit here is `map2`, not `Time.delay`. That said, I'm fine with these types of glitches, dealing with these cases is a matter of choosing the right mental model.

**Comment by mgold** [comment]
Yup - you can define `c` exactly the same way as `b` and still only get even numbers. They update asynchronously but imperceptibly close to one another (that would be the right mental model), and for a short time `bar` has an odd value. It's just that the interval is imperceivable, or perhaps so small as to not even be rendered.

**Comment by staltz** [comment]
> They update asynchronously but imperceptibly close to one another (that would be the right mental model), and for a short time bar has an odd value. It's just that the interval is imperceivable, or perhaps so small as to not even be rendered.

That's pretty much the definition of a glitch. http://soft.vub.ac.be/Publications/2012/vub-soft-tr-12-13.pdf

**Comment by phadej** [comment]
So `Time.delay 0 signal ≠ signal`, is that documented somewhere? Both way (equal and inequal) make (some) sense. 

Yet I'd prefer to be them to be equal. I'm not sure how, but it feels that order of definitions could be observable. That ruins refactorability (if that is a word).

**Comment by staltz** [comment]
@phadej the same glitch you documented also happens with this:
```elm
b : Signal ()
b = Time.delay 200 Mouse.clicks

c : Signal ()
c = Time.delay 200 Mouse.clicks
```

**Comment by staltz** [comment]
OTOH

Glitches:
```elm
b : Signal ()
b = Mouse.clicks

c : Signal ()
c = Time.delay 0 Mouse.clicks
```

Does not glitch:
```js
b : Signal ()
b = Mouse.clicks

c : Signal ()
c = Mouse.clicks
```

Not good, since you can't think about them in the same way.

**Comment by mgold** [comment]
This is clearly not a cut-and-dry bug, so please take this discussion to the [mailing list](https://groups.google.com/forum/#!forum/elm-discuss).

**Comment by phadej** [comment]
https://groups.google.com/forum/#!topic/elm-discuss/1Z5xvqr0uY4

**Comment by evancz** [comment]
I don't think there is a clear resolution here, so I am going to close for now. Going towards `Task.sleep` gets the same functionality on a nicer foundation, so perhaps that'll be the move longer term.
