### ISSUE TITLE
Unfinished sentence in Haddocks for getAsset

### ISSUE THREAD

**Issue by MaxGabriel** [elm-lang/elm-compiler#1005]
The sentence describing [getAsset](http://hackage.haskell.org/package/elm-compiler-0.15/docs/Elm-Utils.html) appears to be unfinished. The docs say:

> Get the absolute path to a data file. If you install with cabal it will look

I think there's supposed to be something after "will look"

**Comment by evancz** [comment]
Thanks for the report! Based on [this discussion](https://groups.google.com/forum/#!searchin/elm-discuss/hackage$200.15.1/elm-discuss/qB0BwwfMTjA/etL1dMaUCQAJ), my feeling is that it's unclear how much more we want to support that release avenue.

Do you mind searching the history around [this line](https://github.com/elm-lang/elm-compiler/blob/master/src/Elm/Utils.hs#L97) to see if that sentence *ever* made sense? Perhaps not :) If so, do you mind doing a PR to fix it?

**Comment by MaxGabriel** [comment]
It looks like that documentation was added in [this commit](https://github.com/elm-lang/elm-compiler/commit/10a84b4d6c2db10ed8536d2473097d6906a1d081)—and hasn't changed since.

**Comment by evancz** [comment]
Thanks for the report, should be fixed!
