### ISSUE TITLE
Compiler reports error without respecting --report=json flag

### ISSUE THREAD

**Issue by dnalot** [elm-lang/elm-compiler#1006]
I was testing [Sublime build integration](https://github.com/dnalot/Elm.tmLanguage/blob/build/elm_make.py) against Hassan's [checkerboard demo](https://github.com/TheSeamau5/elm-checkerboardgrid-tutorial). I moved `Counter.elm` to `widgets/Counter.elm`. Instead of returning JSON `elm-make` fed back plain text. I'm working around it in my error parser. On an aside I'm also confused why the compiler can't find the module there. Here's the generated command:
```bash
elm-make Main.elm --output=build/Main.html --report=json --yes
```

**Comment by evancz** [comment]
In the `elm-package.json` file, is `widgets/` listed under `source-directories`? If not, it can't know to look there. If you just search arbitrary subtrees, you may be following symlinks and such. Does not seem like a better design.

**Comment by dnalot** [comment]
Then why does it work on the site? There's only [one directory linked](https://github.com/elm-lang/package.elm-lang.org/blob/master/elm-package.json#L7) but [with nested subfolders](https://github.com/elm-lang/package.elm-lang.org/tree/master/frontend).

In any case the primary issue is that the compiler ignores the JSON flag causing my parser in Sublime to error out.

**Comment by dnalot** [comment]
PS `'.'` [is listed under](https://github.com/TheSeamau5/elm-checkerboardgrid-tutorial/blob/master/AfterModifications/elm-package.json#L7) `source-directories`.

**Comment by evancz** [comment]
The website has a build process in the Haskell files to make sure everything you need is around.

This should be an `elm-make` issue, so let's migrate this over there. When you open the new issue, please show a minimal reproduction of the issue (not a github repo) with the command that you ran, the result of that command, and the expected result of that command. That'll make it easier to see exactly what is going on without doing a lot of digging.

**Comment by dnalot** [comment]
The issue was caused by moving files. How do I show that without a repo?

**Comment by dnalot** [comment]
Also you're Haskell build process is the key user indicator why we want to search subtress. Because any moderately sized program needs it.

**Comment by evancz** [comment]
Is the fact that the file moved actually matter? As I understand, the file is just in a place that is not recognized. That can happen whether it was moved or put there initially. It is possible that I am not understanding the root issue though, and for me to do that, it's hard to start with a repo.

**Comment by dnalot** [comment]
Oh true it could just be a missing module. I'll try that!

**Comment by dnalot** [comment]
Ah I bet @ajhager found this the same way as me. CC elm-lang/elm-make#26
