### ISSUE TITLE
account for non-keyword names that are treated specially by JS

### ISSUE THREAD

**Issue by TheSeamau5** [elm-lang/elm-compiler#1010]
The following code:

```elm
d = {}
test = 
  { d | toString = "" }
```

Causes the following runtime crash

```
undefined is not a function


Open the developer console for more details.
```

This is due to the fact that the name of the record field is "toString". It happens that Elm records generate JS objects and JS objects come pre-packaged with a number of properties (which seem like they can't be overwritten).

From an analysis of the objects generated by Elm, it would seem that the solution would be to special case the following identifiers (perhaps consider them as JS keywords):

- constructor
- hasOwnProperty
- isPrototypeOf
- propertyIsEnumerable
- toLocaleString
- toString
- valueOf

Note that you can replace the toString field with any of these identifiers and the crash will remain. 

See https://github.com/elm-lang/elm-compiler/issues/897 for more details.

**Comment by evancz** [comment]
Does this only happen with record extension? Or just using the record? Or updating?

**Comment by evancz** [comment]
My testing shows it is only for record extension, which no longer exists. So I am going to close this. Definitely reopen with further details if I have not assessed thing properly!
