### ISSUE TITLE
Generated JS resolves scope in a weird way, resulting in a crash

### ISSUE THREAD

**Issue by zeckalpha** [elm-lang/elm-compiler#1012]
Definition order matters in an unexpected way for mutually recursive declarations.

Here's an example: http://share-elm.com/sprout/55c4da64e4b06aacf0e8bcfe

By switching main's definition, you'll cause a crash. This seems to be due to how JS scope works, but we've not narrowed down a good fix. There's some more discussion in Dandandan/parser#15.

**Comment by zeckalpha** [comment]
Sorry for the vagueness in the description! Hopefully the example is clear.

**Comment by jdavidberger** [comment]
Sorry, I should have linked this back in the thread on the parser page. This was discussed and closed in https://github.com/elm-lang/elm-compiler/issues/999, which was a duplicate of https://github.com/elm-lang/elm-compiler/issues/873.

**Comment by evancz** [comment]
If I understand correctly, this will be fixed by #873, so let's follow along there!

**Comment by zeckalpha** [comment]
Great! Thanks!

**Comment by evancz** [comment]
No problem, thanks for reporting!
