### ISSUE TITLE
built-in typeclasses don't get replaced by the actual type like normal type variables

### ISSUE THREAD

**Issue by Apanatshka** [elm-lang/elm-compiler#1013]
Another issue to be aggregated in #1008?

Observe:

```
$ elm-repl
> f1 = (<)
<function> : comparable -> comparable -> Bool
> f2 = (<) 1
<function> : comparable -> Bool
> f2 "a"
As I infer the type of values flowing through your program, I see a conflict
between these two types:

    comparable

    String
```
**Expected behaviour**: `f2 : number -> Bool` (or perhaps `Int`, I don't know exactly what the compiler does there). 

Original data comes from [this StackOverflow question](http://stackoverflow.com/q/31885622/859279).

**Comment by evancz** [comment]
Thanks for describing this. Seems separate from #1008, looks like a bug instead. It is closer to #880 which seems to stem from the same code.

I suspect the root issue arises from [this function](https://github.com/elm-lang/elm-compiler/blob/bc4825d7b5b5d1b64fee5c9032847fd12161b4fe/src/Type/Unify.hs#L385-L423) or from [this section](https://github.com/elm-lang/elm-compiler/blob/bc4825d7b5b5d1b64fee5c9032847fd12161b4fe/src/Type/Unify.hs#L179-L203). If someone could take a look, it may not be too crazy to find the root issue here.

**Comment by evancz** [comment]
Alright, this is resolved on the `type-fixes` branch which I am currently merging into master. So it'll be out with 0.16 and I'll try to do an alpha soon. Here's what I'm seeing now:

```
$ elm-repl
---- elm repl 0.16.0 -----------------------------------------------------------
 :help for help, :exit to exit, more at <https://github.com/elm-lang/elm-repl>
--------------------------------------------------------------------------------
> (<)
<function> : comparable -> comparable -> Bool
> isNegative n = n < 0
<function> : number -> Bool
> isPositive = (<) 0
<function> : number -> Bool
> 
```
