### ISSUE TITLE
Allow preprocessor directives in GLSL shader blocks

### ISSUE THREAD

**Issue by nphollon** [elm-lang/elm-compiler#1015]
I would like to make use of WebGL's [frag depth extension](https://www.khronos.org/registry/webgl/extensions/EXT_frag_depth/) in my code. In Elm, the syntax for this would look like

    fragmentShader = [glsl|
      #extension GL_EXT_frag_depth : require
      ...
    |]

There are a few additional preprocessor directives for GLSL. Unfortunately, the Elm compiler throws an error if I try to begin a line with `#`.

The syntax works fine with `WebGL.unsafeShader`, but it would be nicer to be able to use a shader block instead.

**Comment by evancz** [comment]
We rely on https://hackage.haskell.org/package/language-glsl to parse the GLSL code and get out the information we need. I think they'd have to add support for this there.

**Comment by evancz** [comment]
Have you tried asking them about it on their github repo? Should we close this? What's up?

**Comment by nphollon** [comment]
Looks like there is already [an issue open](https://github.com/noteed/language-glsl/issues/4) on their repo, although it's been dormant for over a year. I will try to get it fixed on their end. Thanks for your help!
