### ISSUE TITLE
Records and aliases

### ISSUE THREAD

**Issue by archaeron** [elm-lang/elm-compiler#1019]
shouldn't this compile 

```elm
type alias A = { a : String }

type alias B = A

bar : B
bar = B "Hello"
```

because I find writing this counter intuitive:

```elm
type alias A = { a : String }

type alias B = A

bar : B
bar = A "Hello"
```

**Comment by mgold** [comment]
What you're getting at is that record constructors aren't created recursively. If you replace the last line with `bar = {a = "Hello"}` then it works. It might be possible to add this feature though. Having isolated the problem with a minimal example, is there a real-world use case where this would be needed?

**Comment by archaeron** [comment]
Hello, thanks for replying.
It isn't strictly speaking needed.
It's just a bit confusing that you have to know what the alias points to, to be able to create a value of that type.
And I'd make the type alias to make it clear that a function takes a value of a certain type. But then I'd have to give the other type for it to function.

```elm
type alias A = { a : String }

type alias B = A

takesB : B -> String
takesB b = "I take a B: " ++ b.a

takesB (A "I was made with the A constructor")
```

**Comment by evancz** [comment]
Essentially, constructors are made in the specific case that you are creating a record type alias. These things are all aliases, so there is no such thing as "type `A` and type `B`" they are just aliases for the real type which is `{ a : String }`.

We have had other issues about how the current thing is kind of confusing. I have a idea about how to make this more uniform, but I'm not sure what the timeline will be on getting that out.

**Comment by archaeron** [comment]
Fair enough :+1:
