### ISSUE TITLE
Cannot access fields of a record with an import qualifier

### ISSUE THREAD

**Issue by rhaps0dy** [elm-lang/elm-compiler#1020]
The following fails to compile:

```elm
-- File: Module.elm
module Module ( record ) where

record : { field : String }
record = { field = "Hello, World!" }


-- File: Main.elm
module Main ( main ) where

import Graphics.Element as Element
import Module

main : Signal Element.Element
main = Signal.constant <| Element.show Module.record.field
```

because of the `Module.record.field` in the end.

**Comment by jvoigtlaender** [comment]
Have you checked there's no other issue open about this already?

**Comment by rhaps0dy** [comment]
I did. I read the titles of all the issues and didn't find one referencing this. Two weeks ago, and now.

However, I may have missed something.

**Comment by jvoigtlaender** [comment]
Look at https://github.com/elm-lang/elm-compiler/issues/520.

**Comment by rhaps0dy** [comment]
Oops. :(

Sorry
