### ISSUE TITLE
Compiler error for duplicated names should tell you the lines for all the variables

### ISSUE THREAD

**Issue by rhaps0dy** [elm-lang/elm-compiler#1022]
This is really low priority. But consider the following code:

```elm
module Main ( main ) where

import Graphics.Element as Element

value : String
value = "first"

main : Signal Element.Element
main = Signal.constant <| Element.show value

value : String
value = "second"
```

The compiler error thrown has a really good explanation, but it only shows the location of the second definition of 'value'. It would be great if it showed several of them.

**Comment by jvoigtlaender** [comment]
Maybe better fit for this repo: https://github.com/evancz/error-message-catalog

**Comment by rhaps0dy** [comment]
Yes, thank you. Submitting pull request now!
