### ISSUE TITLE
finding unambiguous names for generated code

### ISSUE THREAD

**Issue by evancz** [elm-lang/elm-compiler#1025]
In #1024 we are planning to map Elm values like `Basics.fst` onto `elm-lang$core$Basics$fst` in the generated JavaScript. The problem is that you cannot have a hyphen in there. So the question is, **how can we change unusable characters but keep the names canonical?**

It looks like github does not allow underscores in user names. I am not certain about repo names though. [This](http://www.quora.com/Why-doesnt-GitHub-allow-underscores-or-spaces-in-repository-names) suggests that you can't use underscores anywhere. Though repos like [this](https://github.com/owncloud/files_texteditor/issues/3) suggest otherwise. Maybe that is historical. **Can someone test if they can make accounts or repos with underscores today?**

Ideas so far:

  * Map `-` to `_`. Hope it works.
  * Map `-` to `_`. Have elm-package reject packages with underscores in the user/repo name.
  * Map `-` onto something crazy from [here](https://mathiasbynens.be/notes/javascript-identifiers).
  * Map hyphens to `$`. Use some other character to separate chunks of the name.
  * Since there will be a known set of packages in a build, turn them into a number. (Pain in the ass)

One thing to think about here is that some Elm variables end up having a `$` in them for various reasons (e.g. it is a reserved word in JS, it uses a prime). I think that will not cause issues though. It should not be possible to have a variable name that makes the prefix before it ambiguous.

**Comment by JoeyEremondi** [comment]
Just tried it: `_` is not allowed in a username, but is allowed in repo names.

I just went through the number keys, and it looks like basically any special characters are allowed in repository names.

Since we're only restricting repo names, which can be easily changed, we could just restrict that a published elm package can't contain special characters other than `-`, and then just map `-` to `_`

**Comment by laszlopandy** [comment]
I agree. Disallow underscore or dollar signs in package names. Allowing
them would make the package list really ugly anyway. Dashes are nice.

**Comment by rtfeldman** [comment]
+1 for disallowing underscore or dollar signs in package names.

The "mandate sane package names" thing seems like a very Elm thing to do. If there's going to be a "this is not a legal package name" checker, might I suggest some simple checks to make sure nobody ever makes the `--look---at----meeee--` package:

1. The only allowed characters are letters, numbers, and dashes.
2. Packages must begin and end with a letter.
3. Two consecutive dashes is disallowed.

**Comment by rtfeldman** [comment]
Relatedly, if this isn't already a check (I haven't attempted it but don't want to push a bad package if it's currently allowed), package names should be reserved on a case-insensitive basis.

In other words, if I try to publish both `rtfeldman/elm-foo` and `rtfeldman/Elm-Foo`, that should be an error.

**Comment by mgold** [comment]
+1 to everything Richard said.

**Comment by Apanatshka** [comment]
> Relatedly, if this isn't already a check (I haven't attempted it but don't want to push a bad package to find out), package names should be reserved on a case-insensitive basis.

If we're going there, we might as well say all names should be lower case and use dashes instead of camel case. Which I'm fine with by the way.

**Comment by sindikat** [comment]
+1 to **Apanatshka**: force package authors to name with lowercase only (in addition to what **rtfeldman** said).

**Comment by evancz** [comment]
Thanks for the input everyone! I will do these things.
