### ISSUE TITLE
Proposal: Accessor magic for union types -- @UnionTypeTag : SuperType -> Maybe SubType

### ISSUE THREAD

**Issue by rgrempel** [elm-lang/elm-compiler#1030]
To cut to the chase, this proposal would be to add some compiler magic, roughly analogous to the existing magic that turns `.property` into `{ b | property : a } -> a`, or which creates `Record : String -> Record ` from `type alias Record = { property : String }`.

The new magic would do something like this:

```elm
-- Given a type like this
type SuperType
    = SubTag1 SubType1
    | SubTag2 SubType2

-- You could then write something like this:
    @SubTag1 supertype

-- or like this:
    supertype@SubTag1

-- and the compiler would behave as if the following function had been magically defined
@SubTag1 : SuperType -> Maybe SubType1
```

Before providing the rationale, let me say that I'm not asking anyone to implement this -- I'd be happy to do it myself. However, it's not really useful (even to me) unless it might actually be accepted into the master compiler repository. So, it seems to me that it would be wise to propose the idea before writing the code. (Note that I'll explain below why this needs to be compiler magic and cannot -- as a general case -- be done in a library).

Here's the rationale -- first, the motivating example, and then a more theoretical justification.

**Motivating Example**

It is a very common Elm idiom to construct a union type which, in turn, tags union types from lower-level modules, and so on. E.g.

```elm
type Action
    = Module1 Module1.Action
    | Module2 Module2.Action
    | Module3 Module3.Action
```

Note that I'm using Action as an example here, but the proposal isn't tied to 'actions' in particular.

One would then typically pattern-match in order to use such a type ... in fact, the `case` statement is about the only way you can use such a type. E.g.:

```elm
update : Action -> Model -> Model
update action model =
    case action of
        Module1 subaction ->
            Module1.action subaction model

        Module2 subaction ->
             Module2.action subaction model

        Module3 subaction ->
             Module3.action subaction model
```

Now, I have found that there are cases where I want the lower-level module to take the equivalent of a `Maybe Action` rather than an `Action`. That is, instead of dispatching to **just one** of the lower-level modules, I want to dispatch to **each** of them (aggregating the results in some way), and I want to let each lower-level module either receive the sub-type it knows about, or Nothing.

To imagine a non-contrived example, consider this. You are generating the HTML for a web page, which you've divided into many 'virtual pages' (i.e. you show only one part of the whole model at a time) to be generated by various sub-modules. You want a menu at the top of the page to allow the user to switch from one 'virtual page' to another. The bulk of the page is generated in your `view` method by dispatching to just one sub-module (depending on what virtual page we're on). However, to construct the menu, you need to dispatch to **every** sub-module (to let each sub-module draw its own menu item), and then aggregate the results. In addition, you'd like to let the sub-module's `menu` method know something about its own typed data, but only if it is the current virtual page ... e.g. so it can draw itself differently if it is the active virtual page. (Or do whatever else might depend on its own typed data).

To do this efficiently, I end up writing little functions that take this form:

```elm
maybeSubType : SuperType -> Maybe SubType
maybeSubType supertype =
    case supertype of
        SubTag subtype -> Just subtype
        _ -> Nothing
```

So, I end up with one of these little functions per tag. Which works, but is tedious to write. So, I naturally considered ways to reduce the tedium.

**Implementing as a Native Function**

I considered writing a native function of this form:

```elm
specialize : (a -> b) -> b -> Maybe a

-- Which you could call like
--    specialize SubTag supertype
```

This would have taken advantage of the fact that the SubTag is, in fact, a function which takes the subtype and returns the supertype.

However, it turns out that this doesn't work. The reason is that when you try to implement this, what your native function actually gets as its first parameter is actually a function -- let's call it the 'tagging function'. Now, you can see the second parameter's ctor property, so that's fine. But, you don't know what ctor property the tagging function will actually produce. So, you can't test if they match ... that is, you can't test whether the second parameter was produced using the first parameter.

Now, there are a couple of possible workarounds. You could call the tagging function with arbitrary parameters and see what ctor it produces. You could call `toString` on the function and parse its source. You could take a `String` as the first parameter and rely on the compiler's mapping from tags to ctor. But those are all way too hackish, even with my moderately high tolerance for hackishness. 

**Implementing via compiler magic**

However, it should be possible to modify the compiler, so that when it sees:

```elm
@SubTag supertype

-- and, for extra bonus magic
supertype@SubTag
```

... it behaves as though the following function were defined ...

```elm
@SubTag : SuperType -> Maybe SubType
@SubTag supertype =
    case supertype of
        SubTag subtype -> Just subtype
        _ -> Nothing
```

And, I would propose doing this in a zero-cost way if you don't use it. That is, unless you actually use a `@SubTag` in your code, the complier wouldn't emit anything extra. (And, again, I'm not asking anyone to implement this for me -- would be glad to do it myself).

**Theoretical Justification**

Now, you may or may not have found my motivating example to be convincing. There would, after all, be other ways to accomplish the particular example. And, even if you did find the example convincing, you may wonder why *this particular* compiler magic makes sense -- since, obviously, there are tons of little bits of syntax that could be added to make the compiler do one thing or another, and one would have to be pretty selective about adding them.

So, here is my stab at theoretical justification.

It seems to me that this bit of compiler magic would reproduce, for union types, some of the compiler conveniences we already have for extensible records.

Consider what would happen if the SuperType in my example were an extensible record, rather than a union type. In that case, there are two interesting differences.

First, the supermodule can probably pass a record type directly to the submodule's methods without any particular pre-processing, since that is what extensible records are for -- your supertype satisfies the subtype. With union types, you'll need *some* preprocessing inevitably, since the union type, by definition, is either one subtype or the other (not both at the same time, which is what the extensible record in effect is). However, wouldn't it be nice, in theory, to make that preprocessing as compact as possible? Wouldn't that reproduce, as much as possible, for union types, some of the convenience of record types?

Now, of course, if your code genuinely is branching based on the subtype, then manually writing out the case statement is always going to be more efficient. However, as noted above, sometimes you're not really branching -- that is, sometimes you're inevitably supplying `Just subtype` or `Nothing`, so it's nice to be able to do so compactly.

Furthermore, a bare reference to `@SubTag` by itself would simply be a function of the form `SuperType -> Maybe SubType`. That function can, in turn, be a parameter to another function. This would enable certain interesting types of composition of functions.

Second, the compiler magic for records goes in **both directions**, so to speak. That is, there is compiler magic for **constructing** a record, but there is also compiler magic for **pulling things out of records.** That is, there is compiler magic which creates `Record : String -> Record `from `type alias Record = { property : String }` -- that is the 'constructor' magic. But, there is also 'accessor' magic, which turns
`.property` into `{ b | property : a } -> a`.

The new magic proposed here is essentially 'accessor magic for union types'. Union types already have the 'constructor magic', since the tag is a function which constructs the supertype. But they have no accessor magic -- you have to write the case statement yourself. Now, if you think to yourself 'what would accessor magic be for a union type?', it necessarily takes the form `SuperType -> Maybe SubType` ... since, after all, the whole point of the SuperType is that it *may be* one sub-type or another.

So, I would suggest that in addition to the practical uses for such compiler magic, there is a kind of theoretical inevitability to it -- it's what you end up with if you start with the idea of 'accessor magic for union types', just like we have accessor magic for record types.

**Tags with multiple arguments**

I should note that so far my examples have all assumed that the tags take just one type. What if they take two or more? Or zero? Consider:

```elm
type SuperType
    = SubType0
    | SubType2 Int String
    | SubType3 String String String
```

In that case, the magic accessor functions would need to take this form:

```elm
@SubType0 : SuperType -> Maybe ()

@SubType2 : SuperType -> Maybe (Int, String)

@SubType3 : SuperType -> Maybe (String, String, String)
```

Now, this may complicate the implementation to a degree (that is, it may complicate the changes to the compiler needed to produce this magic), but I think the general idea remains sound.

**Question**

So, I guess my question is whether this seems like something which, if implemented, might be accepted into the compiler? I'm happy to work on implementation, but it's of no use to me if it will be inevitably rejected. Well, I suppose I can rely on private compiler modifications in code that I don't intend to publish, but I mostly intend to publish it all, and you can't really go around asking people to install compiler variants to use your code :-)

**Comment by laszlopandy** [comment]
Cool idea. But my first thought was that `SubTag1?` would have the type:
`SubTag1? : SuperType -> Bool`
In the same way that Haskell's `isJust` and `isNothing` return a bool. My intuition is that the question mark implies there should be a yes or no answer. Your maybe magic would be surprising for me if I came across it in code.

**Comment by rgrempel** [comment]
I see what you mean. But if it returns a `Bool`, then one is still left manually writing some kind of case statement to extract the *value* of the subtype. So, I think the type is correct -- the question is whether `SubTag1?` is the appropriate syntax -- that is, whether to appropriate the question mark for this task, or use something else.

That is, one could imagine the syntax being one of these instead (amongst many, many others):

```elm
SubTag1^ 
SubTag1<>
SubTag1@
@SubTag1
```

Actually, now that I look at it, I'm sort of partial to the last one there -- it kind of reads sensibly -- so the magic function signature would be:

```elm
@SubTag1 : SuperType -> Maybe SubType

-- used like this
@SubTag1 supertype
```

On the question of appropriating punctuation, this proposal would mean that whatever punctuation one chose would be partly appropriated from other uses. However, this would only be when it is put at the end (or, the beginning) of something that could be a tag name. So I don't think it is a big problem -- that is, I don't think it would interfere with parsing other typical uses of a question mark (or whatever punctuation is chosen) -- but it is a consideration.

**Comment by rgrempel** [comment]
In fact, I like the prefixed @ so much better than the postfixed ? that I've changed my initial post to adopt it. Thanks, @laszlopandy

**Comment by Apanatshka** [comment]
1. Good idea, these are useful functions that can be generated
2. Not sure if this warrants extra syntax. Can't you prefix the tag name with something and generate that as a normal function?
3. This is a step towards first-class pattern-matching. I think first-class pattern matching is a neat idea, but not sure if such a thing would fit Elm though. ([Haskell package](https://hackage.haskell.org/package/first-class-patterns), [publication the package is based on](https://web.archive.org/web/20140908044209/http://www.itu.dk/people/mir/typesafepatterns.pdf), [simpler approach](www.cs.yale.edu/homes/tullsen/patterns.ps))

**Comment by rgrempel** [comment]
Thanks for the reference to first-class pattern matching -- I wasn't aware of that -- my Haskell-fu is relatively limited. (By which I mean I've heard of it, but most of my Haskell knowledge comes via Elm, rather than vice-versa).

I wouldn't say that what I'm proposing is so much a step towards first-class pattern matching so much as a pragmatic implementation of a small, comparatively inflexible example of it. That is, "step towards" seems to imply that it would be implemented with techniques that logically help lead to more first-class pattern matching, which wouldn't be the case (at least, as I imagine the implementation).

I did consider implementing something like this proposal via a build system -- I think that's what you're getting at in the second comment -- that is, by creating some home-grown syntax and using a pre-processor in the build process so that the Elm compiler only sees the generated source files.

I think that would be perfectly appropriate for some local, project-specific idioms. For instance, I might use that approach to automate the creation of JSON decoders, based on type information I already have defined in one way or another.

However, I'm less fond of that approach for something with general use like this. For instance, if one is going to use this idiom in a published package, then one would have to distribute the generated code rather than its pre-generation source (since one wouldn't want to force users of the package to use any particular code generation process). I suppose that's not impossible, but it seems awkward. For instance, it makes collaboration on source code a little awkward.

I suppose the way I see it is that it comes down to whether my theoretical case for this is convincing. That is, if this is just a facility that is useful for the particular idiom that a particular project happens to have adopted, then the code generation solution probably makes sense. However, if 'accessor magic for union types' actually does fill a logical gap in the Elm language, then I think it makes more sense to teach the compiler to do it.

Or, to put it another way, the compiler magic for `record.property` could also be implemented by code generation -- you can, after all, implement it as a normal function which pattern-matches on the record. (For all I know, that could be what the Elm compiler turns it into). But, you wouldn't want to do it that way. So, the question is whether what I'm proposing is as fundamental as that.

**Comment by rgrempel** [comment]
It occurs to me that one other implementation strategy -- between 'compiler magic' and 'pre-process files before the compiler sees them' -- would be some kind of 'macro' system.

I was thinking about what @Apanatshka said a little more, and it seems to me that it's true that the issue I'm raising reflects a desire to mitigate one of the limitations of pattern-matching, which is that pattern-matching requires the tags to be mentioned as literals. And, that's the sense in which one might think of this in terms of 'first-class' pattern-matching -- that is, a kind of pattern-matching which does not rely so much on literals. (Just like a first-class function is something that can be passed around, rather than just a literal). So, it matches with my desire to take something like `@SubTag1` and have that magically be a function that I can pass around. (Or, to put it another way, we can pass around `SubTag1` as a first-class constructor function, so it would be nice to be able to pass around `@SubTag1` as a first-class matching function as well).

However, in terms of implementation, I wasn't really thinking of something that would generalize to what first-class pattern matching is in Haskell -- that is, I wasn't really thinking of something quite that sophisticated. In reality, I was thinking more of a kind of macro -- that is, that the compiler would more-or-less turn `@SubTag1` into a certain kind of function definition when it saw it. (I say more-or-less because I'm sure it's more complex than that when you get down to it, but you'll see the general strategy I have in mind). Not to say that I'm super-focused on implementation details, but my point is that I'm thinking of something that looks more like a macro than anything else.

Now, the other way to do this, of course, would be to define a more general 'macro' or 'templating' facility in Elm. Now, I'm not suggesting that this kind of meta-programming is a good idea generally -- that is, one would not want it to be over-used. However, it is particularly suited for cases like this, where the otherwise-repeititve code requires the use of literals.

Just to elaborate on that thought for a moment, normally if I see repetitive code, my instinct is to find some way to unify it -- say, with a function or some unifying data structure or whatever. So, that requires some varying degree of cleverness. But, if the repetitive code must use literals, then you're basically stuck -- no matter how clever you are, the literal needs to be literally there.

But, a macro facility of one form or another can potentially deal with that, since the macro can automate the writing out of literals (so as far as the next stage of the compiler is concerned, it's seeing the literals it expects).

What I would like about a macro facility, compared the 'code generation' approach, is that the macro facility requires less build coordination amongst multiple users. That is, the macro facility would include everything needed to build inside the Elm source itself, rather than relying on an external build process. So, you can re-use someone else's code without having to change your build process.

Now, this is not meant to be an argument for a macro facility -- I'd be perfectly happen to implement this proposal without it, and there sure would be a lot of reasons why you might or might not want a macro facility in a language. However, I thought it might be useful to mention the possibility -- for instance, I'd be happy to work on a macro facility if that is thought to be desirable and this proposal by itself isn't.

**Comment by VesaKarvonen** [comment]
IMHO, what you really want is to make variant types aka discriminated unions structural like is done for records.  There are many published papers on this topic, e.g. [Extensible Programming with First-Class Cases](http://people.cs.uchicago.edu/~blume/papers/icfp06.pdf). I'm surprised that Elm incorporates Leijen's [Extensible records with scoped labels](http://research.microsoft.com/pubs/65409/scopedlabels.pdf), but didn't do the same for variants.

**Comment by Apanatshka** [comment]
@rgrempel involving macro's into this discussing is going to make it any more focussed :frowning: Look up "type directed macro's" on the mailing list, there have been discussions before. 

@VesaKarvonen Good point! I'd love to see extensible variants too, although the scoped label thing is even stranger there. The `case`-`of` would suddenly have a different semantics for two consecutive cases with the same label.

**Comment by rgrempel** [comment]
Ah, I should have known that mentioning macros was a little naive! The previous discussion you refer to is quite interesting.

So, let me back up to say that my original proposal doesn't necessarily have anything at all to do with macros!

I do appreciate how friendly the Elm community is with newcomers -- you all are very patient with people like me who only discovered Elm recently, and don't have a theoretical background in Haskell.
