### ISSUE TITLE
instanceof Array can fail

### ISSUE THREAD

**Issue by mthurman** [elm-lang/elm-compiler#1037]
I'm hacking on an Electron project which I'm trying to use elm for. In the electron code, one of my dependencies uses ```vm.runInNewContext``` which causes that code to have a different Array prototype which causes elm's ```instanceof``` checks to fail (see https://github.com/joyent/node/issues/1277).

Can elm use Arrays.isArray instead of instanceof checks?

It looks like it's probably just a matter of editing https://github.com/elm-lang/elm-compiler/blob/a9658ccb44cf3358991671b7abe02c4d87a31151/src/Generate/JavaScript/Port.hs#L87 and possibly adding a new helper. But I'm very new to elm (and don't have a great grounding in JS stuff anyway), so I figured I'd raise the issue before I sent a pull request.

**Comment by evancz** [comment]
How widely supported is the thing you are suggesting?

@rtfeldman, do you know anything about this?

**Comment by rtfeldman** [comment]
It was introduced in ES5: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/isArray

Unfortunately this is only one of many ways people can mess up the global execution environment in a way that could mess Elm up. Monkey patching is and always has been caveat emptor.

I think we should leave the current behavior as-is on this one.

**Comment by evancz** [comment]
Okay, I don't want to drop support for IE9 for this reason, and I suspect that's what we'd need to do here.

Thanks @rtfeldman!
