### ISSUE TITLE
Error out when Json.Decoder creates a record with wrong keys

### ISSUE THREAD

**Issue by amitaibu** [elm-lang/elm-compiler#1042]
Our model has `id` and `label`, but in the `decoder` function, we map a wrong key instead of label.
Compiling this will result with `Err ("expecting an object with field 'wrongKey' but got {\"id\":1,\"label\":\"foo\"}")` but maybe it could be error out upon compiling?

```elm
import Graphics.Element exposing (show)
import Json.Decode as Json exposing ((:=))

type alias Model =
  { id: Int
  , label: String
  }


serialized : String
serialized = "{\"id\":1,\"label\":\"foo\"}"


decoder : Json.Decoder Model
decoder =
  Json.object2 Model
    ("id" := Json.int)
    -- Notice instead of the key "label" we have a "wrongKey"
    ("wrongKey" := Json.string)

main =
  show (Json.decodeString decoder serialized)
```

**Comment by rgrempel** [comment]
But there is nothing that **requires** that the Elm key you use matches the JSON key.

For instance, how is the compiler supposed to know that you don't actually mean to consume a JSON object that looks like this:

    {
        "id": 17,
        "wrongKey": "label contents"
   }

... and turn it into an Elm value that looks like this:

    { id = 17
    , label = "label contents"
    }

That might be a perfectly sensible thing to do. Imagine, for instance, if you don't control the JSON formatting, but you want to use a different key internally.

**Comment by amitaibu** [comment]
@rgrempel my assumption was based on:

```elm
  Json.object2 Model
    ("id" := Json.int)
    -- Notice instead of the key "label" we have a "wrongKey"
    ("wrongKey" := Json.string)
```

Where `Model` is the constructor of the record. I'm new to elm, so the assumption might very well be wrong ;)

**Comment by rgrempel** [comment]
Ah, but even there the `Model` constructor you're using has this signature:

    Int -> String -> Model

So, it doesn't care and doesn't know what key was used in the JSON -- by the time you reach the `Model` constructor, all it is seeing is a `String`.

Now, what `Json.object2` is doing must be sort of interesting -- clearly it's resolving the additional parameters and only then supplying them to `Model` (if they work).

In any event, your code would successfully decode 

    {
        "id": 17,
        "wrongKey": "label contents"
    }

... if that was, in fact, what the JSON was supposed to look like.

**Comment by amitaibu** [comment]
> Ah, but even there the Model constructor you're using has this signature:

I see your point. My assumption was also based on the fact we defined the keys in:

```elm
type alias Model =
  { id: Int
  , label: String
  }
```

Anyway, I guess I should close the issue? :)

**Comment by rgrempel** [comment]
I suppose this is one of the "It's a feature, not a bug" cases ... the Json.Decode module is actually pretty amazingly flexible in allowing you to consume all sorts of JSON and turn it into what you want.

**Comment by amitaibu** [comment]
:+1:
