### ISSUE TITLE
flow down flows to the right sometimes

### ISSUE THREAD

**Issue by vbychkovsky** [elm-lang/elm-compiler#105]
If one of the fields in the flow down gets too long, other fields don't see to flow to the right instead. If you run the code below and type a long enough string into the first field, you'll see that second text field jump into the first line as the first. Is this expected behavior?

    (f1, s1) = Input.textField ""
    (f2, s2) = Input.textField ""

    scene blah = 
      flow down 
        [ f1
        , f2
        , plainText blah
        ] 

    main = scene <~ s1

**Comment by evancz** [comment]
I am trying to clean up the issues in this repo, so I am going through and closing a bunch of issues with ideas on how to get them done.

In this case, we should verify that the issue still manifests after the changes to the `Graphics.Input` API and if so, open an issue at https://github.com/elm-lang/core/issues

Thanks for the report!
