### ISSUE TITLE
Elm misses static pages examples

### ISSUE THREAD

**Issue by G4BB3R** [elm-lang/elm-compiler#1051]
Elm misses examples of programming static pages for beginners knowing how to replace a simple html/css page with pure Elm.

**Comment by jvoigtlaender** [comment]
This here is definitely not the right place to bring up this issue.

You could bring it up for discussion on the mailing list. Or maybe as an issue at the https://github.com/elm-lang/elm-lang.org repository (where the webpage with examples is developed).

Please close here.

**Comment by evancz** [comment]
You can usually get lots of help on [the mailing list](https://groups.google.com/forum/#!forum/elm-discuss) so I would try there first. If we get some good examples, the best path is probably to do a bit of blogging about it. The learning resources on the website need to be appropriate for a pretty large range of people, so it's not super easy to add stuff and still serve everybody as well. Blogging is easier :)
