### ISSUE TITLE
Proposal: support Haskell-style multiple function bodies with different patterns

### ISSUE THREAD

**Issue by awh** [elm-lang/elm-compiler#1058]
For example
````
fn : Maybe Int -> Int
fn (Just x) = x
fn Nothing = 0
````

**Comment by laszlopandy** [comment]
There is already a way to do this with `case`. What is the reason to add a second way to do it?

**Comment by awh** [comment]
Good question. For my own part, nothing hugely compelling - it's familiar and I find it more readable (less indenting). But now you have me wondering - why does Haskell have this duplication?

**Comment by mgold** [comment]
Why does Haskell have a lot of things? The same argument goes for `where` clauses - we're targeting JS and Ruby devs, not Haskellers, and part of that strategy is to have only one way to do something.

Although, you can write `fn (Just x) = x` and it will runtime error if given a `Nothing`. Part of me wants to fix that, but I've used it in cases that I've known it was safe (e.g. elm-lang/core#402).

**Comment by laszlopandy** [comment]
I think in 0.16 extracting types in the signature is not allowed. It will be considered an incomplete pattern match. Extracting tuples will still be allowed (because the type signature guarantees it will work), but others like List and type will not.

**Comment by Apanatshka** [comment]
This is a feature of Haskell that only Haskellers ever ask for. The reason the request is always declined is that this code style is or was advised against by the Haskell style guide. (That style guide is moving around on the wiki and seems to get rewritten often enough that this kind of stuff gets lost, but I've definitely seem it on there. )

**Comment by evancz** [comment]
The reasoning is roughly that:

  * Diffs become huge when you want to add a variable.
  * It contributes to an odd "visual texture" in which top level declarations are not necessarily separate, making it harder to scan a file.

I forget if there were more, but this was a decision that I made in like 0.3? A long time ago when I was like, "wait, why do I want this?" So this is a no for now. But thanks for opening the issue, and I hope you are enjoying using Elm!

**Comment by 5outh** [comment]
I think it's been discussed plenty, but have you considered a syntax along the lines of lambda case? E.g.

```
fn : Maybe Int -> Int
fn = case
  Just x -> x
  Nothing -> 0
```

I sort of like this because it removes some verbosity, but in the same breath I could see how it could be confusing, which is something I know Elm actively avoids.

**Comment by evancz** [comment]
@5outh, I have, but I'm not super into it. OCaml has something just like this (for many years actually :P) but I feel like "write a helper function" is often "the right thing to do" so I like that the current syntax nudges people in this direction.

**Comment by 5outh** [comment]
@evancz Makes sense, I deleted the comment because it felt like playing devils advocate in a resolved issue; thanks for your comment :)

**Comment by mgold** [comment]
> I think in 0.16 extracting types in the signature is not allowed. It will be considered an incomplete pattern match.

@laszlopandy Will it be allowed when there is only one tag in the union type?

**Comment by laszlopandy** [comment]
@mgold Almost certainly yes, and the tag check will even be omitted from the generated JS in these cases when we can statically know it will always be true.

**Comment by mgold** [comment]
Sounds great, hope you're right!

**Comment by evancz** [comment]
Yeah, it's fine as long as there is only one variant. Other behavior would be silly.

**Comment by mgold** [comment]
Cool thanks!
