### ISSUE TITLE
compiler message for missing variable

### ISSUE THREAD

**Issue by flip111** [elm-lang/elm-compiler#1060]
code
```haskell
view : Signal.Address Action -> Model -> Html
view address model =
  div []
    [ table [] [ thead [] [tr [] (makeHead model)]
               , tbody [] (makeBody model)
               ]
    ]

makeHead model =
  map (\x -> th [onClick address Sort] [text x]) (getKeys model)
```

message
```
The 1st argument to function `onClick` has an unexpected type.

79|                  onClick address Sort]
                             ^^^^^^^
As I infer the type of values flowing through your program, I see a conflict
between these two types:

    Signal.Address a

    List Attribute -> List Html -> Html
```

Comments:

* don't understand how address can have a type at all when it was not given to the function
* message could be something like: `address` not defined, did you forget to pass it to the `makeHead` function?

**Comment by evancz** [comment]
Can you retarget this to https://github.com/elm-lang/error-message-catalog and check to see if there are any issues open reporting the same kind of thing. If so, still open a separate issue, but link to the related one.

**Comment by evancz** [comment]
Also, try to include a [SSCCE](http://sscce.org/) to illustrate the issue. In this case, it is definitely missing all the imports that would make this work, and I expect that's where the oddity is. So when you reopen, can you make sure that the example can be copied into elm-lang.org/try and show the same error you are seeing?

**Comment by evancz** [comment]
Ohhh, what if the `address` there is actually [`Html.address`](http://package.elm-lang.org/packages/evancz/elm-html/4.0.1/Html#address)?!?!

I think that's the root thing here!

**Comment by mgold** [comment]
... and one more reason to ditch the Address type? Just say'in.

**Comment by flip111** [comment]
confirmed `import Html exposing (..)` was in the source file.
