### ISSUE TITLE
Doesn't allow to update a record with fully qualified name

### ISSUE THREAD

**Issue by kika** [elm-lang/elm-compiler#1067]
This code 
```elm 
import Http
{Http.defaultSettings | timeout <- 300}
```
doesn't compile, while this

```elm
import Http
dS = Http.defaultSettings
{dS | timeout <- 300}
```

does.

**Comment by Apanatshka** [comment]
duplicate of #520

**Comment by evancz** [comment]
It is actually a duplicate of #635 which is a feature request. The issue @Apanatshka is a legitimate bug that should be fixed.

I have started #1068 to track these record things that come up from time to time.

**Comment by Apanatshka** [comment]
Oops, sorry for the confusing link! I knew there was another issue open about this, did a quick search but obviously didn't check well enough before I linked.
