### ISSUE TITLE
keyboard.presses returns zeros in firefox

### ISSUE THREAD

**Issue by bburdette** [elm-lang/elm-compiler#1069]
So there's this piece of code here:

inputKeyboard : Signal String
inputKeyboard = Signal.map (\c -> Char.fromCode c |> String.fromChar) Keyboard.presses

Which is part of this file:

https://github.com/whodidthis/elm-sockets/blob/master/Main.elm

In chromium it returns a stream of characters, one per key press, as one might expect.  But in firefox it returns zeros (it prints "\0"), except for the enter and tab keys which result in "\r" and "\t". 

I'm in FF 41.0, chromium 45.0.2454.85, and elm 0.15.1.  

I gave it try using fromString to see the whole integer value instead of converting to char, but still zeros.

**Comment by jvoigtlaender** [comment]
This is a known issue, and belongs at the `core` repo, see here: https://github.com/elm-lang/core/issues/326.

Please check over there, put your information in a comment there if it adds something over what is already collected there, and close the issue here in the `elm-compiler` repo.

**Comment by bburdette** [comment]
ok thx jvoightlaender!
