### ISSUE TITLE
Json.encode and Json.decode not roundtripping

### ISSUE THREAD

**Issue by jvoigtlaender** [elm-lang/elm-compiler#1076]
I don't know whether this really is a problem, but at least it might be something to watch out for.

It so happens that `Json.decode (Json.encode (Type "_Tuple0")) :: Maybe Type` is not `Type "_Tuple0"`, but instead `App (Type "_Tuple0") []`.

Is this expected/okay?

Is there a desired invariant of the compiler that in `App type args` the `type` should always be a type *constructor* and the `args` never the empty list? (If so, this would be violated here.)

If unification is applied at some point, will `Type "_Tuple0"` be considered equal to `App (Type "_Tuple0") []`?

(The above non-roundtripping property came up in https://github.com/elm-lang/elm-compiler/issues/1072, but I'm wondering whether it might have bad implications elsewhere as well.)

**Comment by evancz** [comment]
The compiler never works with JSON for build artifacts so I think this won't mess with anything.

That said, I think this is a bug. Whenever there is a `Type` with no arguments it is not put inside an `App` so this would be bad if this round trip was ever taken.

**Comment by jvoigtlaender** [comment]
You know this, but just for the record:

Well, the roundtrip kind of is taken at the moment, if only for documentation processing. That's what caused [this issue](https://github.com/elm-lang/elm-compiler/issues/1072). In [these lines](https://github.com/elm-lang/package.elm-lang.org/blob/17091449ed3b9bc31cfc97cc3d5b23329672f19b/backend/Routes.hs#L240-L249), `documentation.json` is read and parsed. Any, or maybe only some, occurrences of `()` in there (which most likely were put there originally via some `Json.encode (Type "_Tuple0")`) are getting `Json.decode`d into `App (Type "_Tuple0") []`.

If this were fixed, i.e., `Json.decode "()"` were to give `Type "_Tuple0"` instead of `App (Type "_Tuple0") []` (and also otherwise the invariant that in `App _ args` the `args` is never the empty list were definitely maintained), then [the lines I added in https://github.com/elm-lang/elm-compiler/pull/1075](https://github.com/jvoigtlaender/elm-compiler/blob/e9ceea664bebf52aa3e9939e1d184fbe53f40994/src/Elm/Compiler/Type.hs#L62-L63) could be dropped again.

**Comment by evancz** [comment]
Let's get a SSCCE for this. There are many representations of `Type` in the compiler and it's not clear what's going on here. Maybe get a Haskell file that I can call `runhaskell` on in my compiler repo.

**Comment by jvoigtlaender** [comment]
SSCCE (different behavior in 0.17 than above, but still wrong) here: https://github.com/elm-lang/elm-compiler/issues/1378
