### ISSUE TITLE
Incomplete pattern matches problem with True/False

### ISSUE THREAD

**Issue by evancz** [elm-lang/elm-compiler#1077]
Because `True` and `False` are treated as literals, they are assumed to be infinite like all the other literals like ints, floats, chars, and strings. They are not though.

```
-- MISSING PATTERN ---------------------------------------------- ./src/Http.elm

The following `case` does not handle all possible inputs.

430│>  case 200 <= response.status && response.status < 300 of
431│>    False ->
432│>        fail (BadResponse response.status response.statusText)
433│>
434│>    True ->
435│>        case response.value of
436│>          Text str -> handle str
437│>          _ -> fail (UnexpectedPayload "Response body is a blob, expecting a string.")

The following patterns are not being handled:

    <values besides: False True >

Did you add a new tag to a union type? Add how it should be handled here and
you will be all set!
```

Not sure how what needs to be done in the compiler to allow this kind of code again. Plans like "`Bool` is no longer a literal" have unfortunate results in the type inference phase. Maybe there just needs to be a special case in the pattern match checker.

**Comment by rgrempel** [comment]
I guess that a workaround would be something like:

```elm
case 200 <= response.status && response.status < 300 of
   False ->
       fail (BadResponse response.status response.statusText)

   _ ->
       case response.value of
            Text str -> handle str
            _ -> fail (UnexpectedPayload "Response body is a blob, expecting a string.")
```

But I don't mean to say that that is ultimately desirable :-)

**Comment by evancz** [comment]
I already did a different workaround, but I think this in unacceptable as is. The actual fix is quite tricky and depends on a lot of internal compiler details, so I want threads like this to stay focused on that kind of stuff.
