### ISSUE TITLE
`_U.range is not a function` error on 0.16-alpha

### ISSUE THREAD

**Issue by pdamoc** [elm-lang/elm-compiler#1085]
Running the following code on the 0.16-alpha 

```elm
hd = List.head [1..10]
```
produces the following error:

    _U.range is not a function

this one line of code crashes
http://elm-lang.org:1234/try

**Comment by evancz** [comment]
Okay, it should be fixed in elm-lang/core, thanks for the report! The website is broken in other ways still, but this issue is fixed. If you want the fixed version locally, remove your `elm-stuff/` directory and build it again. The new code will come.
