### ISSUE TITLE
"Cannot read property 'ctor' of undefined" on 0.16-alpha

### ISSUE THREAD

**Issue by pdamoc** [elm-lang/elm-compiler#1086]
The following code produces a `Cannot read property 'ctor' of undefined`

```elm
import Graphics.Element exposing (show) 

type AType = First     (() -> Bool)
               | Second    (() -> Bool) String String

getSecond : a -> a -> AType
getSecond a b = Second (\_ -> a == b) (toString a) (toString b)

toName : AType -> String
toName a =
    let 
        name = case a of
                 First _ -> "True"
                 Second _ a b    -> a ++ " == " ++ b
    in 
        name 

main = show <| toName <| getSecond  1 1
```

If I get rid of the let, the error disappears:
```elm
import Graphics.Element exposing (show) 

type AType = First     (() -> Bool)
               | Second    (() -> Bool) String String

getSecond : a -> a -> AType
getSecond a b = Second (\_ -> a == b) (toString a) (toString b)

toName : AType -> String
toName a =
    case a of
        First _ -> "True"
        Second _ a b    -> a ++ " == " ++ b

main = show <| toName <| getSecond  1 1
```

Adding a quote to variable `a` as in `a'` also gets rid of the error 
```elm
import Graphics.Element exposing (show) 

type AType = First     (() -> Bool)
               | Second    (() -> Bool) String String

getSecond : a -> a -> AType
getSecond a b = Second (\_ -> a == b) (toString a) (toString b)

toName : AType -> String
toName a =
    let 
        name = case a of
                 First _ -> "True"
                 Second _ a' b    -> a' ++ " == " ++ b
    in 
        name 

main = show <| toName <| getSecond  1 1
```

If only one case remains, the error becomes `Cannot read property '_1' of undefined`
```elm
import Graphics.Element exposing (show) 

type AType = Second    (() -> Bool) String String

getSecond : a -> a -> AType
getSecond a b = Second (\_ -> a == b) (toString a) (toString b)

toName : AType -> String
toName a =
    let 
        name = case a of
                 Second _ a b    -> a ++ " == " ++ b
    in 
        name 

main = show <| toName <| getSecond  1 1
```

**Comment by evancz** [comment]
Thanks for the report and versions that get it working again!

This is a relatively unfortunate JS scoping issue. The generated code from the bad example is this:

```javascript
var toName = function (a) {
      var name = function () {
         var _p0 = a;
         if (_p0.ctor === "First") {
               return "True";
            } else {
               var a = _p0._1,b = _p0._2;
               return A2($Basics._op["++"],a,A2($Basics._op["++"]," == ",b));
            }
      }();
      return name;
   };
```

The issue is that the `var a` in the `else` branch comes into scope for the whole surrounding closure, so it retroactively makes the argument `a` undefined before we get a chance to look at its contents. Need to think about how to avoid this.

**Comment by Apanatshka** [comment]
With new JavaScript features you can use let instead of var, but then
you’ll lose support of old browser, so that’s not really an option I guess.
Another option is to only generate globally unique variables names, so no
shadowing occurs in the generated code at all. That option depends on name
analysis (def/use) information.

​

**Comment by pdamoc** [comment]
Wouldn't make more sense to aim towards the future (ES2015) and provide support for older browsers via something like BabelJS?

**Comment by evancz** [comment]
No, I'm planning to go for ES3 or whatever. No need for those new features here.

The fix here is relatively simple and should make the resulting code faster. So it's all sorted out, I just need to spend a few hours on it.

**Comment by Warry** [comment]
If ES3 is the target, I've noticed a couple of times that the generated JS had trailing comas in js literals (which generates exceptions on old IE), like:

```js
var foo = {
  bar: "hello",
  baz: 42,
}
```

Last time I've seen it was on the generated code in the benchmark (https://github.com/elm-lang/elm-compiler/tree/dev/bench).

**Comment by dustinfarris** [comment]
I am seeing this in v0.18

![screenshot 2017-04-15 19 21 37](https://cloud.githubusercontent.com/assets/1087165/25067421/0cc66858-2211-11e7-90b9-47561212cde8.png)

**Comment by dustinfarris** [comment]
Here is the offending line:

![screenshot 2017-04-15 19 28 27](https://cloud.githubusercontent.com/assets/1087165/25067447/e1b16518-2211-11e7-8090-8db59c450325.png)

**Comment by evancz** [comment]
Open a new issue with a new [SSCCE](http://sscce.org/) of what you are seeing.

Don't add onto old / closed issues, and we always need an SSCCE to determine the root cause.

**Comment by dustinfarris** [comment]
Turns out my Elm code had a typo but the compiler did not catch it.

**Comment by dustinfarris** [comment]
Opened https://github.com/elm-lang/elm-compiler/issues/1583
