### ISSUE TITLE
Extra comma in exports produces unhelpful error message in 0.16-alpha

### ISSUE THREAD

**Issue by rgrempel** [elm-lang/elm-compiler#1087]
Here's a little program with an error (an extra comma in the exports):

    module Example
        ( a ,
        , b) where

    a = 7
    b = 8

In Elm 0.15, if you run elm-make, you get this error:

```
-- SYNTAX PROBLEM ----------------------------------------------------- Test.elm

I ran into something unexpected when parsing your code!

3|     , b) where
       ^
I am looking for one of the following things:

    a value or type to expose
    whitespace
```

In Elm 0.16-alpha, you get this error message:

```
elm-make: TODO
```

I considered putting this in the error messages catalog, but that is set up for 0.15, so I thought perhaps the issue should go here, for the moment anyways.

**Comment by evancz** [comment]
Ah, had some TODOs left in the error reporting code! This should be fixed along with some other things now!
