### ISSUE TITLE
[0.16-alpha] Can't find generated function for extensible record

### ISSUE THREAD

**Issue by Warry** [elm-lang/elm-compiler#1088]
I don't know if this is because of my cranky environment (https://github.com/elm-lang/elm-repl/issues/80), but I can't compile code using generated functions for the extensible records:

The error:
```
➜ elm-make Main.elm
[                                                  ] - 0 / 1
elm-make: Could not find `Foo` when solving type constraints.
elm-make: thread blocked indefinitely in an MVar operation
```

The sample:
```elm
type alias Foo a =
  { a | foo : String }

-- Code that breaks (each with the same error):

myFoo : Foo {}
myFoo = Foo "Hello" {}

myFoo2 : Foo { x : Int }
myFoo2 = Foo "Hello" { x = 42 }

myFoo3 : a -> Foo a
myFoo3 x = Foo "Hello" x

--

-- All the following works:

type alias Bar a =
  { a | bar : String }

myBar : Bar {}
myBar = { bar = "World!" }

type alias Baz =
  { baz : String }

myBaz : Baz
myBaz = Baz "John"
```

Env. : 0.16-alpha on osX 10.11
The same code works on 0.15.1

**Comment by Warry** [comment]
Maybe related to https://github.com/elm-lang/elm-compiler/issues/953

**Comment by evancz** [comment]
Records with type holes no longer generate record constructors. So there should be no `Foo` function for creating values in the first place. Record extension literally does not exist in syntax anymore, and this is one form of it.

**Comment by Warry** [comment]
Ok, I'll make a PR for the update to 0.16 docs

**Comment by evancz** [comment]
The weird thing is that this is not a NAMING ERROR, where it cannot find `Foo` at the value level. I don't quite get that, and it seems like a bug.

**Comment by Warry** [comment]
Ok, feel free to reopen the issue if you think it's relevant.

**Comment by ccapndave** [comment]
https://github.com/elm-lang/error-message-catalog/issues/67
