### ISSUE TITLE
infixl behaves as if imported modules exposed all operators

### ISSUE THREAD

**Issue by rgrempel** [elm-lang/elm-compiler#1094]
Here's a little module that illustrates the problem:

```elm
module Test where

(~) a b = 7

infixl 4 ~
````

This compiles fine under 0.16-alpha. But, it errors under 0.15, with the following error:

```
-- INFIX OVERLAP ------------------------------------------- Test.elm

The infix declarations for (~) must be removed.

5| infixl 4 ~
   ^^^^^^^^^^
The precedence and associativity can only be set in one place, and
this information has already been set somewhere else.
```

It is as if Signal.(~) had been auto-imported in 0.15. Except that it wasn't -- if you try to use it without importing it, you get the expected error.

Now, there is no point fixing this specific case in 0.15, since it works fine in 0.16. However, I can trigger the problem under 0.16 as well, with these two modules:

```elm
module Test where

(>>>) a b = 7

infixl 4 >>>
```

```elm
module Test2 where

import Test

(>>>) a b = 7

infixl 4 >>>
```

Note that `Test2` compiles fine under 0.16 if you remove the `import Test`.

Also note that it doesn't help to remove `(>>>)` from the exports in `Test` -- `infixl` still behaves as though it had been exported. It also doesn't help to do something like `import Test exposing (otherFunc)` in `Test2` -- that is, it doesn't help to explicitly limit the import or the exports.

So, this does appear to be a bug with how `infixl` treats imports -- it appears to act as though all operators had been exposed, and all operators had been imported.

**Comment by rgrempel** [comment]
In case anyone saw the first version of my original comment, I had to edit it for a typo in the second code example.

**Comment by evancz** [comment]
This is a known behavior of infix declarations right now. I believe there can only be one for each operator in the whole project. I'll make an issue that notes this more specifically. It would require a fairly serious change to the parsing code, so I won't be able to change this behavior in the short term.
