### ISSUE TITLE
Sort out infix precedence later in pipeline

### ISSUE THREAD

**Issue by evancz** [elm-lang/elm-compiler#1096]
Right now the fixity of all infix operators used in the code you compile is globally known. This means there can only be one fixity declaration for a certain name. #1094 describes what this means for users right now.

This was easier to parse, but I believe it can be avoided by moving the fixity stuff to canonicalization. I think this is a relatively large project, so I don't know the timeline here, but this may be a nicer way to go. 

cc @avh4

**Comment by avh4** [comment]
See https://github.com/avh4/elm-format/commit/e0e8151750b5f9a136744ee203509adfd061035c

**Comment by evancz** [comment]
Nice!

We already discourage infix operators very heavily. At some point people
were roughly saying the design guidelines
<http://package.elm-lang.org/help/design-guidelines#avoid-infix-operators> hurt
their feelings. I think we could make that more prominent. Or make the info
on how to do it in the first place less prominent.

I am hesitant to remove this feature entirely. Not sure if you saw
Richard's "CSS to Elm" prototype, but he uses infix operators to achieve
something that looks very much like normal CSS in Elm. It's pretty cool. I
have a feeling that there are more things like this to explore before we
say "okay, this is definitely not worth it". So I'd wait to remove it all
the way.

We can also think about encoding the culture of "don't use custom infix
operators" into tooling. Maybe certain tools would be like "hey, this kind
of thing is advised against". Like elm-package when you publish. Stuff like
that.

**Comment by klaftertief** [comment]
I stumbled upon this as described here https://github.com/klaftertief/elm-compiler-infix-precedence in an SSCCE.
The compiler does not complain in this case though, it silently produces different JavaScript depending on whether there are caches in `elm-stuff` or not.

I'm happy to add a proper separate issue if you want to track this separately.
