### ISSUE TITLE
[0.16] functions in polymorphic records raise a syntax problem

### ISSUE THREAD

**Issue by Warry** [elm-lang/elm-compiler#1100]
(With 0.16-alpha2)
This example is copy/pasted from the doc:

```elm
group =
  { op a b = a ++ b
  }
```

```
-- SYNTAX PROBLEM ------------------------------------------------------
I ran into something unexpected when parsing your code!

3│   { op a b = a ++ b
          ^
I am looking for one of the following things:

    "|"
    an equals sign '='
    whitespace
```

**Comment by Warry** [comment]
BTW, it works fine with an anonymous functions.

**Comment by evancz** [comment]
I believe I removed this syntax as well. I thought I removed that from the 1234 website, but maybe not.

**Comment by evancz** [comment]
Do you need this syntax for something in particular?

I wanted to remove this until we actually had rank2 polymorphism such that we could use this for cool stuff.

**Comment by Warry** [comment]
I think it looks clean and cool, but again it works with anonymous ƒ so, at the end of the day the functionality is more important. I already updated my code anyway :)

Maybe it should be reflected in the update to 0.16 doc.

**Comment by mgold** [comment]
>Maybe it should be reflected in the update to 0.16 doc.

Fixed in my syntax guide PR.
