### ISSUE TITLE
Unifying comparable tuples while decomposing them from a union

### ISSUE THREAD

**Issue by bugQ** [elm-lang/elm-compiler#1106]
Tuples of comparable types are comparable, but it's currently impossible to decompose a "Maybe (Float, Int)" in a single step, as in f1 below, when a "Maybe comparable" is expected.  Using Maybe.withDefault or decomposing one layer at a time, as in f2 and f3, work just fine.

```elm
type Heap comparable = Leaf | Node comparable (List (Heap comparable))

type alias State = { heap : Heap (Float, Int) }

findmin : Heap comparable -> Maybe comparable
findmin heap = case heap of
  Leaf -> Nothing
  Node element heaps -> Just element

f1 : State -> Int
f1 state = case (findmin state.heap) of
  Just (f, i) -> i
  Nothing -> -1

f2 : State -> Int
f2 state = case (findmin state.heap) of
  Just c -> let (f, i) = c in i
  Nothing -> -1

f3 : State -> Int
f3 = .heap >> findmin >> Maybe.withDefault (0.0, -1) >> snd
```

---

    Problem with `Maybe.Just` in this pattern match.
    
    12| Just (f, i) -> i
    
    Note: comparable types include Int, Float, Char, String, lists, and tuples. As I infer the type of values flowing through your program, I see a conflict between these two types:
    
        comparable
        (b, c)

**Comment by jvoigtlaender** [comment]
Most likely the same bug as https://github.com/elm-lang/elm-compiler/issues/1013 and https://github.com/elm-lang/elm-compiler/issues/880?

**Comment by bugQ** [comment]
very well could be, or at least, the solution will probably be the same

**Comment by evancz** [comment]
The example provided compiles fine in the master branch, looks like the `type-fixes` branch covered this case as well. Thanks for describing the issue with a small example!
