### ISSUE TITLE
Type checker should forbid unbound type variables in type aliases

### ISSUE THREAD

**Issue by psfblair** [elm-lang/elm-compiler#1110]
Example case:

    type MyData = MyData String
    type alias MyDataAlias a = MyData

Complete example here: http://share-elm.com/sprout/56213fb6e4b0966c193dd8ee

The type checker just ignores the type variable, but this should probably be an error instead -- either the author intended a phantom type, which can't be introduced by a type alias, or intended to bind the type variable, in which case the code is erroneous. I suggest having the type checker say something like: "You have an unbound type variable in a type alias. Phantom types are not supported through aliases. Maybe you meant ...?"

**Comment by evancz** [comment]
Thanks for the report!
