### ISSUE TITLE
Rename record pattern matches with "as" keyword

### ISSUE THREAD

**Issue by mgold** [elm-lang/elm-compiler#1111]
It would be a neat little trick to be able to use `as` to rename the fields of records when pattern matching on them.

```elm
{signal as actions, address as actionsAddress} = Signal.mailbox NoOp
```

Not expecting this anytime soon; please file away as necessary.

**Comment by evancz** [comment]
It probably makes more sense to go the same route as OCaml and them. They let you do deeper pattern matches, like this:

```elm
  case person of
    { age = Nothing } ->
      ...

    { age = Just age } ->
      ...
```

Whatever happens, I don't really want to track it here. I know the idea and the variations, but it's on hold until later.

**Comment by wende** [comment]
@evancz Was there any development in this direction?
It'd be really nice feature to have
