### ISSUE TITLE
Call into JS without boilerplate

### ISSUE THREAD

**Issue by hanshoglund** [elm-lang/elm-compiler#1112]
From looking at the [source code of the http package](https://github.com/evancz/elm-http/blob/2.0.0/src/Native/Http.js), I understand that Elm is now able to call into non-pure JS using native modules and tasks. From a user (i.e. non-language developer) point of view this feature has two drawbacks:

- It seems to require manual translation between Elm and JS types
- It is undocumented

Given that Tasks are part of the Elm core, it would make sense to develop something akin to the GHC or PureScript FFI, where binding library developers can call into pure functions unrestricted, and into non-pure functions with a (Task Failure a) on the return type, and have the boilerplate being generated from the types. As far as I understand this would not interface with the FRP core at all, as all non-pure code would execute in tasks, and exceptions etc could be caught there and propagated back to the Elm caller.

Motivation for this? Millions of JS libraries out there. Haskell and Clojure both succeeded because they understood the importance of binding to exiting code. I added this feature partly to inquire about how the Elm community stands on this.

**Comment by jvoigtlaender** [comment]
Getting to know how the Elm community stands on such a feature is more likely successful on the [mailing list](https://groups.google.com/forum/#!forum/elm-discuss). This repo's issue tracker is mainly for bug reports (and to some extent for more specific feature requests, but not really AFAIK for such large-ranging/high-level design questions).

In fact, by searching the mailing list you may find some answers already. The approach to native code is a not uncommon topic there.

**Comment by evancz** [comment]
Thanks @jvoigtlaender!

**Comment by hanshoglund** [comment]
Thanks for the replies, found some relevant threads:

- https://groups.google.com/forum/#!searchin/elm-discuss/native/elm-discuss/DPuUPv72abc/j-W5JadU0McJ

- https://groups.google.com/forum/#!searchin/elm-discuss/native
