### ISSUE TITLE
Could elm be used outside the browser?

### ISSUE THREAD

**Issue by Maximilianos** [elm-lang/elm-compiler#1113]
Particularly interested in server side rendering (the Isomorphic/Universal development pattern) and static site generation?

**Comment by jvoigtlaender** [comment]
I'd say this is a question for the [mailing list](https://groups.google.com/forum/#!forum/elm-discuss), not for an (Elm) GitHub repo's issue tracker.

**Comment by Maximilianos** [comment]
Done: https://groups.google.com/forum/#!topic/elm-discuss/SFIC-yuHTI8

**Comment by evancz** [comment]
In short, yes, it's possible. It's something I am quite interested in, and I have already started doing some preliminary work in this direction. I don't know the exact timeline, but this is something to expect eventually.

**Comment by Maximilianos** [comment]
Yes it would make elm even more appealing. Thanks, @evancz @jvoigtlaender

**Comment by ariscn** [comment]
There are several closed issues around isomorphic / server side rendering Elm. I don't see any open issues - is there somewhere else I can subscribe for updates on how this feature is coming along? Is there a best guess for when it might drop?

**Comment by jvoigtlaender** [comment]
I *think* you may want to check https://github.com/NoRedInk/take-home#support-summary. Note the item "Server-side rendered client-side HTML". (The organization that repository is from is where Evan currently works.)

**Comment by evancz** [comment]
@ariscn, I will share updates on the elm-dev mailing list as things progress.
