### ISSUE TITLE
Strange error message on 0.16 alpha 3

### ISSUE THREAD

**Issue by pdamoc** [elm-lang/elm-compiler#1119]
Starting from Elm Architecture Tutorial Example No. 7 and using the code bellow in Main.elm

```elm

import Effects exposing (Never)
import RandomGifList exposing (init, update, view)
import RandomGif exposing (Action(NewGif))
import StartApp
import Task
import Html

app : StartApp.App RandomGifList.Model
app =
  StartApp.start
    { init = init
    , update = update
    , view = view
    , inputs = []
    }

main : Signal Html.Html
main =
  app.html



detect value  =
    case value of 
        NewGif _ ->  Debug.log "Bingo" value
        _ -> Debug.log "Some Other Task" value


port tasks : Signal (Task.Task Never ())
port tasks = Signal.map (\t -> Task.map detect t) app.tasks
```  

I get the following error message in Sublime Text 3:

![screen shot 2015-10-25 at 10 57 06](https://cloud.githubusercontent.com/assets/878106/10714804/6d39b9ae-7b07-11e5-9cb5-ee2ac23d2362.png)

**Comment by evancz** [comment]
What's the weird part exactly? The `ESC[33m` stuff? Or the actual content?

If it is the escape characters, that's something going wrong with the Sublime Text  extension. They are not handling ANSI escape characters properly.

**Comment by pdamoc** [comment]
Yes, the `ESC[33m` part looked weird.  

But since this is more likely to be a Sublime Text issue, I'll just close the issue here.

**Comment by evancz** [comment]
Okay, cool. It probably makes sense to move the report to the repo that is in charge of this extension. It'd be lame to have improvements like this and have them look all weird in sublime!
