### ISSUE TITLE
0.16 misleading hint: case on list

### ISSUE THREAD

**Issue by mgold** [elm-lang/elm-compiler#1120]
Given the code

```elm
type Nonempty a = Nonempty a (List a)    

fromList : List a -> Maybe (Nonempty a)    
fromList ys = case ys of    
    x::xs -> Just (Nonempty x xs)    
    -- [] -> Nothing
```

the 0.16-alpha3 compiler errors with

```
-- MISSING PATTERNS -------------------------------------- ././List/Nonempty.elm

This `case` does not have branches for all possibilities.

54│>              case ys of
55│>    x::xs -> Just (Nonempty x xs)

You need to account for the following values:

    []

Did you add a new tag to a union type? Add a branch for it here!

If you are seeing this error for the first time, check out these hints:
<https://github.com/elm-lang/elm-compiler/blob/0.16.0/hints/missing-patterns.md>
The recommendations about `Debug.crash` and wildcard patterns are important!

Detected errors in 1 module.
```

The issue is that the compiler talks about union types, but lists are not union types. A relatively minor point, but ideally the compiler would know not to make this recommendation when the type involved is a list.

The rest of the error is great, especially since 0.15 has no issue with this code!

**Comment by jvoigtlaender** [comment]
If going down that route, one would want to special-case not only lists, but also other pre-existing types (which *are* union types, as are lists in a fashion, but union types that the programmer *definitely* hasn't extended by a new tag). So we would want to also suppress that part of the hint for Maybe, Result, and probably a few other types as well. Or wouldn't we?

**Comment by mgold** [comment]
Right, any type defined in core would qualify. Or, indeed, in any imported module. I doubt the compiler has all that information available, so I'd settle for an 80/20 solution.

**Comment by evancz** [comment]
Canonical names now include which package they came from, so you actually can know if a type can be added to or not. I don't know if I can get it all hooked together for the release because you need to know what the root project name is, which I'm not sure how easy it'd be to grab.

In any case, I'll try to make the error message nicer.

**Comment by evancz** [comment]
It should not say a wrong thing anymore. Thanks for the report!

**Comment by mgold** [comment]
Better than it was, thanks!
