### ISSUE TITLE
Missing type annotations, errors and warnings

### ISSUE THREAD

**Issue by mgold** [elm-lang/elm-compiler#1121]
I have some code without a type annotation, like this:
```elm
module Test where
type Nonempty a = Nonempty a (List a)

fromElement x = Nonempty x []
```
Module `Test` is not listed in `exposed-modules` in `elm-package.json`. When I run `elm make Test.elm --warn`, it issues no warnings about this missing type annotation. (It correctly does not error on the missing annotation.)

With this code in the "real" module that *is* listed as exposed, I get

```
$ elm make --warn
=================================== WARNINGS ===================================

-- missing type annotation ------------------------------- ././List/Nonempty.elm

Top-level value `fromElement` does not have a type annotation.

48│ fromElement x = Nonempty x []
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
I inferred the type annotation so you can copy it into your code:

fromElement : a -> Nonempty a

-- MISSING ANNOTATION ------------------------------------ ././List/Nonempty.elm

The value `fromElement` does not have a type annotation.

48│ fromElement x = Nonempty x []
    ^^^^^^^^^^^
Adding type annotations is best practice and it gives you a chance to name
types and type variables so they are as easy as possible to understand!

Detected errors in 1 module.
````

If I do not pass `--warn`, I only see the test from `MISSING ANNOTATION` down, which does not include the inferred annotation. Because missing annotations in exposed modules is an error, ideally the error would include the inferred annotation even when warnings are off, and this particular warning would be suppressed even when warnings are on.

**Comment by mgold** [comment]
The exact same thing, actually. I thought warnings and printing the inferred type was new in 0.16. Whelp, not a regression, just a thing to tighten up if you like.

**Comment by evancz** [comment]
I think this will be covered by revamping the error reporting pipeline, so I'd like to close. I think it makes sense to track https://github.com/elm-lang/elm-make/issues/98 which will require that revamp.

**Comment by beenotung** [comment]
can the type be added automatically?
