### ISSUE TITLE
Incorrect parsing of strings containing backslash-whitespace

### ISSUE THREAD

**Issue by avh4** [elm-lang/elm-compiler#1123]
The parser currently tries to make use of Parsec's `stringLiteral` and `charLiteral` parsers which parse escaped characters and gaps.

If a string in an Elm source file contains backslash-whitespace, things go wrong.

This is notable in the following:
```elm
a = "\
"
b = "\ 
" -- Previous line has trailing space
```
which is parsed the same as
```
a = "\\n"
b = "n"
```

Literal chars and `"""` strings are also affected.  Here are a few other examples:

```elm
c = '\ ' -- does not compile (this is arguably correct)
d = """\ "hello" world""" -- parses as an empty string
```

**Comment by evancz** [comment]
Yow, very weird! Closing to track from the #1280 meta issue.

**Comment by despairblue** [comment]
May I add the `"\."` combination as well.

```elm
import Html exposing (text)

main =
  text "\."
```

Leads to the following compile error:

```
Detected errors in 1 module.


-- SYNTAX PROBLEM --------------------------------------------------------------

(line 1, column 3): unexpected "." expecting space, "&" or escape code

5|   text "\."
              ^
Maybe <http://elm-lang.org/docs/syntax> can help you figure it out.
```

Not sure if I should open a new issue for this, as it seems the underlying issue is the same.

**Comment by evancz** [comment]
The new parser does not use `stringLiteral` or `charLiteral` anymore. So you now get this error:

![screen shot 2016-12-17 at 8 53 21 pm](https://cloud.githubusercontent.com/assets/1658058/21291168/1346ff4a-c49b-11e6-8e01-009f1e36be4b.png)

Thanks for the report!
