### ISSUE TITLE
module Foo exporting (bar, qux)

### ISSUE THREAD

**Issue by mgold** [elm-lang/elm-compiler#1124]
From [this mailing list thread](https://groups.google.com/d/msg/elm-discuss/AgdSMznz2mw/QaWfk5FnDQAJ), Richard and I propose that `module Foo where (val1, val2)` be changed to `module Foo exporting (val1, val2)`. A module that exports everything will be written `module Foo exporting (..)`.

This makes the syntax match import, reads a little better (more explicitly), and makes it less burdensome to start making some values private.

As per the second post on the thread, we like the idea of distinguishing between what's _exported_ by the module author and what's _exposed_ by the package client.

**Comment by Apanatshka** [comment]
I think you mean that the current syntax is: `module Foo(val1, val2) where`

**Comment by mgold** [comment]
Right, sorry. So it's even further from the import syntax, with the list of things at the end, than I thought.

**Comment by esad** [comment]
Could we also have a simple syntax for exporting everything, but markign few functions as private, i.e.:

`module Foo exporting (..) hiding (bar, baz)`

**Comment by igrep** [comment]
@esad Sounds cool! :+1:

**Comment by rtfeldman** [comment]
@esad @igrep That's a separate feature; to keep discussions organized, would you mind opening a separate issue for it? Appreciate it!

**Comment by dasch** [comment]
Is there a good reason for putting all exported names in a single list? How about this:

```elm
module BinaryTree

{-| Building trees
-}
export insert, fromList

{-| Merging trees.
-}
export merge, mergeMany
```

Currently, you have to write a name three times when it's part of your module's API:

1. when defining it,
2. when exposing it from the module,
3. when referring to it from the module docs.

This seems like at least once too many. You could also prepend a keyword before the assignment, e.g. `exposed insert value tree = ...`.

**Comment by dasch** [comment]
By the way, I believe it's _exposing_, not _exporting_. I get confused by that a lot, too.

**Comment by mgold** [comment]
Nope: [see here](https://groups.google.com/d/msg/elm-discuss/AgdSMznz2mw/kQxwAOhoDQAJ).

**Comment by dasch** [comment]
Ah, ok.

**Comment by jvoigtlaender** [comment]
Isn't this issue obsolete now, as of commit https://github.com/elm-lang/elm-compiler/commit/47f165713ed4b46dc4946d7ab1cf182b80e5815c?

**Comment by mgold** [comment]
I still would have liked `exporting` and not `exposing`, but ... basically, yes.
