### ISSUE TITLE
Unsoundness when shadowing identifiers

### ISSUE THREAD

**Issue by seliopou** [elm-lang/elm-compiler#1127]
The following code compiles and behaves as expected:

```elm
import Graphics.Element exposing (..)
import Random exposing (..)
import Signal exposing (..)

genPoints : Int -> Generator (List { x : Float, y : Float })
genPoints n =
  let points =
    customGenerator <| \seed ->
      let (x, seed') = generate (float 0 640) seed in
      let (y, seed'') = generate (float 0 480) seed' in
      ({ x = x, y = y }, seed'')
  in
  list n points

genPoints' : Int -> Seed -> List { x : Float, y : Float }
genPoints' n s = fst (generate (genPoints n) s)

seed : Signal Seed
seed = Signal.constant (initialSeed 1234)

main : Signal Element
main =
  let randomPoints = genPoints' 100 <~ seed in
  show <~ randomPoints
```
However the following code produces the runtime error `Cannot read property 'state' of undefined`.

```elm
import Graphics.Element exposing (..)
import Random exposing (..)
import Signal exposing (..)

genPoints : Int -> Generator (List { x : Float, y : Float })
genPoints n =
  let points =
    customGenerator <| \seed ->
      let (x, seed) = generate (float 0 640) seed in
      let (y, seed) = generate (float 0 480) seed in
      ({ x = x, y = y }, seed)
  in
  list n points

genPoints' : Int -> Seed -> List { x : Float, y : Float }
genPoints' n s = fst (generate (genPoints n) s)

seed : Signal Seed
seed = Signal.constant (initialSeed 1234)

main : Signal Element
main =
  let randomPoints = genPoints' 100 <~ seed in
  show <~ randomPoints
```
The difference between the two is the naming of the intermediate seed identifiers. In the former, they are unique to the program. In the latter, they successively shadow themselves.

**Comment by seliopou** [comment]
This is on 0.15.1, installed form npm.

**Comment by jvoigtlaender** [comment]
Same root cause as https://github.com/elm-lang/elm-compiler/issues/1086? Which Evan said elsewhere that he has it fixed for Elm 0.16.

**Comment by jvoigtlaender** [comment]
Also https://github.com/elm-lang/elm-compiler/issues/1090 and https://github.com/elm-lang/elm-compiler/issues/1091.

**Comment by jvoigtlaender** [comment]
@seliopou, have you encountered anything like this on 0.16? Unfortunately it's not directly possible to try out your above code examples there, because `Random.customGenerator` was removed.

**Comment by jvoigtlaender** [comment]
@seliopou, is it or is it not still a problem on 0.16?

**Comment by evancz** [comment]
Not sure how to reproduce now, so will close. I believe this is a fancier case of #873 where we end up with mutually recursive self-definitions. I think it makes sense to track there. Thanks for the report!
