### ISSUE TITLE
Cannot read property 'time' of undefined

### ISSUE THREAD

**Issue by fuzzthink** [elm-lang/elm-compiler#1128]
Running examples/1 in https://github.com/evancz/elm-architecture-tutorial/

Triggered after clicking [rewind] in debug panel.

Running 0.15.1

**Comment by jvoigtlaender** [comment]
Can you move this issue over to https://github.com/elm-lang/elm-reactor? Also, first check whether there isn't already an issue open there that covers the problem you are reporting. For example, https://github.com/elm-lang/elm-reactor/issues/122 looks relevant, but there are also others that might be.
