### ISSUE TITLE
Feature request - unfoldl

### ISSUE THREAD

**Issue by MKloczko** [elm-lang/elm-compiler#1132]
Hey!

Elm 0.15.1 here

I'm not sure if this is the right repository to ask for such feature, but anyway...

I've been trying to simulate Lorenz attractor using Elm and ThreeJS. To do so, i generate points using tail recursion.

Above 1500 points, i hit the limit: too much recursion.

The same problem could be either solved through implementing unfold function or using tail recursion optimisations.

**Comment by mgold** [comment]
Can you ask this on the [mailing list](https://groups.google.com/forum/#!forum/elm-discuss)? There are a few ways to do what you're trying to do.

**Comment by MKloczko** [comment]
Oh.. thank you!

I should've tried looking for answers there first, thanks!

**Comment by evancz** [comment]
In 0.16, tail recursion for self-recursive functions will get optimized into while loops that can go on for however long you need. In the meantime, it's possible to use the `Trampoline` module in core.
