### ISSUE TITLE
Indentation-sensitivity does not close an expression

### ISSUE THREAD

**Issue by avh4** [elm-lang/elm-compiler#1135]
I would expect the following code to display `17`, but it instead displays `10` because the `+ 7` is parsed as following the `_ ->` clause instead of as following the case statement.

```elm
import Html

foo x = 
    case x of
        Just _ ->
            10
        _ ->
            100
    + 7


main = Html.text <| toString <| foo (Just ())
```

**Comment by jvoigtlaender** [comment]
Not that this needs to predetermine the behavior of Elm, but have you checked how other indentation-sensitive languages interpret this case, like Haskell?

**Comment by Apanatshka** [comment]
I ran it through haskell and it outputs 17:

```haskell
foo x = 
    case x of
        Just _ ->
            10
        _ ->
            100
    + 7

main = print $ foo $ Just ()
```

This is simply [Landin's off-side rule](https://en.wikipedia.org/wiki/Off-side_rule) at work, which is where all indentation-sensitive language base their parsing on AFAIK.

**Comment by evancz** [comment]
Track in #1375
