### ISSUE TITLE
Improve compiler warning when trying to update modules

### ISSUE THREAD

**Issue by maxhoffmann** [elm-lang/elm-compiler#1142]
```
-- SYNTAX PROBLEM -------------------------------------------- repl-temp-000.elm

I ran into something unexpected when parsing your code!

4|   Mymodule.value = "trying to change this"
                    ^
I am looking for one of the following things:

    end of input
    whitespace
```

This error message could be improved for people who think modules can be altered.

**Comment by jvoigtlaender** [comment]
Please move this over to https://github.com/elm-lang/error-message-catalog/issues, because that repo is exactly for this kind of thing.

**Comment by mgold** [comment]
Good catch, but as Janis says please move it to the other repo.

**Comment by maxhoffmann** [comment]
Moved to https://github.com/elm-lang/error-message-catalog/issues/55.
