### ISSUE TITLE
No kind checking

### ISSUE THREAD

**Issue by mgold** [elm-lang/elm-compiler#1146]
It is possible to use higher-kinded types in union types and type aliases:

```elm
type Impossible
    = A List
    | B (List Int Int)

type alias Uninhabited =
    { field : Dict String
    }
```

None of these types are possible, so while it's not hurting anyone, it's also kind of weird to let meaningless things be written down.

**Note:** Comment edited to summarize discussion and refinement in the further comments.

**Comment by mgold** [comment]
Failing test submitted in PR.

**Comment by jvoigtlaender** [comment]
Also, this
```elm
type A = B Maybe
```
is accepted, even though it is meaningless.

So the issue here is not really just about type aliasing. It is about a lack of kind checking.

Maybe rename the issue?

Also, [here](https://groups.google.com/d/msg/elm-discuss/GkNP-EbiHlI/obTnsas0BAAJ)'s a case where this (possibility of defining meaningless types this way) hit a user.

**Comment by evancz** [comment]
It's not 100% obvious to me that higher-kinded type aliases should not be permitted, but it does seem reasonable to demand that a certain things have kind `Type`, such as record fields or values in a union type. Stuff that needs to be a value that can exist!

**Comment by Heimdell** [comment]
Maybe, the compiler should perform a kind check at the declaration site? Is the kind of type atoms stored anywhere?

**Comment by mgold** [comment]
Another kind issue: extending record aliases with non-aliases crashes the compiler.

```elm
type alias Foo a =
  { a | bar : Int }
  
type alias Bar = Foo (Int -> Int)

bar : Bar
bar = {bar = 2}
```
The dumb solution is to improve the error message found [here](https://github.com/elm-lang/elm-compiler/blob/967c8959674ba4d9d64e139e9d1c623973ac27d7/src/Type/Type.hs#L332-L341).

**Comment by evancz** [comment]
Centralizing into #1373, will track from there.

**Comment by evancz** [comment]
The development branch resolves this by requiring that things line up syntactically. It is not doing a kind check during type inference though. So in this case, it is fixed with:

```
-- TOO FEW ARGS ------------------------------------------------------- temp.elm

The `Dict` type needs 2 arguments, but I only see 1:

15|     { field : Dict String
                  ^^^^^^^^^^^
What is missing? Is there some typo?
```
