### ISSUE TITLE
0.16 JSON.Decode mismatch

### ISSUE THREAD

**Issue by AZon8** [elm-lang/elm-compiler#1147]
Up front I will say two things. 
1) I Love this languages so far 
2) Sorry that this issue doesn't have a small scale example . No time to figure out the smallest working example. But i thought it would be worth posting anyway. 

File1 has :
```
type alias SomeType = {
 ... 
A : Maybe SubType
,B : Maybe SubType
}
```

File2 has :
```
decodeSomeType =
    Decode.object7 SomeType
       ... 
        (maybe ("A" := decSubType))
        (maybe ("B" := decSubType))
```
When decodeSomeType was given JSON (with only B defined. )
```
{
 B : {...}
}
```
it got mapped to a value with only A defined and B was Nothing

If this is a unkown bug and nobody can reproduce it , ill take some time this weekend to post an example

**Comment by jvoigtlaender** [comment]
This issue should be moved to the https://github.com/elm-lang/core repo.

The problem reported is not one I have heard of before.

Looking through the history of the relevant source files over in the `core` repo, it looks like in a long time there have been mainly documentation changes, nothing really that should lead to wrong behavior as above. So I wonder whether this is a problem specific to 0.16 or already existing for a longer time.

All in all, it would indeed be good to see a full example that exhibits the problem, in a new issue opened at https://github.com/elm-lang/core/issues.

**Comment by evancz** [comment]
I have not seen this before either. Thanks @jvoigtlaender for figuring out what needs to happen!

Please provide a http://sscce.org on a new issue on https://github.com/elm-lang/core/issues
