### ISSUE TITLE
Unable to update qualified record

### ISSUE THREAD

**Issue by unknownloner** [elm-lang/elm-compiler#1149]
The following results in a compile time error:
```
import SomeModule

modifiedValue = { SomeModule.defaultValue | something <- "Something Else" }
```
where the error is
```
I am looking for one of the following things:

    a closing bracket '}'
    a lower case name
    whitespace
```

Instead, one must do one of the following:

```
import SomeModule exposing (defaultValue)

modifiedValue1 = { defaultValue | something <- "Something Else 1" }

modifiedValue2 = 
  let
    default = SomeModule.defaultValue
  in
    { default | something <- "Something Else 2" }
```
It seems like updating the qualified record should be possible, and that it's just a bug in the current compiler.

**Comment by jvoigtlaender** [comment]
Yes, this is a syntactic limitation that shouldn't exist. It's almost certainly already reported in another issue in this repo. Can you please take a look through the existing issues page, see whether it was indeed already reported, then close this issue here as a duplicate?

**Comment by evancz** [comment]
Original report in #635 and now tracked in meta issue #1068
