### ISSUE TITLE
Writing isomorphic web application with Elm

### ISSUE THREAD

**Issue by gyzerok** [elm-lang/elm-compiler#1150]
Hi, @evancz!

I'm have been looking on Elm for a while and think its really great. So now I'm ready to try it in production and have an ability to move some tricky parts of a huge enterprise project to Elm to understand if it would really result in solving maintanability issues.

One part that I'm probably missing is an ability to render server-side since our project is very SEO-dependant. Is there a way to do it now?

**Comment by gyzerok** [comment]
Sorry, it seems to be a duplication of https://github.com/elm-lang/elm-compiler/issues/1113. I just used the wrong keys for search.

Just to clarify things. Do you plan to add this in 0.16?

**Comment by evancz** [comment]
There is not an easy route for this at the moment. You can already run Elm on node, no problem. But some libraries will cause issues. The elm-html library does not have a `renderToString` function that'd turn an `Html` type into the corresponding string of HTML.

So this is not really a compiler thing. 0.16 will not be addressing this, but it is a priority of mine to get this going a bit better. I don't have an exact timeline here though.

**Comment by gyzerok** [comment]
@evancz Can you provide a link on an example of running Elm on node? I would try to investigate in adding `renderToString` by my own.

**Comment by evancz** [comment]
So Elm just produces .js code, so you can put that through node like anything else.

The REPL does this, and adds a bit of [a prelude of code](https://github.com/elm-lang/elm-repl/blob/master/src/Eval/Code.hs#L103-L119) to fake certain things well enough for things to work out. In subsequent releases, the plan is to just have a compiler flag that will be runnable directly.

**Comment by gyzerok** [comment]
@evancz sorry for one more stupid question but I can't get from REPL how to use it server-side.

Here is my code:
```elm
module Server where

port input : Signal Int

port output : Signal Int
port output =
  Signal.map square input

square : Int -> Int
square a = a * a
```
```js
var Elm = require('./elm');
var ports = Elm.worker(Elm.Server).ports;
```
```
TypeError: Elm.worker is not a function
```

I've also found `elm-oracle` package which seem to use it like this https://github.com/ElmCast/elm-oracle/blob/master/bin/elm-oracle.

**Comment by evancz** [comment]
Can you ask on the mailing list? I think the issue is that the code is not set up to work through `require` but folks on elm-discuss know all about these things as well.

**Comment by Warry** [comment]
There is a library for virtual-dom.js : https://github.com/nthtran/vdom-to-html/

**Comment by gyzerok** [comment]
@evancz As a tricky way I now run compiler in this way:

`elm-make Main.elm && echo "if (typeof module !== 'undefined' && typeof module.exports !== 'undefined') module.exports = Elm;" >> elm.js`

It works. Maybe you can add this to the compiler directly to make things just work.

**Comment by gyzerok** [comment]
@evancz also I've send you to PRs which enables `renderToString` possibilities.
