### ISSUE TITLE
0.16 - section heading for warnings but not errors

### ISSUE THREAD

**Issue by rtfeldman** [elm-lang/elm-compiler#1152]
This screenshot shows a big yellow section heading for WARNINGS, followed by two warnings and then one error:

![screen shot 2015-11-09 at 5 35 29 pm](https://cloud.githubusercontent.com/assets/1094080/11076903/3798d142-87b2-11e5-8fdf-1adb64ddf2ec.png)

Presumably if there's going to be a section heading for warnings, there ought to be a corresponding big yellow ERRORS one too.

**Comment by evancz** [comment]
Please, I need a http://sscce.org to test these kinds of things.

With this example:

```elm
import Task

badCase maybe =
  case maybe of
    Just x ->
      42
```

I fixed it to see this result:

![screen shot 2015-11-11 at 12 35 02 pm](https://cloud.githubusercontent.com/assets/1658058/11091266/b0bc3a3c-8870-11e5-9479-55481a72a491.png)
