### ISSUE TITLE
0.16 - "wrong number of arguments" error just says "ARGUMENTS"

### ISSUE THREAD

**Issue by rtfeldman** [elm-lang/elm-compiler#1153]
Following the pattern of other error messages (e.g. `TYPE MISMATCH`, `MISSING PATTERNS`), presumably this one should say `TOO MANY ARGUMENTS`:

![screen shot 2015-11-09 at 5 32 26 pm](https://cloud.githubusercontent.com/assets/1094080/11077046/e626b972-87b2-11e5-8217-768afe5056d9.png)

**Comment by mgold** [comment]
To be clear, we're talking about the aqua text at the top?

Also, move to the error catalog?

**Comment by rtfeldman** [comment]
Yes, the aqua text - and I'd say this is more clearly a bug than a confusing error message. :smile:

**Comment by evancz** [comment]
This existed in 0.15 as well, but I fixed it anyway. It's a pretty easy one.
