### ISSUE TITLE
request: allow use of keywords as record field names

### ISSUE THREAD

**Issue by sporto** [elm-lang/elm-compiler#1160]
if I try:

```
type alias Config = {
  host: String,
  port: Int
}

config =
  Config "localhost" 3000
```

Compiler complains with:

```
unexpected keyword 'port', variables cannot be keywords
```

So I am wondering if this is a real limitation, I don't really understand why (port is a keyword, but why can't it also be used as a record field?)

it seems to me like this should be allowed.

**Comment by laszlopandy** [comment]
I had the same issue. I wanted to use the attribute "type" inside a record.

Most languages work this way: keywords cannot be used as variable
identifiers. In Python at least the convention is to put a trailing
underscore. So I used "type_".

**Comment by avh4** [comment]
The way the current parser works, I don't see any reason we couldn't allow keywords to be used as record fields.  Note that this would need to be supported not only in record types `{x:Int}` and expressions `{x=9}`, but also in patterns `{x}`, field access `r.x`, and field accessors `.x`.

**Comment by durkiewicz** [comment]
+1

**Comment by evancz** [comment]
Track in #1375
