### ISSUE TITLE
Infinite object recursion not detected at compile time

### ISSUE THREAD

**Issue by zoren** [elm-lang/elm-compiler#1161]
With this program
```elm
f = f
r = f 5
```
i was expecting a compile time type error warning me about infinite recursion i the declaration of `f`. Instead the program runs and i get a runtime error that 
> f is not a function

**Comment by jvoigtlaender** [comment]
There are open issues in this repo talking about this already. Can you check those, and if your case adds no new aspect, close it as a duplicate?

**Comment by zoren** [comment]
#873
