### ISSUE TITLE
Ports of type Int accept non-integer numbers

### ISSUE THREAD

**Issue by jdudek** [elm-lang/elm-compiler#1162]
Here’s the problem I mentioned in #1159.

See the following Elm program:

```elm
module Sample where

import Graphics.Element exposing (show)

main =
  let
    impossible =
      3 < int && int < 4

    msg =
      "Given integer: " ++ (toString int) ++
      (if impossible then " is bigger than 3 and smaller than 4" else "") ++
      ". Multiplied by 2: " ++ (toString (int * 2)) ++ "."
  in
    show msg

port int : Int
```

When run like this:

```javascript
Elm.fullscreen(Elm.Sample, { int: 3.14 })
```

It prints:

```
Given integer: 3.14 is bigger than 3 and smaller than 4. Multiplied by 2: 6.28.
```

(a full runnable example is here: https://gist.github.com/jdudek/d89c52f12b10f732d912)

I don’t know what would be the best expected behavior here. Either we convert values given to the port (e.g. with `parseInt`) or we raise an exception. We can check if a number is integer with [Number.isInteger](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/isInteger) (we can have a function in `Utils` that falls back to the polyfill).

I can work on this issue, if you think it’s worth fixing :)

**Comment by mgold** [comment]
JS -> Elm ports have a concept of invalid values, and I think we should build on that rather than silently converting floats to ints.

**Comment by evancz** [comment]
Should be relatively simple to add in. Can this be a PR?

**Comment by jdudek** [comment]
The PR is here: https://github.com/elm-lang/elm-compiler/pull/1164 :)

**Comment by evancz** [comment]
Ah, thanks! Should make it into 0.16 then :)

**Comment by evancz** [comment]
Alright, your fix just got merged. Thanks again! :D
