### ISSUE TITLE
[0.16] `Set comparable` type annotation forbidden

### ISSUE THREAD

**Issue by rtfeldman** [elm-lang/elm-compiler#1163]
This may be a duplicate of #1143, but posting it in case it's not. (If it's not a duplicate, I'll SSCCE it up.)

I had an annotation for an unrestrained `Set` in 0.15 (`Set comparable`) which I had to change to `Set a` in 0.16 alpha3 for it to compile: https://github.com/rtfeldman/elm-validate/commit/f8314715654ec431c5d4218b77ab70558bf38736

Error message in 0.16 alpha3 before I made that change:
<img width="814" alt="screen shot 2015-11-12 at 11 07 18 pm" src="https://cloud.githubusercontent.com/assets/1094080/11140777/24f70aee-8993-11e5-878d-519d85b92345.png">

(Separately, worth noting that the error message changed `comparable` to `b`, making the error message appear confused.)

Error message in 0.15.1 if I provide the `Set a` version that compiles in 0.16.
<img width="824" alt="screen shot 2015-11-12 at 11 05 47 pm" src="https://cloud.githubusercontent.com/assets/1094080/11140778/2630901a-8993-11e5-9392-6fdeee9e08f0.png">

**Comment by evancz** [comment]
Yes, I believe this is the same as the #1143 report. I don't fully get what the root is looking at Max's example. I can try to debug this on my flight and on Monday.

**Comment by mgold** [comment]
If you're at a loss for ideas, you can always try to `git bisect` and see where the bug was introduced.

**Comment by evancz** [comment]
I know about that ;)

**Comment by evancz** [comment]
Alright, I have resolved #1143 which seems to be the same thing.

Can you test this again? If it is still bad, open a new issue with a SSCCE. If that is the case, this is just gonna make it into 0.16.
