### ISSUE TITLE
Set.fromList [1,2,3,4] /= Set.fromList [4,3,2,1]

### ISSUE THREAD

**Issue by rtfeldman** [elm-lang/elm-compiler#1166]
This was true in 0.15 and it's still reproducible in 0.16. Run this in `elm-repl`:

```
> import Set
> (Set.fromList [1,2,3,4]) /= (Set.fromList [4,3,2,1])
True : Bool
```

Since these two Sets are identical, presumably this should return False, yeah?

**Comment by jvoigtlaender** [comment]
See https://github.com/elm-lang/core/issues/403#issuecomment-152402738.

**Comment by mgold** [comment]
The docs also state that *Set equality with `(==)` is unreliable and should not be used.*. This is not ideal, especially since one of my favorite insults of JavaScript is that `[] != []` (also `!==`). If there was a simple fix, it would be in place by now, right?

Another possibility is to add an `equals` function, similar to [what I did for elm-animation](http://package.elm-lang.org/packages/mgold/elm-animation/1.0.1/Animation#equals).

**Comment by mgold** [comment]
A slightly more minimal version:
```
> import Set
> Set.fromList [0,1] /= Set.fromList [1,0]
True : Bool
```

**Comment by Ryan1729** [comment]
I ran into this, and just want to mention this workaround:

```
> import Set
> s1 = Set.fromList [0,1]
Set.fromList [0,1] : Set.Set number
> s2 = Set.fromList [1,0]
Set.fromList [0,1] : Set.Set number
> Set.diff s1 s2 == Set.diff s2 s1
True : Bool
```

This has performance issues on sufficiently large sets, unfortunately.

**Comment by evancz** [comment]
Known, no need to track here for me.

**Comment by altaic** [comment]
So, how do interested parties follow along? This sort of opaqueness isn't very welcoming or confidence inspiring.

**Comment by evancz** [comment]
Some folks in the community are working on a way to share a roadmap that'll help with these kinds of things. Just trying to do a good job on stuff, and having tons of issues open about the same fundamental problem is not helpful. I am trying to trim all the issues here down to the like 5 or 6 real things that need work.

**Comment by altaic** [comment]
Thanks, I really appreciate your work. A shared roadmap sounds like a great addition to the community's resources.

Alternatively, or perhaps additionally, github's labels might help categorize and optionally hide less important issues. Some projects close and label to keep track of stuff that isn't immediately relevant but also isn't necessarily resolved.

My impression of closed yet unresolved elm-lang issues has been that they sort of vanish into the Sea of Abandoned Plans, which is a bit discouraging. OTOH, I get that the overhead of managing lots of less important stuff is sometimes just not worth it. Just my 2 cents, anyway.
