### ISSUE TITLE
asm.js as compilation target

### ISSUE THREAD

**Issue by gyzerok** [elm-lang/elm-compiler#1168]
I've done with nothing searching this in issues. What do you think about use asm.js as a compilation target for elm?

**Comment by jvoigtlaender** [comment]
There have been some related discussions on the mailing list at least: https://groups.google.com/forum/#!searchin/elm-discuss/asm.js

**Comment by gyzerok** [comment]
@jvoigtlaender thanks!

**Comment by evancz** [comment]
I hear the browser folks are planning to create a standard sort of garbage collector. We'll see though. If that ever exists, this will be a much easier project :)
