### ISSUE TITLE
No way to put self-made types into the Set

### ISSUE THREAD

**Issue by Heimdell** [elm-lang/elm-compiler#1169]
The `Set`'s `comparable` constraint on its type argument allows to put inside only "Int, Float, Char, String, lists, or tuples". However, there are some pretty neat things which I'd like to have a `Set` of - `type Point3D = {x : Int, y : Int, z : Int}`, for instance.

The solution I see (without changes to Elm type system), is to add a new `Set'` type which has a ctor `Set'.emptyWithComparison : (a -> a -> Ordering) -> Set' a` or `Set'.emptyWithProjection : (a -> comparable) -> Set' a`.

Or, we can have an ability to declare a type to be `comparable`. And `numeric`. And `appendable`. And `whatever`. Interfaces/typeclasses to the rescue!

P.S.: Moreover, I cannot even use the `Point3D` as the `Dict`'s key! Its quite disappointing.
P.S.S: For now, I can circimvent the problem by storing `(Int, Int, Int)` and having `toTuple`/`fromTuple` conversions, but it feels clumsy.

**Comment by jvoigtlaender** [comment]
Are you aware of https://github.com/elm-lang/elm-compiler/issues/1008 and of the sub-issues that meta-issue is tracking? Does your case add anything to that discussion?

**Comment by Heimdell** [comment]
Now I am. Nothing new, except for proposition to add ability to declare new typeclasses/instances.

**Comment by jvoigtlaender** [comment]
Well, *that* proposition is not particularly new either. :smile: 

Believe me, it's been discussed again and again and again...

Anyway, probably you can close this issue here, then? (as a clean-up measure for the repository)

**Comment by Heimdell** [comment]
Yes.
I hope, it will be discussed further. Along with "add higher-kinded types".
