### ISSUE TITLE
[0.16] "branches of this `case` produce different types of values" compiler crash on windows

### ISSUE THREAD

**Issue by phouchguk** [elm-lang/elm-compiler#1171]
Compiling this with the 0.16 alpha 3 compiler crashes on windows

Code:

    import Html exposing (text)

    main =
      let
        x = 5

        s = case x of
          5 -> { name = "Hello, World!", nr = 42 }
          7 -> { nme = "Seven", nr = 7 }
          _ -> { name = "Dunno", nr = 0 }
      in
        text s.name

Error:

    The 1st and 2nd branches of this `case` produce different types of values.

    12│         case x of
    13│       5 -> { name = "Hello, World!", nr = 42 }
    14│>      7 -> { nme = "Seven", nr = 7 }
    15│       _ -> { name = "Dunno", nr = 0 }

    The 1st branch has this type:

        { elm-make.exe: <stderr>: hPutChar: invalid argument (invalid character)

**Comment by mgold** [comment]
On Mac, it prints `{ …, name : … }` so I suspect Windows does not like the single-character ellipses.

This example also looks pretty bad on elm-lang/try (special port) because the various text color encodings are getting escaped into the HTML.

**Comment by laszlopandy** [comment]
@phouchguk Which language and encoding settings do you have on windows? We have seen issues in the past with non-utf8 windows systems.

**Comment by phouchguk** [comment]
@laszlopandy It's English (United Kingdom). I had no issues with the 15.1 compiler on this same machine.

**Comment by phouchguk** [comment]
@laszlopandy Ok I've researched around and if I change the code page in the command prompt with 'chcp 65001' I no longer get the compiler error but some of the symbols still look strange (ellipses is ok, just after the ellipses and where it denotes the line number). That'll be the font I guess.  Do we really need to use Unicode chars in the compiler messages? I'd use linux at home but I'm trying to push Elm at work. Is this a barrier to entry for Windows users?

**Comment by evancz** [comment]
Aww, that is a shame. I figured the ellipsis would be a character that wouldn't be too crazy.

I want to release it and see how many folk show up with this problem. If it is a lot, we can do `...` instead.

@phouchguk, what was the link you found that suggested the `chcp 65001` command? What is that doing? The more we know about your setup, the easier it will be to figure out if this is a systematic issue.

**Comment by phouchguk** [comment]
@evancz I think this was the link https://stackoverflow.com/questions/388490/unicode-characters-in-windows-command-line-how. I'm by no means a unicode on Windows expert! As far as I know my Windows settings are standard UK. I've used the pre-compiled windows binary for 0.16. The compiler crashes as above if i run elm make in node command prompt or git bash. If I run the chcp 65001 command the compiler doesn't crash but the output is still slightly mangled.

**Comment by evancz** [comment]
Lame! I'm testing what it looks like with `...` and it looks worse, but acceptable.

Okay, can you say more about what "slightly mangled" means? Can you just put what you are seeing directly into this thread to check if there are other problems?

**Comment by phouchguk** [comment]
-- TYPE MISMATCH ------------------------------------------------------ Main.elm


The 1st and 2nd branches of this `case` produce different types of values.

 7│��         case x of
 8│��       5 -> { name = "Hello, World!", nr = 42 }
 9│��>      7 -> { nme = "Seven", nr = 7 }
10│��       _ -> { name = "Dunno", nr = 0 }

The 1st branch has this type:

    { …��, name : …�� }

But the 2nd is:

    { …��, nme : …�� }

Hint: I compared the record fields and found some potential typos.

    name <-> nme

Hint: All branches in a `case` must have the same type. So no matter which one
we take, we always get back the same type of value.

Detected errors in 1 module.

This is *after* I've run the chcp 65001 command. I'm away now until the morning (for me). Cheers.

**Comment by evancz** [comment]
Interesting! I am actually using some [unicode box-drawing characters](https://en.wikipedia.org/wiki/Box-drawing_character) to do the vertical bars, so it looks like you get the question marks after non-ascii things now. What is cool is that the vertical bar worked in the original message!

I use these box characters (along with some arrows) for error messages for cyclic dependencies. I'm going to give you a test program in one second, hold on!

**Comment by evancz** [comment]
Okay, what do you see when you compile this program with alpha3?

```elm
type alias Comment =
  { message : String
  , upvotes : Int
  , downvotes : Int
  , responses : Responses
  }

type alias Responses = List Comment
```

Most importantly, can you show it with and without `chcp 65001`? I think it should work *without* but would like to make sure.

**Comment by phouchguk** [comment]
Without I get the same error:

    -- ALIAS PROBLEM ---------------------------------------------------- Cyclic.elm
    
        
    This type alias is part of a mutually recursive set of type aliases.

    1│>type alias Comment =
    2│>  { message : String
    3│>  , upvotes : Int
    4│>  , downvotes : Int
    5│>  , responses : Responses
    6│>  }

    The following type aliases are mutually recursive:

    ┌─────┐
    │    Comment
    │     elm-make.exe: <stderr>: hPutChar: invalid argument (invalid character)

With chcp 65001 I get:

    -- ALIAS PROBLEM ---------------------------------------------------- Cyclic.elm


    This type alias is part of a mutually recursive set of type aliases.

    1│��>type alias Comment =
    2│��>  { message : String
    3│��>  , upvotes : Int
    4│��>  , downvotes : Int
    5│��>  , responses : Responses
    6│��>  }

    The following type aliases are mutually recursive:

    ┌��─��─��─��─��─��┐��
    │��    Comment
    │��     ↓��
    │��    Responses
    └��─��─��─��─��─��┘��

    You need to convert at least one `type alias` into a `type`. This is a kind of
    subtle distinction, so definitely read how to fix it and have great
    code:<https://github.com/elm-lang/elm-compiler/blob/0.16.0/hints/infinite-alias.
    md>

    Detected errors in 1 module.

This is with the build you posted to elm-dev in Oct. I don't know how to get a build that incorporates #1174 changes...

**Comment by evancz** [comment]
Okay, I am switching the arrows to be roughly this:

```
|
V
```

so it'll work for everyone. Thanks again for reporting this. Any negativity you are sensing from me is directed at windows for taking away my precious arrows and dots!

**Comment by phouchguk** [comment]
I sensed no negativity :) I lold at the issue title. Elm is a revelation to me. I'm on my second production Elm app (production means windows at my job :( ). Thank you for your hard work. Let me know if you need me to test a build or anything. Cheers.
