### ISSUE TITLE
Request: Even more helpful error messages

### ISSUE THREAD

**Issue by sporto** [elm-lang/elm-compiler#1181]
If I do something like:

```elm
message =
  1
  
format: String -> String
format str =
  "Hello" ++ str

main =
  text (format message)
```

I get an error:

```
The 1st argument to function `format` has an unexpected type.

11|   text (format message)
As I infer the type of values flowing through your program, I see a conflict
between these two types:

    String

    number
```

But from the error it is not clear enough what I am doing wrong. I cannot see if I am expecting a string and giving a number or the other way around.  

This is pretty easy to figure out in this trivial example, but in a complex app figuring out where the wrong type is coming from can be quite difficult.

Would it be possible to provide more information in the error? e.g.

```
The 1st argument to function `format` has an unexpected type.

11|   text (format message)
As I infer the type of values flowing through your program, I see a conflict
between these two types:

    format expects: String

    given: number
```

Just adding an indication of what is expected and what was given will help a lot.

**Comment by jvoigtlaender** [comment]
Version 0.16 of the compiler, which will be released in the next few days, will have this feature.
