### ISSUE TITLE
Update changelog for 0.16

### ISSUE THREAD

**Issue by Apanatshka** [elm-lang/elm-compiler#1191]
I was looking for a quick exhaustive list of all the changes in 0.16, rather than the nice blog post, so I looked in the changelog. But it's not updated yet.. Can you add the syntax changes and the breaking changes in core please? :)

**Comment by jvoigtlaender** [comment]
Have you seen this?

https://github.com/elm-lang/elm-platform/blob/master/upgrade-docs/0.16.md#updating-syntax

**Comment by Apanatshka** [comment]
Ah, that's what I was looking for. Is this the new policy, to have upgrade docs? Then maybe the changelog should be removed?

**Comment by evancz** [comment]
Maybe a PR to add a link to this and the blog post in the change log?

**Comment by igrep** [comment]
How about this? https://github.com/elm-lang/elm-compiler/pull/1215

**Comment by evancz** [comment]
Awesome, thanks!
