### ISSUE TITLE
Typechecking can be circumvented by compiling individual modules

### ISSUE THREAD

**Issue by colinmccabe** [elm-lang/elm-compiler#1193]
Say you have three modules, Main, A and B.

Main imports A and A imports B, so the dependency graph looks like this:

Main <- A <- B

1. Suppose the program typechecks initially. Build the entire module graph with `elm-make Main.elm`
2. Change the signature of a function in B that is called by A, but do not update A.
3. Run `elm-make B.elm`. This succeeds as expected since B is internally consistent.
4. Run `elm-make Main.elm`. This succeeds, even though A is inconsistent with B!

In step #4 elm-make doesn't appear to check if A and B are consistent with each other since they are already built.

It's easy to stumble on this when using the Elm Sublime plugin, which lets you build individual modules with Ctrl+B.

This doesn't happen when the dependency graph is only two levels deep (Main <- A) since `elm-make Main.elm` always rebuilds and checks Main.

Example - https://gist.github.com/colinmccabe/4a0c7a2769ab98a80d3e

**Comment by evancz** [comment]
Tricky! Not sure how to resolve this, but can you move it over to https://github.com/elm-lang/elm-make/issues where the root issue lives?

**Comment by mgold** [comment]
Done (linked above).
