### ISSUE TITLE
0.16 - function closure incomplete in let binding

### ISSUE THREAD

**Issue by kurtharriger** [elm-lang/elm-compiler#1196]
Just started learning elm by creating a simple battleship game.
I was trying to understand out how to create nested state machines and ran into a bug where the let binding does not appear to close over all required values.

I wanted something like the following:

```
 view address model =
   case model of
     Preparing prepareModel ->
       let prepareHandler action =
         let prepareModel = (updatePreparing action prepareModel)
             {placed, selected, orientation} = prepareModel
         in
         if (length placed) == 5 then PlayGame (placed, [])
         else PrepareAction prepareModel
       in
       prepareView
        (Signal.forwardTo address prepareHandler) prepareModel
```

Here prepareHandler takes an action and expects prepareModel to closed over. However, when I run this I got a javascript error `'Uncaught TypeError: Cannot read property 'placed' of undefined`.

If I explicitly add prepareModel to prepareHandler as followed then code then works as desired:
```
 view address model =
   case model of
     Preparing prepareModel ->
       let prepareHandler prepareModel action =
         let prepareModel = (updatePreparing action prepareModel)
             {placed, selected, orientation} = prepareModel
         in
         if (length placed) == 5 then PlayGame (placed, [])
         else PrepareAction prepareModel
       in
       prepareView (Signal.forwardTo address (prepareHandler prepareModel)) prepareModel
```
Here is an original source and diff to reproduce the issue.

https://github.com/kurtharriger/elm-battleship/compare/elm-bug?diff=split&name=elm-bug

**Comment by laszlopandy** [comment]
Can you slim it down to make a minimal example which can be compiled on its
own?

**Comment by jvoigtlaender** [comment]
I think you are accidentally shadowing the prepareModel variable in your original code. So this is the standard problem of a self-recursive definition. See #873.

**Comment by jvoigtlaender** [comment]
That the revised code works is caused by the fact that you have implicitly applied the make-stuff-lazy-by-introducing-a-function-thunk trick. So you simulate some limited lazy evaluation, which happens to make the definition well-defined enough, contrary to the standard strict evaluation interpretation.

**Comment by kurtharriger** [comment]
Renaming value to prevent shadowing also resolves this. 
So probably probably duplicate of #873 then, thanks!
