### ISSUE TITLE
Move the 0.16 tag so that people installing from source get the post-release fixes

### ISSUE THREAD

**Issue by jvoigtlaender** [elm-lang/elm-compiler#1197]
@evancz?

**Comment by evancz** [comment]
I just moved this because I figured out the remaining issues with ANSI. Working on updating installers now.

**Comment by lluchs** [comment]
Please don't move tags. It makes tracking changes hard and silently breaks the [AUR package](https://aur.archlinux.org/packages/elm-platform/#comment-522940).
