### ISSUE TITLE
"Wrong" type displayed in elm-repl

### ISSUE THREAD

**Issue by imeckler** [elm-lang/elm-compiler#1199]
Here is a session with the repl

```elm
> (\x -> case x of { Just x -> x ; Nothing -> 0 })
<function> : Maybe.Maybe a -> a
```

It's a bit confusing because the number type variable is simply shown as `a`. It's clear that elm knows the type variable is not a general one because we get

```elm
> (\x -> case x of { Just x -> x ; Nothing -> 0 }) (Just "")
## ERRORS in repl-temp-000.elm #################################################

-- TYPE MISMATCH --------------------------------------------- repl-temp-000.elm

The 1st argument to this function has an unexpected type.

3|          case x of { Just x -> x ; Nothing -> 0 }) (Just "")
                                                       ^^^^^^^
As I infer the type of values flowing through your program, I see a conflict
between these two types:

    a

    String
```

**Comment by jvoigtlaender** [comment]
The second example you show indeed suggests it is not just an `elm-repl` problem. It seems to be a type checker/inference problem of some kind. The error message should contrast `number` and `String`, not `a` and `String`.

@evancz, could this be a side effect of https://github.com/elm-lang/elm-compiler/commit/dae8e04abfa388b3b72e47a5cee0c6fc63a92806 or some such of the recent fixes concerning treatment of constrained type variables?

**Comment by imeckler** [comment]
> The second example you show indeed suggests it is not just an elm-repl problem. It seems to be a type checker/inference problem of some kind. 

Oh, I actually took the second example as evidence that the type was correct, but the printed representations of the type was wrong.

**Comment by jvoigtlaender** [comment]
Indeed, also possible (if there is a difference between "type is correct" and "printed representation of type is correct" in the implementation, i.e., if something non-trivial happens during printing).

**Comment by evancz** [comment]
What version of Elm are you using?

Here's what I am seeing with 0.16.

![screen shot 2015-12-01 at 12 36 53 am](https://cloud.githubusercontent.com/assets/1658058/11495926/b85bdae2-97c3-11e5-9552-10b7d4381be5.png)

Possible to close this?

**Comment by jvoigtlaender** [comment]
Ah, actually the original problem as reported cannot have been with 0.16, because `(\x -> case x of { Just x -> x ; Nothing -> 0 })` isn't even legal syntax in 0.16.

**Comment by evancz** [comment]
Yeah, that's what I was thinking, but I wanted to check to see if I was thinking straight. I guess I'll preemtively close then. Please reopen if something is off!
