### ISSUE TITLE
Compiler generates invalid JavaScript instead of rejecting syntactically invalid Elm (qualified tags in union types)

### ISSUE THREAD

**Issue by jvoigtlaender** [elm-lang/elm-compiler#1200]
From this Elm code:

``` elm
module Test where

type A = B.C
```

the compiler generates this JavaScript code:

``` javascript
Elm.Test = Elm.Test || {};
Elm.Test.make = function (_elm) {
   "use strict";
   _elm.Test = _elm.Test || {};
   if (_elm.Test.values) return _elm.Test.values;
   var _U = Elm.Native.Utils.make(_elm),
   $Basics = Elm.Basics.make(_elm),
   $Debug = Elm.Debug.make(_elm),
   $List = Elm.List.make(_elm),
   $Maybe = Elm.Maybe.make(_elm),
   $Result = Elm.Result.make(_elm),
   $Signal = Elm.Signal.make(_elm);
   var _op = {};
   var B.C = {ctor: "B.C"};
   return _elm.Test.values = {_op: _op,B.C: B.C};
};
```

which fails at runtime like so:

```
   var B.C = {ctor: "B.C"};
        ^
SyntaxError: Unexpected token .
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3
```

**Comment by laszlopandy** [comment]
Please send a PR with the example in the good/ directory. For example, like this PR:
https://github.com/elm-lang/elm-compiler/pull/1179/files
Then when Evan fixes the issue, he will have a easy test case to check if the right output is produced.

**Comment by jvoigtlaender** [comment]
I'm afraid your request makes no sense. There is no "correct code" here. The compiler should reject the Elm program!

**Comment by deadfoxygrandpa** [comment]
@jvoigtlaender there's also a "bad" directory for files that should not compile. I added a case for this issue in the above PR.

**Comment by jvoigtlaender** [comment]
Okay, that makes more sense. :smile:

**Comment by agrafix** [comment]
I can confirm this bug, ran into it, too. ( https://github.com/agrafix/elm-html-shorthand/commit/a674950a60ffce48d0ac85f4c9a40e4482c94c1f )

**Comment by ccapndave** [comment]
And me too :)

**Comment by jfeaver** [comment]
For people running into this issue: The solution is probably to use a [Type Alias](https://guide.elm-lang.org/types/type_aliases.html):

```elm
module Test where

type alias A = B.C
```

**Comment by jvoigtlaender** [comment]
No.

**Comment by evancz** [comment]
Fixed by the new parser!

![screen shot 2016-12-17 at 8 43 06 pm](https://cloud.githubusercontent.com/assets/1658058/21291105/7d544de0-c499-11e6-9a6d-bad84faf1780.png)

Thanks for the report!
