### ISSUE TITLE
Literate Elm?

### ISSUE THREAD

**Issue by davidmason** [elm-lang/elm-compiler#1209]
I couldn't find anything about literate programming in Elm, but I think it would be a good candidate for it. Is anything like this possible or in the works? I am more than happy to have a go at implementing something that would parse literate elm programs if there is call for it and we can agree on some sensible syntax for it.

As a super-quick intro to those not familiar with the concept, literate programming is essentially flipping the concept of comments vs. code in the source file: text that is not marked up in any way is considered documentation, and code is specifically marked up to indicate it is code. The whole source file can still compile in the same way that a normal code file would.

For example, what if the compiler could handle markdown-style documents, compiling all the code-annotated parts into the program? This example supposes the compiler would treat anything indented 4 spaces as code, and anything "fenced" with triple-backticks (```) as code.

    mathemator.elmd
    # Mathemator
    
    This program takes mathematics to the next level!!! Why just add
    two things when you can add infinity things?!!
    
    ## Addition
    
    **additionator** adds as many things as you like together! Wow!
    *Note: numericals sounds fancier, right?*
    
        additionator : List Float -> Float
        additionator numericals = effin' (+) 0 numericals
    
    ## Subtraction
    
    **subtractionator** is like **additionator**, but a lot more negative.
    It pretty much just brings everybody down. Probably just don't invite it.
    
        subtractionator : List Float -> Float
        subtractionator victims = effin' (-) 0 victims
    
    
    ## Multiplication
    
    ***Caution: this can make some really big numbers!*** Make sure you
    have enough room to store all your numbers - maybe a *warehouse* or something.
    
        multiplicatinator : List Float -> Float
        multiplicatinator dimensions = effin' (*) 1 dimensions
    
    
    ## Utilities
    
    This takes the core logic of the mathemator funcitions so that it is not repeated.
    
    I could have written it with folds and stuff, but I love typing and I'm not
    some kind of Einstein math robot, gosh, get off my back man!
    I worked in a bit of a *nautical* theme here to help with understanding, since
    there's all this *Float*ing going on.
    
    ```
    effin' : (Float -> Float -> Float) -> Float -> List Float -> Float
    effin' swab yarrrrr plank =
      case plank of
        [] -> yarrrrr
        ye :: deck -> effin' swab yarrrrr deck |> swab ye
    ```

**Comment by igrep** [comment]
:+1:

**Comment by davidmason** [comment]
There are several possible formatting styles:

 - markdown (plain or github-flavoured)
 - "bird" style: prefix code lines with `> `
 - latex stye. I have not learned any latex, but it features in [Literate programming | haskell wiki](https://wiki.haskell.org/Literate_programming)
 - etc.

There is also the question of whether to include a macro system. My gut feeling is that it would not add much, since Elm is already fine with definitions in whatever order. It may not add much of use.

A few other features I would like in a literate elm compiler:

 - [ ] can put text between any code lines, even if it would split up an expression.

  ```
  I start an if-expression:
      if wantToGo
        then "sure"
  I don't really want to give a clear "no" here. Keep 'em guessing.
        else "maybe... maybe"
  ```

 - [ ] all error messages use the correct line and column numbers. It would be easy (depending on formatting style) to just strip out the non-code lines and feed them into the normal elm compiler, possibly sacrificing the proper context information.
 - [ ] ability to include non-elm code blocks, which are treated as documentation.

        So I write Elm with the 'fence' syntax and no language specified:
        
        ```
        getName : { name : Maybe String } -> String
        getName { name } = Maybe.withDefault "Anonymous" name
        ```
        
        or with elm specified...
        
        ```elm
        type alias Person = { name : Maybe String }
        ```
        
        ... although that may be better to use for showing elm code that is not evaluated
        
        Then I can write some JavaScript that the compiler will just ignore.
        Mainly handy for writing docs that compare elm with other languages,
        I would guess.
        
        ```javascript
        function getName (person) {
          return person.name ? person.name : 'Anonymous'
        }
        ```
        
        Another thought, for JavaScript specifically, is to possibly specify some
        of it to include in the compiled .js file, but I doubt this is something
        that anyone would really want to encourage.

**Comment by evancz** [comment]
What is your goal here?

I have done some literate programming in Haskell and was not very into it. It ended up making my blog posts much harder to read because I kept having to show code that didn't *really* matter to getting an understanding of the key points. So I ended up with stuff that I didn't really work as a blog or as code.

Do you have a usage scenario that'd motivate further work on this? From there I can say some stuff about prioritization.

**Comment by davidmason** [comment]
@evancz my main motivation for suggesting this is just that it seems like a fun idea that might be fun to try implementing, so not much beyond a possible weekend project at the moment.

I can imagine a few scenarios where literate syntax might be a bit nicer to work with, but I have no pressing or immediate need:

 - small modules that have `README.md` with all the code and docs, and  `elm-package.json`, and nothing else. The imagined benefit would just be reducing the chance of the information in the readme getting out of sync with the code.
 - applications in teaching, where there might be a lot more text than code. It may be marginally easier for an educator to write, but whether there is any substantial value will depend on whether students find it easier to get started. I am thinking here particularly of younger students - primary school level. This would probably need a thesis to investigate before I could really say whether there would be any real benefit.

**Comment by evancz** [comment]
Okay, makes sense. I think there's a pretty low chance that this'd make it into the compiler for a few reasons:

  * Supporting an alternate parser is a big deal. I don't think there is adequate justification for that maintenance burden right now.
  * I prefer having one good way rather than two competing ways with different strengths. In this case, my experience would lead me to believe that students would do better with normal doc comments. That way there is no "new syntax" to learn when switching between literate and illiterate code. I have observed that even tiny changes can be pretty confusing for new people, and that's from total beginners to folks with programming jobs.

That said, I think it's possible to do this outside the compiler which would cool. If you have a pre-processor that strips out all the literate parts and removes whatever the "code line starter" character is, you could just feed that to Elm. You can leave all the vertical indentation the same so the line numbers would work out. This'd mean you'd get normal Elm errors that are correctly aligned with row and column.

So that'd be my recommendation. Now that I say it, maybe that'd be my recommendation even if I wanted to fold it in officially ;)

**Comment by davidmason** [comment]
> maybe that'd be my recommendation even if I wanted to fold it in officially. It is certainly a better route to that because it is zero risk for the compiler

I agree, as long as it is getting the positions right in error messages it is certainly good enough for me. Also sounds pretty straightforward, so I may have time to implement it soon.

**Comment by jigargosar** [comment]
@davidmason Hey has any work been done around it? I am really impressed by this idea.

**Comment by davidmason** [comment]
@jigargosar No work so far. As you can guess from the delay in my response, I have had a lot on (daughter born in December and had a sick relative who passed away earlier this year).

Anyone could have a go at implementing this. It would really just be a script that reads in a literate code file, replaces lines that are not Elm code with empty lines, then feeds it to the elm compiler. It could be as simple as:

 - lines with ` ``` ` or ` ```elm ` start a block of code
   - lines with ` ``` ` end the current code block
 - in a code block, all lines are kept
 - outside a code block, lines with 4+ spaces at the start are kept, lines without are stripped

**Comment by jigargosar** [comment]
@davidmason I appreciate your response. Specially after all you have gone through.

I was just wondering if you had made any progress, if so I would love to see it. 

I understand that this might be easier to implement. But, from my past experience, every time I have started to work on a weekend project, it tends to expand itself in a bigger scope then initially estimated. Case in point jigargosar/elm-simple-gtd ;)

Once again, really appreciate your response.

**Comment by davidmason** [comment]
I think it would be fun to make, so I will keep it in mind. I am slowly catching up on everything, so I may make some time some month soon to have a crack at it.

If I can use a library to get an AST, that will avoid the incidental complexity of trying to do the initial parsing myself. From an AST with line/column numbers it should be straightforward.

This looks like it would do: https://github.com/textlint/textlint/tree/master/packages/markdown-to-ast

Code is:

```json
"type": "CodeBlock",
"lang": "elm", // or null
```
