### ISSUE TITLE
Unexpected types in type error in case expression

### ISSUE THREAD

**Issue by zgotsch** [elm-lang/elm-compiler#1211]
Running the code
```
strangeError : List Float -> List Float -> Maybe Float
strangeError xs ys = case (xs, ys) of
  ([], _) -> Nothing
  ((x::xs), ys) ->
    case strangeError x ys of
      Just match -> Just match
      Nothing -> strangeError xs ys
```
gives the error message
```
The 1st argument to function `strangeError` is causing a mismatch.

7│                  strangeError xs ys
                                 ^^
Function `strangeError` is expecting the 1st argument to be:

    List Float

But it is:

    List (List Float)
```

The error is due to the incorrect call `strangeError x ys` with a `Float` and a `List Float` instead of two `List Float`s. 

I expect an error like 
```
The 1st argument to function `strangeError` is causing a mismatch.

5│                  strangeError x ys
                                 ^
Function `strangeError` is expecting the 1st argument to be:

    List Float

But it is:

    Float
```

It seems like the compiler is assuming that the arguments in the call `strangeError x ys` are correct, which leads it to think that `xs` is of type `List (List Float)`. This surprises me, since it knows the matched `xs` in the case expression is of type `List Float`, so it should know that the shadowing `xs` in the matching expression is also of type `List Float`.

Let me know if you need anything else from me.

**Comment by kommen** [comment]
I think I just ran into the same issue.
Made up example to illustrate:

```elm
test : { foo : List String } -> List String
test model =
  let
    l = floor model.foo
   in
   List.reverse model.foo
 ```
leads to:
```
TYPE MISMATCH
The argument to function `reverse` is causing a mismatch.

7|    List.reverse model.foo
Function `reverse` is expecting the argument to be:

    List a

But it is:

    Float
```

I'd expect that the compiler infers the type of `model.foo` from the type declaration and tell me that I can not pass a `List String` to `floor`.

**Comment by jvoigtlaender** [comment]
Ouch, this second example is really frustrating. I'm not sure whether this issue should be here or in the https://github.com/elm-lang/error-message-catalog repository. Because I'm not sure this is a compiler *error* per se.

@evancz, what do you think?

**Comment by zgotsch** [comment]
I originally filed it here because it seemed that typechecking was throwing away type information when trying to unify.

**Comment by kommen** [comment]
@jvoigtlaender It look to me this could be reported there already as https://github.com/elm-lang/error-message-catalog/issues/71

**Comment by jvoigtlaender** [comment]
Right. I hadn't made the connection, though I had seen that other issue. But yes, it might be the same thing.

But I must say the concrete problematic example shown here is the most hurting one. It almost defeats what the 0.16 announcement post says about the helpfulness of "expected vs. actual" type hints. The example can even be brought down to a more minimal one:
```elm
test : List String -> List String
test list =
  let
    l = floor list
  in
    List.reverse list
```
I'll add that over there.

**Comment by evancz** [comment]
Definitely for the error message catalog. Type inference checks the body of a definition before trying to unify it with a type annotation. There is definitely an issue on the error message catalog about this already.
