### ISSUE TITLE
Expose internal compiler modules?

### ISSUE THREAD

**Issue by pkamenarsky** [elm-lang/elm-compiler#1212]
I have some spare time and would like to explore the possibilities of writing some external tools for elm, like refactoring support etc. However, this would require that `elm-compiler` exposes some internal modules like `AST.*`.

Other tools like `elm-format` seem to just copy the compiler source into their project structure, but this doesn't seem like an optimal solution.

Are compatibility concerns the only reason why these modules aren't exported?

**Comment by jvoigtlaender** [comment]
Note that the issues of this repository are not used for this kind of question. They are mainly used for reporting and tracking bugs (and to some extent for feature suggestions). The question you ask would be more appropriate for the `elm-dev` mailing list. See http://elm-lang.org/community#mailing-list. (In particular, the sentence "Check this out if you are looking to contribute to projects like the compiler or elm-package.")

**Comment by pkamenarsky** [comment]
Ah, I see - sorry about that. I'll cross post in elm-dev.
