### ISSUE TITLE
syntax proposal: disallow whitespace in operator-turned-function

### ISSUE THREAD

**Issue by jvoigtlaender** [elm-lang/elm-compiler#1213]
This is a kind of companion to https://github.com/elm-lang/elm-compiler/issues/1210.

The proposal here is to disallow stuff like `( + {- whee -} )`. Turning an operator into a function should be `(operator)`, nothing else.

Reasoning follows:

It is already the case that conversely turning a function into an operator can only be done as ``x `f` y``, not as ``x ` f ` y`` or other whitespacey stuff. So it seems odd to allow `( + )` instead of only `(+)`.

The operator section syntax was taken over from Haskell (I suppose). But there, the situation is different. It allows syntax like `(12 +)` and `(+ (17-3))`. Since arbitrary expressions must be allowed to the right or left of the operator in such partially applied sections, it makes sense (and seems unavoidable) to also allow whitespace, and to do so in every case, even the "pure" case of no parameters provided. But in Elm these other cases don't exist. One can *only* turn an operator into a non-applied function. Hence, no motivation for allowing anything else than exactly `(+)`.

**Comment by evancz** [comment]
Follow along in #1375
