### ISSUE TITLE
Record identifiers cannot start with an underscore

### ISSUE THREAD

**Issue by ccapndave** [elm-lang/elm-compiler#1218]
Specifically for using Elm and PouchDB it is necessary to have records with un-Elmy names like `_id`, `_rev` and `type`.  It would be good if there were special syntax for using any string as a record name (similar to quoting keys in JSON).

**Comment by rgrempel** [comment]
One workaround for this sort of thing is to use `Json.Encode` and `Json.Decode.decodeValue` to move back and forth between a Javascript object (with the keys that you need) and the Elm record.

Here's an example:

```elm
module Test where

import Json.Encode as JE
import Json.Decode as JD exposing ((:=))

type alias ElmRecord =
    { id : Int
    , rev : Int
    , type' : String
    }
    
encode : ElmRecord -> JE.Value
encode record =
    JE.object
        [ ( "_id", JE.int record.id )
        , ( "_rev", JE.int record.rev )
        , ( "type", JE.string record.type' )
        ]
 
decoder : JD.Decoder ElmRecord
decoder =
    JD.object3 ElmRecord
        ( "_id" := JD.int )
        ( "_rev" := JD.int )
        ( "type" := JD.string )
```

You could then use `encode` and `Json.Decode.decodeValue decoder` to move back and forth between the raw Javascript object with the special keys you need and the Elm record.

If you're dealing with JSON objects which come from elsewhere anyway, it's actually kind of nice to de-couple the JSON format from the type of the Elm record.

**Comment by ccapndave** [comment]
Ok, I'll try it.  Thanks!

**Comment by jvoigtlaender** [comment]
Isn't this issue essentially the same as https://github.com/elm-lang/elm-compiler/issues/1160?

**Comment by jvoigtlaender** [comment]
@ccapndave, is your issue here different from #1160? If not, please close it.

**Comment by ccapndave** [comment]
Its similar, but not quite the same - #1160 is specifically talking about identifiers that are Elm keywords like `type`, `port`, etc, whereas this is talking about "non-Elmy" identifiers; for example, things that start with an underscore.  (That's not to say that the fix won't cover both these issues though!)

**Comment by jvoigtlaender** [comment]
Ah, I see. Probably you should rename the issue then. What you mean by "keywords" is not clear from the title.

**Comment by evancz** [comment]
Right now there's a general rule that variables do not start with underscores in any context in Elm. I was reserving it to possibly mean things, like in Go or something. Someday a final decision will be made and we'll get this or not.
