### ISSUE TITLE
Bad type definition generates invalid js instead of compiler error

### ISSUE THREAD

**Issue by mattrrichard** [elm-lang/elm-compiler#1219]
```
import Html 
import Http

type alias MyError = String

type Error 
  = MyError
  | Http.Error
  

main = 
  Html.text "Oops"
```

No compiler error happens, and the generated javascript contains `var Http.Error = {ctor: "Http.Error"};` which causes a syntax error and no user code is run.

**Comment by jvoigtlaender** [comment]
This is already reported. Please look around.

**Comment by jvoigtlaender** [comment]
Duplicate of https://github.com/elm-lang/elm-compiler/issues/1200. Please close.

**Comment by mattrrichard** [comment]
Oops! I looked but I didn't see any that looked like the same issue.
