### ISSUE TITLE
Confusing error message

### ISSUE THREAD

**Issue by G4BB3R** [elm-lang/elm-compiler#1222]
The error is that I need to convert the model.count with toString before using it in the `text` function, but the error is really confusing to newcomers.

![image](https://cloud.githubusercontent.com/assets/6143964/11617736/e8199e62-9c79-11e5-8157-22c2ebec3995.png)
![image](https://cloud.githubusercontent.com/assets/6143964/11617740/f037e568-9c79-11e5-87af-5e3befff425d.png)

**Comment by mgold** [comment]
This is probably better suited for the [error message catalog](https://github.com/elm-lang/error-message-catalog/issues/new).

That said, "whenever the inferred definition says String, suggest using `toString`" is not a bad rule.

**Comment by jvoigtlaender** [comment]
@G4BB3R, since you have moved the issue over to the error message catalog, you should close it here.
