### ISSUE TITLE
Bad error message for `comparable` errors in recursive functions

### ISSUE THREAD

**Issue by JoeyEremondi** [elm-lang/elm-compiler#1224]
Was fiddling around with the Dict library, seeing what would be needed to make a generic dictionary, when I stumbled across this error message:

Here's a minimal code snippet:

```elm
import Basics exposing (..)
import Maybe exposing (..)
import List exposing (..)
import Native.Debug

type NColor
    = Red
    | Black
    | BBlack  
    | NBlack 


type LeafColor
    = LBlack
    | LBBlack 


type Dict k v
    = RBNode_elm_builtin NColor k v (Dict k v) (Dict k v)
    | RBEmpty_elm_builtin LeafColor


get : (a, a -> a -> Order) -> Dict (a, a -> a -> Order) v -> Maybe v
get targetKey dict =
  case dict of
    RBEmpty_elm_builtin _ ->
      Nothing

    RBNode_elm_builtin _ key value left right ->
      case compare targetKey key of
        LT ->
          get targetKey left

        EQ ->
          Just value

        GT ->
          get targetKey right
```

Which gives this lovely error:
```
Function `get` is expecting the 1st argument to be:

    ( a, a -> a -> Order )

But it is:

    ( a, a -> a -> Order )
```

I can see that the actual error is that I'm trying to use `compare` on something that isn't comparable, but to a beginner this error message gives zero information.

**Comment by mgold** [comment]
Is this related to #1192?

**Comment by JoeyEremondi** [comment]
Looks like it is, missed that. I was assuming it was a glitch with the `comparable` quasi-typeclass

**Comment by mgold** [comment]
Yeah, I've stumbled across this in a seemly-unrelated issue as well.

If you paste the code sample (and delete `import Native.Debug`) into share-elm, which runs 0.15, you can an error message that complains about `a -> a -> Basics.Order` and `comparable`. This is a pretty bad regression in either the error detection code or the printing code.
