### ISSUE TITLE
Runtime error due to forgotten name normalization, probably in tail call optimization

### ISSUE THREAD

**Issue by jvoigtlaender** [elm-lang/elm-compiler#1226]
While this program works:
```elm
import Html

go n = if n > 0 then go (n-1) else 1

main = Html.text (toString (go 5))
```
this one doesn't:
```elm
import Html

go n' = if n' > 0 then go (n'-1) else 1

main = Html.text (toString (go 5))
```
(Check at http://elm-lang.org/try)

It appears that somewhere during tail call optimization, the name `n'` is not properly escaped, so the `'` is interpreted as start of a string literal.

@evancz or @JoeyEremondi, does this ring a bell with you?

**Comment by evancz** [comment]
Can you paste the relevant JS in here as well?

Should be a pretty easy fix.

**Comment by jvoigtlaender** [comment]
```js
Elm.Main = Elm.Main || {};
Elm.Main.make = function (_elm) {
   "use strict";
   _elm.Main = _elm.Main || {};
   if (_elm.Main.values) return _elm.Main.values;
   var _U = Elm.Native.Utils.make(_elm),
   $Basics = Elm.Basics.make(_elm),
   $Debug = Elm.Debug.make(_elm),
   $Html = Elm.Html.make(_elm),
   $List = Elm.List.make(_elm),
   $Maybe = Elm.Maybe.make(_elm),
   $Result = Elm.Result.make(_elm),
   $Signal = Elm.Signal.make(_elm);
   var _op = {};
   var go = function (n$) {
      go: while (true) if (_U.cmp(n$,0) > 0) {
            var _v0 = n$ - 1;
            n' = _v0;
            continue go;
         } else return 1;
   };
   var main = $Html.text($Basics.toString(go(5)));
   return _elm.Main.values = {_op: _op,go: go,main: main};
};
```

**Comment by jvoigtlaender** [comment]
Most likely, one or more calls of [`Generate.JavaScript.Variable.safe`](https://github.com/elm-lang/elm-compiler/blob/2521c5e9c03c89354bb0773bdd0bfb3e197b9d32/src/Generate/JavaScript/Variable.hs#L87-L92) need to be added somewhere in the tail call optimization code.

**Comment by laszlopandy** [comment]
Please add an expected js test for it and send a PR. It will make fixing it
much quicker.

**Comment by jvoigtlaender** [comment]
Sorry, but I have to ask: Is there any evidence that bugs are fixed sooner if tests exist for them?

**Comment by jvoigtlaender** [comment]
https://github.com/elm-lang/elm-compiler/pull/1250

**Comment by laszlopandy** [comment]
@jvoigtlaender No there is not. But I believe it's better to break the task into smaller pieces and involve more people. Otherwise Evan gets stuck doing everything.

**Comment by jvoigtlaender** [comment]
Yes, yes. I was being a bit snarky, sorry about that. I added a test case above.

About breaking the task into smaller pieces, though: That means that there are now two tickets vying for Evan's attention, namely the bug report ticket and the test case PR. So that might actually not help at all with speeding things up. See, for example, the test case PR https://github.com/elm-lang/elm-compiler/pull/1201 for another bug. That PR remains unmerged, even though it is "just" a test case. I wouldn't be surprised if at some point the underlying bug https://github.com/elm-lang/elm-compiler/issues/1200 gets fixed sooner than the test case is merged. Some procedure is not working here, I'm afraid.

**Comment by jvoigtlaender** [comment]
Maybe this is turning into too much meta, but:
> But I believe it's better to break the task into smaller pieces and involve more people. Otherwise Evan gets stuck doing everything.

My impression by now is that involving more people in submitting pull requests is not enough, as long as not more people are getting involved in merging pull requests as well.

**Comment by jvoigtlaender** [comment]
Okay, I have found the place where the normalization was missing. Fixed in https://github.com/elm-lang/elm-compiler/pull/1251.

**Comment by laszlopandy** [comment]
You are right about too many issues. Now that you have a fix, you should merge your fix with your test case and close this bug. Then there will be only one PR for Evan to review.
