### ISSUE TITLE
Runtime error with record initialization needs to be caught at compile-time

### ISSUE THREAD

**Issue by srikumarks** [elm-lang/elm-compiler#1228]
RHS values in record initializations may not refer to the record being initialized, but the compiler lets this through and it bombs at runtime. Compiling below code using "elm make test.elm" (v0.16) succeeds in producing an index.html. Loading the index.html results in the error - `undefined is not an object (evaluating 'costs.veggies')`.

```elm
module Test where
costs = { veggies = 5
        , bread = 3
        , spices = costs.veggies
        }
```

I don't see this as a compiler bug, but as a violation of the "no runtime errors" expectation.

**Comment by rgrempel** [comment]
It looks like this is a duplicate of, or at least related to, #873, #912 and #1194.

**Comment by srikumarks** [comment]
Indeed. As indicated in #912, it can be considered a duplicate of #873.

**Comment by mgold** [comment]
It's slightly different than #912, since in that case you have two records that each rely on the other. In this case, you have a single record that references its own name.

I think `foo = { x = 3, y = foo.x }` would make a good expected-to-not-compile test case.

**Comment by srikumarks** [comment]
They all feel the same to me - RHS of a record/structure initialization refers to a value that isn't available "yet".

The primary reason this can't be supported in Elm is that it is eager. While general laziness is out of scope, I wonder whether we can support this kind of initialization-laziness for variables defined within a single let block using a [spreadsheet-like evaluation technique][loeb] (just speculating). That would give an "it just works" feel to let blocks.

[loeb]: http://blog.sigfpe.com/2006/11/from-l-theorem-to-spreadsheet.html

**Comment by mgold** [comment]
I mean, that *could* work, but it would make the implementation more complicated for a feature that doesn't seem to get much use. Also, it could lead to, "wow that compiled? Hope is works as I intended," even if it does.

It's already possible to do `foo = let val = 3 in {x = val, y = val}`.

That said, I agree this should be caught and rejected at compile time.
