### ISSUE TITLE
Runtime Error with Debugger on Html

### ISSUE THREAD

**Issue by trotha01** [elm-lang/elm-compiler#1229]
We get a runtime error when running Debug.log on html

Here's a minimal example:
```
import Html exposing (div)
import Debug

main = Debug.log "div" (div [] [])
```

The error is ```Uncaught TypeError: Cannot use 'in' operator to search for 'ctor' in null``` from a toString function.

I don't know if we want to support this or to print a compiler error.
This is with elm 0.16.0

**Comment by jvoigtlaender** [comment]
@trotha01, this is covered by https://github.com/elm-lang/core/issues/488, and also linked there is a pull request possibly resolving this. In any case, `elm-compiler` is not really the right repository for this. Can you close this issue?

**Comment by trotha01** [comment]
Thank you for following up @jvoigtlaender, I will close and follow along the other issue.
