### ISSUE TITLE
Infinite type for self-recursive definition causes compiler crash

### ISSUE THREAD

**Issue by evancz** [elm-lang/elm-compiler#1231]
The following code snippet (as reported in #1230) puts the compiler into an infinite loop of some sort.

```elm
f = f (f f f)
```

Running this on OS X, it just never stops for me. In previous attempts to fix this, the problem was actually in pretty printing, not in type inference. If you look into this, be sure to pinpoint *when* things start looping before looking for the problem.

Also look into these: #1240, #1241

**Comment by evancz** [comment]
This expression is now rejected by the check for values defined directly in terms of themselves from #873.

**Comment by jvoigtlaender** [comment]
What about #1240 and #1241, though? Both are currently closed because they were replaced by this instance here, and both are not prevented by the fix to #873.

**Comment by evancz** [comment]
Please create an http://sscce.org/ that works with 0.18 that represents them.

**Comment by auxsoft** [comment]
#1380 still crashes the compiler with OOM in 0.18. I'm posting here in case my comment in the other issue goes missing.

**Comment by nonpop** [comment]
I don't know whether I should open a new issue or not, but here is an example which makes elm 0.18 freeze.

```elm
module Test exposing (..)


type alias Focus b s =
    { get : b -> s
    , update : (s -> s) -> b -> b
    }


create : (b -> s) -> ((s -> s) -> b -> b) -> Focus b s
create get update =
    { get = get
    , update = update
    }


idF : Focus { r | id : a } a
idF =
    create .id (\f s -> { s | id = f })  -- should be { s | id = f s.id }
```

If I remove the type annotation from `idF` it will produce an error message about a weird self-referential type, but with the annotation the compiler will freeze.

**Comment by evancz** [comment]
Always open a new issue.
