### ISSUE TITLE
Allow `main` to have type String

### ISSUE THREAD

**Issue by dasch** [elm-lang/elm-compiler#1232]
This is of course a bit stupid for anything other than a first Hello World application, but I actually believe that those are the most important ones if you want to get new people to start using Elm. Having to figure out how to use the Elm tools to get `elm-html` or use `Graphics.Element` is a barrier to just playing around with some code. Getting a String to show up on the screen is a big achievement for someone who has never used a functional language before.

Imagine this Hello World program:

```elm
main = "Hello, World!"
```

Boom? Boom.

**UPDATE:** `Signal String` would of course also make sense.

**Comment by 5outh** [comment]
I don't know of any language that allows you to write something like this. Typically the shortest "Hello, World" program in any language will be something along the lines of `print("Hello, World!")`. In Elm, this is:

```
main = text "Hello, World!"
```

which seems clear and concise to me -- allowing `main = "Hello, World!"` to compile seems a bit unintuitive/confusing.

**Comment by dasch** [comment]
```
$ elm make HelloWorld.elm
-- NAMING ERROR ------------------------------------------------- HelloWorld.elm

Cannot find variable `text`

1│ main = text "Hello, World!"
          ^^^^


Detected errors in 1 module.
```

**Comment by dasch** [comment]
I think that's *both* unintuitive *and* confusing. Most languages have a global `print` function of sorts, which Elm lacks. I think assigning a string to `main` would be pretty damn good.

**Comment by doppioslash** [comment]
my 2c:
Elm is a language different from the kind of language that would allow you to do `main = "hello world"`. 
It's not Python, and its objectives are quite different from Python.
In fact just doing `main = "hello world"` doesn't tell you anything about how Elm actually works. 
And I can't imagine that the people who get stuck if main don't conform to their dynamically typed OOP expectation, will be able to wrap their heads around Signals without some effort ^^;; 
So why lead them on with an artificially easy hello world?

**Comment by dasch** [comment]
Because it's a nice way to explore a new language without the overhead of a DOM? You can still do a lot of stuff, e.g. play around with fibonacci and other introductory problems. Why would we want to push a DOM library onto people for no reason other than that it's the "right thing"? It's not like `main` doesn't already accept multiple types, one of which is not even in the core library...

**Comment by dasch** [comment]
I actually think numbers should be allowed as well.

**Comment by laszlopandy** [comment]
You don't need numbers to be supported because there is a global built in `toString`. But otherwise I agree it's nice to have `String` supported. I often try things quickly in the online editor (instead of using the REPL) and it would be nice not to have to wrap it in `text`.

**Comment by 5outh** [comment]
Essentially have strings auto-cast to `Html` where appropriate?

**Comment by mgold** [comment]
I've written `import Graphics.Element exposing (show)` more times than I can count. Obviously no one is going to use this for an actual website, but it makes it much easier to try things out.

**Comment by dasch** [comment]
@mgold maybe `main` should just accept anything that `show` does? It took me a while to even discover `Graphics.Elements.show`. Initially I thought it was part of some 2D drawing lib.

**Comment by mgold** [comment]
`show` accepts literally anything, so I'm not sure that's a good idea.

**Comment by dasch** [comment]
Sounds good to me – it'll just pretty-print whatever you hand off to `main`. A great way to get started.

**Comment by evancz** [comment]
I'm not going to make this change
