### ISSUE TITLE
Strange characters appearing in compiler output outside of terminal

### ISSUE THREAD

**Issue by AWaselnuk** [elm-lang/elm-compiler#1233]
I get strange characters appearing (i.e. `[33m` `[0m`) in compiler output when it is appearing in non-terminal apps. Attached is a screenshot of the output in Google Chrome (via elm-reactor), the Sublime Text console, and iTerm. Notice that the output is clean in iTerm but not in the other two.

![screen shot 2015-12-17 at 9 17 58 am](https://cloud.githubusercontent.com/assets/3630241/11871731/69fd0d9c-a49f-11e5-952f-850fc3b9672c.png)

**Comment by jvoigtlaender** [comment]
Which version of Elm? How installed?

It is very likely that you used a too early version of an 0.16 installer. An issue like you describe was caught and fixed within a few days of the 0.16 release. After the fix the installers were updated/replaced. Maybe you have one from before that?

**Comment by AWaselnuk** [comment]
@jvoigtlaender That's exactly what happened. Just reinstalled and it cleared up. Thanks for the help!
