### ISSUE TITLE
Elm 0.16 segmentation fault on Mac OS X 10.7.5

### ISSUE THREAD

**Issue by FranklinChen** [elm-lang/elm-compiler#1234]
I have an old MacBook from 2008 that can only run Mac OS X 10.7.5. The Elm 0.16 binary seg-faults on this platform. If nobody cares about 10.7.5, that's fine with me (I can try to build from source, just as I build GHC from source successfully), but maybe it should be noted in the documentation which versions of OS X are supported.

**Comment by mgold** [comment]
For reference, the current version of OSX is 10.11.

In order to document this properly, we'd need to know what version it starts working, i.e. maybe 10.8 is also borked.

**Comment by FranklinChen** [comment]
I'm too busy now to find and spin up a VM for 10.8, but will do that after holiday season. Like I said, low priority, but I'll get to it. My "real" Macs are current.

**Comment by evancz** [comment]
The suggested fix seems to be "should be noted in the documentation" but I do not know what that means concretely. @mgold, perhaps it makes sense to put it in the wiki of things to know?

I want to close this because I cannot act on it. If someone wants to gather more info on how all our installers work, that'd be great, but I can't lead that effort.

**Comment by mgold** [comment]
Not sure what wiki you had in mind. I think the version of OSX is old enough that it can be ignored.

**Comment by evancz** [comment]
Not sure what I had in mind either!

**Comment by FranklinChen** [comment]
It's safe to ignore my 2008 MacBook stuck at an unsupported version of Mac OS X :-). If I ever feel like getting Elm to work on it I'll submit a patch or something.

**Comment by mgold** [comment]
2008 is 8 years ago. Wow.

**Comment by FranklinChen** [comment]
"Wow" is right... my first car lasted 14 years, my second car is 11 years old now and going strong, yet my phone from 2 years ago is already obsolete.
