### ISSUE TITLE
Possible compiler bug: Cannot read property 'arity' of undefined

### ISSUE THREAD

**Issue by simonh1000** [elm-lang/elm-compiler#1237]
This code causes a runtime error: `Cannot read property 'arity' of undefined`.  Others have reported this  this error associated with elm-html, but I can see no link in my case.

If I switch to the commented code and don't use `pStructure`, everything works.

You can see the full code at https://github.com/simonh1000/json-interpreter/blob/dev/src/Parser.elm#L154

```
pArr : Parser Command
pArr =
    pStructure "array" Arr
    -- string "array" *> spacing *> pCommand
    -- `andThen` (succeed << Arr)

pStructure : String -> (Command -> Command) -> Parser Command
pStructure typ cnstrctr =
    string typ *> spacing *> pCommand
    `andThen` (succeed << cnstrctr)
```

**Comment by jvoigtlaender** [comment]
I'm pretty sure this is just yet another instance of https://github.com/elm-lang/elm-compiler/issues/873.

**Comment by jvoigtlaender** [comment]
@simonh1000, close this as a duplicate?

**Comment by MrMormon** [comment]
@simonh1000 Hello?
