### ISSUE TITLE
error when printing out types with kind errors

### ISSUE THREAD

**Issue by burnt43** [elm-lang/elm-compiler#1238]
I have a small program where I mess up a recursive data structure as show below.
```elm
type LList t = Empty t | Node t LList t
foo : LList Int
foo = 
  Node 5 Empty
```

When attempting to compile it will fail with the following message
<pre>
elm make repro.elm --output=repro.js
-- TYPE MISMATCH ----------------------------------------------------- repro.elm

The type annotation for `foo` does not match its definition.

2│ foo : LList Int
         ^^^^^^^^^
The type annotation is saying:

    elm-make: type applications should start with a type atom
</pre>

The elm-make is in yellow like "\033[0;33m" and is never set back to the default color so my terminal remains yellow until I clear it manually by printing out "\033[0;39m", so I'm not sure if this is a full message or if there is supposed to be more to it

**Comment by burnt43** [comment]
possible solution may be just to resolve the root issue #1146

**Comment by mgold** [comment]
Namely, that `Node t LList t` implies a `Node` has a `t`, a `LList`, and another `t`. Since `LList` is not a type on its own, this bombs. You're looking for `Node t (LList t)`.

**Comment by evancz** [comment]
Makes sense to fix the root issue instead of this.
