### ISSUE TITLE
CLA process too cumbersome

### ISSUE THREAD

**Issue by maxnordlund** [elm-lang/elm-compiler#1239]
The current contributor agreement process is _way_ too cumbersome, at least for most people. I do agree that having an CLA is a good thing, but requiring _every single_ PR author to first (like that's gonna happen) send an email with a _PDF_?

I think that is expecting too much, especially since signing PDF:s can be very hard depending on which platform/PDF reader you have available.

Instead I suggest to use an automated service, like the two examples below, to ensure that the CLA is followed.
* https://clabot.github.io/ (https://github.com/clabot/clabot)
* https://www.clahub.com/ (https://github.com/clahub/clahub)

P.S.
Sorry if it came across as a bit harsh, that isn't my intention, but I do feel strongly for this and will leave it as is
D.S

**Comment by evancz** [comment]
Started a discussion about this [here](https://groups.google.com/forum/#!topic/elm-dev/lLUDdcN3BVE). I think it makes sense to continue talking about it there. Can you bring up these two projects? On the mailing list, can you say who uses these projects for their CLA? Are there any languages that do?
