### ISSUE TITLE
compiler freezes compiling a recursive data type

### ISSUE THREAD

**Issue by folkertdev** [elm-lang/elm-compiler#1240]
my compiler freezes when compiling the following snippet of code. This was reproduced by people in the elm irc channel. 

I am not sure that this code should compile (I may need List.map instead of concatMap), but in any case it shouldn't freeze the compiler. 

```elm
import Dict exposing (Dict)

type Trie comparable = Trie Bool (Dict comparable (Trie comparable))

toList : Trie comparable -> List (List comparable)
toList (Trie final dict) = 
    List.concatMap (\(key, trie) -> key :: toList trie) (Dict.toList dict)
```

system: Linux mint with elm 0.16, installed via npm.

In addition, the elm playground at elm-lang.org/try doesn't compile this snippet either, and displays a "server refused connection". Maybe some feedback can be given? (something like "The server could not compile your code")

A possible cause is the recursive data structure. Using a fold over this data structure to try get a List of elements also freezes the compiler. 

UPDATE

when the type signature is removed, this code does compile, but its type signature was incorrect all along. When changing `List.concatMap` to `List.map`, the compiler freezes. Other ways of arriving at this type signature also result in a compiler freeze.

```elm
toList : Trie comparable -> List (List comparable)
toList (Trie final dict) = 
    List.map (\(key, trie) -> key :: toList trie) (Dict.toList dict)
```

**Comment by evancz** [comment]
It seems there are still cases where the compiler does not correctly catch infinite types. I have been tracking that #1231, so I'm going to close this issue and add a reference to it over there. This way I know to circle back to this one.
