### ISSUE TITLE
Undue Infinite type message

### ISSUE THREAD

**Issue by benzen** [elm-lang/elm-compiler#1241]
Doing the following produce an infinite type error.

I think we could have a much better type error for this case

````elm
import Maybe
import List

type alias Tile =  { value: Int  }

addTileToList: Tile -> Maybe (List Tile) -> Maybe (List Tile)
addTileToList tile value =
  case value of
    Nothing -> Just [tile]
    Just a -> Just (a ++ tile)
````

To solve this, the second advice the the infinite type wiki page help.

We just need to change this
````
elm
    Just a -> Just (a ++ tile)
````

For this

````elm
    Just a -> Just (tile::a)
````

Still it could be possible to give better help for this kind of cases.

Hope this help

**Comment by mgold** [comment]
It might be worth adding this example (or something similar) to the [infinite type page](https://github.com/elm-lang/elm-compiler/blob/master/hints/infinite-type.md). And it is an infinite type, since is it a list, or a list of lists, or so on.

That said, there's no real reason to have a maybe list. Just use the empty list.

**Comment by benzen** [comment]
In my case it was, but totally agree that for the sake of the minimal example it should be remove

**Comment by benzen** [comment]
```elm
import List

type alias Tile =  { value: Int  }

addTileToList: Tile -> List Tile -> List Tile
addTileToList tile value =
  case value of
    [] -> [tile]
    a -> (a ++ tile)
```

**Comment by evancz** [comment]
I'd recommend reporting the poor error message at https://github.com/elm-lang/error-message-catalog/issues

In the meantime, I'll add a reference to #1231 because when I work on this topic, it'll be through that entry point and I can come find these things again.
