### ISSUE TITLE
Proposal: Remove exhaustiveness check in the repl

### ISSUE THREAD

**Issue by imeckler** [elm-lang/elm-compiler#1242]
I find the exhaustiveness check to be a nuisance when using the repl. For example, while experimenting with the `Date` module, I have to type 
```elm
> x = case Date.fromString "10/1/2015" of \
|  Ok x -> x \
|  Err _ -> Debug.crash ""
```
rather than 
```elm
> x = case Date.fromString "10/1/2015" of Ok x -> x
```
or 
```elm
> Ok x = Date.fromString "10/1/2015"
```
which is surprisingly a syntax error. I guess patterns being removed from let bindings makes sense in light of the mandatory exhaustiveness since single-constructor ADTs are mostly useless, but still it is nice to have in cases like this…

**Comment by evancz** [comment]
This makes sense, but I don't see it happening any time soon. I think it makes sense to have this proposal on elm-repl so I'm gonna close here.
