### ISSUE TITLE
Proposal: Special case relational operators

### ISSUE THREAD

**Issue by porglezomp** [elm-lang/elm-compiler#1243]
I've been writing some code with numerical constraints, and have run into lots of cases where I'm writing `a < b && b < c`. I feel like we could take a note out of Python's book and special case the syntax to allow that to be written `a < b < c`. Similarly, allow `a == b && b == c` to be written `a == b == c`.

## Benefits:
- Many comparisons become more natural and succinct to express.

## Downsides:
- Potentially difficult to support for user-defined operators.
  It's questionable how much of a downside this is since custom infix operators are generally discouraged in Elm, but it bears mentioning.
- More complexity in the parser.

## Implementation:
Relational operators would be parsed without any associativity, and then transformed.
An AST like
```
[ a, OP1, b, OP2, c, OP3, d ]
```
would then be transformed into
```elm
let
  a' = a
  b' = b
  c' = c
  d' = d
in
  a' OP1 b' && b' OP2 c' && c' OP3 d'
```

Thoughts?

**Comment by mgold** [comment]
I agree, in principle, that this would be useful for `a < b <= c` comparisons that are common in mathematics. The major problem is that the tokens `a < b` are an expression on their own, of type Bool. One would have to keep two possibilities open parsing the next characters, looking for either the completion of the two-operator-three-value pattern, or some acceptable use of a Bool.

It's not impossible, but it sounds a bit tricky and it only solves a very superficial problem.

**Comment by rtfeldman** [comment]
This doesn't seem worth it...having all operators be simple functions seems more valuable than allowing this!

**Comment by evancz** [comment]
Agree with @rtfeldman on this one. I knew about this in Python when I initially made these operators and chose not to have that.
