### ISSUE TITLE
decoder is not a function

### ISSUE THREAD

**Issue by bartavelle** [elm-lang/elm-compiler#1244]
Here is a minimal test case:

    module Main where
    
    import Html exposing (div, text)

    import Json.Decode exposing (..)
    import Dict exposing (Dict)
    
    type Rec = A Int
             | R (List Rec)
    
    decodeSumObjectWithSingleField : String -> Dict String (Decoder a) -> Decoder a
    decodeSumObjectWithSingleField name mapping = keyValuePairs value `customDecoder` \lst -> case lst of
        [(key,value)] -> decodeSumFinal name key value mapping
        _ -> Err ("Can't decode " ++ name ++ ": object has too many keys")
    
    decodeSumFinal : String -> String -> Value -> Dict String (Json.Decode.Decoder a) -> Result String a
    decodeSumFinal name key value mapping =
        case Dict.get key mapping of
            Nothing -> Err ("Unknown constructor " ++ key ++ " for type " ++ name)
            Just dec -> Json.Decode.decodeValue dec value
    
    decRec : Decoder Rec
    decRec =
        let dic = Dict.fromList
                    [ ("A", map A int)
                    , ("R", map R (list decRec))
                    ]
        in  decodeSumObjectWithSingleField "Rec" dic
    
    sample : String
    sample = "{\"R\":[{\"A\":1}]}"
    
    main : Html.Html
    main = div [] [text <| toString <| decodeString decRec sample]

It displays `Err ("custom decoder failed: decoder is not a function")` instead of the expected decoded output. I think this is related to #873, but I really am not sure.

**Comment by mgold** [comment]
Anyone have any idea how to get this down to an [SSCCE](http://sscce.org/)?

I can guess that some kind of JS runtime error is occurring, which is caught and turned into an `Err`.

**Comment by bartavelle** [comment]
While debugging I noticed that the "decoder" variable was undefined.
Le 1 janv. 2016 5:05 PM, "Max Goldstein" <notifications@github.com> a
écrit :

**Comment by bartavelle** [comment]
This is the faulty code:

    var decRec = function () {
      var dic = $Dict.fromList(_U.list([{ctor: "_Tuple2"
                                        ,_0: "A"
                                        ,_1: A2($Json$Decode.map,A,$Json$Decode.$int)}
                                       ,{ctor: "_Tuple2"
                                        ,_0: "R"
                                        ,_1: A2($Json$Decode.map,R,$Json$Decode.list(decRec))}]));
      return A2(decodeSumObjectWithSingleField,"Rec",dic);
   }();

In the second entry of the `Dict`, `decRec` is undefined!

**Comment by mgold** [comment]
I didn't even see the recursive call in all of that!

**Here is an SSCCE:**
```elm
import Graphics.Element exposing (show)
import Json.Decode exposing (..)

type Person = Person { name : String, children : List Person }

decode : Decoder Person
decode =
  map Person <|
    object2 (\n c -> {name = n, children = c})
      ("name" := string)
      ("children" := list decode)

json =
  """ { "name": "Nat King Cole", "children": [ { "name": "Natalie Cole", "children": [] } ] }"""

main = show <| decodeString decode json
```

It seems recursive decoding is buggy.

**Comment by jvoigtlaender** [comment]
It's not recursive *decoding* that is buggy. It's just again that recursive values are problematic. Just another instance of #873.

**Comment by jvoigtlaender** [comment]
Or https://github.com/elm-lang/core/issues/361 if you want it more specific.

**Comment by jvoigtlaender** [comment]
@bartavelle, your code can be made to work, as follows:
```elm
module Main where

import Html exposing (div, text)

import Json.Decode exposing (..)
import Dict exposing (Dict)

type Rec = A Int
         | R (List Rec)

decodeSumObjectWithSingleField : String -> Dict String (() -> Decoder a) -> Decoder a
decodeSumObjectWithSingleField name mapping = keyValuePairs value `customDecoder` \lst -> case lst of
    [(key,value)] -> decodeSumFinal name key value mapping
    _ -> Err ("Can't decode " ++ name ++ ": object has too many keys")

decodeSumFinal : String -> String -> Value -> Dict String (() -> Json.Decode.Decoder a) -> Result String a
decodeSumFinal name key value mapping =
    case Dict.get key mapping of
        Nothing -> Err ("Unknown constructor " ++ key ++ " for type " ++ name)
        Just dec -> Json.Decode.decodeValue (dec ()) value

decRec : Decoder Rec
decRec =
    let dic = Dict.fromList
                [ ("A", \() -> map A int)
                , ("R", \() -> map R (list decRec))
                ]
    in  decodeSumObjectWithSingleField "Rec" dic

sample : String
sample = "{\"R\":[{\"A\":1}]}"

main : Html.Html
main = div [] [text <| toString <| decodeString decRec sample]
```
Can the issue be closed, then?

**Comment by bartavelle** [comment]
I already applied a workaround to my code, but I thought the issue was the code generator bug, not its manifestation in my specific use case ?

**Comment by jvoigtlaender** [comment]
Sure. But the code generator bug is already tracked in #873. So, the issue here could be closed irrespective of the code I posted above to address the specific use case. That, I posted just as a convenience.

**Comment by bartavelle** [comment]
Oh yes, sure!

**Comment by bartavelle** [comment]
(and thanks again by the way)

**Comment by yoni-tock** [comment]
For anyone else who stumbles on this issue, we ended up using

```elm
JSDecode.succeed () `JSDecode.andThen` recursiveDecoder
```

to thunkify the decoder in question
