### ISSUE TITLE
Minor issue: kind mismatch is allowed in typedecls, disallowing the object creation

### ISSUE THREAD

**Issue by Heimdell** [elm-lang/elm-compiler#1245]
Here is the code causing the issue:

```elm
import Graphics.Element exposing (..)

type A a = A (List A)

main = show "wat"

a = A []

b = A [A []]

```
When line with "b" is added, the elm-lang.org/try provides the next error message:
```
TYPE MISMATCH
The argument to function `A` is causing a mismatch.

9| b = A [A []]
Function `A` is expecting the argument to be:

    List A

But it is:

    List (A a)
```
I we comment out the line with "b", the module will compile happily and show us a `"wat"`.

The situation won't change much if we change typedecl to 
```elm
type A a = A (List (A String String))
```
I expect such _kind mismatches_ to be reported as errors at the declaration site. "As is" behaviour could lead to existence of libraries with untested types inside (for instance, due to their simplicity) which will cause the library user to loose his faith for the language.

**Comment by Heimdell** [comment]
Diplicate of #1146

**Comment by evancz** [comment]
Yep, thanks for the report. I'm going to close and have us follow along in the other issue.
