### ISSUE TITLE
Using Elm (or React) is a bad idea for performant graphics in the web.

### ISSUE THREAD

**Issue by trusktr** [elm-lang/elm-compiler#1247]
This runs laggy on my macbook: http://daiw.de/games/breakout/. The reason is because using Elm's functional diffing algorithm to calculate graphics is not a good idea (it's not a good idea to do this with React, Mercury, Om, Mithril, or any library with these concepts). To have control of graphics, the pipeline to the browser renderer needs to be pure and have the smallest layer above the browser's renderer. 

Making a game like that in Elm (or React, etc) causes the render path to go through Elm's  (or React's) diffing algorithms on each and every tick of the frame that needs to be drawn. That just isn't a good idea.

If you'd like to animate things with Elm (or React, Mithril, etc) one technique you can use for basic web sites is to use Elm only to modify CSS classes, then let the browser handle animations with CSS transitions. Another technique for things like a WebGL or Canvas app would be to let Elm (or React) components care only about start and end states, then let a renderer algorithm perform the animation to/from those states.

Compare the idea in the previous paragraph with calculating (and diffing) the position of an animation for each and every frame inside an Elm (or React) component. Lots of performance will be lost to the diffing algorithm on each tick. That won't be as fast, for example, as simply modifying a CSS class (or WebGL start/end state). When using the better technique, Elm will only be put in charge of calculating state at two possible moments: at the beginning of an animation or at the end. A renderer (for example one made in Three.js) will do the hard work between the two states. Compare that to the not-so-good approach of have Elm calculate all the animation positions between the two states. Invoking the diffing algorithm (and whatever else Elm (or React) do) in each frame is overkill.

**Comment by trusktr** [comment]
For reference, I talked about this over at Mithril: https://github.com/lhorie/mithril.js/issues/830#issuecomment-162136104

**Comment by jvoigtlaender** [comment]
The [mailing list](https://groups.google.com/forum/#!forum/elm-discuss) is suitable for such discussion. The issue tracker here is only for recording bugs and possibly feature requests concerning the Elm compiler.

So please close the issue.

**Comment by gabn88** [comment]
I just tried it on a 2013 macbook air but I saw not problems using safari? Maybe the code is updated?

**Comment by trusktr** [comment]
I wanted to add that @jwmerrill made [elm-animation-frame](https://github.com/jwmerrill/elm-animation-frame).

@jwmerrill could you explain briefly what elm-animation-frame does to speed things up?

**Comment by mgold** [comment]
It works by using [requestAnimationFrame](https://developer.mozilla.org/en-US/docs/Web/API/window/requestAnimationFrame) instead of [setTimeout](https://developer.mozilla.org/en-US/docs/Web/API/WindowTimers/setTimeout).

**Comment by FranzSkuffka** [comment]
`Time.milliseconds` allows you to change your model every millisecond. With `AnimationFrame` it's roughly every 30ms in most browsers. I do not know the implications for game mechanics that require high temporal precision.
