### ISSUE TITLE
Runtime error with arrays

### ISSUE THREAD

**Issue by ckoster22** [elm-lang/elm-compiler#1252]
Copy/paste into http://elm-lang.org/try

```
import Array exposing (Array)

type alias Box =
  { value : String }

convertTo2D : Array Box -> Int -> Array (Array Box)
convertTo2D boxArray numRows =
  let
    nextRow = Array.slice 0 numRows boxArray
  in
    if Array.length nextRow > 0
    then Array.push nextRow (convertTo2D (Array.slice numRows (Array.length boxArray) boxArray) numRows)
    else Array.empty

oneDimArray = Array.initialize 100 (\index -> { value = toString index })

temp = convertTo2D oneDimArray 10
```

This is boiled down from a larger application. The relevant error is:
"Uncaught TypeError: Cannot read property 'height' of undefined  everything.js:831"

**Comment by jvoigtlaender** [comment]
This is more likely relevant for the https://github.com/elm-lang/core repository, so I suggest moving the issue over to there. In fact, first please check whether there is already a relevant issue open there, to avoid duplication. If there is, just close the one here.
