### ISSUE TITLE
Inconsistency in extensible record syntax

### ISSUE THREAD

**Issue by TheRaspPie** [elm-lang/elm-compiler#1254]
The point of aliasing is that the alias represents exactly the same thing that it's aliased to.

Consider the following example:
```elm
import Graphics.Element exposing (..)

main = show test

type alias StringRecord = { string : String }
type alias ExtensibleIntRecord e = { e | int : Int }

--test : { StringRecord | int : Int }    -- doesn't work
test : ExtensibleIntRecord StringRecord  -- does work
test = { int = 10, string = "" }
```

So if have an extensible record type aliased to a name, I can write `ExtensibleType CombinedType` to get a new record type that contains the union of both types where
`type alias ExtensibleType e = { e | someRecordFields... }`

I can however only do this if I gave both types a named type alias, otherwise the compiler will give me the following error:
```
I ran into something unexpected when parsing your code!

8| test : { StringRecord | int : Int }    -- doesn't work
I am looking for one of the following things:

    "}"
    a lower case name
    whitespace
```

I am not exactly sure whether this is intended behaviour or a bug.

Maybe there could also be a way to directly union types in Elm:
```elm
type alias UnionType = { StringRecord | IntRecord }
```

**Comment by jvoigtlaender** [comment]
Also:
```elm
import Graphics.Element exposing (..)

main = show (test { int = 5 })

type alias StringRecord = { string : String }

-- test : { e | int : Int } -> Int   -- does work
test : { StringRecord | int : Int } -> Int   -- doesn't work
test { int } = int
```

**Comment by jvoigtlaender** [comment]
It's possibly just an issue in the parsing code, choking on uppercase identifiers in such places. See also https://github.com/elm-lang/elm-compiler/issues/635.

**Comment by evancz** [comment]
At the value level, records only allow *variables* in that position, not arbitrary expressions. It is the same logic here. Added this to the #1068 meta issue.
