### ISSUE TITLE
Problem with integer division for n > 2^31

### ISSUE THREAD

**Issue by kavon** [elm-lang/elm-compiler#1258]
The following program results in an incorrect value:

    import Graphics.Element exposing (..)
    
    x : Int
    x = 85899345920
    one : Int
    one = 1
    ten : Int
    ten = 10
    
    main : Element
    main =
        show (x // ten)   -- this results in 0, which is wrong
        -- show (x + one)  -- this works

I'm using `elm-make` to compile and running it in Firefox 43.0.4 on OS X, Elm 0.16

**Comment by mgold** [comment]
This is a precision and overflow issue. A better title would be, "Integer Division is Broken **for Integers ≥ 2^31**". In the REPL,

```elm
> 2^31 // 1
-2147483648 : Int
> (2^31 - 1)// 1
2147483647 : Int
```

We can see that this code
```elm
x = 2^31 / 1
y = 2^31 // 1
```
compiles to
```js                                                       
var x = Math.pow(2,31) / 1; 
var y = Math.pow(2,31) / 1 | 0;   
```

Integer division is implemented as normal division, with a bitwise operation to make it an integer -- *a 32-bit signed integer*.

The proper way to do this is `Math.floor`, but that might cause some other issue (and it's probably slower and more characters). However, at this point it time I think it seems somewhat reasonable that division is limited to 32-bit unsigned ints.

**Comment by kavon** [comment]
> I think it seems somewhat reasonable that division is limited to 32-bit unsigned ints.

I disagree completely, it's not type safe. You shouldn't have addition work for all `Int` type values, yet division, who also claims to accept `Int`, in fact does not work correctly for of the all values an `Int` can be.

**Comment by mgold** [comment]
It's typesafe, it's not the types that break, it's just not mathematically expected.

I agree it's a leaky abstraction and ideally it should be fixed. So yes, keep the issue open so it can be tracked. But, and I say this knowing Evan's workload, don't expect it to be patched any time soon.

**Comment by fredcy** [comment]
I got burned by this problem too and I agree that it should be fixed.

See also https://github.com/elm-lang/core/issues/92

**Comment by evancz** [comment]
What's the proposed change? You don't like how it works. How should it work instead?

**Comment by mgold** [comment]
`z = x // y` *could* compile to `var z = Math.floor(x / y)`. However, this would change the results for negative numbers:

```js
> (-3 / 2) | 0
-1
> Math.floor(-3 / 2)
-2
```

There is `Math.trunc` which behaves as we'd like. It requires a small polyfill for IE; see [mdn](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/trunc).

**Comment by evancz** [comment]
What's the behavior for Python's `(//)`?

**Comment by mgold** [comment]
In Python,
```python
>>> -3 // 2
-2
```

In Ruby,
```ruby
> -3 / 2
=> -2
```

So there's precedent for it working the same way as `Math.floor`. Haskell `div` works the way Elm currently does. There's not really an analogous case in JS because all numbers are floats.

**Comment by kavon** [comment]
> @mgold showed what the compiler produces now. What should it produce instead?

@evancz I'm not actually familiar with JS, so I'm not sure what the compiler should produce given that JS apparently has no integers (explains why you are using a bitwise ORing trick). If `Int` is defined as a 64-bit signed integer in Elm, then I think integer division should work as it always has in languages that have hardware support for integers such as C or Haskell, which would be the `Math.trunc` method proposed by @mgold; Python and Ruby's use of flooring and not truncation is bewildering.

**Comment by mgold** [comment]
That's a good point - even though Elm compiling to assembly is years away, we should go with what's more natural with machine integers.

**Comment by mgold** [comment]
There's one other thing to worry about, and that is `x//0 == 0`. It just so happens that `thing | 0` in JS happens to be zero even when `thing` is infinity or NaN. We definitely don't want to introduce an issue where NaN can slip in to being an integer.

**Comment by evancz** [comment]
Can someone summarize the final proposal here in a new issue?

**Comment by rdprescott** [comment]
Hello all!  I would like to re-open that case.  I don't think someone doing an integer division of two positive number can expect a negative number as an output.  At least not with a high level language promoting reliability as a prime value.

I don't see anything in the comments that justify that behaviour.

My two cents as a user.

**Comment by rlefevre** [comment]
@rdprescott see https://github.com/elm/compiler/issues/1832, particularly https://github.com/elm/compiler/issues/1832#issuecomment-440081267.

**Comment by Selbstdiagnose** [comment]
@kavon  Python and Ruby's use of flooring and not truncation is bewildering.

I think this due to a difference in operator precedence
In Python unary minus takes precedence over (//):
` (-3) // 2` evaluates to ` -2 `
` -(3 // 2)` evaluates to `-1`
In Haskell it is different, but you get the same behaviour using parentheses:
` (-3) div 2` gives `-2` (haskell also seems to round towards negative infinity)
` -(3 div 2)` gives `-1`
So `-3 // 2` means ` -(3 div 2)` in Haskell and `(-3) // 2` in Python.
