### ISSUE TITLE
`\` Unavailable as literal

### ISSUE THREAD

**Issue by Fresheyeball** [elm-lang/elm-compiler#1263]
```elm
oneSlash = '\' -- does not compile 
oneSlash = '\\' -- compiles as two slashes, not desired 
oneSlash = "\" -- does not compile
```

I do believe there should be some way of representing `\` for usage in `String`s in Elm.

**Comment by evancz** [comment]
Isn't it just `"\\"` in strings? The `Char` one seems like a bug though.

**Comment by evancz** [comment]
@avh4, is this the same as your issues about weird escaping? If so, can you add it to the meta issue?

**Comment by avh4** [comment]
Yes, probably the same root cause as https://github.com/elm-lang/elm-compiler/issues/1123

**Comment by evancz** [comment]
Cool, thanks :)

**Comment by evancz** [comment]
The problem with `'\\'` is resolved by the new parser. The other two things should not compile, and they still do not.
