### ISSUE TITLE
Asset Pipeline (calling the compiler) from Haskell

### ISSUE THREAD

**Issue by srijs** [elm-lang/elm-compiler#1264]
Hi.

I'm writing a small Haskell web app, and just started using Elm for the front-end part.

It works very well so far, but I have one small issue: Instead of running some scripts to bundle the two together, would like to be able to compile the Elm project from within the Haskell web server (on startup) and then serve `elm.js` from memory.

I've seen that the compiler at one point was published to Hackage as a library, however it is now marked as deprecated.

Are there plans to support something like that in the future, or has it proven unpractical for the Elm project?

**Comment by evancz** [comment]
I don't think it's likely that I'll publish to hackage for quite some time. I would like to move towards "compiler as a service" in the long term so you can get whatever information you need easily, whether you are using Python or Haskell or whatever else. Not sure exactly what that will look like.

**Comment by saurabhnanda** [comment]
@evancz Please consider exposing the compiler as a Haskell library. I'm trying to figure out how to auto-generate Elm code based on Haskell data-types.

**Comment by jhrcek** [comment]
@saurabhnanda be aware that something like that was implemented by Kris Jenkin's [elm-export](http://hackage.haskell.org/package/elm-export) project. I'm not sure if this is still alive (if it was migrated to Elm 0.19). Just mentioning that project so that you don't have to start from zero..
