### ISSUE TITLE
Some un-parenthesized patterns rejected in let (but not in case)

### ISSUE THREAD

**Issue by jvoigtlaender** [elm-lang/elm-compiler#1266]
Consider this type definition:
```elm
type A = B Int
```
Then this is rejected:
```elm
f : A -> Int
f x =
    let
        B n = x
    in
        n
```
On the other hand this is accepted:
```elm
f : A -> Int
f x =
    let
        (B n) = x
    in
        n
```
The first version should be accepted as well.

After all, this is also accepted:
```elm
f : A -> Int
f x =
    case x of
        B n ->
            n
```
As is this:
```elm
type A = B

f : A -> Int
f x =
    let
        B = x
    in
        0
```
(Haskell will accept all these variations.)

**Comment by mgold** [comment]
+1, ran into this the other day. Not too hard to work around though.

**Comment by evancz** [comment]
I did this on purpose. I think pattern matching directly looks too much like defining a function.

I'm not sure what to do with this issue, but I guess I'd say this is unlikely to change in the short term. So my preference would be to close this and revisit if we start talking about patterns like `{ x = myX }` in a few releases.
