### ISSUE TITLE
Incoherence in type-checking with number types

### ISSUE THREAD

**Issue by jvoigtlaender** [elm-lang/elm-compiler#1268]
The following program is currently accepted by Elm:
```elm
f : Int -> Bool
f x = g (x + 0) x

g : Int -> Float -> Bool
g _ _ = False
```
Clearly it shouldn't be. After all, the `x` argument of `f` is declared to be an `Int`, but the function `g` expects its second argument to be a `Float`. We don't have silent conversions in Elm, so this program should be strictly rejected as type-incorrect.

Another clear indication of incoherence is that the following rather similar program *is* currently rejected by Elm:
```elm
f : Int -> Bool
f x = g x x

g : Int -> Float -> Bool
g _ _ = False
```

**Comment by jvoigtlaender** [comment]
Expanding on the weirdness observed above...

The following program is accepted by http://elm-lang.org/try:
```elm
import Graphics.Element

f : Float -> Int
f x = flip always (x + 0) x

main = Graphics.Element.show (f 12.5)
```
It prints "12.5" to the screen, despite the fact that `f`'s return type is `Int`.

Moreover, if we replace `flip always (x + 0) x` by `always x (x + 0)`, the program is suddenly rejected.

**Comment by jvoigtlaender** [comment]
Just to make clear that this incoherence is a real problem (which the above examples with `Graphics.Element.show` may not convey):

Lets consider the following function:
```elm
g : Int -> Int
g n =
    let
        h m =
            case m of
                0 -> 0
                m -> h (m-1)
    in
        h (abs n)
```
It's easy to convince oneself that this is terminating for all inputs.

So, great, well-typed programs don't go wrong!

But now use that function in the following code:
```elm
import Graphics.Element

f : Float -> Int
f x = flip always (x + 0) x

main = Graphics.Element.show (g (f 12.5))
```
Suddenly we have a non-terminating program, despite the fact that we only put together, in a type-correct way, functions of which we know that they terminate for all their inputs.

**Comment by mgold** [comment]
This is a regression since 0.15. The first program in the first post is rejected by that compiler:

```
Type mismatch between the following types on line 2, column 17 to 18:

        Int

        Float

    It is related to the following expression:

        x
```

(share-elm is great for testing old versions)

Good catch, Janis!

**Comment by jvoigtlaender** [comment]
@mgold, it's not certain that this is a regression since 0.15. This example from above:
```elm
import Graphics.Element

f : Float -> Int
f x = flip always (x + 0) x

main = Graphics.Element.show (f 12.5)
```
is accepted by 0.15 at share-elm as well, despite the fact that it treats `12.5` as an `Int`. So it might be the case that the issue is older and it's just that for 0.16 it happens to surface for a few more (and maybe also a few less, who knows) programs.

**Comment by evancz** [comment]
Centralizing into #1373, will track from there.
