### ISSUE TITLE
Elm command should have a command or switch to print out the version (and nothing else)

### ISSUE THREAD

**Issue by arsatiki** [elm-lang/elm-compiler#1269]
It is useful to be able to extract the version of the installed compiler programmatically. Right now the way to do this is to run the `elm` command and then taking the first line of the output. Even then, the output contains extra text that may change between releases.

It would be better to have an explicit command, such as `elm version` or a switch (`-v` or `--version`) that output the version number and nothing else.

**Comment by mgold** [comment]
+1 for `elm make --version`. Others are more subjective. But it's low priority.

**Comment by tylerdmace** [comment]
+1 for `-v` and `--version` both.

**Comment by arsatiki** [comment]
I don't understand why the version would be hidden behind `elm make`. After all, simply running `elm` right now gives you the version along with the usage guide. From my end user perspective, the `elm` command *is* Elm.

**Comment by tylerdmace** [comment]
It's not, though. `elm-make` is actually it's own thing.

**Comment by mgold** [comment]
`elm --version` could print just the Elm Platform version, while the individual tools would print their own versions.

**Comment by Fresheyeball** [comment]
I've tripped on this too from time to time. Ultimately I'd like `elm --version` to have output the platform version as well as each component. It could be convenient over checking the version of each component one at a time (for the rare scenario where you would need to do such a thing.)

**Comment by tylerdmace** [comment]
@mgold @Fresheyeball I agree with you both, here. I really think that this makes the most sense:

`$ elm -v` or `$ elm --version` for an Elm platform version & the version of all included components.

`$ elm make -v` or `$ elm make --version` for the version of the `make` component only.

**Comment by evancz** [comment]
I think there's an issue open for this on the elm-make repo (https://github.com/elm-lang/elm-make/issues) but I'm not sure.

In any case, that's where this should be. Also, the version should be uniform across all command line tools now. For the CLI's that have this flag, you can see this now:

```
$ elm-repl --version
0.16.0
$ elm-reactor --version
0.16.0
```

**Comment by evancz** [comment]
Oh, I see, it does not work on `elm`, `elm-make`, or `elm-package` at the moment. I'll open an appropriate issue for this.
