### ISSUE TITLE
Custom favicon 

### ISSUE THREAD

**Issue by mjgpy3** [elm-lang/elm-compiler#1271]
First off, thanks for Elm, I'm loving the language, especially its error messages :+1: :heart: :+1: 

I'm looking for a way to set a custom favicon. I saw something about a syntax port for favicons (see bottom of [syntax reference](http://elm-lang.org/docs/syntax)), however, it wasn't particularly helpful.

Thank you!

**Comment by jvoigtlaender** [comment]
Welcome! Please ask such questions on the [mailing list](https://groups.google.com/forum/#!forum/elm-discuss) instead. The issue tracker here at GitHub is for bugs and feature requests.

**Comment by mjgpy3** [comment]
Alright, thank you!
