### ISSUE TITLE
Identifiers starting with an underscore are read as two identifiers

### ISSUE THREAD

**Issue by aymanosman** [elm-lang/elm-compiler#1272]
```elm
> \_b_ a -> a
<function> : a -> b -> c -> c
```

So `_a_` is read as `_ a_`. Noticed this when trying to do the idiomatic thing of saying "here is a variable we are ignoring but still give it a name".

**Comment by evancz** [comment]
For some context, it is not possible to have variables in Elm that start with an underscore. This is freaky nonetheless, so thanks for the report! I'll try to circle back to this before 0.17 comes out.

**Comment by evancz** [comment]
Centralizing into #1374, follow along there

**Comment by evancz** [comment]
This is fixed by the new parser. The new error message looks like this:

![screen shot 2016-12-17 at 8 35 16 pm](https://cloud.githubusercontent.com/assets/1658058/21291079/9667df5a-c498-11e6-9cd5-112ee7c16e37.png)

**Comment by nonpop** [comment]
This seems to still/again be happening in 0.18. Not critical but caused some confusion.

```
---- elm-repl 0.18.0 -----------------------------------------------------------
 :help for help, :exit to exit, more at <https://github.com/elm-lang/elm-repl>
--------------------------------------------------------------------------------
> \_a -> a
<function> : a -> b -> b
> 
```

**Comment by zwilias** [comment]
The new parser described above is to be part of 0.19 due to some breaking changes :)
