### ISSUE TITLE
JavaScript generator scoping issue in 0.16 (mapping is undefined)

### ISSUE THREAD

**Issue by thSoft** [elm-lang/elm-compiler#1275]
Steps to reproduce:
* Clone https://github.com/thSoft/dux
* Follow the steps in the [readme](https://github.com/thSoft/dux/blob/master/readme.md)
* Open [Test/Dux/Language/Mappings.elm in elm-reactor](http://localhost:8000/elm/Test/Dux/Language/Mappings.elm)

Output in Firefox 43.0.4:
```
mapping is undefined
Open the developer console for more details.
```

Developer console:
```
TypeError: mapping is undefined
Elm.FirebaseModel.Mapping.make/_op[":="]</result.subscribe<() Mappings.elm:11427
A2() Mappings.elm:869
Elm.FirebaseModel.Mapping.make/object3</<.subscribe<() Mappings.elm:11616
A2() Mappings.elm:869
Elm.FirebaseModel.Mapping.make/mirror<() Mappings.elm:11542
A2() Mappings.elm:869
Elm.Test.Dux.Language.Mappings.make() Mappings.elm:11884
init() Mappings.elm:410
Elm.fullscreen() Mappings.elm:293
```

The problematic source:
```js
   _op[":="] = F2(function (key,mapping) {
      var realUrl = function (url) {    return A2($Basics._op["++"],url,A2($Basics._op["++"],"/",key));};
      var result = {transform: F2(function (url,cache) {    return A2(mapping.transform,realUrl(url),cache);})
                   ,subscribe: F2(function (address,url) {    return A2(mapping.subscribe,address,realUrl(url));})
                   ,unsubscribe: F2(function (url,cache) {    return A2(mapping.unsubscribe,realUrl(url),cache);})
                   ,handle: F3(function (address,url,state) {    return A3(mapping.handle,address,url,state);})};
      return result;
   });
```

Since I see no name shadowing, I suppose this is different than #1086.
(Sorry for not providing an SSCCE, hopefully this info is enough or the steps to reproduce are simple.)

**Comment by jvoigtlaender** [comment]
This is almost certainly another instance of #873. Look at [these lines](https://github.com/thSoft/dux/blob/e6bcdc4c90aef0d6773d99d700ffed035d1dfbd0/src/main/elm/Dux/Language/Mappings.elm#L33-L47). There, `functionCall` is a constant that depends on `expression`, which itself is a constant that depends on `functionCall`. Bang, nontermination. Elm is a strict language, so combinator style DSLs are more tricky than in Haskell, for example.

Read the advice in various issues referenced over at #873. Particularly, what you probably need is something like these combinators:
* http://package.elm-lang.org/packages/Bogdanp/elm-combine/2.0.0/Combine#rec
* http://package.elm-lang.org/packages/Dandandan/parser/6.2.3/Parser#recursively

or the equivalent trick for `Json.Decoder`s, explained in some of the issues mentioned above.

**Comment by jvoigtlaender** [comment]
More focused advice, and how other people got over similar problems:
* https://github.com/elm-lang/core/issues/471#issuecomment-169036594
* https://github.com/elm-lang/core/issues/361
* https://github.com/elm-lang/elm-compiler/issues/1244

**Comment by thSoft** [comment]
Thank you for your elaborate help! I think I will introduce a recursive combinator like the mentioned parser combinator libraries.
