### ISSUE TITLE
Occam's Razor for Error Messages

### ISSUE THREAD

**Issue by dan-tull** [elm-lang/elm-compiler#1277]
Running the compiler on the following program:

```
import Graphics.Element exposing (Element, show)

combine : List String -> String
combine words =
  List.foldr (++) "" words

textToShow : List String -> String
textToShow words =
  let
    backward = List.reverse words
    _ = Debug.log "halves" (List.map ((/) 2) backward)
  in
    combine words

main : Element
main =
  show <| textToShow ["1", "2", "3"]

```

Produces the following error:
```
-- TYPE MISMATCH ------------------------------------------------------ Test.elm

The argument to function `combine` is causing a mismatch.

13│     combine words
                ^^^^^
Function `combine` is expecting the argument to be:

    List String

But it is:

    List Float

```

Note I stripped this example down from one that seemed more sensible but had more baggage.

The call to Debug.log is leading the type inference down a bad path (commenting it out fixes the error) by trying to map with a function that implies the elements of the List are Float values.

I've run into a few similar issues where the type annotations were correct and most of the code aligned with that, but a single earlier call implied a different type and obfuscated the real problem.

One improvement would be for it to provide an explanation of the reasoning behind thinking that words is a List Float which would point to the indirect usage on line 11 (via line 10).

Even better would be doing further analysis to recognize that blaming line 11 directly is simpler because presuming line 11 to be right produces several other contradictions whereas 13 is consistent with everything except line 11.

Contradictions caused by assuming line 11 is correct (that words is a List Float): 
- the type annotation for textToShow is wrong
- the type annotation for combine is wrong
- and the call to textToShow on line 17 is wrong.

I've really been enjoying using Elm and mostly the compiler messages are really helpful so I wanted to lay out this example of where they could be even better.

Thanks!

**Comment by jvoigtlaender** [comment]
Error message issues are tracked elsewhere: https://github.com/elm-lang/error-message-catalog/issues

There are already issues there about the problem you point out. With https://github.com/elm-lang/error-message-catalog/issues/71 being the most recent one, I think. I suggest you close here and maybe add your example over there and/or, more importantly, add your conceptual suggestion over there. As comment to the mentioned issue, or as a new issue in that repository.

**Comment by dan-tull** [comment]
Oops. Sorry, I hadn't run across that other repo. Thanks for the pointer!
