### ISSUE TITLE
Certain escaped characters in strings cause crashes on Windows

### ISSUE THREAD

**Issue by avh4** [elm-lang/elm-compiler#1279]
The following file compiles on Mac/linux, but produces `elm-make.exe: elm-stuff\build-artifacts\0.16.0\user\projects\1.0.0\Main.elmo: user error (Bad encoding; the file must be valid UTF-8)` on Windows:

```elm
nbsp = "\xA0"
```

The following also compiles on Mac/linux, but produces `elm-make.exe: elm-stuff\build-artifacts\0.16.0\user\projects\1.0.0\Main.elmo: commitBuffer: invalid argument (invalid character): thread blocked indefinitely in an MVar operation` on Windows:

```elm
nbsp = "\x9F"
```

**Comment by avh4** [comment]
This was brought to my attention via https://github.com/avh4/elm-format/issues/132

**Comment by evancz** [comment]
Closing, will track from #1280 meta issue instead

**Comment by evancz** [comment]
The `\xFF` syntax is no longer allowed. You can only use `\uFFFF` now, and it preserves the escaped version into JavaScript.
