### ISSUE TITLE
Inconsistent "duplicate definition" error

### ISSUE THREAD

**Issue by Steve-OH** [elm-lang/elm-compiler#1284]
In this code:

```
type Foo
  = Bar Bar
  | Baz Baz

type alias Bar = List Int

type alias Baz = 
  { foo: Int
  , bar: Int
  }
```
Baz raises a "duplicate definition" error, but Bar does not. I don't know which behavior is supposed to be correct, although I would expect neither to be an error. There is a workaround:
```
type Foo
  = Bar Bar
  | Baz Baz

type alias Bar = List Int

type alias Baz' =
  { foo: Int
  , bar: Int
  }

type alias Baz = Baz'
```

**Comment by mgold** [comment]
This seems really weird, but there's a reason for it. The definition of `Foo` creates the value (not type) `Baz : Baz -> Foo`. Creating a type alias for a record creates a record constructor, in this case `Baz : Int -> Int -> Baz`. This is where the conflict is.

So, not a bug, but *definitely* file this in the [error message catalog](https://github.com/elm-lang/error-message-catalog/issues)!

**Comment by Steve-OH** [comment]
Given the simple workaround (alias the alias), it seems like this is something that the compiler could figure out.

> So, not a bug, but definitely file this in the error message catalog!

Done.
