### ISSUE TITLE
Inconsistent 0.16 ifs

### ISSUE THREAD

**Issue by vans163** [elm-lang/elm-compiler#1285]
Why change the functional style ifs to OOP style ifs:
```
if key == 40 then
    n + 1
else if key == 38 then
    n - 1
else
    n
```
But the case is left alone:
```
case maybe of
  Just xs -> xs
  Nothing -> []
```

Either change the case to OOP style like
```
switch maybe of
    Ok then Ok
    Else then Else
```

Or return function programming ifs.

I can suggest
```
if
    key == 40 -> n+1
    key == 38 -> n-1
    _ -> n
```

I see nothing wrong with this syntax and its much more readable then the spaghetti then/else/elseif produces. Also the new ifs stand out as a sore thumb in the language. 

Please don't go down the road of Microsoft, sacrificing correctness for noob friendlyness. Microsoft as a result has not made a usable product since 2010.

**Comment by mgold** [comment]
You're don't going to get anywhere making demands and irrelevant comparisons.

This issue was [discussed at length](https://github.com/elm-lang/elm-plans/issues/3).

**Comment by vans163** [comment]
That issue was closed. It seems almost split decision. Unfortunate, IMO it does not fit the functional nature. Is all.
