### ISSUE TITLE
Support --version flag for `elm` CLI

### ISSUE THREAD

**Issue by evancz** [elm-lang/elm-compiler#1286]
Should be uniform across all Elm things. Right now `elm-repl` and `elm-reactor` have this flag, but `elm`, `elm-make`, and `elm-package` do not.

**Comment by egonSchiele** [comment]
Hi Evan,
I would like to start contributing to Elm. This seems like an easy bug for me to start with, do you mind if I take this? I've already gotten elm-platform to build from source, and I've signed the contributor agreement.

**Comment by evancz** [comment]
Hey, sorry I did not get back to you! I was missing a lot of notifications at that time.

I'd say the best way to start contributing is to get involved with the community on slack and see what folks are up to. Make some projects. Make some libraries. Basically, it makes sense to meet folks who are working on things and ramp up by working on things with them or at least in public. Hopefully that helps!
