### ISSUE TITLE
Tuple maximum element

### ISSUE THREAD

**Issue by yang-wei** [elm-lang/elm-compiler#1289]
From the doc[http://elm-lang.org/docs/syntax]:

> There is a special function for creating tuples:

> (,) 1 2              == (1,2)
> (,,,) 1 True 'a' []  == (1,True,'a',[])
> You can use as many commas as you want.

This is not true. The maximum commas can be used is 8, which is to create 9 elements.

```
---- elm repl 0.16.0 -----------------------------------------------------------
 :help for help, :exit to exit, more at <https://github.com/elm-lang/elm-repl>
--------------------------------------------------------------------------------
> (,,,,,,,,) 1 2 3 4 5 6 7 8 9
(1,2,3,4,5,6,7,8,9)
    : ( number
      , number'
      , number''
      , number'''
      , number''''
      , number'''''
      , number''''''
      , number'''''''
      , number''''''''
      )
> (,,,,,,,,,) 1 2 3 4 5 6 7 8 9 10
elm-make: Could not find `_Tuple10` when solving type constraints.
elm-make: thread blocked indefinitely in an MVar operation
```

The maximum element in a tuple is 9 ? This is undocumented (I think)

**Comment by avh4** [comment]
Thanks!  We probably won't support large tuples like this, but the error message should be improved.  Can you please submit this at https://github.com/elm-lang/error-message-catalog/issues
