### ISSUE TITLE
Dead code not being type checked?

### ISSUE THREAD

**Issue by joeandaverde** [elm-lang/elm-compiler#1292]
I did not receive a compiler error after removing a property from a record. Likely due to the fact that the code using that record was "dead".

Here's the record before:

```elm
type alias BottleValidationData =
  { battery : ValidationValue Float
  , signal : ValidationValue Int
  , temperature : ValidationValue Float
  , weight : ValidationValue Float
  }
```

I removed the weight value:

```elm
type alias BottleValidationData =
  { battery : ValidationValue Float
  , signal : ValidationValue Int
  , temperature : ValidationValue Float
  }
```

There was code that was using this for display:

```elm
validationResultComponent : Address Action -> Model -> Html
validationResultComponent address model =
  let
    signalStrengthComponent data =
      (valueComponent "Signal Strength" [ text (signalToText data.signal.value) ])

    batteryComponent data =
      (valueComponent "Battery" [ text <| toString (batteryPercent data.battery.value) ++ "%" ])

    weightComponent data =
      (valueComponent "Weight" [ text <| toString data.weight.value ++ " g" ])

    temperatureComponent data =
      (valueComponent "Temperature" [ text <| (toString data.temperature.value) ++ " °F" ])

    valueComponent caption valueDisplay =
      [ h4
          [ class "push-5 font-w300" ]
          valueDisplay
      , div
          [ class "h6 font-w300 text-muted" ]
          [ text caption ]
      ]

    defaultDisplay =
      []

    content =
      case model.validationResult of
        Just result ->
          case result.validation of
            BroadcastEvent.BottleValidation data ->
              div
                [ class "block-content" ]
                [ div
                    [ class "row items-push text-center" ]
                    [ div
                        [ class "col-xs-3 border-r" ]
                        (signalStrengthComponent data)
                    , div
                        [ class "col-xs-3 border-r" ]
                        (batteryComponent data)
                    , div
                        [ class "col-xs-3 border-r" ]
                        (temperatureComponent data)
                    , div
                        [ class "col-xs-3" ]
                        (weightComponent data)
                    ]
                ]

        _ ->
          text ""
  in
    div
      [ class "validation-results" ]
      [ content ]
```

if you remove the line that reads:

```elm
, div
                        [ class "col-xs-3" ]
                        (weightComponent data)
```

The compiler is fine. See the output below:

```javascript  
     var weightComponent = function (data) {
         return A2(valueComponent,
         "Weight",
         _U.list([$Html.text(A2($Basics._op["++"],
         $Basics.toString(data.weight.value),
         " g"))]));
      };
      var batteryComponent = function (data) {
         return A2(valueComponent,
         "Battery",
         _U.list([$Html.text(A2($Basics._op["++"],
         $Basics.toString($Types$Device.batteryPercent(data.battery.value)),
         "%"))]));
      };
```

This specific situation wouldn't result in a run-time error because the function is never used. However, I would think that `Basics.toString` would cause a compile error due to inability to infer type.

**Comment by jvoigtlaender** [comment]
All looks fine to me. Also unused code is type-checked, in particular also the weightComponent function. I think what confuses you is that the type it gets assigned is not the one you think it gets. Try to annotate it locally with the type you think it has, and you will see whether the compiler agrees.

**Comment by jvoigtlaender** [comment]
The point being: That function's inferred type is *not* of the form BottleValidationData -> ..., and never was. Also not before you removed the weight field from that type alias.

**Comment by joeandaverde** [comment]
I am indeed confused: `data.weight.value` doesn't refer to anything (after I removed the field).

**Comment by joeandaverde** [comment]
Is this because/related to structural typing of records?

**Comment by joeandaverde** [comment]
Maybe it's just better to be explicit with the type annotation like so: 

```elm
    signalStrengthComponent : BroadcastEvent.BottleValidationData -> List Html
    signalStrengthComponent data =
      (valueComponent "Signal Strength" [ text (signalToText data.signal.value) ])

    batteryComponent : BroadcastEvent.BottleValidationData -> List Html
    batteryComponent data =
      (valueComponent "Battery" [ text <| toString (batteryPercent data.battery.value) ++ "%" ])

    temperatureComponent : BroadcastEvent.BottleValidationData -> List Html
    temperatureComponent data  =
      (valueComponent "Temperature" [ text <| (toString data.temperature.value) ++ " °F" ])

    valueComponent : String -> List Html -> List Html
    valueComponent caption valueDisplay =
      [ h4
          [ class "push-5 font-w300" ]
          valueDisplay
      , div
          [ class "h6 font-w300 text-muted" ]
          [ text caption ]
      ]

```

**Comment by jvoigtlaender** [comment]
Yes, this is about structural typing of records. In your original program, the inferred type for `weightComponent` is of the form `{a | weight : { b | value : c}} -> ...`. This means that function *can* be applied to a `BottleValidationData` record, but not that it *must* be applied to exactly such a record. After you have removed the `weight` field from the `BottleValidationData` definition, the function *cannot* anymore be applied to a `BottleValidationData` record, but that does not mean the function has become ill-typed. It still has exactly the same type as before (given above). If you then try to use it on a `BottleValidationData` record, you get an error, if you don't, you don't.

Concerning the comment 
> `data.weight.value` doesn't refer to anything (after I removed the field)

consider this example:
```elm
fun arg = arg.name ++ " the great"
```
That function is perfectly well-typed, with type `{a | name : String} -> String`, even if the whole program does not contain a record type alias definition containing a `name` field.

**Comment by joeandaverde** [comment]
I understand now. Thank you. This issue can be closed.
