### ISSUE TITLE
Record update syntax with qualified name

### ISSUE THREAD

**Issue by mcapodici** [elm-lang/elm-compiler#1293]
I get a compiler error when using a qualified name in a record update statement e.g.

`bug = { Counter.myData | value = 4 }`

Gives

```
-- SYNTAX PROBLEM ------------------------------------------ .\.\CounterPair.elm

I ran into something unexpected when parsing your code!

8▒ bug1 = { Counter.myData | value = 4 }
            ^
I am looking for one of the following things:

    a closing bracket '}'
    a lower case name
    whitespace

Detected errors in 1 module.

```

Similar to https://github.com/elm-lang/elm-compiler/issues/951

Can be reproduced here: https://github.com/mcapodici/elm-architecture-tutorial/tree/master/examples/2

**Comment by jvoigtlaender** [comment]
There is already an issue covering this. Please check, then close this duplicate here.

**Comment by jvoigtlaender** [comment]
https://github.com/elm-lang/elm-compiler/issues/1068

**Comment by mcapodici** [comment]
Correct it is a duplicate. Happy if you close this or i can next time im
logged in. Sorry i didnt find this i did search before i raised.

**Comment by jvoigtlaender** [comment]
Yeah, it's difficult to find, because Evan "hides" it behind the meta issue collecting all record related stuff into one. Please close the issue yourself, I don't have the access rights to do so in this repository.
