### ISSUE TITLE
Provide official arm build

### ISSUE THREAD

**Issue by rosenk** [elm-lang/elm-compiler#1294]
On Raspberry Pi 2:
`npm -g install elm`
`Unfortunately, there are currently no Elm Platform binaries available for your operating system and architecture.`

Building from source is a horrific experience on such slow device. I tried but ghc is running out of ram or something.

**Comment by jvoigtlaender** [comment]
This issue might be better opened at https://github.com/elm-lang/elm-platform.

**Comment by rosenk** [comment]
Thanks, I filed an issue there.

**Comment by rlefevre** [comment]
For now, you can try the unofficial and experimental binaries provided here:
https://github.com/dmy/elm-raspberry-pi
