### ISSUE TITLE
Compilation of tail recursive code leads to scope violations

### ISSUE THREAD

**Issue by jvoigtlaender** [elm-lang/elm-compiler#1297]
Consider this code:
```elm
import Graphics.Element

f n =
  if n > 0 then
    let
      x =
        42
    in
      f 0
  else
    let
      x =
        x + 1
    in
      x

main =
  Graphics.Element.show (f 1)
```
It shouldn't result in a value, because of the `let x = x + 1`. But it does result in value `43`.

Here is the JavaScript that the compiler produced:
```js
   var f = function (n) {
      f: while (true) if (_U.cmp(n,0) > 0) {
            var x = 42;
            var _v0 = 0;
            n = _v0;
            continue f;
         } else {
            var x = x + 1;
            return x;
         }
   };
```
Note how the `var x = x + 1` will use the value from `var x = 42`, in violation of the Elm semantics.

**Comment by mgold** [comment]
Shouldn't `let x = x + 1` be disallowed once #873 is fixed? And if so, shouldn't it be okay that TCO fails in a case that's caught by the compiler?

**Comment by jvoigtlaender** [comment]
@mgold, the point is not this particular example only. For example, we could have `let x = 0 :: x`, which will be allowed even after #873 is fixed (as allowing something like this is the motivating example of #873). And then what?

**Comment by jvoigtlaender** [comment]
See https://github.com/elm-lang/elm-compiler/issues/873#issuecomment-189343524.

**Comment by mgold** [comment]
Then fine, it's a bug. But let's make that version the SSCCE.
