### ISSUE TITLE
Hackage publishing

### ISSUE THREAD

**Issue by agrafix** [elm-lang/elm-compiler#1300]
Are there any plans to release the compiler on hackage again? I have some projects that generate Elm code, and it would be really cool if I could reuse Elm's AST (and pretty printer?). An alternative would be to only release the Syntax (AST, parser and pretty printer) as separate package on Hackage as `language-elm`.

**Comment by evancz** [comment]
No, this is not a priority for me. I think there are other issues either here or on elm-discuss about this. As the compiler becomes better for supporting tooling, I want it to work with any language so I'd expect things to be available as command line options.
