### ISSUE TITLE
Typed holes

### ISSUE THREAD

**Issue by sjfloat** [elm-lang/elm-compiler#1306]
It would be truly awesome if elm supported typed holes, yes?

**Comment by evancz** [comment]
This is a feature I consider from time to time. Not sure if or when it'd be added though.

Issues here are more about tracking bugs in the language as is, so discussions like this should happen in the places listed here http://elm-lang.org/community

If you have a real-world usage scenario, it'd be great to get it documented and shared with the community so folks can think about this potential workflow.
