### ISSUE TITLE
Not informative error message: "Unable to find a set of packages that will work with your constraints."

### ISSUE THREAD

**Issue by stereobooster** [elm-lang/elm-compiler#1314]
This error appears on `elm make`

Code causing it :
```
{
    "version": "0.4.2",
    "summary": "elm bindings for D3.js",
    "repository": "https://github.com/seliopou/elm-d3.git",
    "license": "BSD3",
    "source-directories": [
        "src"
    ],
    "exposed-modules": ["D3", "D3.Event"],
    "native-modules": true,
    "dependencies": {
        "elm-lang/core": "2.1.0 <= v < 3.0.0"
    },
    "elm-version": "0.15.1 <= v < 0.16.0"
}

```

**Comment by jvoigtlaender** [comment]
You are running this with Elm 0.16? Then the problem is that the elm-package.json requests an older version.

**Comment by stereobooster** [comment]
The problem is in `"elm-lang/core": "2.1.0 <= v < 3.0.0"` actually. When I changed it to `"elm-lang/core": "2.1.0 <= v <= 3.0.0"` it suggested to install `elm-lang/core 3.0.0`

```
elm make
Some new packages are needed. Here is the upgrade plan.

  Install:
    elm-lang/core 3.0.0
```

**Comment by jvoigtlaender** [comment]
If the more general issue is "Why doesn't the tool tell me what the conflict was?", then see https://github.com/elm-lang/elm-package/pull/177.

Anyway, the issue here should be closed. It's a matter for the elm-package repository.

**Comment by jvoigtlaender** [comment]
So you are on Elm 0.16. It's wrong then that the contradictory elm-version constraint is not pointed out, but there's already an issue open about that as well.

So in summary, the issue here can be closed.

**Comment by stereobooster** [comment]
Yes that is the original problem. Wrong repository
