### ISSUE TITLE
Invalid JS produced if type union has a value with a . in it

### ISSUE THREAD

**Issue by Sushisource** [elm-lang/elm-compiler#1315]
The compiler should definitely complain about this - but instead it happily produces JS with invalid syntax. Here's a simple repro:

```elm
type UhOhType = OkName | Bad.Name

badcasefn a = case a of
  OkName -> 1
  Bad.Name -> 2
```

Loving the language! Keep up the good work!

**Comment by jvoigtlaender** [comment]
Please always first check whether there is an existing issue already. Your issue is a duplicate of https://github.com/elm-lang/elm-compiler/issues/1200. Please close.

**Comment by Sushisource** [comment]
Sorry about that. Thanks!
