### ISSUE TITLE
Different "type-classy" type variables not differentiated

### ISSUE THREAD

**Issue by jvoigtlaender** [elm-lang/elm-compiler#1316]
This function rightly does not type-check:
```elm
f : a -> b -> Int
f x y = List.length [x, y]
```
For the same reasons, this function should also not type-check:
```elm
g : comparable -> comparable' -> Bool
g x y = x < y
```
But it currently does, on http://elm-lang.org/try.

In https://github.com/elm-lang/elm-compiler/issues/821#issuecomment-150410111, @evancz said that this error (such an example wrongfully type-checking) was fixed, but it seems the bug is back?

**Comment by jvoigtlaender** [comment]
Same with `number` and `appendable`. For example, the following should not type-check, but does:
```elm
h : appendable1 -> appendable2 -> appendable3
h x y = x ++ y
```

**Comment by evancz** [comment]
Centralizing into #1373, will track from there.
