### ISSUE TITLE
'Uncaught Error: Notify function called synchronously!'

### ISSUE THREAD

**Issue by brobrts** [elm-lang/elm-compiler#1317]
not sure what this is, but following through on the suggestion below from the debugger =>

Uncaught Error: The notify function has been called synchronously!
This can lead to frames being dropped.
Definitely report this to <https://github.com/elm-lang/Elm/issues>
notify @ Main.elm?debug:1315(anonymous function) @ debug.js:3341

-- this happened in Chrome while debugging the architecture example in folder 2 with some Debug.log statements.  see attached folder.

[2.zip](https://github.com/elm-lang/elm-compiler/files/175082/2.zip)

**Comment by jvoigtlaender** [comment]
Please report this at https://github.com/elm-lang/elm-reactor/issues, and close here. You were pointed to the wrong repo due to this issue: https://github.com/elm-lang/core/issues/430.

**Comment by brobrts** [comment]
As requested.
