### ISSUE TITLE
record field names must start with a lowercase letter

### ISSUE THREAD

**Issue by avh4** [elm-lang/elm-compiler#1319]
And here is an SSCCE:

```
f x = x.Counter

main = f { }
```

This results in error message:

```
Function `f` is expecting the argument to be:

    { b | Counter : ... }

But it is:

    {}
```

So the compiler is printing out a "type" { b | Counter : ... } as if it were valid Elm, though it isn't.

---
Previous discussions: #1318, https://github.com/elm-lang/error-message-catalog/issues/98

**Comment by evancz** [comment]
Centralizing into #1374, follow along there

**Comment by evancz** [comment]
This is fixed by the new parser. Thanks for the new report!
