### ISSUE TITLE
elm-compiler 0.16 fails to build with "Compiled JS did not match expected JS."

### ISSUE THREAD

**Issue by jgillich** [elm-lang/elm-compiler#1320]
The elm-compiler builds on Nix have recently started failing with messages like:
```
    tests/test-files/good/Soundness/SpecificAnnotationInt.elm: [Failed]

Compiled JS did not match expected JS.

  If the change is intentional, rerun the tests with environment variable: ELM_WRITE_NEW_EXPECTED=1

expected: "Elm.Main = Elm.Main || {};\nElm.Main.make = function (_elm) {\n   \"use strict\";\n   _elm.Main = _elm.Main || {};\n   if (_elm.Main.values) return _elm.Main.values;\n   var _U = Elm.Native.Utils.make(_elm);\n   var _op = {};\n   var px = function (x) {    return \"test\";};\n   return _elm.Main.values = {_op: _op,px: px};\n};"

 but got: "Elm.Main = Elm.Main || {};\nElm.Main.make = function (_elm) {\n       \"use strict\";\n       _elm.Main = _elm.Main || {};\n       if (_elm.Main.values)    return _elm.Main.values;\n       var _U = Elm.Native.Utils.make(_elm);\n       var _op = {};\n       var px = function (x) { return \"test\";};\n       return _elm.Main.values = {_op: _op,px: px};\n    };"
```
Full build log: https://travis-ci.org/jgillich/mp/builds/116983036#L1567

As far as I can see, the only difference is some additional whitespace. We suspect some other dependency that got upgraded is causing this, does anyone have any idea which one that might be?

ref https://github.com/NixOS/nixpkgs/issues/14028

**Comment by domenkozar** [comment]
Something in http://hydra.nixos.org/api/scmdiff?uri=https%3A%2F%2Fgithub.com%2FNixOS%2Fnixpkgs.git&rev2=1a07877b5c13bcae5d57382ee64d72384e039905&rev1=fd4cdf183a98b0b7086e7fb140a04854805f2b47&branch=&type=git

**Comment by domenkozar** [comment]
cc @evancz

**Comment by abbradar** [comment]
Found it, offending dependency is language-ecmascript. You can see from their [CHANGELOG](https://github.com/jswebtools/language-ecmascript/blob/master/CHANGELOG) that they did pretty-printing improvements in the new release. Bounding `language-ecmascript >= 0.15 && < 0.17.1` should fix this.

**Comment by mgold** [comment]
The test failures suggest running with an environment flag to regenerate the tests. Perhaps someone should do that.

**Comment by jvoigtlaender** [comment]
Can confirm that the suggested fix does the trick. See https://github.com/elm-lang/elm-compiler/pull/1330.

**Comment by jvoigtlaender** [comment]
As of commit https://github.com/elm-lang/elm-compiler/commit/684504e4744cfced1a02ca0839632610bd412637, the pretty-printing part of `language-ecmascript` is not used anymore at all. So this issue is obsolete and can be closed. (The compiler tests are passing as of https://github.com/elm-lang/elm-compiler/commit/cd8eb70843fdbecf9520532eeec46818da7ac618 as well.)
