### ISSUE TITLE
Duplicate field definition

### ISSUE THREAD

**Issue by ordavidil** [elm-lang/elm-compiler#1323]
Hey,

It seems that the compiler allow me to define the same field twice, even with a __different type__, it just takes the latest definition but I would've expect it will raise an error.

Example:
```elm
type alias Model =
  { id: Int
  , a: Int
  , a: String
  }
```

**Comment by mgold** [comment]
Good catch! A fuller example shows that the record constructor can also be used, but the earlier duplicated field is dropped.

```elm
import Html

type alias Model =
  { id: Int
  , a: Int
  , a: String
  }
  
model = Model 2 3 "foo"

main = Html.text (toString model)
```
This prints `{ id = 2, a = "foo" }`. Record literals with duplicate fields are properly rejected.

**Comment by jvoigtlaender** [comment]
The problem is not only in type aliases, but also in type annotations:
```elm
f : { foo : String , foo : Int } -> Int
f r = r.foo
```

**Comment by kittykatattack** [comment]
I recently had a similar problem which might be related. I was cross-browser testing on IE, and received this run-time error:

![ie10errormessage](https://cloud.githubusercontent.com/assets/2936104/14562218/6d4de05e-02e9-11e6-8743-23f236a545c2.PNG)

I checked the line of offending JS code, and found this. The `image` property is defined twice:

![ie10errorcodedebug](https://cloud.githubusercontent.com/assets/2936104/14562256/902162c2-02e9-11e6-88a7-903d57a6de02.PNG)

I checked my Elm source, and found that, indeed, I had mistakenly assigned a value to `image` twice.

![ie10errormessage](https://cloud.githubusercontent.com/assets/2936104/14562272/accd9e22-02e9-11e6-8d21-ce859818ecb1.PNG)

Removing the first definition fixed the error.
The Elm compiler didn't catch this - although it has caught similar duplicate definitions in the past.

I'm not sure how to recreate this error with a simpler test cast but if anyone would like to see more of my source code, please let me know.
(By the way, the final JS build was done with webpack.)

**Comment by jvoigtlaender** [comment]
@kittykatattack, can you open a new issue for this? It's a separate thing to consider, since the issue here is about duplicate fields in record types, whereas yours is about duplicate fields in record value expressions. It potentially makes sense to be happy with the one, but not with the other. So the two questions should be considered separately.

**Comment by kittykatattack** [comment]
@jvoigtlaender: Removed.  
Thank you, I will open a new issue.

**Comment by jvoigtlaender** [comment]
Good, thanks. For keeping this issue here clear, I'll remove my comment as well. (It probably still makes sense to reference one issue from the other, because somewhat related they are.)

**Comment by evancz** [comment]
Tracking in #1374, thanks for the report!
