### ISSUE TITLE
Compiler doesn't allow updating sub-records directly

### ISSUE THREAD

**Issue by stellanor** [elm-lang/elm-compiler#1325]
Suppose I define a record type alias with a field whose value is another record. I would like to be able to use Elm's record update syntax to update the sub-record, for example: 

```
{ parent | 
     child = { parent.child | 
                      childField = "foo" 
             } 
}
```

Unfortunately, this syntax is not supported directly. The workaround is to use a `let` expression, such as:

```
let oldChild = parent.child
in
  { parent | 
       child = { oldChild | 
                        childField = "foo" 
               } 
  }
```

Here is a simple program that demonstrates the issue:

![image](https://cloud.githubusercontent.com/assets/3003676/14000967/a8fc23fc-f111-11e5-9d83-483db487320e.png)

**Comment by jvoigtlaender** [comment]
This is a duplicate. Please close.

**Comment by stellanor** [comment]
I see. When I originally searched for existing issues I was not searching closed issues. A duplicate issue #537 was closed because the issue is being tracked in https://github.com/elm-lang/elm-plans/issues/16

**Comment by jvoigtlaender** [comment]
Actually it's now tracked in https://github.com/elm-lang/elm-compiler/issues/1068.
