### ISSUE TITLE
Expression syntax can change the type of a record field (but probably shouldn't)

### ISSUE THREAD

**Issue by jvoigtlaender** [elm-lang/elm-compiler#1327]
Elm 0.16 is stated to have dropped support for changing record types in expressions. According to that, the following program should not be accepted, but it is:
```elm
type A = A
type B = B

rec1 : { x : A }
rec1 = { x = A }

rec2 : { x : B }
rec2 = { rec1 | x = B }
```

**Comment by evancz** [comment]
Did it state that?

**Comment by jvoigtlaender** [comment]
Didn't you? I have certainly seen you state something like "there is no syntax for record type changes anymore". Should I do a search where that was?

**Comment by jvoigtlaender** [comment]
In https://github.com/elm-lang/elm-compiler/issues/1088#issuecomment-146658115:
> Record extension literally does not exist in syntax anymore, and this is one form of it.

**Comment by evancz** [comment]
"This" = "generated function for extensible record" like in the title of that issue.

You seem to be talking about changing the type of a field. You can express that in terms of a record addition and deletion. I consider that a convenience for writing a nicer paper though.

Maybe it's true this should be gotten rid of as well, but I think that's a totally separate discussion from the extension/deletion topic.

**Comment by jvoigtlaender** [comment]
I know and knew what "This" was referring to in the sentence I quoted. What I was quoting this sentence for was its first half sentence, about "Record extension literally does not exist in syntax anymore".

It's true that this does not imply that also "changing the type of a field" is out. I assumed that was the intention, though. In discussions back then, I think the aim was to avoid that `{ rec | ... }` has a different type than `rec`. So it doesn't seem to be a totally separate discussion.

In any case, yes I think that "changing the type of a field" should be gotten rid of as well. And I'm happy to change the title of this issue to make this more explicit.

**Comment by evancz** [comment]
Can you open a new issue that explains why you think it should be removed?

Please do not link to other discussions to explain your reasoning. I need the ideas to be organized in a single location. I may need to come back to this at a later time, and the best results will come from clear, concise, self-contained issues.

**Comment by jvoigtlaender** [comment]
Done.
