### ISSUE TITLE
Proposal: Don't allow record update to change type

### ISSUE THREAD

**Issue by jvoigtlaender** [elm-lang/elm-compiler#1329]
Currently this is possible:

``` elm
type A = A
type B = B

record1 : { field : A }
record1 = { field = A }

record2 : { field : B }
record2 = { record1 | field = B }
```

I argue that this should not be allowed:

The immediate intuition of the `{ record | field = value }` syntax is to update the `field` with a new `value`. The `field` must already exist in `record`, and a natural expectation is that one updates _that_ field (of course in non-destructive way), not some conceptually different/new field of a different type.

If one's intent is to update the _type_ of the `field` at the same time, one should be able to declare this by an annotation. That is, one should be able to put the new `type` into the syntax somehow. Maybe as `{ record | field : type = value }`. Note that at other places in the language where types are relevant, one can put explicit annotations (for example, one can, but doesn't have to, provide annotations to `let`-bindings). That there is no provision for this in the `{ record | ... }` syntax, even when something non-trivial is actually going on with the type, is a smell itself.

It's a useful conceptual model for Elm programmers that an expression of the form `{ record | ... }` has the same type as `record`. It would help mentally tracking types through complex expressions. It would also help better pinpointing where type errors are made. Let's say I have a type of 2D-points in an integer grid: `{ x : Int, y : Int }`, and a function taking an input `point` of that type. Somewhere in the body of that function I need to update one of the components, then pass the point onwards to further processing. Accidentally, I use a `Float` as new value, `{ point | x = pi }`. If record updates were forbidden to change types, the compiler could tell me that I'm doing something wrong right there, which indeed is most likely the real error I made. In contrast, with the current situation, the compiler will have to assume that I really wanted to change the type into `{ x : Float, y : Int }`, and when that type finally leads to a conflict in some of the context where the updated record is used (maybe a function it is ultimately passed to after some chain of calls), the compiler will have to blame a place that is likely far away from where I actually made the mistake. Being more strict/static here would enable the compiler to provide better guidance. That seems more worthwhile to me, and more in the spirit of Elm language design, than the lure of a more dynamic feel (being able to change the type of record fields as one goes along).

(Note that, of course, if one really wants to make a record with a new type for `x` in the above example, that's easily possible, and not cumbersome at all: `{ x = pi, y = point.y }`. Explicit, and not invoking any expectation that it will have the same type as `point`.)

**Comment by FPtje** [comment]
Hey, that's funny. I sent a tweet about this last week asking if this intended behaviour:

https://twitter.com/FPtje/status/712557033338363904

I haven't gotten a reply. Maybe twitter is the wrong place to ask.

**Comment by evancz** [comment]
I decided to do this. It improves error messages very significantly. I had one case where I had to reconstruct a record to have a new type (something like `{ a = r.a, b = toFloat r.b }` but it is extremely worth it overall!
