### ISSUE TITLE
The notify function has been called synchronously!

### ISSUE THREAD

**Issue by mmport80** [elm-lang/elm-compiler#1332]
I see this error when a user inputs a date incorrectly.

> Error: The notify function has been called synchronously!
> This can lead to frames being dropped.
> Definitely report this to <https://github.com/elm-lang/Elm/issues>

which is related to a date input field

https://github.com/mmport80/Lazy-PCA/blob/elm-version/web/elm/Forms/AnalysisForm.elm#L120-L133

fwiw, here's the input field component

https://github.com/mmport80/Lazy-PCA/blob/elm-version/web/elm/Forms/Components/InputField.elm

The error crops up when an invalid date enters the system.

I reckon I'll need to keep a pair of validated dates around separately from the raw inputs in order to workaround this error.

Unsure whether the error msg is significant, or whether you can reproduce.

Thought I may as well report it however.

Any tips are welcome!

**Comment by jvoigtlaender** [comment]
You are reporting this to the wrong repository. Unfortunately it's not straightforward what the right repository to report this to would be. See https://github.com/elm-lang/core/issues/430 and #1122.

**Comment by mmport80** [comment]
Aha, it's a dupe. I will close this one then. Thanks for the heads up!
