### ISSUE TITLE
Uncaught Error: The notify function has been called synchronously!

### ISSUE THREAD

**Issue by bilkusg** [elm-lang/elm-compiler#1335]
I received the following error running a StartApp program:

     index.html:325 Uncaught Error: The notify function has been called synchronously!
     This can lead to frames being dropped.
     Definitely report this to <https://github.com/elm-lang/Elm/issues>

There was also an earlier error:

    index.html:12662 Uncaught TypeError: Cannot read property 'nBusinessModelRows' of undefined

I managed to track down the source of the problem to an inadvertant invalid recursive definition caused by a typo in my code: inside an Action case statement I had..(grossly simplified)

     tempVal = ...some expression..    
     newCache = f newVal  -- should have been f tempVal
     newVal = g newCache

and was returning newVal in my updated model. (nBusinessModelRows is a property of tempVal/newVal)

I'm not surprised it didn't work, but the error message was, to put it mildly unhelpful, and since it says I should definitely report it, I have done so
Gary Bilkus

**Comment by jvoigtlaender** [comment]
Thanks for the report. Since the problem causing it has been identified as what #873 is about, the issue here can be closed.

**Comment by bilkusg** [comment]
Ah OK. I will close this then.
