### ISSUE TITLE
Unable to import module located in a folder with "." in its name.

### ISSUE THREAD

**Issue by abadi199** [elm-lang/elm-compiler#1336]
When importing a module that exists in a folder with "." in its name, the compiler is not able to resolve that module, e.g.:
```haskell
{-- File location: /Project.One/View.elm --}
module Project.One.View where

..
```

```haskell
{-- File location: /Project.One/Main.elm --}
module Project.One.Main where

import Project.One.View exposing (..)
..
```

and when I compile the `Main.elm`, I got a compile error:
```
I cannot find find module 'Project.One.View'.

Module 'Project.One.Main' is trying to import it.
```

One workaround for this is to use symbolic link to the folder with "." with a link without the ".", but it will be great if we can use folder with "." in it especially when working on legacy project that already has a lot of folders that can't be easily renamed.

**Comment by JoeyEremondi** [comment]
If we were to allow this, how would the compiler know if you were looking for Project/One/View or Project.One.View, particularly if both were present?

**Comment by evancz** [comment]
I'd recommend making the `source-directories` field in your `elm-package.json` point to the deeper thing. Like, put the Elm all in one place, and have it point to `Project.One/src/` and have it all be in there.

Basically, I think there are work arounds here, and unless you can prove that there is literally nothing that can be done, I wouldn't want to support this.
