### ISSUE TITLE
1 `rem` 0 is NaN

### ISSUE THREAD

**Issue by miikka** [elm-lang/elm-compiler#1338]
Just noticed this (with elm repl 0.16.0 - not sure if that's the relevant version information):

```
> 1 `rem` 0
NaN : Int
```

Issue #262 seems to say that `NaN` shouldn't be an `Int`, so I assume this is a bug.

**Comment by mgold** [comment]
This might be better reported in Core, but yes, `NaN` shouldn't be an `Int`. [Relevant source](https://github.com/elm-lang/core/blob/3.0.0/src/Native/Basics.js#L18).

**Comment by miikka** [comment]
I reported this against Core as elm-lang/core#563.
