### ISSUE TITLE
compiled html returns 'Cannot read property 'value' of undefined Open the developer console for more details.'

### ISSUE THREAD

**Issue by category** [elm-lang/elm-compiler#1340]
[Archive.zip](https://github.com/elm-lang/elm-compiler/files/215645/Archive.zip)

The above code, when compiled, returns html with the above error in Chrome.

Note - requires package 'jvoigtlaender/elm-drag'

**Comment by mgold** [comment]
Can you try to reduce your example to a [http://sscce.org/](SSCCE)? Have you looked through similar issues?

**Comment by category** [comment]
Thanks for the reply - the above link returns a 404 however - if you're referring to the line of the error, I couldn't isolate it as the code compiled correctly with no errors in elm-mode.

The closest issue was this
https://github.com/elm-lang/elm-repl/issues/39
fixed using 
https://github.com/elm-lang/elm-repl/commit/677cb2cfa6f2ed2ef35f57bceb76a40d69b2a769

**Comment by jvoigtlaender** [comment]
The problem is almost certainly the following definition in your `Slider.elm`:
```elm
showShapePos : Signal Element
showShapePos =
  Signal.map show showShapePos
```
(or some other use of bad recursion).

The compiler doesn't currently handle this nicely. See #873.

**Comment by jvoigtlaender** [comment]
PS: What Max was trying to refer you to was: http://sscce.org/

**Comment by category** [comment]
Fab! Thanks very much, also will use the above. Thanks for elm-drag also by way.
