### ISSUE TITLE
Type inference error

### ISSUE THREAD

**Issue by Deimos28** [elm-lang/elm-compiler#1343]
The following function does not compile with elm 0.16:

    matchlist : String -> Json.Decode.Decoder (List a) -> (a -> b) -> List b -> Assertion
    matchlist json decoder extractor expected =
      let
        no_errors : String
        no_errors = ""
        parse_result : Result String (List a)
        parse_result = Json.Decode.decodeString decoder json
      in
        case parse_result of
            Ok values -> assert (List.foldl (&&) True (List.map2 (==) expected (List.map extractor values)))
            Err error -> assertEqual no_errors error

The compile error is:

    The type annotation is saying:
    String -> Json.Decode.Decoder (List a) -> (a -> b) -> List b -> Assertion
    But I am inferring that the definition has this type:
    String -> Json.Decode.Decoder (List a) -> (b -> c) -> List c -> Assertion

Changing the type annotation to
    String -> Json.Decode.Decoder (List a) -> (b -> c) -> List c -> Assertion

changes the error message to:

    The type annotation is saying:
    String -> Json.Decode.Decoder (List a) -> (b -> c) -> List c -> Assertion
    But I am inferring that the definition has this type:
    String -> Json.Decode.Decoder (List a) -> (b -> c) -> List c -> Assertion

I can compile the function by removing the type annotation altogether and disabling warnings (remove the  ̀--warn` flag)

**Comment by jvoigtlaender** [comment]
Don't think this is anything new. What you encounter looks like a mixture of https://github.com/elm-lang/elm-compiler/issues/1214 and https://github.com/elm-lang/elm-compiler/issues/1192.

**Comment by jvoigtlaender** [comment]
@Deimos28, close this? I think I have provided the relevant pointers above that should enable you to see what's going on.

**Comment by Deimos28** [comment]
OK no worries, thanks.
