### ISSUE TITLE
Duplicate fields in record update expressions

### ISSUE THREAD

**Issue by kittykatattack** [elm-lang/elm-compiler#1344]
I was cross-browser testing on IE 10, and received this run-time error:

![ie10errormessage](https://cloud.githubusercontent.com/assets/2936104/14562218/6d4de05e-02e9-11e6-8743-23f236a545c2.PNG)

I checked the line of offending JS code, and found this. The `image` property is defined twice:

![ie10errorcodedebug](https://cloud.githubusercontent.com/assets/2936104/14562256/902162c2-02e9-11e6-88a7-903d57a6de02.PNG)

I checked my Elm source, and found that, indeed, I had mistakenly assigned a value to `image` twice.

![elmoffendingcode](https://cloud.githubusercontent.com/assets/2936104/14562451/aab4607a-02ea-11e6-8d82-6110db47bc1b.PNG)

Removing the first definition fixed the error.
The Elm compiler didn't catch this - although I seem to recall that it has caught similar duplicate definitions in the past.

I'm not sure how to recreate this error with a simpler test case but if anyone would like to see more of my source code, please let me know.
(By the way, the final JS build was done with webpack.)

**Comment by jvoigtlaender** [comment]
Just as a notice: This has some relation to issue https://github.com/elm-lang/elm-compiler/issues/1323.

**Comment by evancz** [comment]
Thanks for the report! Tracking in #1374
