### ISSUE TITLE
Wrong compilation of local operator definitions

### ISSUE THREAD

**Issue by jvoigtlaender** [elm-lang/elm-compiler#1345]
This program is well-typed:
```elm
import Graphics.Element

g : Int -> Int
g u = 
 let (=>) x y = x+y
 in (=>) u 2

h : (Int, Int)
h = 
 let (=>) x y = (x,y)
 in (=>) (g 3) 4
 
main = Graphics.Element.show h
```
Certainly it should print a pair of integers (because that's the type of `h`). But what it does print instead is the single number `9`. 

(http://elm-lang.org/try at version 0.16)

The reason for the bug here is that the above gets compiled to the following JavaScript code:
```js
   var _op = {};
   var g = function (u) {
      _op["=>"] = F2(function (x,y) {    return x + y;});
      return A2(F2(function (x,y) {    return A2(_op["=>"],x,y);}),
      u,
      2);
   };
   var h = function () {
      _op["=>"] = F2(function (x,y) {
         return {ctor: "_Tuple2",_0: x,_1: y};
      });
      return A2(F2(function (x,y) {    return A2(_op["=>"],x,y);}),
      g(3),
      4);
   }();
```
Instead of truly local operator definitions, a global table of operator definitions is used, and the "local" definition in one function overwrites that in the other. That's a side-effect, and one that destroys correct semantics (and even typing) in this program.

**Comment by evancz** [comment]
Tracking in #1377

**Comment by Skinney** [comment]
Not sure if you want me to comment this issue here or elsewhere, so I'm taking a chance that it's here.

The way Clojure and Clojurescript solves this is by giving operators special names.

`=` turns into `__EQUALS__`
`*` turns into `__STAR__`
`+` turns into `__PLUS__`
`-?>` turns into `-__QMARK____GT__`

etc.

**Comment by evancz** [comment]
In 0.19 it will not be possible to define infix operators in `let` expressions. Only at the top level.
