### ISSUE TITLE
toString isn't type safe for Html

### ISSUE THREAD

**Issue by emptyflash** [elm-lang/elm-compiler#1347]
I get a runtime error from this code
``` elm
viewBoard : Address Action -> Board -> Html

view : Address Action -> Model -> Html
view address model =
  div
    [ containerStyle ]
    [ viewBoard address model.board
        |> toString
        |> text
    ]
```

The error given is `Uncaught TypeError: Cannot use 'in' operator to search for 'ctor' in null` coming from the generated `toString` function. I think this has something to do with the fact that `typeof` for null returns "object", but this line `else if (type === 'object' && 'ctor' in v)` throws an error if v is null.

Here's my generated code:
``` javascript
var view = F2(function (address,model) {
    return A2($Html.div,_U.list([containerStyle]),_U.list([$Html.text($Basics.toString(A2(viewBoard,address,model.board)))]));
});
```

I don't actually want to convert the Html to a string, the Elm code above was a mistake, but it seems like maybe the compiler could have caught or handled it.

**Comment by jvoigtlaender** [comment]
Wrong repository to report this in. And the correct repository, https://github.com/elm-lang/core, already has a corresponding issue. Please close here.
