### ISSUE TITLE
Parser accepts single-field records with a trailing comma

### ISSUE THREAD

**Issue by avh4** [elm-lang/elm-compiler#1356]
The following invalid code is accepted by the parser:

```elm
foo = { a = 1, }
```

But should not be due to the trailing comma.

**Comment by evancz** [comment]
Centralizing into #1374, follow along there

**Comment by evancz** [comment]
Fixed by the new parser:

![screen shot 2016-12-17 at 8 38 54 pm](https://cloud.githubusercontent.com/assets/1658058/21291084/f0d6ba6a-c498-11e6-9641-bfba050eac86.png)

Thanks for the report!
