### ISSUE TITLE
'Notify Function called Synchronously' in spaceship game

### ISSUE THREAD

**Issue by Chadtech** [elm-lang/elm-compiler#1357]
Hi,

Im working on a simple space ship game, largely to practice Elm. Im now getting an error..

> The notify function has been called synchronously!
> This can lead to frames being dropped.
> Definitely report this to <https://github.com/elm-lang/Elm/issues>
> notify @ elm.js:326(anonymous function) @ elm.js:6707

Im not sure what change I made to my code that brought this error about (sorry). Ill try retracing my steps through my commits and report back. If youd like to see the code its available here: 

https://github.com/Chadtech/elm-prac-9

**Comment by Chadtech** [comment]
Oh, I just figured it out.

I had a recursive function...

```Elm
rollYTop : Float -> Float
rollYTop y =
  if y > 250 then 
    rollYTop (y - 500)
  else y
```

then I removed the parentheses around y minus 500 and had

```Elm
rollYTop : Float -> Float
rollYTop y =
  if y > 250 then 
    rollYTop y - 500
  else y
```

Which is an endless chain of rollYTop checking and returning the same number, when rollYTop takes y as a parameter rather than (y - 500).

**Comment by mgold** [comment]
Did you mean to reopen the issue? And yes, if you have infinite recursion, there's nothing the compiler can do (see The Halting Problem).

**Comment by Chadtech** [comment]
I re-opened it because I closed it by accident. Sorry, not sure what the issue etiquette is. I opened it originally because the error message suggested I do so. Thank you for referencing The Halting Problem. I hadnt heard of it, and its wikipedia page is interesting.
