### ISSUE TITLE
Bad worst-case performance for pattern match compiler

### ISSUE THREAD

**Issue by evancz** [elm-lang/elm-compiler#1362]
When you have large, complex pattern matches, it can trigger bad performance during the optimization phase. This issue is for organizing http://sscce.org/ that illustrate this problem:
- https://gist.github.com/athanclark/0e29485cb245ff07a97730cfef365d10
- The main logic in `Dict`

The solution is known. If you suggest another example for some reason, please link it as a gist. We may delete your comment to keep this issue simple and clear.

**Comment by treeowl** [comment]
Where is the known solution? A non-invasive change that I suspect would likely improve matters substantially (although perhaps not enough) would be to switch from `Map Int` to `IntMap`.

**Comment by gbaz** [comment]
So I skimmed the "When Do Match-Compilation Heuristics Matter" paper cited in the Optimizer source. It describes that the Small Branching Factor heuristic is unusably slow. Here it is used apparently as a tiebreaker when Small Defaults doesn't suffice. So -- if you have something where Small Defaults generates lots of ties, you will be tossed into the pessimal case and things will grind to a halt.

It seems to me that the Elm compiler should simply avoid heuristics, even as fallbacks, which have such terrible worst-case performance, as it makes the compiler unpredictable.

**Comment by Ryan1729** [comment]
If you change a flat pattern match to a series of nested pattern matches, the (0.17.1) compiler has a much easier time of it. Would having the compiler perform a pass to convert pattern matches of tuples into this form be a good way to address this problem?

[Here's](https://gist.github.com/Ryan1729/4fdf3f9437e44ff2576926a30e6b4adb) a faster to compile version of the month example linked above.

And [here's](https://gist.github.com/Ryan1729/a60784a9acf82d461debd7aedebe190e) a slow and a fast version of a different example.

**Comment by pyladune** [comment]
Is there a simple to identify during compilaiton which part of the code creates such situation ? or at least file ?

**Comment by JoeyEremondi** [comment]
Doing the conversion from flat to nested is, by my understanding, exactly
why the compiler is taking so long right now. Making them nested in your
code makes you do the work instead of the compiler, which speeds up
compilation.

Have you tried 0.18? I think the pattern match compiler got an overhaul to
fix the performance issues.

**Comment by pyladune** [comment]
I'm in 0,18 since start

**Comment by cscalfani** [comment]
Here's an example of the bug in 0.18. Hopefully, this helps: https://gist.github.com/cscalfani/8c84015c4ce34a31c06776b67cd57ef1

**Comment by evancz** [comment]
I fixed this. You can read about it some [here](https://groups.google.com/d/msg/elm-dev/EeVeNo5VNio/cD235S_4CgAJ). The faster version will be out with 0.19, so I'll close for now.

If any folks reading this issue see new ones pop up reporting the same thing, please refer them here or the elm-dev posts that follow up on that status report.
