### ISSUE TITLE
Incoming ports that take unit as an argument causes a crash at runtime

### ISSUE THREAD

**Issue by ccapndave** [elm-lang/elm-compiler#1367]
If you have an incoming port with the unit type:

```elm
port myIncomingPort : (() -> msg) -> Sub msg
```

this causes a crash when trying to embed the Elm application in Javascript:

```
Main.js:9940 Uncaught ReferenceError: _Tuple0 is not defined(anonymous function) @ Main.js:9940(anonymous function) @ Main.js:11929
app.ts:33 ReferenceError: Elm is not defined(…)
```

**Comment by eeue56** [comment]
https://github.com/elm-lang/elm-compiler/pull/1361

ping @lukewestby

**Comment by lukewestby** [comment]
I closed that PR because I haven't had time to get an elm dev env set up to test the fix. If someone wants to take that code and test it and submit a new pr that would be excellent

**Comment by lukewestby** [comment]
Until then, if anyone is experiencing this bug you can work around it by sending an empty record `{}` over the port instead

**Comment by pdamoc** [comment]
Sending an empty record no longer works (`0.19.1`). The error is:

```
Uncaught Error: Trying to send an unexpected type of value through port `fromJS`: [object Object]
```

 If anyone runs into this issue, try sending `null` instead.

**Comment by lydell** [comment]
@pdamoc See also https://github.com/elm/core/issues/1043
