### ISSUE TITLE
Have `elm` list binaries instead of delegating

### ISSUE THREAD

**Issue by rtfeldman** [elm-lang/elm-compiler#1369]
Having `elm make` call out to `elm-make` is annoying in that:
- it makes there be two ways to run `elm-make`, and it's unclear which way is "better"
- it introduces a jargon problem - do you tell people it's `elm-package` or `elm package`? (clearly the former, but then why is the latter a thing?)
- newcomers to the language need to have the `elm` binary explained to them

If instead the `elm` binary simply did something like `ls elm-*` and printed out all the binaries it was aware of, maybe along with some cool ascii art, that would simplify things. 😄

**Comment by laszlopandy** [comment]
Or just remove all the elm-* from the path, and only let the main elm binary be exposed. This is how git does it and it seems that everyone is fine with git.

**Comment by avh4** [comment]
It's good for git because it has over 160 subcommands.

It's unnecessary complexity for elm which only has 6 (if you include -test and -format).  I expect that Elm's philosophy will also lead to trying to keep the number of subcommands small.

Why not remove the `elm` binary instead?  Does having it make things less confusing for beginners?

**Comment by rtfeldman** [comment]
Another point: what about third-party binaries that shouldn't be part of Platform, such as `elm-css`?

When people install `elm-css`, they add the package called `elm-css`, they get the binary from `npm install -g elm-css`, they talk about it in terms of `elm-css`...but they should run it as `elm css`? Or they should run `elm repl` without the dash but `elm-css` with the dash? Seems unnecessarily inconsistent. 😄

**Comment by evancz** [comment]
Everything will be in the `elm` binary in 0.19 and will work like `git` for things that are not built in. So `elm make` and `elm install` will be the standard way.
