### ISSUE TITLE
Allowing tabs for indentation

### ISSUE THREAD

**Issue by drathier** [elm-lang/elm-compiler#1370]
I think it's time to look at the tabs vs spaces debate. I currently do not see any reason to not allow tabs, as long as each file is consistent. The compiler could error out if a file mixes tabs and spaces.

The main argument for using tabs would be that some people prefer 2-space indentation, while others prefer 4 (or 8, 6 or 3). There's no reason to force everyone else to use the same indentation level as you are using. Setting the tab width in your editor of choice should be easy enough. 

I'm assuming that the influence Haskell has on Elm is the reason Elm forces spaces for indentation. Haskell requires column alignment in the syntax, so varying tab width is dangerous to a haskell program. Elm does not.

The main benefit of using spaces is column alignment, but that's against the [style guide](http://elm-lang.org/docs/style-guide) anyway.

**Comment by jvoigtlaender** [comment]
What makes you believe that Elm does not require column alignment?

**Comment by jvoigtlaender** [comment]
The following program is legal Elm:
```elm
import Html

main = let
         a = "a"
         b = "b"
       in Html.text (a ++ b)
```
The following program is not legal Elm:
```elm
import Html

main = let
         a = "a"
          b = "b"
       in Html.text (a ++ b)
```
Doesn't that destroy your argument?

**Comment by drathier** [comment]
Sorry, I was unclear. What I ment was, you don't have to align by column like in Haskell:

```
type Boolean = Literal Bool
             | Not Boolean
             | And Boolean Boolean
             | Or Boolean Boolean

```

It is more like indentation in Python. Thus, tabs work as indentation.

**Comment by jvoigtlaender** [comment]
> Thus, tabs work as indentation.

No, they don't, as my example shows:
```elm
import Html

main = let a = "a"
tab-tab-tab b = "b"
       in Html.text (a ++ b)
```
Depending on what the tab-size is, this program might or might not be correct Elm.

**Comment by drathier** [comment]
Sure, but 
```
type Boolean
    = Literal Bool
    | Not Boolean
    | And Boolean Boolean
    | Or Boolean Boolean
``` 
is valid with tabs, and follows the [style guide](http://elm-lang.org/docs/style-guide)

**Comment by jvoigtlaender** [comment]
And how does that help? The following is valid Haskell:
```haskell
data Boolean = Literal Bool
           | Not Boolean
                | And Boolean Boolean
             | Or Boolean Boolean
```
Does that mean Haskell has reason to eschew tab characters?

**Comment by jvoigtlaender** [comment]
Sorry, meant "Does that mean Haskell has *no* reason to eschew tab characters?" in the previous comment.

**Comment by LiamGoodacre** [comment]
@drathier your latest example is the only one so far which is actually using indentation, the rest are using spacing - which is a different thing and shouldn't use tabs.

**Comment by jvoigtlaender** [comment]
Anyway, I'll defer to @evancz. I'm pretty sure the fact that
```elm
import Html

main = let a = "a"
           b = "b"
       in Html.text (a ++ b)
```
is a legal Elm program, while
```elm
import Html

main = let a = "a"
            b = "b"
       in Html.text (a ++ b)
```
is not a legal Elm program means that the compiler should not accept tabs (because what might look like a legal Elm program in some editor with some set tab size might not anymore look like a legal Elm program in some editor with another set tab size).

**Comment by drathier** [comment]
But you can just add a line break, which makes tabs ok again:

```
import Html

main = 
    let 
        a = "a"
        b = "b"
    in Html.text (a ++ b)
```
```
main = 
    let 
        a = "a"
        b = "b"
    in 
        Html.text (a ++ b)
```
```
main =  let 
        a = "a"
        b = "b"
    in Html.text (a ++ b)
```

**Comment by jvoigtlaender** [comment]
I've said what I have to say. :smile:

**Comment by drathier** [comment]
[This style guide](https://gist.github.com/laszlopandy/c3bf56b6f87f71303c9f) uses C-like (Go-like) syntax formatting that works great with tabs. 

I'm not forcing you to change, I just don't want to be forced myself, or forced to force others :)

**Comment by drathier** [comment]
Pretty sure that could be one limitation when using tabs; it should be valid regardless of tab width. Shouldn't be too hard for the compiler/lexer to check.

**Comment by evancz** [comment]
I'm aware of this idea. This repo is for tracking bugs with the compiler. If you have changes, it's best to discuss them in one of the community forums and build support. I follow this stuff.
