### ISSUE TITLE
Doc comments with odd indentation cause parse problems

### ISSUE THREAD

**Issue by athanclark** [elm-lang/elm-compiler#1376]
In reference to [this issue](https://github.com/elm-lang/elm-make/issues/95#event-658283396), basically the module documentation parser is demanding 0 whitespace in the closing bracket, leaving a very inaccurate error. Specifically something like this:

```
{-| ...
-}
```

And not like this:

```
{-| ...
 -}
```

**Comment by evancz** [comment]
Thank you for the report! I am aggregating related problems into "omnibus issues" that will let me focus on a particular part of the compiler and do a bunch of fixes in a batch. This minimizes the amount of context switching needed to get to all the related issues. This one is covered by #1374. Thanks again for logging this one!

**Comment by evancz** [comment]
I can not reproduce this with the new parser. Thanks for the report!
