### ISSUE TITLE
Json.encode and Json.decode not roundtripping

### ISSUE THREAD

**Issue by jvoigtlaender** [elm-lang/elm-compiler#1378]
SSCCE: In the compiler repo sandbox (presumably a directory of the form `.../Elm-Platform/0.17`), put the following file `Test.hs`:

``` haskell
import qualified Elm.Compiler.Type
import Data.Aeson as Json

test =
  let
    tipe = Elm.Compiler.Type.Type "_Tuple0" :: Elm.Compiler.Type.Type
    json = Json.encode tipe
    result = Json.decode json :: Maybe Elm.Compiler.Type.Type
  in
   case result of
     Nothing -> error "How is this not a Just?"
```

and then do:

```
> cabal repl
GHCi, version 7.10.2: http://www.haskell.org/ghc/  :? for help
Prelude> :l Test.hs
[1 of 1] Compiling Main             ( Test.hs, interpreted )
Ok, modules loaded: Main.
*Main> test
*** Exception: How is this not a Just?
```

I think the solution is to not have `Json.decode` for that `Type` type anymore.  See https://github.com/elm-lang/package.elm-lang.org/pull/111, which was merged, later reverted.

**Comment by jvoigtlaender** [comment]
More context on why https://github.com/elm-lang/package.elm-lang.org/pull/111 was reverted, as a stop-gap measure: https://groups.google.com/d/msg/elm-dev/G9FGTAyHATk/8cM02uT3AwAJ

That's also why "the elm-compiler part" mentioned in https://github.com/elm-lang/package.elm-lang.org/pull/111#issuecomment-158076950 wasn't done.

The roadmap would be (but was blocked by stuff going on in other branches of the packages.elm-lang.org repo, the docs preview or the diff stuff, making it unfeasible to work on `master`):

1. Make sure the `docs/*.json` files are not used anymore. (They should not be, as you agreed to [here](https://groups.google.com/d/msg/elm-dev/G9FGTAyHATk/-9WF9Av4AwAJ).)
2. Reinstate https://github.com/elm-lang/package.elm-lang.org/pull/111.
3. Drop the `FromJSON` instance for `Elm.Compiler.Type.Type` in this repo here (and probably also other `FromJSON` instances, whose only purpose was to enable the one for `Elm.Compiler.Type.Type`).

**Comment by evancz** [comment]
I stopped using `aeson` recently, so if this is still an issue, it is at least different now.
