### ISSUE TITLE
hintLink points to 0.17.0 but on github, only the tag 0.17 is known

### ISSUE THREAD

**Issue by tcoopman** [elm-lang/elm-compiler#1379]
An example of an link on elm-lang.org/try

```
Usually staring at the type is not so helpful in these cases, so definitely read
the debugging hints for ideas on how to figure this out:
<https://github.com/elm-lang/elm-compiler/blob/0.17.0/hints/infinite-type.md>

```
This link is not correct. It should be https://github.com/elm-lang/elm-compiler/blob/0.17/hints/infinite-type.md.

The code is found here: https://github.com/elm-lang/elm-compiler/blob/716f65354b40d02993e0a77df71cf3064ab7efb6/src%2FReporting%2FError%2FHelpers.hs#L53

Because I don't know how you want to fix this, I'm not submitting a PR.

**Comment by evancz** [comment]
Added a 0.17.0 tag so things should work now.
