### ISSUE TITLE
Feature Request: Support for type inspection

### ISSUE THREAD

**Issue by Fresheyeball** [elm-lang/elm-compiler#1387]
It would rock if an editor/IDE would show type information of hover, for all variables (not just top level). I believe this requires compiler support, and there is definitely desire:

- https://github.com/mybuddymichael/linter-elm-make/issues/23
- https://github.com/sbrink/vscode-elm/issues/25
- https://github.com/rundis/elm-light/issues/14

**Comment by evancz** [comment]
As mentioned in #1388, I think it makes some sense to be able to spit out the AST for editor folks. If that format exists, it could also be consumed by the Elm compiler. So I can imagine putting little `?` holes in that AST so editor folks can ask for certain information in a strategic way.

That route is dependent on the `elm-format` work on spitting out an AST, so this is at least blocked on that. It's also not clear that this will ultimately be the right way to go about things. So obviously this is something that I'd like Elm to have, but I don't think tracking it here will make it happen any faster.
