### ISSUE TITLE
Feature Request: Rename Refactor

### ISSUE THREAD

**Issue by Fresheyeball** [elm-lang/elm-compiler#1388]
Its useful to support the renaming of things. 

Changing the name of a variable can impact multiple modules, and it would be nice if there was a way the compiler could support this workflow, as "find/replace" doesn't comprehend the structure of Elm code. Same for renaming modules, and types (most especially types). 

It would be even nicer if shadows and conflicts are called out in the workflow if they exist.

**Comment by bgourlie** [comment]
Renaming/Refactoring is a tooling concern, not a compiler concern.  The elm plugin for intellij already supports this.

**Comment by evancz** [comment]
I have talked with @avh4 recently about how to make this happen. The current idea is to make the following things true:

  - `elm-format` can spit out an AST (with comments) that anyone can use
  - `elm-format` can accept an AST that has been changed in various ways

From there, it is the role of the editor authors to implement this kind of feature. So in the end, yeah, this should not need any changes in the compiler.
