### ISSUE TITLE
"type applications should start with a type atom"

### ISSUE THREAD

**Issue by avh4** [elm-lang/elm-compiler#1391]
The following minimal example (in 0.17):

```elm
type Model source out
    = Model
        { currentValue : source
        , definition : (source -> out, source)
        }


init : (source -> out) -> source -> Model source out
init fn def0 =
    fn <| Model
        { currentValue = def0
        , definition = (,) fn def0
        }
```

Produces the following error:

```
-- TYPE MISMATCH ---------------------------------------------------------------

The type annotation for `init` does not match its definition.

9| init : (source -> out) -> source -> Model source out
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
The type annotation is saying:

    (a -> b) -> a -> Model a b

But I am inferring that the definition has this type:

    elm-make: type applications should start with a type atom
```

which seems to be an unexpected and unhandled condition in the compiler.

**Comment by jvoigtlaender** [comment]
There have been several reports of this bug as issues here already, that Evan has closed as duplicates of an existing one.

**Comment by jvoigtlaender** [comment]
For example, https://github.com/elm-lang/elm-compiler/issues/1238 and https://github.com/elm-lang/elm-compiler/issues/1326.

**Comment by avh4** [comment]
Oh, oops, I searched for the other one I just files and didn't see it, so I assumed this one didn't exist yet either.

Dupe of https://github.com/elm-lang/elm-compiler/issues/1238
