### ISSUE TITLE
Let allows use of variable before it is properly defined

### ISSUE THREAD

**Issue by Skinney** [elm-lang/elm-compiler#1392]
Minimal test case which should not compile.

```elm
import Html exposing (text)

main =
  let
    h1 = h1 + 7
  in
    text "Hello, World!"
```

Elm allows you to use `h1` before it has been defined. In the resulting Javascript, `h1` has the value `undefined`. `undefined` + 7 results in `NaN` which, while valid javascript, really shouldn't be a state your program should be allowed to get into when you're writing Elm.

**Comment by mgold** [comment]
Yet another dupe of #873.

**Comment by Skinney** [comment]
So sorry. I looked through the issue list and didn't find anything. Must have missed this one.

**Comment by mgold** [comment]
They say that dupe frequency indicates how many users are affected by a bug...
