### ISSUE TITLE
elm-make complains about overlap in non-exposed infix operators

### ISSUE THREAD

**Issue by xarvh** [elm-lang/elm-compiler#1394]
```
> elm make --yes src/Main.elm --output build/app.js

-- INFIX OVERLAP ----------------------------------------------- ./src/Pasat.elm

The infix declarations for (&>) must be removed.

9| infixl 9 &>
   ^^^^^^^^^^^
The precedence and associativity of a particular operator can only be set in one
place in a code base, and (&>) has already been set somewhere else.

Detected errors in 1 module.    
```

To reproduce:

* Clone https://github.com/xarvh/cortex/pull/24
* Run `npm run build` (Succeeds)
* Modify in any trivial way `src/Pasat.elm` to trigger recompile
* Run `npm run build` again (Fails with the error above)

**Comment by jvoigtlaender** [comment]
* https://github.com/elm-lang/elm-compiler/issues/1096
* https://github.com/elm-lang/elm-compiler/issues/1305#issuecomment-198502129
* https://github.com/elm-lang/elm-compiler/issues/1375#issue-154600343

**Comment by evancz** [comment]
What @jvoigtlaender is saying is that this problem is tracked in #1375 about changing the parsing pipeline to sort out precedence later. For now, this is just how it is. Probably best to just not define custom infix operators anyway. I regret making them in 99% of cases.
