### ISSUE TITLE
[0.17] destructured record fields don't hide existing variables

### ISSUE THREAD

**Issue by avh4** [elm-lang/elm-compiler#1395]
The following program should display "True", but instead enters an infinite loop because the `f` in the body of the function is referring to the top-level `f` instead of the destructured parameter `f`

![screen shot 2016-05-24 at 10 33 44 pm](https://cloud.githubusercontent.com/assets/1222/15529160/054eba2e-2200-11e6-9014-b17efa53f804.png)

A comparable program that doesn't use record destructuring works correctly (displays "hi"):

``` elm
import Html

f : a -> a
f f = f

main = Html.text <| f <| "hi"
```

**Comment by jvoigtlaender** [comment]
But it's not specific to record destructuring. This also hangs:
```elm
import Html

f : (String -> Bool) -> Bool
f f = f "Hello"

main = Html.text <| toString <| f <| always True
```

**Comment by laszlopandy** [comment]
The more examples I see [like this](https://github.com/elm-lang/geolocation/commit/0a4bb90cab807ee0d31b38356921a84747548fda#diff-37d15480c9455db8ded300c2ae87a919L250), the more I think shadowed variables should be an error, plain and simple.

**Comment by evancz** [comment]
Took @laszlopandy's advice, so in the development build, the errors for the various programs in here are:

```
-- SHADOWING ---------------------------------------------------------- temp.elm

These variables cannot have the same name:

12| f {f} = f "Hello"
    ^  ^
Think of a more helpful name for one of them and you should be all set!

Note: Linters advise against shadowing, so Elm makes “best practices” the
default. Read <https://elm-lang.org/hints/0.19.0/shadowing> for more details on
this choice.
```

```
-- SHADOWING ---------------------------------------------------------- temp.elm

These variables cannot have the same name:

9| f f = f
   ^ ^
Think of a more helpful name for one of them and you should be all set!

Note: Linters advise against shadowing, so Elm makes “best practices” the
default. Read <https://elm-lang.org/hints/0.19.0/shadowing> for more details on
this choice.
```

Etc.

Thank you for the report, and thanks to Laszlo for having excellent design sense! 😄
