### ISSUE TITLE
function parameter referenced in nested let can be undefined when referenced

### ISSUE THREAD

**Issue by avh4** [elm-lang/elm-compiler#1396]
I'm not sure exactly what is going on, but the follow programing (in 0.17) produces a runtime error when you click the button.

```elm
import Html exposing (Html)
import Html.App as Html
import Html.Events as Html

choice' right =
    let
        selectNew _ =
            let
                all = right |> List.reverse

                right =
                    all
            in
                all |> Debug.log "OK"
    in
        Html.map selectNew
            <| Html.button [ Html.onClick () ] [ Html.text "button" ]


main = 
  choice' [] 
```

The error is `Uncaught TypeError: Cannot read property 'ctor' of undefined`
![screen shot 2016-05-24 at 11 28 32 pm](https://cloud.githubusercontent.com/assets/1222/15530113/4029ec0c-2207-11e6-9d16-908f085e62e7.png)

When this happens, `right` (the outer one) is undefined when `selectNew` gets called.

Deleting `right = all`, or renaming either of the two variables called `right` makes the problem go away.

**Comment by jvoigtlaender** [comment]
> When this happens, right (the outer one) is undefined when selectNew gets called.

No, doesn't seem like that. In `all = right |> List.reverse` you are not referencing the outer `right`. You are referencing the `right = all`. Note that `let` is a recursive `let`, including mutual recursion.

**Comment by jvoigtlaender** [comment]
In other words, if anything, this is an instance of #873.

**Comment by avh4** [comment]
If you look at the compiled javascript, you can clearly see that it is in fact referencing the outer `right`.  This can also be seen in the following program which shows that the outer variable can be referred to in a let block https://gist.github.com/avh4/8954024d05928c54eeeb116bab13d39c

**Comment by jvoigtlaender** [comment]
The semantics of Elm is that in
```elm
f text =
  let
    b = text
    text = b
  in
    text
```
the `b = text` and `text = b` are referring to each other, not one of them to the outer `text`.

That it seems like the `b = text` is referring to the outer `text` is an accidental side effect of #873.

**Comment by jvoigtlaender** [comment]
If you don't agree with the 
> The semantics of Elm is

part, ask @evancz, he will confirm.

**Comment by avh4** [comment]
That sounds fine if that's what's intended.

**Comment by domenkozar** [comment]
I *think* I've hit this one with `case` yesterday. Couldn't manage to provide ahttp://sscce.org sadly.

**Comment by evancz** [comment]
Agree with @jvoigtlaender's diagnosis
