### ISSUE TITLE
ghc 8 workaround for dependencies

### ISSUE THREAD

**Issue by ilovezfs** [elm-lang/elm-compiler#1397]
To get elm building under GHC 8.0.1 for Homebrew (we only typically support the latest GHC), I've needed to add a "cabal.config" file at the root of the package containing "allow-newer: aeson,base,HTTP,time,transformers", at which point everything builds as expected. Without this, I get

```
Resolving dependencies...
cabal: Could not resolve dependencies:
trying: elm-compiler-0.17 (user goal)
trying: base-4.9.0.0/installed-4.9... (dependency of elm-compiler-0.17)
trying: unix-2.7.2.0/installed-2.7... (dependency of
process-1.4.2.0/installed-1.4...)
next goal: aeson (dependency of elm-compiler-0.17)
rejecting: aeson-0.11.2.0, aeson-0.11.1.4, aeson-0.11.1.3, aeson-0.11.1.2,
aeson-0.11.1.1, aeson-0.11.1.0, aeson-0.11.0.0, aeson-0.9.0.1, aeson-0.9.0.0
(conflict: elm-compiler => aeson>=0.7 && <0.9)
rejecting: aeson-0.8.1.1, aeson-0.8.1.0, aeson-0.8.0.2 (conflict:
base==4.9.0.0/installed-4.9..., aeson => base>=4.5 && <4.9)
rejecting: aeson-0.7.0.6, aeson-0.7.0.4 (conflict: unix =>
etc. etc.
```

**Comment by evancz** [comment]
I don't think there are clear things for me to do here, so I am going to close.

Elm 0.17 is just meant to be built with 7.10 and I think it's just that way. We will probably upgrade GHC for future releases though.

**Comment by ilovezfs** [comment]
@evancz You certainly don't have to do anything. The main point is to inform upstreams of any patching we do, which is a matter of policy for us.
