### ISSUE TITLE
List.uniq_by

### ISSUE THREAD

**Issue by hamiltop** [elm-lang/elm-compiler#1403]
Currently the only way to dedupe a list is to convert it to a set and then back to a list. However, this only works for comparable types. To do this with records or other non comparable types, one could convert it to a dict via a comparable key and then call `Dict.values`.

Both of these workarounds can be avoided with a `List.uniq_by : (a -> comparable) -> List a -> List a`

This likely ties in with https://github.com/elm-lang/elm-compiler/issues/1008

**Comment by jvoigtlaender** [comment]
@hamiltop, I suggest to read this: https://github.com/elm-lang/core/blob/master/CONTRIBUTING.md#adding-new-functions

Your feature request would be well suitable for https://github.com/elm-community/list-extra.

So I further suggest that you open an issue (or even a pull request) over there, for adding a `dropDuplicatesBy` of the function which is already there: http://package.elm-lang.org/packages/elm-community/list-extra/2.0.0/List-Extra#dropDuplicates.

**Comment by hamiltop** [comment]
Seems reasonable. Thanks!
