### ISSUE TITLE
Repository names with `.` generate invalid JS

### ISSUE THREAD

**Issue by neoeinstein** [elm-lang/elm-compiler#1406]
Given an `elm-package.json` file like the following:

```json
{
    "version": "1.0.0",
    "summary": "Error reproduction Elm 0.17",
    "repository": "https://github.com/example/error.repro.git",
    "license": "BSD3",
    "source-directories": [
        "src"
    ],
    "exposed-modules": [],
    "dependencies": {
        "elm-lang/core": "4.0.0 <= v < 5.0.0",
        "elm-lang/html": "1.0.0 <= v < 2.0.0"
    },
    "elm-version": "0.17.0 <= v < 0.18.0"
}
```

Elm generates invalid JavaScript:
![image](https://cloud.githubusercontent.com/assets/18165/15793184/5ced9360-29b0-11e6-9ade-7746bef35d18.png)
![image](https://cloud.githubusercontent.com/assets/18165/15793207/7ffd3a86-29b0-11e6-8123-a8989fc0a264.png)

In the event of a `.` in a repository name, Elm should convert it to an underscore as it does in other cases of `-` in a repository name.

**Comment by evancz** [comment]
That would be ambiguous though. `tom/this.that` would be the same as `tom/this-that`. Is there a better way to avoid this?

**Comment by dam5s** [comment]
I think it would be great to be able to specify a repository that is not on Github or specify how we want to namespace our modules. For instance, I've been doing work for a client, and using Github is not an option for them, so being able to specify an alternative would be nice in that context.

An example of config could look like
```
{
    "version": "1.0.0",
    "repository": "https://example.com/dam5s/my.repo.git",
    "jsNamespace": "dam5s$myRepo",
    ....
}
```

**Comment by zsiciarz** [comment]
Ran into a similar problem in my project (https://github.com/zsiciarz/variablestars.net/tree/elm-0.17). The generated JS file contains names like these:

`_zsiciarz$variablestars.net$Astronomy$dateToJd`
`_zsiciarz$variablestars.net$Astronomy$jdToTime`

and so on. The actual console error is `SyntaxError: missing ; before statement` pointing to the first occurence of a variable name like above.

Here's my [elm-package.json](https://github.com/zsiciarz/variablestars.net/blob/elm-0.17/elm-package.json). Not sure how to fix this though, perhaps there could be a way to set some sort of alias for the project, so that generated identifiers use that instead of the name of the repo?

**Comment by evancz** [comment]
Tracking in #1377, thanks for the report!

**Comment by evancz** [comment]
In 0.19 it will not be possible to give packages names like this, thereby avoiding the code gen issues and making package names more uniform across the ecosystem.

**Comment by mfeineis** [comment]
I ran into an issue with the `no dots in project names` approach: I'm currently building a `myname.github.io` page and this repo **has** to have the dots in the name for github to use that repo when you're using the simplest approach. See [githubs docs on configuring a publishing source](https://help.github.com/articles/configuring-a-publishing-source-for-github-pages/) on that. Just wanted that to sit in a place other than Slack :-). Thanks for the good work, it's making my life so much more fun.

**Comment by zwilias** [comment]
@mfeineis It's recommended to leave the repository set to the default `http://github.com/user/project.git` for applications. There is no value to changing it, other than possibly breaking the compiled result 😉 .

There is a bunch of metadata in `elm-package.json` that only makes sense to change for packages published to the package repository (like version, repo, description, license). If I'm not mistaken, these fields will no longer longer be available in the application descriptor file in Elm 0.19; to prevent this type of confusion.

**Comment by mfeineis** [comment]
@zwilias Thank your for the clarification, that's exactly what I did :-). As you guessed the result won't be published on `package.elm-lang.org` but is for my blog that is currently in migration-to-elm-static-html-lib mode.
