### ISSUE TITLE
enhancement: improve type annotation error message

### ISSUE THREAD

**Issue by arnehormann** [elm-lang/elm-compiler#1410]
Taking `Bug.elm` with Elm 0.17
```elm
import Html exposing (..)
import Html.App exposing (beginnerProgram)

main =
  beginnerProgram
    { model = {key = "", value = ""}
    , view = view
    , update = (\_ u -> u)
    }

type alias Model =
  { key: String
  , value: String
  }

view : Model -> Html msg
view m =
  div
    []
    [ strong [] [m.key]
    , text (": " ++ m.value)
    ]
```
I get this error on `elm-make Bug.elm --output=bug.html`:
```
-- TYPE MISMATCH ------------------------------------------------------- Bug.elm

The type annotation for `view` does not match its definition.

16| view : Model -> Html msg
           ^^^^^^^^^^^^^^^^^
The type annotation is saying:

    { ..., key : String } -> Html a

But I am inferring that the definition has this type:

    { ..., key : VirtualDom.Node a } -> Html a

Detected errors in 1 module.
```

The cause is `strong [] [m.key]`, it should be `strong [] [text [m.key]]`.

Though the compiler knows all intended types, it says the annotation in `view` is wrong and does not point to the wrong argument for `strong`.

This error message confused me for an embarrassing time, it could probably be improved. I'm new to the language (which is amazing) and this was one of the issues that made me stumble - the hardest in this case. I'm reporting it so [Elm can be mainstream](http://www.elmbark.com/2016/03/16/mainstream-elm-user-focused-design) 😀

**Comment by mgold** [comment]
This might work better on the [error message catalog](https://github.com/elm-lang/error-message-catalog/issues/new). Maybe @process-bot could learn about that too.
