### ISSUE TITLE
Quote (prime) in record field name sent through port causes JS SyntaxError

### ISSUE THREAD

**Issue by ricklupton** [elm-lang/elm-compiler#1414]
If a record field with a quote (prime) character in it, such as `field'`, is sent through a port, the compiled JS code is invalid.

Here is a SSCCE:
```elm
port module QuoteBug exposing (main)

import Html exposing (text)

type alias Record = { field' : String }
port recordPort : Record -> Cmd msg

main = text "hello"
```

This generates the following JavaScript, which obviously causes a SyntaxError:
```js
var _user$project$QuoteBug$recordPort = _elm_lang$core$Native_Platform.outgoingPort(
	'recordPort',
	function (v) {
		return {field': v.field'};
	});
```

I am using Elm 0.17 (on Linux, installed via npm).

**Comment by evancz** [comment]
Tracking in #1377. Thanks for the report!

**Comment by evancz** [comment]
No longer a problem in 0.18
