### ISSUE TITLE
Error message could help more with finding offending functions

### ISSUE THREAD

**Issue by willnwhite** [elm-lang/elm-compiler#1419]
![why string - html changing to text tostring model fixes this somehow](https://cloud.githubusercontent.com/assets/8081877/16129812/5f17c13a-33fe-11e6-811b-9c17620f6c4c.png)
It's `String -> Html Msg` because `text` is `String -> Html Msg`. The compiler must know that, so it could say that too. The solution here is to change to `text (toString model)`.

**Comment by mgold** [comment]
This would be a better fit for the [error message catalog](https://github.com/elm-lang/error-message-catalog/issues/new).

**Comment by willnwhite** [comment]
![](http://www.reactiongifs.us/wp-content/uploads/2014/03/not_aware_waynes_world.gif)

Thank you.
