### ISSUE TITLE
Renaming/Re-exporting infix raises `Maximum call stack size exceeded` error

### ISSUE THREAD

**Issue by Warry** [elm-lang/elm-compiler#1421]
I discovered recently that the infix operators behaviours had changed. It seems that it is now impossible to redefine an operator, and "re-exporting" an operator may compile, but raises a runtime error as follows:

```elm
module Infix exposing (..)
import Json.Decode exposing ((:=))
(:=) = (:=)
```

When using `(:=)` from Infix, there is a *Maximum call stack size exceeded* error at runtime.

**Comment by mgold** [comment]
Seems to be another dupe of #873...
