### ISSUE TITLE
Proposal: allow union type extension to help address the Expression Problem

### ISSUE THREAD

**Issue by mlanza** [elm-lang/elm-compiler#1423]
In Clojure protocols are open for extension.  You can define new types that conform to an existing protocol.  This works because each type is defined independently rather than as part of a closed set as is the case with Elm's union types.

If my program defines a union type then I can extend it directly. If I want to use some popular third-party library for payment processing, however, and also support bitcoin I'd have to

    type Payment = CreditCardPayment | PayPalPayment -- in third-party library
    type ExtendedPayment = Payment | Bitcoin -- in my library

but I would prefer

    extend type Payment = (..) | Bitcoin

Obviously, I would then have provide a similar extension to each of the functions that accept the type

    show : Payment -> String
    extend show pymt = 
      case pymt of
        Bitcoin -> "One-million dollars!"

When you consider that someone else might come along and want to extend my library with yet another option you can see how wrapping and rewrapping union types can make it unnecessarily awkward to share and reuse code.

    type ExtendedExtendedPayment = ExtendedPayment | StockOptions

While permitting extension makes the compiler's job more difficult, it doesn't break static type checking.  Rather it allows types that may belong to some union to be added in modular fashion similar to [partial classes](https://msdn.microsoft.com/en-us/library/wa80x488.aspx) in C#.  Complex union types could be split across several files so that all of the logic for a particular union subtype could be neatly bundled together allowing each file to speak to a separate concern.

This design could also allow the hot reloading of union types.  Think dynamic plugins!  Developers love writing extensible products.  Take any of the popular text editors.  Many can load and apply plugins without having to restart the editor.  The same would be possible in Elm.

The problem with union types is that all of the participants in the set must be known at compile time.

    type Plugin = ParanMatching | AutoComplete | Snippets -- what about those not yet written?

With extensible union types that set could remain open.

    type Plugin = (..)

    activate : Plugin -> Plugin
    activate plugin = (..)

    deactivate : Plugin -> Plugin
    deactivate plugin = (..)

The set might start off as empty and at run time, per user configurations, be extended as the chosen modules (plugins, components, widgets) are loaded.  Each module, during its own packaging process, would have already been been statically checked for completeness keeping all of the compile-time benefits of Elm intact.

**Comment by mgold** [comment]
I think this would be more suited for the `elm-dev` mailing list.

**Comment by mlanza** [comment]
OK.  The checklist didn't mention what to do with proposals so I wasn't sure and I did see other proposals reported this way.

**Comment by samvv** [comment]
Is there by any chance a link to the relevant discussion on the mailing list? Really interested in this one ...

**Comment by samvv** [comment]
@mlanza Never mind, found id 😊  https://groups.google.com/forum/#!searchin/elm-dev/union$20type$20extensions%7Csort:date/elm-dev/HEF2Yca4B6Q/Bm-aX1QxBgAJ Has there been any follow-up?

**Comment by mlanza** [comment]
@samvv here is the thread:

https://groups.google.com/d/topic/elm-dev/wymnXbZy5wA/discussion

The discussion didn't go far, but if you have new insight to offer or if you want to advance it please advocate your thoughts.
