### ISSUE TITLE
Feature Request: destructuring record with alias

### ISSUE THREAD

**Issue by jinjor** [elm-lang/elm-compiler#1424]
For example,
```elm
case model.maybeChild of
  Just { model } -> ...
```
this hides original `model` value. So it would be nice to have `as` keyword for destructuring record. Like this:

```elm
case model.maybeChild of
  Just { model as childModel } -> ...
```
How do you think?

**Comment by mgold** [comment]
The `elm-dev` mailing list is probably a better place for this. Although nonessential language changes are heavily scrutinized, I personally like this idea and think it fits nicely with how the `as` keyword works today.

**Comment by jinjor** [comment]
Thank you for your advice.
But sorry, after thinking more, now I am not confident with this idea by following reasons.

1. This problem can be avoided by just not using destructuring.
2. The same thing is also said about `import SomeModule exposing (someFunc)` syntax

If imported function names are duplicated, using absolute name is a natural thing. That may be the better solution. So I close this.
