### ISSUE TITLE
Runtime Error: Subscription to Time.every x where x is computed based on the model

### ISSUE THREAD

**Issue by jesseilev** [elm-lang/elm-compiler#1426]
The example below behaves weirdly and then crashes after a little while. 

It is a simple timer that increments a label every so often:

```elm
import Html exposing (text)
import Html.App as App
import Time exposing (Time)


model = 
  0
  

init = 
  ( model, Cmd.none )


type Msg 
  = Tick Time
  
  
update msg model =
  case msg |> Debug.log ("tick #" ++ (toString model)) of 
    Tick _ ->
      ( model + 1
      , Cmd.none
      )


subscriptions model =
  let 
    tickLength = 
      if model % 10 == 0 then 100 else 1000
  in 
    Time.every tickLength Tick
    
    
view model =
  text (toString model) 


main =
  App.program
    { init = init 
    , update = update
    , subscriptions = subscriptions
    , view = view
    }
```

The timer ticks once per second, *unless* the current time is a multiple of 10, in which case it speeds up and increments every 0.1 seconds ("every" is sort of misleading of course, because the faster tick only happens once in a row).

The eventual error is:

```
compile:2678 Uncaught TypeError: Cannot read property 'ctor' of null
```

### Versions and Stuff

Elm:

* 0.17.0 (locally)
* also occurs on elm-lang.org/try (might be 0.17.1)

Browsers:

* Chrome  51.0.2704.103 (64-bit)
* Safari 9.1 (11601.5.17.1)

OS

* OSX 10.11.4

### Description of Symptoms

The first 11 ticks seem to go smoothly. We transition from 10 to 11 more quickly, as expected. But then...

We also go really quickly from 12 to 13, and from 14 to 15, etc. So now the numbers are now coming in pairs: Pause for 1 second on an odd number, then skip quickly over the even number to the next odd number.

After a while, the numbers start coming in groups of 3:  pause at 21, skip to 24 and pause, skip to 27 and pause, etc. The exact numbers here are *not* deterministic. For example, sometimes it is 22, 25, 28...

Near the 30s, we start getting groups of 4. Near the 40s, groups of 5, etc.

Pretty soon the crash happens. Usually in the early 50s could be anywhere in the 30 - 70 range.

I also observed it is *not* the case that the gratuitous skipping occurs in intervals of 100ms or whatever time I specify as the "fast" time. Many of the skips occur in smaller intervals of just a few dozen milliseconds (varies a little), maybe the browser's refresh rate?

**Comment by jvoigtlaender** [comment]
Possibly related: https://github.com/elm-lang/core/issues/612, https://github.com/elm-lang/core/issues/628.

**Comment by OvermindDL1** [comment]
This was likely fixed by https://github.com/elm-lang/core/commit/9320969bf47082b902d4511ef8a48a93612d7bf0 and should be tested and closed if so.

**Comment by evancz** [comment]
Great SSCCE, thanks @jesseilev! And thank you @OvermindDL1 for tracking down all these related issues!

I was able to reproduce this by making the timer increments smaller (more chance of problem / second) and unable to produce it when the mentioned fix was in place. So I'm going to close. If you see this again with core 4.0.4, please open a new issue!
