### ISSUE TITLE
Proposal: Bring back record field adding/deletion

### ISSUE THREAD

**Issue by KatsCyl** [elm-lang/elm-compiler#1427]
````Elm
record = { x : 4 }
evenBetterRecord = { record | y = 5 }
````

Elm had this feature, and I think it still should have it. Mainly because it makes it possible to follow '[Scrap Your Typeclasses](http://www.haskellforall.com/2012/05/scrap-your-type-classes.html)' without insane amounts of boilerplate. 

I can see how this feature may not be used by the average elm developer, but for developers maintaining/creating packages it would be really handy. 

Personally I have created way too many toSomethingComparable functions for my own datatypes, and I'd like this to change.

For more detailed description on why this is needed can be found [here](http://reasonablypolymorphic.com/blog/elm-is-wrong)

**Comment by mgold** [comment]
You know, hurling a lot of insults isn't going to endear you to people who maintain the language. You should go try PureScript. No, I don't need a lengthy exposition of why it sucks too. This post is what "I'm tired of open source" blog posts are made of. Shoo.

**Comment by KatsCyl** [comment]
Sorry, I wasn't really trying to 'hurl a lot of insults'. I am aware that the blog post I linked is a bit salty towards Elm, and I can say that I don't agree on the hate aspect of it. I just think it had a good point about how the addition to record syntax would be a nice feature, even though it was written maybe not in the most constructive way. 

I haven't looked at PureScript, but I don't think that even if I did I would stop using Elm. I like the language, and I think it has enough good sides to bear the writing of occasional boilerplatish code. I just think that it would be better if I didn't have to write it.

**Comment by mgold** [comment]
> I am aware that the blog post I linked is a bit salty

I totally didn't realize that you weren't the author of the post! I'm so sorry!

> I haven't looked at PureScript

That remark was aimed squarely at the author of the post.

As for the issue at hand... the feature was removed because no one had found a good use for it, and having it around lead to confusion (i.e. record updates were not type-stable). "Here's a neat trick from Haskell" is never, by itself, considered good enough reason to add something to Elm. But if you can identify a real pain point in building web apps, let's hear it.

**Comment by mgold** [comment]
Or, as Evan [said](https://github.com/elm-lang/elm-compiler/issues/1283):

>I think it makes sense to continue discussion in this issue if you think there are valid use cases that we did not see in the 2+ years of having the feature, or that did not come up in the discussions explicitly searching for use cases before it was removed, or that for some reason have not been brought up here already. Once there is a specific and compelling example, perhaps it makes sense to open a new issue that focuses on it explicitly.

**Comment by KatsCyl** [comment]
I don't think how common of a problem my problem is, but for me the greatest pain in writing Elm, is the fact that you cannot define for example comparable instances for your own types. Currently I 've had to resort to writing toInt or toString functions for my datatypes. I like to use my own types as identifiers in dicts, or have sum types which describe some sort of ordering for example.

The record syntax addition would be a fix for the problem, but to be honest anything works for me. I don't really have enough expertise on anything to suggest what would be the best way to achieve this.

I understand if this feature doesn't possibly fit the Elm ideology of being as simple as possible, and if it is just unreasonably complex and/or would complicate the language in some way which I cannot foresee, but I think that having things like comparable should implicate that you can define things to be them.

**Comment by mgold** [comment]
Wanting union types as Dict keys is reasonable, and I think Evan has said as much. (So is wanting to sort a list of custom types, and thankfully it's the same fix.) Some related proposals include making records of comparable things comparable, and making booleans comparable (so data structures containing them are comparable). Implemented well, this could be a lot easier than the SYTC approach! My biggest concern is whether we can automatically infer comparability for anything that a user could reasonably want to compare.

**Comment by evancz** [comment]
If the root problem is "I want more values to be valid keys in dictionaries" I agree that this can be improved. Changing records back would not achieve that at all though. You may be overestimating how flexible this feature was. You cannot just add fields willy-nilly. They'd all show up in the types, so you would not be adding unlimited fields at runtime.

As for the claim that this feature makes the explicit record passing described in Scrap Your Type Classes easier, that is also false. I think [this paper](https://lirias.kuleuven.be/bitstream/123456789/304985/1/icfp001-Devriese.pdf) may help clarify that. Point is, if *that* is the real goal, this approach will also not help in the end.

**Comment by wires** [comment]
I'd like to plea to open this or a similar issue. We can get very far with current Elm, but in many "Real World" scenarios, it's type system is lacking.

So I read the paper but I cannot see where it says something about why SYTC wouldn't benefit from this feature request?
