### ISSUE TITLE
Unexpected results due to variable shadowing

### ISSUE THREAD

**Issue by gurgl** [elm-lang/elm-compiler#1428]
```elm
update : Msg -> Model -> (Model, Cmd Msg)
update msg model =
  let
  newModel = updateModel msg model
  cmd2Send =
    case msg of
      SelectCity locId ->
        WebSocket.send echoServer (toString locId)

      Send ->
        WebSocket.send echoServer newModel.input

      Discard card ->
        let msg= Json.Encode.encode 0 (jsonEncCardAction (CardAction card CardActionDiscard))
        in WebSocket.send echoServer msg


      otherwise ->
          Cmd.none
  in (newModel, cmd2Send)
```
1. msg is the argument of function above
2. msg is then reassigned in "Discard card" of case clause
3. no compiler error - leads to hard to find .js bugs

...
using elm 17.0

**Comment by gurgl** [comment]
...other than that i must say im VERY pleased with what you have done. Never been this joyful coding web apps before! Just a GREAT accomplishment.

**Comment by mgold** [comment]
Variable shadowing is permitted, with the innermost definition taking precedence over the others. That said you're not the first person to find it bothersome.

If you still think it's a bug, please come up with an [SSCCE](http://sscce.org/).

**Comment by gurgl** [comment]
Just wanted to clarify the generated .js code results in that variable "msg" gets overwritten in above example in Discard card.  Then the updateModel function gets called with whatever was set. Different type, different value.

**Comment by jvoigtlaender** [comment]
Can you show that generated .js code here please?

**Comment by gurgl** [comment]
This was the code that caused the problem. Might be some small difference in the elm code above but probebly not. Note "...var msg = A2(..." in Discard "case". If "cmd2Send" is evaluated before "newModel" we'll have a crash.

```
var _gurgl$julius_caesar$Update$echoServer = 'ws://localhost:9160';
var _gurgl$julius_caesar$Update$update = F2(
    function (msg, model) {
        var newModel = A2(_gurgl$julius_caesar$Update$updateModel, msg, model);
        var cmd2Send = function () {
            var _p16 = msg;
            switch (_p16.ctor) {
                case 'SelectCity':
                    return A2(
                        _elm_lang$websocket$WebSocket$send,
                        _gurgl$julius_caesar$Update$echoServer,
                        _elm_lang$core$Basics$toString(_p16._0));
                case 'Send':
                    return A2(_elm_lang$websocket$WebSocket$send, _gurgl$julius_caesar$Update$echoServer, newModel.input);
                case 'Discard':
                    var msg = A2(
                        _elm_lang$core$Json_Encode$encode,
                        0,
                        _gurgl$julius_caesar$ServerModel$jsonEncCardAction(
                            A2(_gurgl$julius_caesar$ServerModel$CardAction, _p16._0, _gurgl$julius_caesar$ServerModel$CardActionDiscard)));
                    return A2(_elm_lang$websocket$WebSocket$send, _gurgl$julius_caesar$Update$echoServer, msg);
                default:
                    return _elm_lang$core$Platform_Cmd$none;
            }
        }();
        return {ctor: '_Tuple2', _0: newModel, _1: cmd2Send};
    });
```

**Comment by jvoigtlaender** [comment]
Could it be the case that you are misunderstanding JavaScript semantics? There is no possible way I see how `cmd2Send` could be evaluated before `newModel` here. After all, in this code:
```js
var newModel = A2(_gurgl$julius_caesar$Update$updateModel, msg, model);
var cmd2Send = function () {
            ...
```
*first* `newModel` gets assigned a value, and *then* `cmd2Send` gets bound to something. Whenever `cmd2Send` gets called later, the `newModel` assignment is long passed.

However, there is indeed a problem in the above JavaScript code. The problem is that in the line `var _p16 = msg;` the `msg` used is not the variable from the `function (msg, model)` call, but instead the one (yet with undefined value at that point) declared at `var msg = ...` further below in that function body. The problem is like in https://github.com/elm-lang/elm-compiler/issues/1359, though the characteristics under which it occurs here are a bit different. So it might be good to bring it down to an SSCCE, as an additional example instance for that code gen bug.

**Comment by gurgl** [comment]
Ah.. you're probebly right. Never been down with .js. Anyway.. IIRC, the problem was somehting like 

"_p16 has no field/property "ctor" on line <where the switch statement is>".

**Comment by evancz** [comment]
I'm not sure exactly what's up based on the conversation, but it is also true that local variable shadowing will be a compiler error in 0.19 so I will close. Thanks for the report!
