### ISSUE TITLE
Compiler doesn't catch statement causing runtime error

### ISSUE THREAD

**Issue by lohmander** [elm-lang/elm-compiler#1429]
Running the following code will pass through the compiler without problems, but will cause a runtime error `Cannot read property 'ctor' of undefined`.

http://www.elmfiddle.io/view/ciq29w07l000nu0tvawnrtesu

Chrome 51 on OSX
elm-make 0.17 (Elm Platform 0.17.0)

```elm
import Html exposing (text)


type alias Model =
  { something : Maybe Bool }

  
update : Model -> Model
update model =
  { model | something = Just True }


main =
  let
    m =
      update m
  in
    case m.something of
      Just b ->
        text (toString b)
        
      Nothing ->
        text "Nothing here"
```

**Comment by jvoigtlaender** [comment]
@evancz, maybe mention in the @process-bot text, or in some of the texts it is linking to, that there are certain issues open in this repository that people should look at to find out whether their's is a duplicate.

Specifically, it would make sense to draw new issue openers' attention to:
* each issue marked as "meta"
* #873 (of which the here newly opened issue is the xth duplicate)
* #1214 

(See also @mgold's pull request https://github.com/elm-lang/elm-compiler/pull/1342.)

**Comment by lohmander** [comment]
Missed that one, sorry about the duplicate. Closing.
