### ISSUE TITLE
HTML helpers

### ISSUE THREAD

**Issue by ghost** [elm-lang/elm-compiler#143]
Is there any possible way to render HTML tags? For example, i need to render something like

```html
<div id="header">
    <span class="title">Title</span>
    <div id="block">
        <input type="text"/>
    </div>
</div>
```

There is a helper for input textfields, but what about other tags? I've found addTag() method in javascript core, but is there any similar method in Elm?

**Comment by evancz** [comment]
Take a look at [elm-html](http://elm-lang.org/blog/Blazing-Fast-Html.elm), all this stuff can be done in a principled way now.
