### ISSUE TITLE
Compiler error when combining Bogdanp/elm-combine and jinjor/elm-time-travel

### ISSUE THREAD

**Issue by pinksalmon** [elm-lang/elm-compiler#1430]
Is this a compiler error? 

These libararies work fine alone, but installing them both gives a compiler error. I guess jinjor/elm-time-travel depends on Dandandan/parser which also defines `*>` and `<*` and neither parser or elm-combine define custom fixity for those operators. This issue is reproducible by having just Dandandan/parser and Bogdanp/elm-combine installed.  

ELM VERSION:

 "elm-version": "0.17.0 <= v < 0.18.0"

DEPENDENCIES:

"Bogdanp/elm-combine": "2.2.1 <= v < 3.0.0"
"jinjor/elm-time-travel": "1.0.10 <= v < 2.0.0",

ERROR REPORT:

[
{
"tag": "TYPE MISMATCH",
"overview": "The type annotation for (<) does not match its definition.",
"subregion": null,
"details": "The type annotation is saying:\n\n Parser a -> Parser b -> Parser a\n\nBut I am inferring that the definition has this type:\n\n Parser (a -> b) -> Parser a -> Parser (c -> b)\n\nHint: A type annotation is too generic. You can probably just switch to the type\nI inferred. These issues can be subtle though, so read more about it.\nhttps://github.com/elm-lang/elm-compiler/blob/0.17.0/hints/type-annotations.md",
"region": {
"start": {
"line": 51,
"column": 8
},
"end": {
"line": 51,
"column": 44
}
},
"type": "error",
"file": "elm-stuff\/packages\/Bogdanp\/elm-combine\/2.2.1\/src\/Combine\/Infix.elm"
},
{
"tag": "TYPE MISMATCH",
"overview": "The type annotation for (>) does not match its definition.",
"subregion": null,
"details": "The type annotation is saying:\n\n Parser a -> Parser b -> Parser b\n\nBut I am inferring that the definition has this type:\n\n Parser (a -> b) -> Parser a -> Parser (c -> c)\n\nHint: A type annotation is too generic. You can probably just switch to the type\nI inferred. These issues can be subtle though, so read more about it.\nhttps://github.com/elm-lang/elm-compiler/blob/0.17.0/hints/type-annotations.md",
"region": {
"start": {
"line": 63,
"column": 8
},
"end": {
"line": 63,
"column": 44
}
},
"type": "error",
"file": "elm-stuff\/packages\/Bogdanp\/elm-combine\/2.2.1\/src\/Combine\/Infix.elm"
}
]

**Comment by jvoigtlaender** [comment]
In all likelihood the overall cause is this:
> Right now the fixity of all infix operators used in the code you compile is globally known.

See https://github.com/elm-lang/elm-compiler/issues/1096.

In the concrete case I'm pretty sure what happens is that the fixity declaration for `` `map` `` in `Dandandan/parser` is affecting the implementations of `(<*)` and `(*>)` in `Bogdanp/elm-combine`.

**Comment by jvoigtlaender** [comment]
Lesson: Ask @Bogdanp to not use `map` in inline form there.

**Comment by jvoigtlaender** [comment]
Or, of course: Ask @Dandandan to not define a non-standard fixity for `map`.

**Comment by pinksalmon** [comment]
This has been resolved
