### ISSUE TITLE
`as` patterns causing overly specific types

### ISSUE THREAD

**Issue by andrewhanschan** [elm-lang/elm-compiler#1432]
The following function
````elm
mapResult f result =
  case result of
    Ok x -> Ok (f x)
    Err e as err -> err
````
has inferred type
```elm
(a -> a) -> Result b a -> Result b a
```

However, the function
````elm
mapResult2 f result =
  case result of
    Ok x -> Ok (f x)
    Err e -> Err e
````
has inferred type
```elm
(a -> b) -> Result c a -> Result c b
```

Is this expected behavior? Should `as` patterns have implications on the inferred type in this case?

**Comment by mgold** [comment]
I don't this is a bug. `err : Result b a`, it carries with it its success type even though us humans know it's a failure. When you put that in the result of the case, it propagates to the result of the function. By contrast, `Err e -> Err e` constructs a new Result with a (possibly) different success type. Something similar happens with Maybe; this doesn't compile:

```elm
mapMaybe m =
  case m of
    Just i -> Just (toFloat i)
    n -> n
```
The `Nothing` being matched carries the type even though it doesn't carry the value. This also goes for Result; this version compiles but has the restricted type:

```elm
mapResult f result =
  case result of
    Ok x -> Ok (f x)
    err -> err
```

**Comment by andrewhanschan** [comment]
Thanks for the explanation and your better example. I see now that it doesn't have to do with `as` patterns.
