### ISSUE TITLE
Compiler generates broken code by declaring variables out of order.

### ISSUE THREAD

**Issue by z5h** [elm-lang/elm-compiler#1433]
I have native modules in my app.
When I compile, the output contains the line

```Elm.Native.StartSeed = {};```

ahead of

```var Elm = {};```

which inevitably leads to 

> Uncaught TypeError: Cannot read property 'Native' of undefined

Using Elm 0.17.1, any browser.

**Comment by z5h** [comment]
**Update**: although there were no problems preventing compilation, I decided to use ```--warn``` and clean up any outstanding issues. They consisted of some unused imports as well as some values that had no type annotations.

After I corrected these warnings, the compiled output is fine!

**Comment by mgold** [comment]
Huh. Would it be possible to get this down to a [http://sscce.org/](SSCCE)? At this point all we have is, 
"if something is weird with unused imports, compilation breaks".

**Comment by z5h** [comment]
I'll try to create an sscce when I have time, probably later this week. The mix was: native modules, unused imports, missing type annotations.

**Comment by evancz** [comment]
Open an new issue if you make an SSCCE. No 0.17 compiler should be generating code like you shared, so I suspect the issue is that your PATH had multiple compilers and the wrong one was being invoked.
