### ISSUE TITLE
Using deltas in float range construction?

### ISSUE THREAD

**Issue by arpad-m** [elm-lang/elm-compiler#1434]
Float numbers sometimes are not perfect. For example, you'll get (using elm repl in this case):

```
> 4.4-1
3.4000000000000004 : Float
```

This is probably due to how floats are represented as IEEE numbers, and not at all the fault of elm, or javascript. But this behaviour creates bugs with ranges:

```
> [2.4..5.4]
[1.4000000000000004,2.4000000000000004,3.4000000000000004,4.4,5.4] : List Float
```
Note the 1.4 here, it doesn't belong here at all.

From looking at the compiled output, I see that the range function is like:

```
function range(lo, hi)
{
	var list = Nil;
	if (lo <= hi)
	{
		do
		{
			list = Cons(hi, list);
		}
		while (hi-- > lo);
	}
	return list;
}
```

probably this bug would be fixed if there was a delta comparison instead of direct > in the loop.

**Comment by mgold** [comment]
Related to #1165

**Comment by evancz** [comment]
No more `[1..6]` in 0.18, only `List.range : Int -> Int -> List Int`, so this is a problem for library authors now.
