### ISSUE TITLE
Error message concerning JSON

### ISSUE THREAD

**Issue by Masaki42** [elm-lang/elm-compiler#1435]
Hello, if you have a mistake in the elm-package.json Elm throws an error:

```
ERROR in ./src/Main.elm
Module build failed: Error: Compiler process exited with error Compilation failed
I cannot parse the JSON. Maybe a comma is missing? Or there is an extra one?
It could also be because of mismatched brackets or quotes.

You can also check out the following example to see what it should look like:
<https://raw.githubusercontent.com/elm-lang/html/master/elm-package.json>
```

It looks like I have an error somewhere in my app, e.g. in JSON from server. This is really confusing.

Please make it explicit that error might be in elm-package.json.

macOS 10.11.4
elm 0.17.1

**Comment by mitchellwrosen** [comment]
Hm, did you notice this?

> You can also check out the following example to see what it should look like:
<https://raw.githubusercontent.com/elm-lang/html/master/elm-package.json>

It points you at a sample elm-package.json, which suggests that yours is malformed.

**Comment by mgold** [comment]
This would work better in the [error message catalog](https://github.com/elm-lang/error-message-catalog/issues/new).

**Comment by Masaki42** [comment]
@mitchellwrosen Yes, but I was confused by the line “ERROR in ./src/Main.elm”. I thought my problem is somewhere in the output from the back-end or with the json-decode.

**Comment by evancz** [comment]
Like @process-bot says, we need a http://sscce.org/ to make any progress on things like this. Right now, we can only guess what the issue is because we have no information except the error message.

So get it down to an http://sscce.org/ and open it in the error message catalog like @mgold suggests.
