### ISSUE TITLE
allow Uint8ClampedArray to cross ports

### ISSUE THREAD

**Issue by maxf** [elm-lang/elm-compiler#1436]
Some JS functions return special arrays, for instance [`getImageData()`](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/getImageData) returns an object containing a [`Uint8ClampedArray`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8ClampedArray), which stores an image's pixel values.

When passing an `Uint8ClampedArray` through a port, it never makes it across. It should instead be passed as a `List Int`.

There is a workaround: converting to a normal array

```
var realArray = Array.prototype.slice.call(uint8array);
app.ports.receiveImage.send(realArray);

```

but it would be nice not to have to use it.

**Comment by evancz** [comment]
Tracking in #1687 so we can get a bigger picture view of what people want from this.
