### ISSUE TITLE
Optimize bitwise functions

### ISSUE THREAD

**Issue by mgold** [elm-lang/elm-compiler#1438]
Evan, we discussed this in person tonight, but I'm filing this issue to capture the idea. Namely, the compiler should optimize all functions in `Bitwise`, and `Basics.rem`, the same way it does for arithmetic.

Going by hand-optimized JS, this is good for a ~20% speedup in the 32-bit variant of PCG, and makes it noticeably faster than core/Random. (That's according to the best numbers I have at the moment; we've going to confirm this over the next few weeks.)

I fully expect this to sit for awhile; we'll use the third party lib for elm-test, and it will be battle-tested before it goes into core.

**Comment by Skinney** [comment]
I just wanted to numbers from my rewrite of Elm Arrays in Elm that shows the improvements of inlining bitwise operations:

Before inline:
```
Testing Large Array (10.000 elements)
Set x 1,256,978 ops/sec ±2.36% (59 runs sampled)
Push x 1,249,187 ops/sec ±2.13% (59 runs sampled)
Get x 3,078,710 ops/sec ±0.76% (56 runs sampled)
```

After inline:
```
Testing Large Array (10.000 elements)
Set x 1,531,744 ops/sec ±2.24% (58 runs sampled)
Push x 1,351,414 ops/sec ±2.31% (57 runs sampled)
Get x 5,004,991 ops/sec ±1.32% (58 runs sampled)
```
