### ISSUE TITLE
Undefined when updating nested records

### ISSUE THREAD

**Issue by sgillis** [elm-lang/elm-compiler#1443]
I got a runtime error in an Elm project I was working on where a value in my model was `undefined`.

I managed to create an SSCCE (at least I hope it is minimal, I'm not 100% sure). What is going wrong is that I can write `foo = { foo | bar = s }` in the update function. I guess this is some kind of self-referential definition. But I can then write `{ model | foo = foo }`, which should not compile.

```
module Main exposing (..)

import Html exposing (Html, div, text, input)
import Html.App
import Html.Events exposing (onInput)


type alias Model =
    { foo : { bar : String } }


init : ( Model, Cmd Msg )
init =
    ( { foo = { bar = "" } }
    , Cmd.none
    )


type Msg
    = Set String


update : Msg -> Model -> ( Model, Cmd Msg )
update msg model =
    case msg of
        Set s ->
            let
                foo =
                    { foo | bar = s }
            in
                ( { model | foo = foo }, Cmd.none )


view : Model -> Html Msg
view model =
    div []
        [ text <| model.foo.bar
        , input [ onInput Set ] []
        ]


main : Program Never
main =
    Html.App.program
        { init = init
        , update = update
        , view = view
        , subscriptions = \_ -> Sub.none
        }
```

This is tested with Elm 0.17.1 on OSX 10.11.5 (15F34) running Chrome 51.0.2704.103 (64-bit).

**Comment by jvoigtlaender** [comment]
Have you read what was inside the issue template before you overwrote it with your own text?

Specifically this:
> - If you're getting a runtime error, make sure you don't have any recursively defined values (see #873).

What you encountered is exactly an instance of #873. I don't think it makes sense to keep this additional issue here open.
