### ISSUE TITLE
Issue in port types

### ISSUE THREAD

**Issue by OvermindDL1** [elm-lang/elm-compiler#1445]
Copy/pasted from a post, seems possibly like a bug:

Two questions about ports.

1)  Why is Dict not supported?  I have a dictionary of mixed string/integers keys and a concrete record-stable from JSON passed in via a port, everything else decomposes fine into a type except for it.

2)  And this is my big question that I am having trouble working around without great verbosity.  I have these types:
```elm
type alias PresenceMeta metaUserType =
    { metaUserType
        | phx_ref : String
    }

type alias RoomSyncMetas =
    { loc : String
    , online_at : String
    }

type alias Testeringa =
    PresenceMeta RoomSyncMetas

```

And a port like:
```elm
port testering : (Testeringa -> msg) -> Sub msg
```
And it generates this error:
```elm
Port `testering` is trying to communicate an unsupported type.

173| port testering : (Testeringa -> msg) -> Sub msg
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
The specific unsupported type is the following extended record:

    { phx_ref : String, loc : String, online_at : String }

The types of values that can flow through in and out of Elm include:

    Ints, Floats, Bools, Strings, Maybes, Lists, Arrays, Tuples, Json.Values,
    and concrete records.
```

So it says that `{ phx_ref : String, loc : String, online_at : String }` is not a supported type, which seems... odd.  So I change the Testeringa type to:
```elm
type alias Testeringa =
    { phx_ref : String
    , loc : String
    , online_at : String
    }
```
And no other changes, and then it compiles fine.

My initial reaction to this is wtf...?  What did I break?!  If an extended record cannot be used here then what other way could I use beside rewriting huge structures each time (this is but a small sampling of the overall size of the actual structures).

Elm 0.17.1, Windows/Debian

**Comment by evancz** [comment]
Can you reopen this as separate issues that are (1) more focused and (2) have better titles? Not sure what's going on here.

**Comment by evancz** [comment]
Also, possibly worthwhile and relevant to read https://twitter.com/czaplic/status/750456301306585088 about when it makes sense to use record extension (not in modeling data!)

**Comment by OvermindDL1** [comment]
I can, #2 was the big one (#1 already exists in other Issues it seems), and its issue is not for function calls or modeling data but rather modeling data that is coming in through a port that is entirely user controlled when the port is not user controlled.
