### ISSUE TITLE
No helpful error message when erroneously using lower case boolean litteral

### ISSUE THREAD

**Issue by redalastor** [elm-lang/elm-compiler#1446]
I type the following erroneous code:

    if true then 1 else 2

The compiler suggests that maybe I meant List.take, since it's an easy mistake to make coming from Javascript where boolean litterals are lower case, maybe the compiler could catch it and correctly suggest I should have used True instead of true.

**Comment by jvoigtlaender** [comment]
Please close this issue here and instead open it at https://github.com/elm-lang/error-message-catalog/issues.

Because that's exactly what that other repository is meant for.

https://github.com/elm-lang/error-message-catalog/blob/master/README.md

**Comment by redalastor** [comment]
Wasn't aware. Closed.

**Comment by jvoigtlaender** [comment]
> Wasn't aware.

@redalastor, may I humbly suggest then that next time you read the GitHub issue template more carefully? That's the text that populated the textbox when you opened the new issue, and that you then overwrote with your own text. It contained this exact item:
> - If you found an unhelpful error message, report it at https://github.com/elm-lang/error-message-catalog/issues

**Comment by evancz** [comment]
@jvoigtlaender, be more chill! I suspected that the GitHub templates wouldn't work in practice, and *that* is what we are observing here. Makes more sense to try to improve how we do things than blame people who go through a process that doesn't do what it is supposed to.

**Comment by jvoigtlaender** [comment]
Fair enough. Ultimately, I'm wondering whether *any* process is going to help much. Maybe in the end it does need *people* to go through issues and triage. That brings its own problems, of course. Who are these people and what are their responsibilities and how much trust is awarded them? (And what motivates them to do that tedious work?)

**Comment by evancz** [comment]
That's possible. I can think of things GitHub could do to help, but yeah, there is definitely a learning process folks have to go through to become great writers of issues.

I have been pretty happy with the "Meta issue" approach, where I just let things pile up for a while and then come through and clean house. The meta issues turn 30 seemingly unrelated things into a few pretty focused projects. I find that doing it all at once takes maybe 1 day every few months, and you can be in the "mindset" for it so it can feel pretty fun actually.
