### ISSUE TITLE
Uncaught Error: The notify function has been called synchronously

### ISSUE THREAD

**Issue by romgrk** [elm-lang/elm-compiler#1455]
Hello,

I've been told by this error message to report this. 
```
Uncaught Error: The notify function has been called synchronously!
This can lead to frames being dropped.
Definitely report this to <https://github.com/elm-lang/Elm/issues>
```

This is from the link on the Elm home page, http://ravichugh.github.io/sketch-n-sketch/releases/v0.5.1/
Pops up when switching to "Basic Slides".

**Comment by romgrk** [comment]
OS: ArchLinux
Browser: Version 53.0.2785.34 beta (64-bit)

**Comment by evancz** [comment]
Thanks for the report! That's from an older version of Elm, and it can sometimes mean the library author is doing something particularly tricky. So I'd say it makes more sense to report to https://github.com/ravichugh/sketch-n-sketch where @ravichugh will know if he's doing any native stuff or custom event stuff that may be causing this.
