### ISSUE TITLE
Compiler stuck, 100% cpu and rising memory usage

### ISSUE THREAD

**Issue by tcoopman** [elm-lang/elm-compiler#1456]
I was writing some code and the compiler (elm 0.17.1 on Linux) got stuck (100% cpu and rising memory usage).

This is the code (the code is work in progress)

```elm
aStar : Position -> Position -> Maze -> A -> List Position
aStar start goal maze a =
    let
        openList = Set.toList a.openSet
        lowestFScoreInOpenSet =
            let
                score ( fScore, bestPos ) position =
                    case (Dict.get position a.fScore) of
                        Nothing ->
                            ( fScore, bestPos )

                        Just a ->
                            if a < fScore then
                                ( a, position )
                            else
                                ( fScore, bestPos )
                head = List.head openList
            in
                List.foldr score ( 99999, head) (Maybe.withDefault [] (List.tail openList))

    in
        case openList of
            [] ->
                a.result

            _ -> a.result
          
```
replacing the `List.foldr` with `(0, 0)` and the code compiles fine.
There is an error in the code `score` receives a maybe as second argument and I don't handle this here. If I handle the maybe, the compiler works fine.

I'm not sure if this is the same issue as #1231 or maybe #1362?

**Comment by jvoigtlaender** [comment]
It's the same issue as https://github.com/elm-lang/elm-compiler/issues/1240, and as such tracked in https://github.com/elm-lang/elm-compiler/issues/1231.

**Comment by jvoigtlaender** [comment]
@tcoopman, same question as I just posed in https://github.com/elm-lang/elm-compiler/issues/1457#issuecomment-238148313:

If the issue template had contained an additional item of the form:
* Compiler hangs? https://github.com/elm-lang/elm-compiler/issues/1240

would that have been enough for you to realize yours is a duplicate issue and you do not need to open it as a new one?

**Comment by tcoopman** [comment]
@jvoigtlaender <https://github.com/jvoigtlaender>, hard to say. It's not
always obvious to me why an item is a duplicate issue. So I just wasn't
sure. Maybe add some more information to the template on what to do if you
think it is the same issue, but you aren't sure?

**Comment by jvoigtlaender** [comment]
> Maybe add some more information to the template on what to do if you think it is the same issue, but you aren't sure?

Well, I guess in that case what to do is really to open the issue and voice your own suspicion of it possibly being a duplicate. Which you did in a perfectly reasonable way.
