### ISSUE TITLE
Cannot pattern match on empty {}

### ISSUE THREAD

**Issue by wyager** [elm-lang/elm-compiler#1459]
`{}` is both a valid type and a valid value expression. Consider the following program:

```
f : {} -> Int
f _ = 5
x = f {}
```

Additionally, elm allows pattern destructuring of structural types. `{<name1>,<name2>,...,<nameN>}` can appear in the LHS of an equation as a pattern. For example,

```
g : {a | v : b} -> Int
g {v} = 5
y = g {v = "It's-a-vee!"}
```

Given that 
- The empty structural type is both a valid type and a valid value (represented by the `{}` term)
- One can pattern match on structural types

One ought to be able to pattern match on the empty structural type. For example, the following should be a valid program:

```
f : {} -> Int
f {} = 5
x = f {}
```

However, it prompts the following error:

```
-- SYNTAX PROBLEM ------------------------------------------------------ foo.elm

I ran into something unexpected when parsing your code!

2| f {} = 5
      ^
I am looking for one of the following things:

    a lower case name
    whitespace

Detected errors in 1 module.
```

I suspect the issue is in `src/Parse/Pattern.hs`'s `record` definition, but changing `commaSep1` to `commaSep` doesn't seem to do the trick.

**Comment by evancz** [comment]
This is permitted in my development build.
