### ISSUE TITLE
Proposal: Newline as optional separator for lists / records

### ISSUE THREAD

**Issue by kspeakman** [elm-lang/elm-compiler#1460]
This is similar to #978 without going quite as far.

The compiler should allow newlines to serve as the separator in lists and records.

Example:

```
type alias Model = 
  { viewMode     : ViewMode
    docs         : List Doc
    currentDocId : Maybe Identifier
    currentDoc   : Doc
  }
```

The newlines divide the visual structure of this code for the programmer, not the commas. This is statement of fact... test it by trying to use the commas without newlines. It's a jumble past a certain size. Example:

`type alias Model =  { viewMode: ViewMode, docs: List Doc, currentDocId: Maybe Identifier, currentDoc: Doc }`

(Wrapping occurs above, not an intentional newline.)

Adding a comma in cases where a newline is also used may be your preference, but it is superfluous to the more important concept of organizing the code with newlines.

```
type alias Model = 
  { viewMode     : ViewMode
  , docs         : List Doc
  , currentDocId : Maybe Identifier
  , currentDoc   : Doc
  }
```

Being an optional feature would allow those who like the explicit separators to continue to use them, and the change would be backwards compatible with existing code.

My experience with this issue: I've used both methods in F#. Initially, I only used the default separator (semi-colon) for lists and records in F#. Later, I started using newlines-as-separators for those structures where they were multi-line. My experience is that the latter makes the code less fiddly to change and more readable for fresh eyes.

**Comment by evancz** [comment]
This has been discussed before. I don't want to track discussions like this as issues, but I think it'd be good on elm-discuss or on the Slack channel. There are benefits and downsides to something like this, but for now, I am trying to focus on making currently-impossible-things possible rather than making possible things slightly nicer.

**Comment by kspeakman** [comment]
Round-filed. Gotcha. Thanks for the response.
