### ISSUE TITLE
Runtime error when comparing nested Html of different depths 

### ISSUE THREAD

**Issue by lpil** [elm-lang/elm-compiler#1465]
Hello!

Today while trying to do some testing I encounted a runtime error. Here's a recreation.

```elm
> import Html exposing (..)
> (div [] []) == (div [] [])
-- True : Bool

> (div [] [ text "Hi" ]) == (div [] [ text "Hello" ])
-- False : Bool

> (div [] [ text "Hi" ]) == (div [] [])
-- TypeError: Cannot read property 'type' of undefined
```

Elm version 0.17.0, installed via the `elm` package on npm.

Debian Jessie Linux OS.

Running Elm in node v4.1.1 via the REPL.

**Comment by jvoigtlaender** [comment]
I think crucial information here is which version of `core` you are using (and maybe also which version of `html`), because the native code doing equality checks (implementing `==`) was changed somewhere around version `4.0.3` of `core`. Look in `elm-stuff/exact-dependencies.json`.

**Comment by jvoigtlaender** [comment]
Also, it's most likely an issue for either the `core` or the `html` repository.

**Comment by lpil** [comment]
Hi

Ah, thank you. I didn't realise there was another repo for Html and core.

Here are the entries from my `elm-stuff/exact-dependencies.json`.
```
    "elm-lang/html": "1.1.0",
    "elm-lang/core": "4.0.4"
```

Should I open an issue elsewhere?

**Comment by jvoigtlaender** [comment]
https://github.com/elm-lang/core seems the best bet to me.

**Comment by lpil** [comment]
Thank you.
