### ISSUE TITLE
Instance Arguments

### ISSUE THREAD

**Issue by vagoff** [elm-lang/elm-compiler#1467]
I heard complaints that Elm is somewhat lack of expressiveness due to absence of type classes. I also heard that implementation of type classes may be considered in some future.

So my suggestion is: why not implement better machinery -- instance arguments -- from very beginning? I think they are more simple and flexible.

Instance argument is argument inserted automatically by compiler. Value for inserted argument is taken from lexical scope of call site. Value is searched by type. If no such value exists of many such values exist compiler throws an error.

Example:

    type alias Ord a = { cmp : a -> a -> Int }

    empty : {{Ord a}} -> Map a b
    empty {{ord}} = ...

    lookup : {{Ord a}} -> Map a b -> a -> Maybe b
    lookup {{ord}} map key = ...

    insert : {{Ord a}} -> Map a b -> a -> b -> Map a b
    insert {{ord}} map key value = ...

    example : Maybe Int
    example = lookup (insert empty 1 2) 1

    example_ord : Ord Int
    example_ord = { cmp = \ a b -> if a < b then -1 else (if a > b then +1 else 0) }

http://agda.readthedocs.io/en/latest/language/instance-arguments.html
http://wiki.portal.chalmers.se/agda/pmwiki.php?n=ReferenceManual.InstanceArguments
https://people.cs.kuleuven.be/~dominique.devriese/agda-instance-arguments/

**Comment by vagoff** [comment]
Note that instance arguments may be passed through transparently and implicitly:

    try_lookup : {{Ord a}} -> Map a b -> a -> Maybe b
    try_lookup {{ord}} m k = ...

    lookup : {{Ord a}} -> Map a b -> a -> b
    lookup m k =
        case try_lookup m k of -- <-- ord arg passed through automatically
            Just v -> v
            Nothing -> Debug.crash "Lookup failed!"

**Comment by evancz** [comment]
I'm familiar with this approach. It is mentioned in #1039 as a possibility, but there are higher priority projects. If I am forced to weigh "expressiveness" of a type-system vs of the language to easily create nice web apps, I'm gonna focus on the latter. In any case, this topic has been discussed quite thoroughly, so I don't think it makes sense to track this in multiple issues.
