### ISSUE TITLE
Cases in lambda [feature request]

### ISSUE THREAD

**Issue by vagoff** [elm-lang/elm-compiler#1468]
What about such feature:

given:

    listFn : List String -> String
    listFn list =
      case list of
        [] -> "This list is empty!"
        [ _ ] -> "This list has one element"
        [ a, b ] -> "This list has two elements: " ++ a ++ " and " ++ b
        a::b::_ -> "This list has several elements. The first 2 are: " ++ a ++ " and " ++ b

instead of repeating argument name, just use cases right in lambda:

    listFn : List String -> String
    listFn = \
        [] -> "This list is empty!"
        [ _ ] -> "This list has one element"
        [ a, b ] -> "This list has two elements: " ++ a ++ " and " ++ b
        a::b::_ -> "This list has several elements. The first 2 are: " ++ a ++ " and " ++ b

pretty convenient and consistent syntax, no?

     f a = g (\ Just x -> x + 1 ; _ -> 0 ) a in z g a

**Comment by evancz** [comment]
I am familiar with this syntax from OCaml and Haskell. I prefer not to log feature requests in issues. I can keep track of these things myself.

More generally though, the focus right now is not on growing the syntax of Elm. (We're actually dropping stuff more often.) If something *can* be expressed in Elm already, I'm not hugely interested in providing alternate ways to express it. In this case, I think we would be adding syntax to make things harder to read. The `Maybe` example is a great example of that IMO.
