### ISSUE TITLE
ReferenceError: _elm_lang$virtual_dom$VirtualDom$text is not defined

### ISSUE THREAD

**Issue by joeandaverde** [elm-lang/elm-compiler#1471]
Elm Package: 0.17.0
Elm Make: 0.17.0

```
ReferenceError: _elm_lang$virtual_dom$VirtualDom$text is not defined
```

This explodes upon script load without calling into a module.

Looking at the compiler generated source I did not see VirtualDom defined before use.

It seems this error was caused by having multiple versions of `virtual-dom` in my elm-stuff directory.

![image](https://cloud.githubusercontent.com/assets/696255/18031249/7cf55a2e-6c9c-11e6-9f7f-009767081a23.png)

Turns out around the time I got this error `virtual-dom` was released with a newer version between subsequent builds which caused the seemingly random error.

**Comment by mxgrn** [comment]
I got this after upgrading a couple of Elm packages. The solution was to delete the `elm-stuff` folder, then run `elm package install` to install everything from scratch.

**Comment by jvoigtlaender** [comment]
Likely solved by https://github.com/elm-lang/elm-make/commit/46ec85c0e8dc5f3427bde6e4f212b4f367ecbd07 (not yet released)?

**Comment by evancz** [comment]
Can you reopen with an http://sscce.org/ ? Seems impossible to resolve with this amount of information, but I suspect @jvoigtlaender is right that the `elm-make` fix will solve it.
