### ISSUE TITLE
Let clause can refer to itself, leading to undefined variable

### ISSUE THREAD

**Issue by snaily** [elm-lang/elm-compiler#1474]
In the right hand side (body) of a let clause, the left-hand side (name) is already defined (and starts shadowing other names). Using it is legal to the compiler, but at runtime the name is an "internal structure" or undefined.

I think this falls under codegen issues, though I feel like it shouldn't compile. It's similar to #1223.

Here is a SSCCE:
```
module Main exposing (..)

import Debug
import Html exposing (button, text)
import Html.Attributes exposing (value)
import Html.Events exposing (onClick)
import Html.App exposing (..)


type Msg
    = FooMsg


main =
    beginnerProgram { model = model, view = (\_ -> button [ onClick FooMsg ] [ text "This will throw an exception" ]), update = update }


type alias Model =
    -- I believe any type would give the same issue
    List Int


model : Model
model =
    let
        -- This is somehow legal to the typechecker
        dummy =
            dummy
    in
        Debug.log "uh-oh" dummy


update : Msg -> Model -> Model
update msg model =
    -- Just for the sake of doing anything
    List.reverse model
```

Elm 0.17.1, Chrome 52.0.2743.116 (64-bit) on OS X.

**Comment by mgold** [comment]
Yet another incarnation of #873. Please read the pre-populated issue text.

**Comment by snaily** [comment]
Oh, great! I thought it was a little too apparent as a bug, but that particular part of the pre-populated text didn't catch my eye. The title of #873 is pretty good, though, perhaps it could be incorporated into the pre-populated text?
