### ISSUE TITLE
project names including `.` produce invalid generated code identifiers

### ISSUE THREAD

**Issue by michaelbjames** [elm-lang/elm-compiler#1475]
Encountered while writing a new version of my website. I have the code in github under michaelbjames.com.git, clone to `michaelbjames.com/`

main.elm:

```
import Html exposing (text)

main =
  text "Hello, World!"
```

Will generate in the following invalid JS:
`var _michaelbjames$michaelbjames.com$Main$main = {
    main: _elm_lang$html$Html$text('Hello, World!')
};`

That pesky dot is what does it in. The elm code should work (it's taken from the most basic examples).

The fix is to better sanitize variable names before they're generated, so they don't conflict with the JS identifier spec.

Version information:
elm-compiler: master@4f5db922692099010a1cc5c987ce3cc536cf0140

Related task: https://github.com/elm-lang/elm-compiler/issues/1377

**Comment by evancz** [comment]
In the latest version of the compiler, I reject project names with dots, so it never gets to this point.

Thanks for the report!
