### ISSUE TITLE
[0.17] Cannot find variable ..- when creating negative ranges

### ISSUE THREAD

**Issue by hendore** [elm-lang/elm-compiler#1477]
When creating a list with a range of numbers I came across an issue if the high number is negative and there isn't a space between range operator and high number.

Possibly related to #1261 

```elm
namingError =
  [-10..-5]
```

```
-- NAMING ERROR ---------------------------------------------- repl-temp-000.elm
Cannot find variable `..-`
3|   [-10..-5]
      ^^^^^^^
Maybe you want one of the following?
    -
    Basics.-
```

Possible work arounds for now include, adding a space after '..' or wrapping the high number in parens

```
> [-10..(-5)]
[-10,-9,-8,-7,-6,-5] : List number
> [-10.. -5]
[-10,-9,-8,-7,-6,-5] : List number
```

**Comment by jvoigtlaender** [comment]
The `[x..y]` syntax is disappearing, see [this comment](https://github.com/elm-lang/elm-compiler/issues/1434#issuecomment-252985577), so this issue here can be closed as well.
