### ISSUE TITLE
Proposal: Allow leading or trailing comma in multiline exposing, list and records

### ISSUE THREAD

**Issue by sporto** [elm-lang/elm-compiler#1478]
Currently the recommended format for multiline `exposing`, list and records is:

```
[ one
, two
, three
]
```

I stumble across two issues with this format all the time:

## 1 Sorting

Sorting in unnecessarily difficult, I cannot just highlight the lines and sort because the first item is different than the other.

## 2 Commit noise

Adding an item at the beginning is cumbersome. I need to change both the first and the second line, creating unnecesary git commit noise.

## Format fix

These issues can be fixed by adopting an alternative formatting for multiline list, records, etc:

```
[
  one,
  two,
  three,
]
```

or 

```
[
, one
, two
, three
]
```

Either way deals with these issues.

However this format cannot be used now as the compiler doesn't allow a leading or a trailing comma.

So, please _consider allowing either a leading or trailing comma_.

**Comment by evancz** [comment]
This has been discussed quite extensively in the past. I don't want to track it on github though.

Features that are "it can be done, but I'd rather do it with a different syntax" are lower priority than "it cannot be done". This is also a change that can be added without breaking any old code, so it does not really matter when this gets added. So this is not urgent in my opinion, and these kinds of considerations will be revisited when it is time to make `elm-format` a core tool.

**Comment by sporto** [comment]
Yes, this has been discussed in here and the list. The issue gets dismissed each time as not important right now, I get that. 

But I don't get why close the issue. Closing the issue gives the impression that we don't want this at all and the current way is fine. How do you track this otherwise?

**Comment by evancz** [comment]
I know I do not use GitHub like other projects, but I prefer not to track feature requests for the language in issues. It clutters things up and makes it harder to find actual bugs.

I don't see what there is to track. Anyone can reconstruct the design of this syntax change with 2 minutes of thought. You allow extra commas. It's not like we need a fancy design doc. If you are worried it will be forgotten, I can promise you that folks will be bringing it up for decades if I do not add it, so I don't see how that can happen.
