### ISSUE TITLE
Dates are not comparable

### ISSUE THREAD

**Issue by rigdern** [elm-lang/elm-compiler#1482]
I tried sorting a list of Dates but got an error due to them not being comparable. Here's some code that produces this error:

```elm
import Html exposing (text)
import Date

dateList : List Date.Date
dateList =
  []

sortedDateList =
  List.sort dateList

main =
  text "Hello"
```

I expected this to compile but instead I got this compiler error:

```
Detected errors in 1 module.


-- TYPE MISMATCH ---------------------------------------------------------------

The argument to function `sort` is causing a mismatch.

10|   List.sort dateList
                ^^^^^^^^
Function `sort` is expecting the argument to be:

    List comparable

But it is:

    List Date.Date

Hint: Only ints, floats, chars, strings, lists, and tuples are comparable.
```

I'm using elm 0.17.1.

**Comment by JoeyEremondi** [comment]
You can use [this comparison function](http://package.elm-lang.org/packages/justinmimbs/elm-date-extra/2.0.0/Date-Extra#compare) with [this sorting function](http://package.elm-lang.org/packages/elm-lang/core/4.0.5/List#sortWith).

**Comment by evancz** [comment]
Added to meta issue #1008, thanks for the report!
