### ISSUE TITLE
Syntax Suggestion: record property shorthand

### ISSUE THREAD

**Issue by noraesae** [elm-lang/elm-compiler#1483]
Hiya,

First of all, if GH Issues is not a proper place for a syntax suggestion, please let me know. I will move the post.

I would like to suggest adopting a shorthand syntax for record property replacement. When we write `update`, we usually meet the code like below:

```elm
{ model | foo = foo, bar = bar }
```

If a field's name is quite long, it easily becomes verbose.

```elm
{ model | shouldDoSomething = shouldDoSomething
        , shouldDoAnother = shouldDoAnother
        }
```

Actually, JS has the same problem and resolved it in ES2015 with [object literal shorthand](http://eslint.org/docs/rules/object-shorthand). I think it can resolve the problem in the similar way.

```elm
{ model | foo, bar }
{ model | shouldDoSomething, shouldDoAnother }
```

Is there any possibility this is implemented in Elm? I would also be really happy if I can participate in implementing this.

Cheers!

**Comment by jvoigtlaender** [comment]
The issue tracker is not for this.

**Comment by noraesae** [comment]
Thank you for your direction. Where should it go?

**Comment by jvoigtlaender** [comment]
The mailing list, I think. But first check previous related discussions (the list has an archive). As you can probably imagine, special syntax for record update has come up as a topic before. (In fact, you would probably find several such discussions as GH issues as well, usually ending with being closed as "does not belong here on the issue tracker".)

**Comment by jvoigtlaender** [comment]
http://elm-lang.org/community

**Comment by noraesae** [comment]
I'm sorry that I didn't notice it. I sent a draft to the mailing list after I tried to look for a similar issue having been closed already. It will be published when a group manager approves it.

Thanks!
