### ISSUE TITLE
Uncaught SyntaxError: Unexpected token .

### ISSUE THREAD

**Issue by n1k0** [elm-lang/elm-compiler#1485]
While messing around trying to figure out how to reuse message types across modules, I've introduced an erroneous use of a dot notation which compiled fine but generated a *SyntaxError* once executed in the browser.

Sample minimal code:

```erlang
module Bug exposing (..)


type Msg
    = NoOp
    | Foo.Bar


type alias Model =
    {}


update : Msg -> Model -> ( Model, Cmd Msg )
update msg model =
    case msg of
        NoOp ->
            ( model, Cmd.none )

        Foo.Bar ->
            ( model, Cmd.none )
```

Compiles just fine while it probably shouldn't. Generated js breaks with a SyntaxError:

![](http://i.imgur.com/bCaKmb0.png)

![](http://i.imgur.com/7stVO74.png)

I'm using Elm v0.17 installed from npm on Ubuntu 16.04 64.

**Comment by jvoigtlaender** [comment]
This is a known problem. As the issue template says, please check the "meta" issues before opening new ones. In this case, #1374.

**Comment by n1k0** [comment]
Sorry, I swear I searched.
