### ISSUE TITLE
Assigning to type constructors gives weird behavior

### ISSUE THREAD

**Issue by folkertdev** [elm-lang/elm-compiler#1486]
Hi, 

When walking through a problem with someone (very inexperienced), I noticed that assigning 
to a type constructor (when there is only one constructor of a type) compiles: 

```elm
import Html exposing (..)

type Msg = A

A = 5 

main =
  text "Hello, World!"
```

When there are multiple type constructors, the compiler will fail complaining about an 
incomplete pattern match: 

```elm
import Html exposing (..)

type Msg = A  | B  | C
C = 6

main =
  text "Hello World!"
```
fails with 

```
-- PARTIAL PATTERN -------------------------------------------------------------

The pattern used here does not cover all possible values.

5| C = 6
   ^
You need to account for the following values:

    Temp1473684102728286.A
    Temp1473684102728286.B

Switch to a `case` expression to handle all possible patterns.
```
*Using elm-lang.org/try on linux/chrome 50*

Assigning to a constuctor that does not exist fails too. The compiler will give 
an incorrect hint in this case 

```elm
import Html exposing (..)


type Msg = A | B | C
D = 6

main =
  text "Hello World!"
```

gives 

```
-- NAMING ERROR ----------------------------------------------------------------

Cannot find pattern `D`

6| D = 6
   ^
Maybe you want one of the following?

    A
    B
    C
```
*Using elm-lang.org/try on linux/chrome 50*

Whilst no-one who understands what type constructors are would attempt such things, a novice might 
and would then run into very weird behavior.

**Comment by evancz** [comment]
Can you move this to https://github.com/elm-lang/error-message-catalog/issues in the future? It looks like someone just reported it actually!

**Comment by JoeyEremondi** [comment]
Does it belong there? The later ones are certainly poor errors, but the first one is a typechecker bug, an ill typed program that compiles...

**Comment by evancz** [comment]
New issue with better title and http://sscce.org/ if that's the case

**Comment by JoeyEremondi** [comment]
New issue here: https://github.com/elm-lang/elm-compiler/issues/1487
