### ISSUE TITLE
Constructor Pattern with no variables accepts ill-typed RHS

### ISSUE THREAD

**Issue by JoeyEremondi** [elm-lang/elm-compiler#1487]
``` elm
type MyType = A 

A = 5
```

compiles without warning.

The LHS is of type `A`, the RHS of type `number`. The same happens if you use `Nothing` in place of `5`, so the issue is not with `number` or other supertypes.

Likewise, the same error happens if you use it in a `let` expression.

More complex patterns also falsely succeed:

``` elm
type MyType = A ()

(A ()) = 5
```

The error goes away if we add any variables to `A`. So `(A x) = 5` fails with the proper error.

**Comment by folkertdev** [comment]
Thanks for creating this. Isn't the type of the left-hand side actually `MyType` (instead of `A`)? 

In addition, adding a second constructor also makes compilation fail, i.e. the following correctly fails to compile: 

```elm
type MyType = A | B

A = 5
```

**Comment by rtfeldman** [comment]
Confirming this is still a bug as of 0.18.

**Comment by evancz** [comment]
I am getting the following in the development build:

```
-- PARSE ERROR -------------------------------------------------------- temp.elm

Something went wrong while parsing a union type.

7| type MyType = A
8| 
9| A = 5
   ^
I was expecting:

  - a declaration, like `x = 5` or `type alias Model = { ... }`
  - more of that union type. Maybe you forgot some code? Or you need more
    indentation?

```

And on the more complex one, I am getting:

```
-- PARSE ERROR -------------------------------------------------------- temp.elm

Something went wrong while parsing a union type.

7| type MyType = A ()
8| 
9| (A ()) = 5
   ^
I was expecting:

  - a declaration, like `x = 5` or `type alias Model = { ... }`
  - more of that union type. Maybe you forgot some code? Or you need more
    indentation?

```

I'm not certain the root thing here where the types were not getting checked properly is working though.

**Comment by evancz** [comment]
If I do this code:

```elm
type MyType = A

foo =
  let
    A = 5
  in
  "foo"
```

I am getting this error:

```
-- TYPE MISMATCH ------------------------------------------------------ temp.elm

I cannot destructure

10|>  let
11|>    A = 5

You are defining a number of type:

    number

But then trying to destructure it as:

    Main.MyType

Hint: Only Int and Float values work as numbers.
```

So between the parser and the types, it looks like this will be caught in either context.
