### ISSUE TITLE
Links in the elm home page don't work

### ISSUE THREAD

**Issue by chrisdavies** [elm-lang/elm-compiler#1489]
Platform: Firefox on Android (moto G).

The elm home page loads and displays fine, but no links are clickable.

**Comment by jvoigtlaender** [comment]
Wrong repository to report this. See the elm-lang.org repository.

**Comment by evancz** [comment]
@chrisdavies, can you reopen this on https://github.com/elm-lang/elm-lang.org/issues with more information about your browser? What version of Firefox? What version of Android? Are there other issues like this on that particular combination?
