### ISSUE TITLE
Parsing error for expression similar to {x | y = {x.y | z = ...}}

### ISSUE THREAD

**Issue by matovitch** [elm-lang/elm-compiler#1492]
Using Elm 0.17 installed from npm on linux (ubuntu and with firefox but it shouldn't matter much)

Hello,

Being just a beginner, this is probably not idiomatic code, I was doing something like this:
```elm
{model | secret = {model.secret | password  = text}}
```
When I got the parsing error
```
I ran into something unexpected when parsing your code! 

20| Msg.Password text -> ({model | secret = {model.secret | password = text}}, Cmd.none)
                                                  ^
I am looking for one of the following things:
     "|"
     an equals sign '='
     more letters in this name
     whitespace
```
whereas if I just use
```elm
let
   {-I chose "secret" as expression name but it could be something less confusing-}
    secret = model.secret
in
    {model | secret = {secret | password  = text}}
```
Compiled just fine. This looks like a parser bug.

(Note without the let I get `Cannot find variable 'secret'` which seems fair enough)

There it is. Thanks a lot for working on this amazing language ! Keep it up !

Best Regards.

**Comment by jvoigtlaender** [comment]
This is already covered by https://github.com/elm-lang/elm-compiler/issues/1375. 

The issue here can be closed.

**Comment by matovitch** [comment]
I missed it sorry. Indeed this is exactly #537 referred to within #1375.

**Comment by jvoigtlaender** [comment]
Okay. Will you close the issue then?

**Comment by matovitch** [comment]
Yes (first time I close one, not used to github, sorry again. :S)

**Comment by jvoigtlaender** [comment]
Don't worry. All is fine. :smile:
