### ISSUE TITLE
Proposal: shorthand record names

### ISSUE THREAD

**Issue by zwhitchcox** [elm-lang/elm-compiler#1493]
Shorthand property names [like in javascript](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Object_initializer)

These are a great feature, and maybe elm can steal something from javascript for a change.

Like I see no reason for this overly-verbose syntax:

```elm
main : Program Never
main =
    Html.App.program
        { init = init
        , view = view
        , update = update
        , subscriptions = subscriptions
        }
```

**Comment by jvoigtlaender** [comment]
Looks a lot like proposal #1483, and what I said there applies here as well: This is something to discuss on the mailing list, if it hasn't already before. But it's not something to be open as a GH issue here.

**Comment by zwhitchcox** [comment]
Sorry!

**Comment by zwhitchcox** [comment]
Can you tell me how to join the mailing list?

**Comment by jvoigtlaender** [comment]
http://elm-lang.org/community
