### ISSUE TITLE
Main.elm:10517 Uncaught TypeError: Cannot read property 'languages' of undefined

### ISSUE THREAD

**Issue by matrixise** [elm-lang/elm-compiler#1494]
With this code in https://github.com/sporto/hop/blob/master/examples/full/src/Update.elm#L36-L37

```elm
                ( updatedModel, cmd ) =
                    Languages.Update.update subMessage updateModel
```

If you modify the code with 

```diff
diff --git a/examples/full/src/Update.elm b/examples/full/src/Update.elm
index e7ba9ee..c749441 100644
--- a/examples/full/src/Update.elm
+++ b/examples/full/src/Update.elm
@@ -34,7 +34,7 @@ update message model =
                     }
 
                 ( updatedModel, cmd ) =
-                    Languages.Update.update subMessage updateModel
+                    Languages.Update.update subMessage updatedModel
             in
                 ( { model | languages = updatedModel.languages }, Cmd.map LanguagesMsg cmd )
 ```

I have no warning or errors with the compiler (`elm-make`), but when I execute this code (`elm-reactor`), I have got this message:
```Uncaught TypeError: Cannot read property 'languages' of undefined```

because `updatedModel` is `undefined` in this case, because not yet defined or assigned to a value.

First time when I have an `undefined` in my code.

**Comment by jvoigtlaender** [comment]
As almost always when an undefined is reported in this repository, yet another instance of #873.

**Comment by jvoigtlaender** [comment]
And I really wonder why the issue template presented to all new issuers does not prevent these duplicates from being opened.

**Comment by matrixise** [comment]
and how to mark this issue as a duplicata of #873 ?

**Comment by jvoigtlaender** [comment]
No need to. Just closed it.

**Comment by jvoigtlaender** [comment]
"close" it, not "closed" it, I mean.
