### ISSUE TITLE
Modules containing incoming ports require Json.Decode to be imported

### ISSUE THREAD

**Issue by ccapndave** [elm-lang/elm-compiler#1496]
Using an incoming port in a `port module` without explicitly import `Json.Decode` causes a runtime error such as `_elm_lang$core$Json_Decode$succeed is not a function` (depending on what type the argument it.

For example:

```elm
port module MyModule exposing (..)

port onBlur : ({} -> msg) -> Sub msg
```

causes `_elm_lang$core$Json_Decode$succeed is not a function` at runtime.  Changing the example to:

```elm
port module MyModule exposing (..)

import Json.Decode

port onBlur : ({} -> msg) -> Sub msg
```

fixes the problem.

_Elm 0.17.1, OSX, not browser specific_

**Comment by jvoigtlaender** [comment]
This is a duplicate of https://github.com/elm-lang/core/issues/703. Evan already knows about the problem. I think one of the two open issues should be closed. Given that Evan opened the other one, and decided to it in the `core` repository, it seems this one here should be closed.

**Comment by ccapndave** [comment]
Blast!  I looked carefully for this issue before opening it, but assumed it would be in the compiler instead of core :)  Hopefully the next person will find this closed issue and know to look in core.  Thanks!
