### ISSUE TITLE
"TypeError: Cannot read property 'ctor' of undefined" in complex shadowing case

### ISSUE THREAD

**Issue by maackle** [elm-lang/elm-compiler#1497]
This seems related to #873, #1045, et al, but I'm opening a new issue because those are over a year old, it seems a lot has been fixed since then, and this seems like an unusual case. Apologies if it's a duplicate.

Here is the smallest case I found to reproduce it. It's extremely contrived, but it stems from a real-life situation I encountered.

```elm
module Bug exposing (..)

import String

f x =
  let
    r _ _ = 1
    m = Just x
    x =
      case m of
        Just _ -> String.foldl r 1 "foo"
        Nothing -> 0
  in
    x
```

Then using elm-repl 0.17.1:

```bash
> import Bug exposing (..)
> f 1
TypeError: Cannot read property 'ctor' of undefined
```

However it works fine if I simplify the function slightly in a trivial way, for instance:

```elm
f x =
  let
    r _ _ = 1
    x =
      case Just x of  -- removed `m` binding
        Just _ -> String.foldl r 1 "foo"
        Nothing -> 0
  in
    x
```

yields

```bash
> import Bug exposing (..)
> f 1
1 : number
```

There are other trivial simplifications that make it work that seem to have nothing to do with removing shadowing, such as:

```elm
f x =
  let
    r _ _ = 1
    m = Just x
    x =
      case m of
        Just _ -> 1  -- `removed nonsensical `String.foldl` call`
        Nothing -> 0
  in
    x
```

**Comment by maackle** [comment]
FYI, type annotations have no effect

```elm
f : Int -> Int
f x =
  let
    r : Char -> Int -> Int
    r _ _ = 1

    m : Maybe Int
    m = Just x

    x : Int
    x =
      case m of
        Just _ -> String.foldl r 1 "foo"
        Nothing -> 0
  in
    x
```

```bash
> f 1
TypeError: Cannot read property 'ctor' of undefined
```

**Comment by z5h** [comment]
I have a `TypeError: Cannot read property 'xxx' of undefined` error.   
I've searched my code for shadowing problems and found none.

**Comment by dustinrohde** [comment]
I'm having this same issue, in fact. No shadowing. I'll post my results
when I get home.

**Comment by jvoigtlaender** [comment]
According to the commit comment of https://github.com/elm-lang/elm-compiler/commit/8b484abfb313f2877403b168e4d7229863f20ba1, all three programs in the opening post here will be rejected by the compiler in version 0.18.

**Comment by evancz** [comment]
Yep, @jvoigtlaender is correct about that!
