### ISSUE TITLE
Intero support

### ISSUE THREAD

**Issue by AndreaCrotti** [elm-lang/elm-compiler#1498]
I'm not a massive Haskell expert but I wanted to have a look at this project with Emacs + Intero:
https://commercialhaskell.github.io/intero/

but I think it needs a stack.yaml file to work, right?
Is it fine to add one?
Thanks

**Comment by JoeyEremondi** [comment]
As in, you want to edit the Elm compiler in interro, or you want to write
Elm code in interro?

I'm not sure if all of Elm's dependencies are on Stackage, so getting a
stack.yaml going might be a fair bit of work.

**Comment by AndreaCrotti** [comment]
Really just being able to use the various nice things like jumping around, auto-completion and so on and so forth while looking at the code...

http://commercialhaskell.github.io/intero/

Ok anyway I thought that Stack was more mainstream and everything was on there, if that's not the case no problem it's not a big issue (unless there are also other advantages in having them of course).

**Comment by jvoigtlaender** [comment]
If you do want to experiment with getting Elm built via Stack (I see no reason why this would not work today, certainly not because of missing dependencies; I really don't share Joey's concern related to this), here is a start that probably just needs minor updating: https://github.com/elm-lang/elm-platform/pull/74.

**Comment by JoeyEremondi** [comment]
I'd tried about a year ago, maybe the situation has improved since then!

**Comment by jvoigtlaender** [comment]
The link I gave has a concrete `stack.yaml` file that worked 13 months ago.

**Comment by evancz** [comment]
Continue discussion on elm-discuss or the Elm slack. Maybe it'll turn into some more concrete work that can be reopened as a new issue.
