### ISSUE TITLE
Runtime error in compiler: Unable to generalize a type variable. It is not unranked.

### ISSUE THREAD

**Issue by dtcaciuc** [elm-lang/elm-compiler#1504]
Follow-up from #1502. I'm running compiled git master (`elm --version` outputs `0.18.0`)

`elm-make` produces the following error when compiling this snippet. As discussed in the previous issue, the code contains a typo wherein the inner function misuses a list initialized outside with the function's own result rather than its provided accumulator argument.

```
module Main exposing (..)

import Html exposing (text)

{-| Return a list populated with a single value
-}
toList value =
    let
        toList_ : number -> List number -> List number
        toList_ value list =
            -- TYPO list_ should be list
            value :: list_

        list_ =
            toList_ value []
    in
        list_


main =
    text <| toString <| toList 1
```

The error is

```
It looks like something went wrong with the type inference algorithm.

Unable to generalize a type variable. It is not unranked.

Please create a minimal example that triggers this problem and report it to
<https://github.com/elm-lang/elm-compiler/issues>
elm-make: thread blocked indefinitely in an MVar operation
```

If we add annotation to `toList`, or remove annotation from `toList_`, the program compiles successfully, however opening resulting `index.html` causes `Uncaught TypeError: Cannot read property 'ctor' of undefined` to be printed out to console (which itself, as discussed, is out of scope of this issue)

**Comment by simianarmy** [comment]
I am in process of upgrading an app from 0.16 to 0.18 and running into this error as well.
There is a lot of code to check...uncertain what I should be doing to help debug.
Full compiler output below:

```
> LANG=en_US.UTF-8 elm-make Main.elm --output=elm.js
Some new packages are needed. Here is the upgrade plan.

  Install:
    elm-community/elm-test 3.1.0
    elm-community/lazy-list 1.0.0
    elm-community/list-extra 4.0.0
    elm-community/random-extra 2.0.0
    elm-community/shrink 2.0.0
    elm-lang/core 5.0.0
    elm-lang/html 2.0.0
    elm-lang/lazy 2.0.0
    elm-lang/trampoline 1.0.1
    elm-lang/virtual-dom 2.0.2
    evancz/elm-graphics 1.0.1
    mgold/elm-random-pcg 4.0.2

Do you approve of this plan? [Y/n] Y
Starting downloads...

  ● elm-community/list-extra 4.0.0
  ● elm-community/shrink 2.0.0
  ● elm-community/lazy-list 1.0.0
  ● evancz/elm-graphics 1.0.1
  ● elm-lang/virtual-dom 2.0.2
  ● elm-community/random-extra 2.0.0
  ● mgold/elm-random-pcg 4.0.2
  ● elm-lang/core 5.0.0
  ● elm-lang/trampoline 1.0.1
  ● elm-lang/html 2.0.0
  ● elm-lang/lazy 2.0.0
  ● elm-community/elm-test 3.1.0

Packages configured successfully!
[========================================          ] - 79 / 97elm-make: It looks like something went wrong with the type inference algorithm.

Unable to generalize a type variable. It is not unranked.

Please create a minimal example that triggers this problem and report it to
<https://github.com/elm-lang/elm-compiler/issues>
elm-make: thread blocked indefinitely in an MVar operation

```

**Comment by ShaneLester** [comment]
@simianarmy I just had this same issue while upgrading to 18 from 17 on compilation.  I got past it by taking any functions that did not have type annotations and defined them explicitly.  

Hope this helps.  I couldn't nail down exactly why, but once I had done this it fixed the problem enough that I can continue the upgrade.

**Comment by simianarmy** [comment]
oo boy, I have a lot of type annotating to do then :)

**Comment by emmanuelrosa** [comment]
Here's a SSCCE which produces this error:

```
import Html exposing (text)

main =
  text "Hello, World!"
  
type LocalMsg =
  Foo String
  | Bar String
  
type GlobalMsg =
  SomethingHappened LocalMsg
  
type alias LocalConfig msg =
  { msg : String -> msg
  }
  
type alias GlobalConfig msg =
  { localConfig : LocalConfig msg
  }
  
createConfig : (a -> msg) -> GlobalConfig msg
createConfig msg =
  { localConfig = 
    { msg = msg Foo
    }
  }
```

## Result

An attempt to compile the example above produces the following:

> Unable to generalize a type variable. It is not unranked.
> Please create a minimal example that triggers this problem and report it to
<https://github.com/elm-lang/elm-compiler/issues>
elm-make: thread blocked indefinitely in an MVar operation

## Environment

* Elm version: 0.18
* Browser: 50.0.1
* OS: Linux 4.4.27-boot2docker #1 SMP x86_64 GNU/Linux

**Comment by simianarmy** [comment]
I added a few type annotations and now back to getting the normal compiler warnings!  I'll update this if it reverts to MVar error after fixing those.

**Comment by fbonetti** [comment]
Does anyone know of a workaround for the example given by @emmanuelrosa? I'm running into a similar issue and my code is already well annotated.

**Comment by inactivist** [comment]
My solution was to use specific rather than generalized types in the annotations.  (Generalized types in annotations also triggers the crash for me.) 

(I don't have any example code handy, sorry.

**Comment by haasDev** [comment]
I recieved this message as well while going through the tutorial on elm-tutorial.org turns out the error was in a type signature.  

I had : 

`view : model -> Html Msg`

instead of : 

`view : Model -> Html Msg`

**Comment by rupertlssmith** [comment]
I've been running into this issue when I took some code that worked on a particular field of a record, and tried to generalize it with a 'selector' function that maps the record to a String, so a consumer of the code can pass in a function to select which field it acts on. I'll try and SSCCE it.

**Comment by simianarmy** [comment]
@inactivist's solution worked for me as well.  Turns out I didn't need the generalized type annotations anyways

**Comment by evancz** [comment]
Thanks for the report @dtcaciuc! Tracking any issues like this in #1613 to get a high-level view of all the examples and try to figure it out.

**Comment by RobertFischer** [comment]
I had another issue like this right now. It had to do with a record whose types were all functions. I moved those functions out and put type annotations on them one at a time until the compiler was happy again.

**Comment by evancz** [comment]
I resolved the unranked thing in commit XXX, but this code is actually handled in a new way in my development build:

![screen shot 2018-03-06 at 1 55 35 pm](https://user-images.githubusercontent.com/1658058/37060761-18fc266e-2146-11e8-80cf-6f707db6a9c2.png)

It will still be possible to create unsafe cyclic values in the next release, but only at the top level. That means you can make self-recursive `Random.Generator`, `Json.Decoder`, etc. but it will not be possible to allocate cyclic values arbitrarily. I think this design will:

1. Allow people to do everything they need.
2. Avoid cyclic values that make GC way harder
3. Produce slightly nicer error messages when it is a typo

Anyway, thanks again for the report!

**Comment by MikaelMayer** [comment]
Until one gets @evancz's fix https://github.com/elm/compiler/commit/4b25980d93ada12236c794f35570e197be82f787, here are my repair steps for big files, which I am still using today. It saves me a lot of time each time this happens. I usually do this step after annotation all functions as @ShaneLester does, but this might work without, so cases similar to @simianarmy should be handled as well.

1. First, I isolate the file that causes the bug. Since this is a type error, I insert in a suspect file the following non-exhaustive pattern error `[a] = [1]`. If this error is not triggered, the "unranked" error comes from this file or from its dependencies. Step by step, I can always find the problematic file.
2. Once I know which file is crashing the compiler, I look for the following regular expression

    `^(?=\w.*=)([^=]+)=(?!Debug)([\s\S]*?(?=\n\w))`  
      
    and replace it by the following, to "hide" the implementation of my functions (it replaces the body of each definition by a debug crash and puts the old body in recognizable comments):

    `$1=Debug.crash "test" {-:$2:-}`

3. Using this replacement, I usually hide the body of half of the functions, and checks if it compiles. If it does not, I continue to replace other definitions. If it does, the error was before so I cancel some replacements. And so on until I found the faulty function - usually the error is in the type signature as @tylerthehaas remarked, or a too generalized type as @inactivist found.
4. To make sure there is no debug code anymore after I found the fix, I do the following replacement to remove all the `Debug.crash "test"`
    
    `Debug.crash "test" \{-:([\s\S]*?):-\}`  
    `$1`

I post this here hoping it can help other unfortunate souls, but I'm looking towards the real fix.
