### ISSUE TITLE
Inlined bitwise shifts has wrong order of arguments

### ISSUE THREAD

**Issue by Skinney** [elm-lang/elm-compiler#1506]
The elm compiler inlines Bitwise operations, but for shifting operations (`shiftLeftBy`, `shiftRightBy` and `shiftRightZfBy`) the arguments are inlined in the wrong order.

Example:

```
module Main exposing (..)

import Html exposing (..)
import Bitwise


main : Html Never
main =
    text <| toString <| shiftTest


shiftTest : Int
shiftTest =
    33
        |> Bitwise.shiftRightZfBy 5
        |> Bitwise.shiftRightBy 5
        |> Bitwise.shiftLeftBy 5
```

Results in the following code for `shiftTest`

```
var _user$project$Main$shiftTest = 5 << (5 >> (5 >>> 33));
```

But it should result in the following code:

```
var _user$project$Main$shiftTest = ((33 >>> 5) >> 5) << 5;
```

**Comment by mgold** [comment]
Confirming that Random.Pcg is totally borked because of this.

**Comment by evancz** [comment]
Should be fixed in the next batch of binaries
