### ISSUE TITLE
Cannot access fields in a record referenced by its qualified name

### ISSUE THREAD

**Issue by avh4** [elm-lang/elm-compiler#1509]
This should probably be added to https://github.com/elm-lang/elm-compiler/issues/1375

```elm
import Http
import Html

x = Http.defaultSettings

main = Html.text <| toString <| x.timeout  -- This works

main = Html.text <| toString <| Http.defaultSettings.timeout -- gives a parse error
```

The error message given by the last line is:
```
Cannot find variable `Http.defaultSettings.timeout`.

8| main = Html.text <| toString <| Http.defaultSettings.timeout
                                        ^^^^^^^^^^^^^^^^^^^^^^^
The qualifier `Http.defaultSettings` is not in scope.
```

I would expect to be able to access fields within records that I refer to by their qualified name.

**Comment by evancz** [comment]
It's in #1374, first reported in #520. I'll add this to the line about it though!

**Comment by evancz** [comment]
This is fixed by the new parser. Thanks for the report!
