### ISSUE TITLE
whitespace syntax error

### ISSUE THREAD

**Issue by gucki** [elm-lang/elm-compiler#1512]
This code fails with a syntax error:

    type alias Entry = {
      title : String,
      column : Int
    }

    entries : List Entry
    entries = [
      {title = "Test sprint meeting", column = 1},
      Entry "Test sprint meeting" 1,
      Entry "1on1 with Nicola" 2
    ]

When adding any number (> 1) of spaces before the last ] it works:

    type alias Entry = {
      title : String,
      column : Int
    }

    entries : List Entry
    entries = [
      {title = "Test sprint meeting", column = 1},
      Entry "Test sprint meeting" 1,
      Entry "1on1 with Nicola" 2
     ]

I'm quite new to elm, but I really assume it's a bug?

**Comment by evancz** [comment]
There is already a note about this in #1375 for record expressions, which behave the same way. I'll add this as an equivalent suggestion for lists. I think the better move may be to make the `type alias` parsing match everything else.
