### ISSUE TITLE
Compiler suceeds but generates Javascript syntax errors

### ISSUE THREAD

**Issue by naddeoa** [elm-lang/elm-compiler#1514]
I have a [demo of this issue](https://github.com/naddeoa/hamster-elm/tree/syntax-error) in a branch on github. Check it out with the following:

```bash
git clone https://github.com/naddeoa/hamster-elm.git
cd hamster-elm
git checkout -b syntax-error origin/syntax-error
make syntax-error
# Go visit http://localhost:8000/src/elm/Main.elm
```

That will build using `elm-make`, start up `elm-reactor` and spit out a url for you to go to. On that page you'll see the following error in your Javascript console.

```
Uncaught SyntaxError: Unexpected token .
Main.elm:10 Uncaught ReferenceError: runElmProgram is not defined
    at http://localhost:8000/src/elm/Main.elm:10:1
```

I probably did something stupid, but I would imagine that the compiler shouldn't have succeeded. All apologies if I end up being wrong or this is a duplicate; I couldn't find any other mentions in the links for the issue template.

Operation system: Ubuntu 16.04
Browser: Chrome (latest stable)
Elm version: 0.17.1

**Comment by mgold** [comment]
The essence of the bug is here, right?

```
type Msgs
    = Msg
    | TagList.Msg -- this isn't showing up as a syntax error to the compiler, even thou IntelliJ catches it
```

If so that sounds like the No Kind Checking found it #1373.

**Comment by jvoigtlaender** [comment]
Depending on how one looks at it, it's either what @mgold says or it's a duplicate of #1200.

In any case, it's a duplicate and should be closed. (Neither I nor @mgold have the power to close, so please, @naddeoa, close it yourself.)

**Comment by jvoigtlaender** [comment]
Oh, and @naddeoa, by way of fixing what seems to be your conceptual problem with union types, these are relevant to read, I think:
* https://github.com/elm-lang/elm-compiler/issues/1200#issuecomment-255552878
* https://guide.elm-lang.org/types/union_types.html

**Comment by naddeoa** [comment]
Thanks for the quick response. @mgold  is right about the cause I think. If its a duplicate then I'll close it down.

@jvoigtlaender  thanks for the feedback. My elm has come a long way since that commit but there is a way to go for sure.
