### ISSUE TITLE
Valid recursion leads to runtime error

### ISSUE THREAD

**Issue by jvoigtlaender** [elm-lang/elm-compiler#1516]
**Edited by @evancz**

The following program leads to a runtime error ("g is not a function").

```elm
import Html

g = h

h n =
  if n < 2 then 1 else g (n - 1)

main = Html.text (toString (h 10))
```

With the 0.18 compiler, it produces this JavaScript:

```js
var _user$project$Main$g = _user$project$Main$h;
var _user$project$Main$h = function (n) {
	return (_elm_lang$core$Native_Utils.cmp(n, 2) < 0) ? 1 : _user$project$Main$g(n - 1);
};
var _user$project$Main$main = _elm_lang$virtual_dom$Native_VirtualDom.staticProgram(
	_elm_lang$html$Html$text(
		_elm_lang$core$Basics$toString(
			_user$project$Main$h(10))));
```

If the `var` definitions for `_user$project$Main$g` and `_user$project$Main$h` were reordered, everything would be fine. It is unclear how to detect this in general, so no concrete steps are proposed to fix this right now.

* * *

The following two programs are equivalent, but *do* run successfully:

```elm
import Html

h n =
  if n < 2 then 1 else g (n - 1)

g = h

main = Html.text (toString (h 10))
```

```elm
import Html

h n =
  if n < 2 then 1 else h (n - 1)

main = Html.text (toString (h 10))
```

**Comment by evancz** [comment]
Please try to use reasonable function names in your examples! Naming things `h` and `g` is a waste of my time.

Also, don't we already have issues open about this? Where the order of arguments *can* matter because of the specifics of how JS is generated? This issue is better I think, but can you find such issues and reference them here. It'd be good to consolidate it all into one place.

**Comment by jvoigtlaender** [comment]
> Please try to use reasonable function names in your examples!

I don't know what this complaint is about. It's an SSCCE, there are no meaningful function names to use. Would `fun1` and `fun2` be better than `g` and `h`? I'm at a complete loss what you are objecting to here.

If you need to know where the example came from: It is reduced from the example `fibonacci` in the README of https://github.com/jvoigtlaender/elm-memo. But had I used that example as is, I would almost certainly have been told to reduce it to an SSCCE instead. Now I did that, but retaining the names `fibonacci` etc. would have been met with disapproval as well for certain, because they would just confuse in an example that is not computing fib numbers anymore.

So why on earth is using `h` and `g` bad or a waste of time?

> Also, don't we already have issues open about this? ... but can you find such issues and reference them here ...

What makes you think I didn't check the open issues before opening this one? I also checked the relevant meta issue about code gen before opening this one. What else would be required that I would have had to do?

**Comment by evancz** [comment]
It looks like you wrote `factorial` and then changed the names to be single letters. Where an example comes from is helpful in knowing the impact it has in practice. If you just make it up in your head, it's not as important as if you saw it in real life.

I don't know what you have or have not done unless you tell me, so I was asking for further information. If you can't find anything, that's fine. I must be misremembering or it got lost in all the #873 issues.

**Comment by jvoigtlaender** [comment]
> Where an example comes from is helpful in knowing the impact it has in practice. If you just make it up in your head, it's not as important as if you saw it in real life.

If that is information you require in issues being opened, then you should probably mention so in the text in which you tell potential contributors what you expect: https://github.com/process-bot/contribution-checklist/blob/master/issues.md

Currently, you only say there that you want to be given an SSCCE. You don't say there or anywhere else in the contribution guidelines that you want to be told about the real example that was the origin from which the SSCCE was reduced.

If you were to actually let potential contributors know up front what you require, and that just giving an SSCCE with often necessarily artificial function names is a waste of your time, then something like your first comment above would create less of an impression that you are just pushing back against a contributor for whatever reason.

**Comment by evancz** [comment]
Okay, I'll do better next time. I am going to try to clean this issue up. It looks like this problem exists with 0.17 as well.

**Comment by omouse** [comment]
Reproduced on elm 0.17. The issue is that the order of definition is incorrect.

## RuntimeError Elm

```haskell
-- leads to a runtime error "g is not a function"
import Html
g = h
h n =
    if n < 2 then
        1
    else
        g (n - 1)

main = Html.text (toString (h 10))
```

produces:

```javascript
var _user$project$Main$g = _user$project$Main$h;
var _user$project$Main$h = function (n) {
	return (_elm_lang$core$Native_Utils.cmp(n, 2) < 0) ? 1 : _user$project$Main$g(n - 1);
};
var _user$project$Main$main = {
	main: _elm_lang$html$Html$text(
		_elm_lang$core$Basics$toString(
			_user$project$Main$h(10)))
};
```

## Valid Elm

```haskell
import Html
h n =
  if n < 2 then
      1
  else
      g (n - 1)
g = h

main = Html.text (toString (h 10))
```

produces:

```javascript
var _user$project$Main$h = function (n) {
	return (_elm_lang$core$Native_Utils.cmp(n, 2) < 0) ? 1 : _user$project$Main$g(n - 1);
};
var _user$project$Main$g = _user$project$Main$h;
var _user$project$Main$main = {
	main: _elm_lang$html$Html$text(
		_elm_lang$core$Basics$toString(
			_user$project$Main$h(10)))
};
```

**Comment by jvoigtlaender** [comment]
@omouse, all you say above is already known. You might as well delete that comment, to keep this issue clean. Just as Evan already deleted other comments of previous exchange between him and me here. 

(And I will delete this comment here.)

**Comment by evancz** [comment]
Added all of these to https://github.com/elm-lang/elm-compiler/issues/1377 so it can be addressed alongside a bunch of similar issues.

Thanks for the report!

**Comment by evancz** [comment]
With latest version of the compiler, it generates this:

```javascript
var user$project$Main$h = function (n) {
	return (_Utils_cmp(n, 2) < 0) ? 1 : user$project$Main$g(n - 1);
};
var user$project$Main$g = user$project$Main$h;
var user$project$Main$main = _VirtualDom_staticProgram(
	elm_lang$html$Html$text(
		elm_lang$core$Basics$toString(
			user$project$Main$h(10))));
```
