### ISSUE TITLE
`effect` is a keyword and therefore it shouldn't be used as an identifier 

### ISSUE THREAD

**Issue by durkiewicz** [elm-lang/elm-compiler#1518]
`effect` is a keyword that changes a module into an effects module. Therefore a definition like that:
```elm
effect x =
    x ++ x
```
should result with a parser's error.
It's similar to a code like that:
```elm
import x =
    x ++ x
```
which raises a parser's error correctly.

**Comment by evancz** [comment]
The term `alias` is also a keyword that can be used as a variable. There are certain keywords that can never be ambiguous, so it does not seem terrible to allow their use.

That said, it's better to make suggestions like this on elm-discuss and refine them into well-supported suggestions once you have some community feedback.
