### ISSUE TITLE
Multiline strings aren't indentation-aware

### ISSUE THREAD

**Issue by cruhl** [elm-lang/elm-compiler#1520]
Multiline strings add newlines in places which aren't intuitive:

```elm
markdown : String
markdown =
    """
    # Hello!
    
    This string is going to have extra spacing to the left
        since it doesn't know about indentation.
    
    This problem gets pretty annoying when working with markdown.
    """
```

Ruby solves this problem pretty well:
https://infinum.co/the-capsized-eight/articles/multiline-strings-ruby-2-3-0-the-squiggly-heredoc

I am using this helper function to alleviate the problem when working with markdown:

```elm
markdownToHtml : String -> Html msg
markdownToHtml =
    String.Extra.unindent >> Markdown.toHtml []
```

**Comment by evancz** [comment]
This is true. I'm not sure if I'd like to change this, but that is a design question. I prefer to track those separately, so I will close here.
