### ISSUE TITLE
"Maximum call stack size exceeded" when passing large values via ports and `--debug` flag used

### ISSUE THREAD

**Issue by ssbb** [elm-lang/elm-compiler#1522]
Looks like Elm trying to escape all values when using `--debug` flag. And when I am trying to pass some big value (Google Maps object in my case) to Elm via ports - there is error "Maximum call stack size exceeded".

Maybe we should just display something like "Value" in debugger instead of trying to expand whole value?

Elm version: 0.18
Browser: Chromium 54.0.2840.100 (64-bit)

**Comment by evancz** [comment]
This is tracked over at https://github.com/elm-lang/virtual-dom/issues/98
