### ISSUE TITLE
Code has side effect, an array value gets modified.

### ISSUE THREAD

**Issue by wearsunscreen** [elm-lang/elm-compiler#1523]
Value `g` gets modified when the following is evaluated...

 ```elm 
 results =
            [ getRow 0 (setColorInGrid ( 0, 0 ) 99 (Debug.log "before" g))
                == [ 99, 4, 2, 4 ]
            , concatGrid g == concatenated
            , getRow 0 (setColorInGrid ( 0, 0 ) 99 (Debug.log "after" g))
                == [ 99, 4, 2, 4 ]
            ]
```

The first and third elements should be identical, but `g` changes when `concatGrid g` is evaluated.

Full code is attached. Happens on v 0.18, Firefox and Chrome. I have not tested on other versions or browsers. 

[GridA.elm.txt](https://github.com/elm-lang/elm-compiler/files/629337/GridA.elm.txt)

**Comment by jvoigtlaender** [comment]
@wearsunscreen, isn't this already captured by https://github.com/elm-lang/core/issues/649? If so, close here. Even if not already captured there, `elm-lang/core` is probably the appropriate repository for reporting bugs like this. So even then the issue should still be closed here and reopened over there.

**Comment by wearsunscreen** [comment]
@jvoigtlaender, it does seem to be close to that issue. I'll move this to core, link it to elm-lang/cor#649, and close this issue. Thanks.

**Comment by wearsunscreen** [comment]
Move this issue to [elm-lang/core#775](https://github.com/elm-lang/core/issues/775).
