### ISSUE TITLE
SSCCE to crash type inference using incorrect annotation

### ISSUE THREAD

**Issue by rtfeldman** [elm-lang/elm-compiler#1525]
EDIT: revised to use the better example in https://github.com/elm-lang/elm-compiler/issues/1525#issuecomment-267857688

## To Reproduce

1. Put the code below in a file called `Main.elm`
2. `elm-make --yes Main.elm`

```elm
type alias Whatever =
    ()


tooGeneral : a -> Int
tooGeneral a =
    alwaysOne a


alwaysOne : Whatever -> Int
alwaysOne _ =
    1
```

```
elm-make: It looks like something went wrong with the type inference algorithm.

Unable to generalize a type variable. It is not unranked.

Please create a minimal example that triggers this problem and report it to
<https://github.com/elm-lang/elm-compiler/issues>
elm-make: thread blocked indefinitely in an MVar operation
```

**Comment by rtfeldman** [comment]
@evancz SSCCE'd an elusive MVar crash!

**Comment by chaseries** [comment]
Ran into what I believe is the same bug. Steps to reproducing the bug for the program below are identical to those of @rtfeldman.

```
type alias T1 =
  ()

f : t1 -> Int
f t1 =
    g t1

g : T1 -> Int
g t1 =
  1
```

**Comment by deBhal** [comment]
I just ran into this too, by accidentally using a lowercase `model` instead of a capital `Model` in a type signature.

You can get here by pasting the elm architecture [forms example](https://guide.elm-lang.org/architecture/user_input/forms.htm) into http://elm-lang.org/try and changing that one character in the view type signature:
`view : Model -> Html Msg` ->
`view : model -> Html Msg`

It's pretty confusing when you're new to the language!

**Comment by rtfeldman** [comment]
Updating OP with a better example. Here's the original example, for posterity:

```
type Msg
    = Report (List String)

type Problem a =
    Problem a

-- This annotation is incorrect because it is too general. It should be:
-- foo : Result (Problem (List String)) Msg -> Msg
foo : Result (Problem a) Msg -> Msg
foo result =
    case result of
        Ok msg ->
            msg

        Err (Problem errors) ->
            Report errors
```

Compiler output:

```
It looks like something went wrong with the type inference algorithm.

Unable to generalize a type variable. It is not unranked.

Please create a minimal example that triggers this problem and report it to
<https://github.com/elm-lang/elm-compiler/issues>
elm-make: thread blocked indefinitely in an MVar operation
```

The `List String` in `Report` is crucial to reproducing the bug. Changing it to `String` yields the correct error message instead of crashing:

```
-- TYPE MISMATCH ------------------------------------------------------ Main.elm

The argument to function `Report` is causing a mismatch.

19|             Report errors
                       ^^^^^^
Function `Report` is expecting the argument to be:

    String

But it is:

    a

Hint: Your type annotation uses type variable `a` which means any type of value
can flow through. Your code is saying it CANNOT be anything though! Maybe change
your type annotation to be more specific? Maybe the code has a problem? More at:
<https://github.com/elm-lang/elm-compiler/blob/0.18.0/hints/type-annotations.md>
```

Compilation succeeds if the incorrect annotation is fixed (as described in a comment in the code) or if the offending annotation is removed.

**Comment by evancz** [comment]
Based on commit 4b25980d93ada12236c794f35570e197be82f787, I am now seeing the following error in my development build!

![screen shot 2018-03-06 at 1 32 54 pm](https://user-images.githubusercontent.com/1658058/37059702-f28bf3ae-2142-11e8-8220-861d10632562.png)

> **Note:** You may see extra qualifiers on types in this error. That is part of the dev build, but should not appear in the final thing.

**Comment by rtfeldman** [comment]
Awesome! 😺

**Comment by rtfeldman** [comment]
Wow, that commit closed a *lot* of issues! 😮

**Comment by evancz** [comment]
Haha, yeah, I made the meta issue on the "unranked" thing because I figured it would be like this. A lot of type inference bugs are like two characters that indicate some deep misunderstanding 😄
