### ISSUE TITLE
error "The following pattern is redundant. Remove it."

### ISSUE THREAD

**Issue by haishengwu-okta** [elm-lang/elm-compiler#1526]
## Description

I modified code from http://elm-lang.org/examples/case as below and click the compile. It generated error 

```
Detected errors in 1 module.
==================================== ERRORS ====================================



-- REDUNDANT PATTERN -----------------------------------------------------------

The following pattern is redundant. Remove it.

23|     two -> "two"
        ^^^
Any value with this shape will be handled by a previous pattern.

```

## Source code

```

import Html exposing (text)
import String


one = "1"
two = "2"
primitiveCount number =
  case number of
    one -> "one"
    two -> "two"
    _ -> "many"


main =
  text (String.join ", " primitiveNumbers)


primitiveNumbers =
  [ primitiveCount "1"
  , primitiveCount "2"
  , primitiveCount "3"
  ]
```

## Browser

- Mac Google chrome Version 54.0.2840.98 (64-bit)

**Comment by JoeyEremondi** [comment]
Everything on the left-hand side of a pattern match is a new variable. If you want to check equality, you're probably better off using If-then-else expressions.

There's a discussion of this here: https://groups.google.com/forum/#!topic/elm-discuss/H87Ck1XMZR0

**Comment by haishengwu-okta** [comment]
@JoeyEremondi thanks.
