### ISSUE TITLE
[new parser] Error reading a valid type from serialized string

### ISSUE THREAD

**Issue by rofrol** [elm-lang/elm-compiler#1531]
SSCCE

```elm
import Html
main = Html.text "Hello"
```

- What OS and browser are you using? What versions?

   Windows 10, Google Chrome 55.0.2883.87 m

- What version of Elm are you using?

  master

**Comment by evancz** [comment]
That works fine for me. Clear your `elm-stuff/` and try again. The binaries I released are internally labeled as 0.18 so that it works with the package website, but they'd need a separate version for a real release, which would mean your would not get the old (incompatible) cached data.
