### ISSUE TITLE
[New parser] Minus sign after paren not accepted

### ISSUE THREAD

**Issue by mgold** [elm-lang/elm-compiler#1536]
SSCCE:
```elm
repro =
  (-2)
```

Error:
```
-- PARSE ERROR -------------------------------------------------------- Main.elm

Something went wrong while parsing an expression (in parentheses) in repro's
definition.

9|     (-2)
         ^
I was expecting to see a closing paren.
```

This also happens for non-literals, such as `f (-myValue |> g)` (which is less minimal but more compelling).

**Comment by evancz** [comment]
Thanks for the report, should be fixed with the latest commit. This was a tricky case because `(-)` and `(-2)` and all the dot stuff all needs to work!
