### ISSUE TITLE
Port error should have a better message

### ISSUE THREAD

**Issue by halfzebra** [elm-lang/elm-compiler#1541]
Port definition is required to have a generic type annotation.

```elm
port out: String -> Cmd msg

port in: (() -> msg) -> Sub msg
```

Error in type definition redirects to the guide, but guide does not stress, that [you should have a generic type definition for messages in port functions](https://github.com/evancz/guide.elm-lang.org/issues/75)

```
Port `input` has an invalid type.

39| port input : (Int -> msg) -> Sub Msg
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
You are saying it should be:

    (Int -> msg) -> Platform.Sub.Sub Main.Msg

But you need to use the particular format described here:
<http://guide.elm-lang.org/interop/javascript.html#ports>
```

It is quite easy to overlook the standardized way of defining ports while reading a guide with many other code snippets.

The compiler should notify, that ports definition should have a generic definition for messages or [The guide on JavaScript interop should explain port function type definitions](https://github.com/evancz/guide.elm-lang.org/issues/75)

Any feedback is very welcome!

**Comment by jvoigtlaender** [comment]
Pleased move this issue to the error message catalog repository. That's what it exists for. 

https://github.com/elm-lang/error-message-catalog/issues

**Comment by rtfeldman** [comment]
As @jvoigtlaender said, this is perfect for the Error Message Catalog! Would be great to open an issue there, but in the meantime I'm going to close this one.
