### ISSUE TITLE
Leaving type parameters out of type annotation compiles when it shouldn't

### ISSUE THREAD

**Issue by naddeoa** [elm-lang/elm-compiler#1542]
We were talking about some weirdness in the general chat today and user alon came up with a simple example to showcase it. The following code compiles.

```Elm
type SomeUnion a b c
    = SomeType a
    | SomeOtherType b c


myFunction : SomeUnion a -> String
myFunction atype =
    "hmm but why?"
```

`SomeUnion` takes three type parameters but only one is supplied. No one will be able to call this function because no one can make a `SomeUnion a` obviously, so I suppose the damage is as minimal as it gets.

This was tested on Elm 0.18.0 on Ubuntu 16.04.

**Comment by mgold** [comment]
Seems to be part of "no kind checking", #1373. Thanks for the report!

**Comment by rtfeldman** [comment]
Added to the No Kind Checking section of https://github.com/elm-lang/elm-compiler/issues/1373 - thanks again!

**Comment by evancz** [comment]
In the development build, I am getting:

```
- TOO FEW ARGS ------------------------------------------------------- temp.elm

The `SomeUnion` type was given 1 argument:

14| myFunction : SomeUnion a -> String
                 ^^^^^^^^^^^
But it needs 3 arguments. What is missing? Are some parentheses misplaced?
```

Because we now rule this out in the canonicalization phase. Thanks for the report!

**Comment by naddeoa** [comment]
Nice, thank a lot
