### ISSUE TITLE
Compiler crash for tuples over 9 members

### ISSUE THREAD

**Issue by kkruups** [elm-lang/elm-compiler#1543]
To reproduce:

```
import Html exposing (text)

myTup = (1,2,3,4,5,6,7,8,9,10)

main =
  text <| toString myTup

```

Compiler output:

```
elm-make: Could not find `_Tuple10` when solving type constraints.
elm-make: thread blocked indefinitely in an MVar operation
```

**Comment by rtfeldman** [comment]
It's best not to combine feature requests with bug reports, so per [this repo's guidelines](https://github.com/process-bot/contribution-checklist/blob/master/issues.md#guidelines) requiring conciseness, I edited the original post to remove everything but the bug report.

Here is the rest, for posterity. 🙂

> This appears to be an arbritary constraint.  Lists do not behave in this manner.  
> Why should tuples be restricted in this way?
> 
> 
> ## Additional Info:
> 
> We should be able to add members and create comprehensions similar to the manner which we can with Lists.  
> 
> I wanted to create a list comprehension which included a tuple (breaks at 10 member):
> 
> This fails with indicated error:
> `tupleIt = \y -> [let baizo x = x * y in (baizo 1 , baizo 2 , baizo 3, baizo 4, baizo 5, baizo 6, baizo 7, baizo 8, baizo 9, baizo 10, baizo 11, baizo 12) ]`
> 
> However with a list is works successfully:
> 
> listIt = \y -> [let baizo x = x * y in [baizo 1 , baizo 2 , baizo 3, baizo 4, baizo 5, baizo 6, baizo 7, baizo 8, baizo 9, baizo 10, baizo 11, baizo 12 ]]
> 
> ## Environment:
> 
> win7 sp1
> elm-repl (0.17)
> elmO (latest version 0.18 release) (should really add version info to elmO)
> 
> 
> ## Issue Added Here (as compiler issue) as per **rtfeldman** request:
> 
> https://github.com/elm-lang/core/issues/781
>

**Comment by drathier** [comment]
Just ran into this as well. Is the tuple size limit a limitation in that Haskell doesn't have variadic functions?

**Comment by jvoigtlaender** [comment]
What ever would a limitation of Haskell have to do with this? The Elm language can be designed (and implemented) to have any size of tuples wanted.

**Comment by drathier** [comment]
The compiler is written in Haskell. Read `thread blocked indefinitely in an MVar operation` and got the hunch from functions like `mapN`. It could be hard to rewrite it.

**Comment by jvoigtlaender** [comment]
I know what the compiler is written in. :smile:

Anyway, none of that is the problem here. 

It would absolutely be possible to implement Elm (in Haskell) supporting tuples of any size.

**Comment by fosskers** [comment]
Had this happen the other day.

**Comment by mgold** [comment]
Can you post your example of large tuples on the [mailing list](https://groups.google.com/forum/#!forum/elm-discuss)? Large tuples are usually (always?) a smell that you should be using a record instead.

**Comment by drathier** [comment]
@mgold `Debug.log ("a", a, "b", b, "c", c, "a*b", a*b, ...)`

**Comment by rtfeldman** [comment]
@drathier That's a clever time-saving trick with `toString` I hadn't considered! Thanks for sharing it.

Having said that, the question of whether the compiler should crash (obviously not) versus whether larger-N tuples should be supported (perhaps) are different discussions, so let's decouple them.

As for the bug part, this seems to be good with the existing SSCCE!

**Comment by evancz** [comment]
In my development build, I am getting the following error:

```
-- BAD TUPLE ---------------------------------------------------------- temp.elm

I only accept tuples with two or three items. This has too many:

4| myTup = (1,2,3,4,5,6,7,8,9,10)
           ^^^^^^^^^^^^^^^^^^^^^^
I recommend switching to records. Each item will be named, and you can use the
`point.x` syntax to access them.

Note: Read <https://elm-lang.org/hints/0.19.0/tuples> for more comprehensive
advice on working with large chunks of data in Elm.
```

Not everything is finalized in the development branch (otherwise it would be released!) but the point is that the compiler now detects the max tuple size.
