### ISSUE TITLE
Where is the logic that chooses types to suggest in error messages located?

### ISSUE THREAD

**Issue by vasily-kirichenko** [elm-lang/elm-compiler#1544]
We are jealous about the Elm error messages where it suggest types in case of typos in code :) 

We are implementing a similar feature and it'd be very useful for us to look at the code which chooses type names to suggest to user. Could anybody point us? Thanks.

**Comment by forki** [comment]
We're especially interested in what distance function elm is using and how you filter false positives. Thanks and kudos for the excellent work!

**Comment by rtfeldman** [comment]
Hi @vasily-kirichenko @forki,

It's really cool that you're excited about how Elm does things! However, we need to use this repository for tracking bugs in the compiler, so this is not the right place to ask this.

Can you post on [elm-discuss](https://groups.google.com/forum/#!forum/elm-discuss) or ask on [Elm Slack](http://elmlang.herokuapp.com/) instead?

Thanks!
