### ISSUE TITLE
[New parser] elm-make fails on elm-mdl/examples/Counter.elm

### ISSUE THREAD

**Issue by rofrol** [elm-lang/elm-compiler#1546]
> $ cd elm-mdl/examples
> $ elm make Counter.elm
> Problem in dependency debois/elm-mdl 8.0.0
> 
> The elm-package.json constraints of 'debois/elm-mdl' are probably
> letting too much stuff through. Definitely open an issue on the relevant github
> repo to get this fixed and save other people from this pain.
> 
> In the meantime, take a look through the direct dependencies of the broken
> package and see if any of them have had releases recently. If you find the new
> thing that is causing problems, you can artificially constrain things by adding
> some extra constraints to your elm-package.json as a stopgap measure.
> 
> 
> Problem in dependency debois/elm-mdl 8.0.0
> 
> The elm-package.json constraints of 'debois/elm-mdl' are probably
> letting too much stuff through. Definitely open an issue on the relevant github
> repo to get this fixed and save other people from this pain.
> 
> In the meantime, take a look through the direct dependencies of the broken
> package and see if any of them have had releases recently. If you find the new
> thing that is causing problems, you can artificially constrain things by adding
> some extra constraints to your elm-package.json as a stopgap measure.
> 
> 
> Detected errors in 2 modules.
>

**Comment by mgold** [comment]
This is not an [SSCCE](sscce.org). These errors arise when the dependency fails to compile.

Omitting output for all but the last command:
```
$ git clone git@github.com:debois/elm-mdl.git
$ cd elm-mdl
$ elm package install
$ elm make

-- NAMING ERROR ---------------------------------------- ./src/Material/Menu.elm

Cannot find pattern `True`

700|                 ( Just g, True ) ->
                               ^^^^


==================================== ERRORS ====================================

-- PARSE ERROR --------------------------------------- ./src/Material/Layout.elm

Something went wrong while parsing a `case` in drawerButton's definition.

783|                        value is available.
784|                     -}
785|                 }
786|                 (Decoder.map
                                     ^
I was expecting to see more of that `case`. Maybe you forgot some code? Or maybe
the body of `drawerButton` needs to be indented?

Detected errors in 2 modules.                                       
```

The issue with the bools is #1539. The other issue I have filed as #1547. I think this issue can be closed now.

**Comment by dubert** [comment]
Pardon me, I'm still having this issue.. has it been resolved? I can't upgrade to 8 from 7.

**Comment by mgold** [comment]
The latest version of the new parser (that I know of) is older than the fix for booleans, so even if the indentation was changed in elm-mdl it would not compile. There's a place where they're pattern matching on a tuple containing a bool, which is not trivially replaced with `if`.
