### ISSUE TITLE
[New parser] case statements require indentation where they did not before

### ISSUE THREAD

**Issue by mgold** [elm-lang/elm-compiler#1547]
SSCCE:

```elm
isTwo x =
    case x of
        2
        -> True

        _
        {- anything else -}
        -> False
```

This style, which is accepted by the old parser, is bizarre for two reasons: the `->` is on the second line, and it is indented equally with the pattern. I have included the comment to show why someone would want to do this. See [here](https://github.com/debois/elm-mdl/blob/5d345bf21eeeff8be2234fd1e1097fecd76709ff/src/Material/Layout.elm#L789-L801) for an example "in the wild".

The error message is:
```
-- PARSE ERROR --------------------------------------------------- src/Repro.elm

Something went wrong while parsing a `case` in isTwo's definition.

4|     case x of
5|         2
6|         -> True
           ^
I was expecting to see more of that `case`. Maybe you forgot some code? Or maybe
the body of `isTwo` needs to be indented?
```

As the message suggests, if you indent line 6, including the `->`, it compiles. That is, (this whole definition compiles in 0.18),

```elm
f x =
    case x of
        1 -> "compiles"

        2 ->
            "compiles"

        3
            -> "compiles"

        4 ->
        "does not compile"

        5
        -> "does not compile"

        _ -> "exhaustive"
```
It seems very odd to allow styles 2 and 3. It seems reasonable to me to reject styles 4 and 5, even though it's a breaking change.

**Comment by evancz** [comment]
Thanks for the report! I prefer that it is this way. Now we have more proof that the parser changes are a major change :)
