### ISSUE TITLE
Record with 'interface' key produces undefined result when used with ports

### ISSUE THREAD

**Issue by vvanders** [elm-lang/elm-compiler#1548]
I have a port that looks like this:
```
port simplelink_init : { interface : String, callsign : String } -> Cmd msg
```

However when I use it like so:
```
case msg of
  InitAction(InitPage.SetLoopback) -> (Main(MainPage.init), simplelink_init { callsign = "KI7EST", interface = "loopback"})
```

On the other end of the port the 'interface' key is undefined. It looks like the generated JS is adding an extra $:
```
case 'SetLoopback':
    return {
        ctor: '_Tuple2',
        _0: _user$project$Main$Main(_user$project$MainPage$init),
        _1: _user$project$Main$simplelink_init(
            {callsign: 'KI7EST', $interface: 'loopback'})
    }
```

If I change they key to 'foo':
```
port simplelink_init : { foo : String, callsign : String } -> Cmd msg
```

Then the generated JS looks correct and everything comes through fine:
```
case 'SetLoopback':
    return {
        ctor: '_Tuple2',
        _0: _user$project$Main$Main(_user$project$MainPage$init),
        _1: _user$project$Main$simplelink_init(
            {callsign: 'KI7EST', foo: 'loopback'})
    }
```

From what I could tell interface isn't a reserved keyword and the compiler didn't yell at me. This is elm version 0.18.0 on Windows and repo with repro branch is https://github.com/vvanders/simplelink/blob/elm_repro/ui/elm/Main.elm

Not sure if this is expected or not but it tripped me up so I thought I'd mention it here so someone else doesn't hit the same thing.

**Comment by pdamoc** [comment]
This and #1510 are triggered by words in the [jsReservedWords list](https://github.com/elm-lang/elm-compiler/blob/master/src/Generate/JavaScript/Name.hs#L201)

**Comment by pdamoc** [comment]
SSCCE:

```elm 
port module Main exposing (main)
import Html exposing (..)
main =
    program
        { init = ( 0, out { default = "hello" } )
        , update = \_ m -> ( m, Cmd.none )
        , view = \_ -> text "Check the Console"
        , subscriptions = \_ -> Sub.none
        }
port out : { default : String } -> Cmd msg
```
```html
<html>
<head> 
</head>
<body>
  <script>
    var app = Elm.Main.fullscreen()
    app.ports.out.subscribe(function(msg) { console.log(msg)}) 
  </script>
</body>
</html>
```

**Comment by evancz** [comment]
Tracking in #1685 now. Thank you for the report!
