### ISSUE TITLE
Union type with period/fullstop in tag name compiles but fails at runtime

### ISSUE THREAD

**Issue by emmanuelrosa** [elm-lang/elm-compiler#1554]
When a tag (union type constructor) has a period/fullstop in its name, the code compiles just fine but fails to run due to a JavaScript SyntaxError.

For example, here's a slightly-modified copy of the counter example from http://elm-lang.org/try

```
import Html exposing (beginnerProgram, div, button, text)
import Html.Events exposing (onClick)


main =
  beginnerProgram { model = 0, view = view, update = update }


view model =
  div []
    [ button [ onClick Decrement ] [ text "-" ]
    , div [] [ text (toString model) ]
    , button [ onClick Increment ] [ text "+" ]
    ]

-- Added a dummy tag named Watch.This
type Msg = Increment | Decrement | Watch.This


update msg model =
  case msg of
    Increment ->
      model + 1

    Decrement ->
      model - 1

    -- Added a no-op  pattern match.
    Watch.This ->
      model
```

The above code compiles fine with Elm 0.18.0. But running it produces the following error: 

> SyntaxError: missing ; before statement

The error points to the line: `var _elm_lang$html$Html$span = _elm_lang$html$Html$node('span');`

I don't see a problem with that particular line, but when I encountered the error in my program (caused by a failed search-and-replace) the issue was that the compiler generated a function name with a fullstop included in the name.

For example, a union type like this:

```
type Msg =
    SetModel.Model Model
```

Produced a function like this:

```
var _user$project$Main$SetModel.Model = function (a) {
	return {ctor: 'SetModel.Model', _0: a};
};
```

# Environment

- Web browser: Firefox 50.1.0
- Elm version: 0.18.0
- OS : Boot2Docker (Linux) 4.4.27 running on Mac OSX 10.11.6

**Comment by evancz** [comment]
With the upcoming version of the compiler, which has a new parser, I am getting this error:

```
-- PARSE ERROR ------------- /Users/evan/Documents/pkgs/dom/src/Dom/LowLevel.elm

Something went wrong while parsing a union type.

131| type Msg = Increment | Decrement | Watch.This
                                             ^
I was expecting:

  - a vertical bar (|) followed by more union type constructors
  - a type, like Int or (List String)
  - more of that union type. Maybe you forgot some code? Or you need more
    indentation?
```

Thanks for the report!
