### ISSUE TITLE
Proposal: Read GLSL from file as an alternative to inline definition

### ISSUE THREAD

**Issue by lpil** [elm-lang/elm-compiler#1556]
Hi!

Currently we can write GLSL inline in our Elm applications using the special `[glsl|...|]` syntax. This is convenient and we gain type checks, but we lose editor support for GLSL that we would get from writing it in another file.

I think it'd be a great to have a way of loading this GLSL code from a file so we can leverage existing tooling without resorting to generating Elm files with scripts. 

# Proposed Implementation

```glsl
/* my-shader.glsl */

precision mediump float;
varying vec3 vcolor;
void main () {
    gl_FragColor = vec4(vcolor, 1.0);
}
```

```elm
-- Main.elm

fragmentShader : Shader {} Uniforms { vcolor : Vec3 }
fragmentShader =
    [glsl-file|my-shader.elm|]
```

I'm happy to work on adding this feature, presuming I can stumble though the Haskell.

Thanks :)

**Comment by w0rm** [comment]
@lpil why not embed glsl syntax into Elm syntax instead like e.g. JavaScript is embedded in the script tag in HTML. https://github.com/edubkendo/atom-elm/issues/50

**Comment by lpil** [comment]
Because that results in loss of existing GLSL tooling. All this work would have to be replicated by the Elm tooling authors.

**Comment by lpil** [comment]
Also GLSL is already embedded in Elm, so we have that already :)

**Comment by w0rm** [comment]
Sorry, I meant embedding glsl syntax highlighting into the Elm sources.
I think you may also try to fetch a shader with Ajax and then use `unsafeShader`.

**Comment by lpil** [comment]
Then we'd lose type safety and add extra HTTP requests at runtime. :(

**Comment by evancz** [comment]
Normally I prefer not to track proposals in the issue tracker. This one is very interesting though. I don't know a ton about GLSL so I don't know how fancy the tooling can be for those files.

I'll start a meta issue to track things like this.
