### ISSUE TITLE
runtime error: `Cannot read property 'tag' of undefined` even in 0.18

### ISSUE THREAD

**Issue by radix** [elm-lang/elm-compiler#1562]
This is the same error as in #873, but I am using Elm 0.18 and still getting it.

Here is the reproducer: https://gist.github.com/radix/8ca065f1be9f64547970943df900b3f6

Notice I am using `lazy` to avoid the recursion.

Reproduced in Chrome/Windows, Firefox/Windows, and Node.js/windows (in the Elm REPL).

*edit* I found a workaround, and it is very specific: if I modify the `ApplyCondition` section of the decoder like this:

```elm
      , ("ApplyCondition", JD.map2 ApplyCondition
                                     (JD.index 0 conditionDurationDecoder)
                                     (JD.index 1 (JD.lazy (\_ -> conditionDecoder))))
```

it works.

The very strange thing is that before this, I tried defining a toplevel `lazyConditionDecoder = JD.lazy (\_ -> conditionDecoder)`. If I used that instead of inlining the call to JD.lazy, it didn't work, which surprised me greatly. The call has to be inlined.

**Comment by jvoigtlaender** [comment]
Seen #1516, #1527, #1529, #1560?

**Comment by radix** [comment]
@jvoigtlaender I did see them after I filed this issue, but I'm not familiar enough with the Elm compiler to know whether this is a dupe. I did quickly skim them to see if they were involving Json.Decode.lazy, and none of them seem to. Also, the thing about how inline JD.lazy works, but a toplevel definition using JD.lazy doesn't, might be significant?

**Comment by jvoigtlaender** [comment]
#1560 does exactly involve JD.lazy. And the thing about "is something top-level or not" seems just a facet of "in which order are things defined".

**Comment by radix** [comment]
@jvoigtlaender sorry I missed that! should I close this ticket?

**Comment by jvoigtlaender** [comment]
Ultimately it's @evancz's prerogative to decide what issues are to be consolidated into one in this repository. I am pretty sure that all of  #1516, #1527, #1529, #1560 and #1562 are the same basic issue. But I am not him. :smile:

**Comment by evancz** [comment]
Adding to https://github.com/elm-lang/elm-compiler/issues/1591
