### ISSUE TITLE
Mac Installer creates directories with incorrect permissions

### ISSUE THREAD

**Issue by alexspurling** [elm-lang/elm-compiler#1563]
When installing Elm on a freshly installed MacOS Sierra 10.12.2, the [Elm Mac Installer for Elm 0.18](http://install.elm-lang.org/Elm-Platform-0.18.pkg) will create the directory `/usr/local/bin/` with the permissions `drwx------`. This means the elm executables will not be found on the PATH when running in user mode:

```
HackbookPro:~ alex$ elm --version
-bash: elm: command not found
HackbookPro:~ alex$ ls -la /usr/local/
total 0
drwxr-xr-x   3 root  wheel  102  5 Feb 23:27 .
drwxr-xr-x@ 10 root  wheel  340  5 Feb 23:27 ..
drwx------   7 root  wheel  238  5 Feb 23:30 bin
HackbookPro:~ alex$ ls -la /usr/local/bin
ls: bin: Permission denied
HackbookPro:~ alex$ sudo ls -la /usr/local/bin
Password:
total 85536
drwx------  7 root  wheel       238  5 Feb 23:30 .
drwxr-xr-x  3 root  wheel       102  5 Feb 23:27 ..
-rwxr-xr-x  1 root  wheel   2055692 11 Nov 02:46 elm
-rwxr-xr-x  1 root  wheel  15449760 11 Nov 02:46 elm-make
-rwxr-xr-x  1 root  wheel  11310156 11 Nov 02:46 elm-package
-rwxr-xr-x  1 root  wheel   7592372 11 Nov 02:46 elm-reactor
-rwxr-xr-x  1 root  wheel   7378676 11 Nov 02:46 elm-repl
HackbookPro:~ alex$ echo $PATH
/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
HackbookPro:~ alex$ sudo elm --version
0.18.0
```

 This directory should be created with the permissions 'drwxr-xr-x'. This will allow users to find the executables on their path.

**Comment by rtfeldman** [comment]
Interesting! I wonder if a lot of people aren't affected by this because `npm` installer does the same thing for global installs, and people have already fixed it for that directory?

**Comment by gac55** [comment]
I think I am in a similar position. I did a clean install on a new OSSierra build. `brew doctor` returns no errors. When I try to install a package: 

```
elm package install
-bash: /usr/local/bin/elm: Permission denied

```
Can anyone suggest a workaround?

**Comment by jvoigtlaender** [comment]
This should be an issue open over at https://github.com/elm-lang/elm-platform, not here in the compiler repo. @alexspurling, move it over?

**Comment by evancz** [comment]
I agree with @jvoigtlaender. Apple changed the permissions of that directory with one of the new OSes and it is not 100% clear what the alternative location should be. In any case, this is def an `elm-platform` thing, which is where all the installers live.
