### ISSUE TITLE
[0,18] Incorrect code generated by function inner binding shadowing...

### ISSUE THREAD

**Issue by GordonBGood** [elm-lang/elm-compiler#1564]
Reproducible with Try Elm 0.18 in any browser (Chrome 55, Firefox 51, latest Edge on Windows 10 tried).

The following code:
``` elm
import Html exposing (text)

outer () =
  let
    x = 42
    f y = x + y
  in
  let x = "7"
  in
    f 7

main =
  text (outer () |> toString)
```

produces "77" (a String) when it should produce 49 (a number).

The problem is that Elm doesn't really produce true closures for captured free variables as it doesn't usually have to worry about it **if** the bindings are immutable; however, it doesn't distinguish between shadowed bindings, linking them all to the same named JavaScript variable, in this case shadowed with something that even has a different type.  This is seen in the produced JavaScript code for "outer":
``` javascript
var _user$project$Temp1487015651361874$outer = function (_p0) {
	var _p1 = _p0;
	var x = 42;
	var f = function (y) {
		return x + y;
	};
	var x = '7';
	return f(7);
};
```
The workaround is to make "f" a true closure around the first "x" binding by changing the definition of "f" to as follows:
``` elm
    f = (\x -> (\y -> x + y)) x
```
which then produces the expected output of 49 (a number).

Having the compiler generate true closures automatically for all functions capturing free bindings that might change is expensive in run time, as creating a function within a function costs (in particular on current versions of Chrome, but also Firefox, not so much with Edge).  I suppose it could be done at some expense in compiler efficiency to create true closures only when bindings are shadowed, which would then only affect this case of shadowing.

Note that Elm already has a problem in not creating true closures when the closure is exported from a TCO'd loop where the captured free bindings appear to be immutable to the Elm code but are mutable variables in the created TCO'd JavaScript code loop; when required, the workaround is the same - manually create a true closure which has the advantage that one can choose the scope in which to create the closure for minimum run time impact.  However, this alternate case effect of not making a closure does not break code semantics as here, as although the value contained in the TCO'd loop exported non-closure function is not as expected when the function is applied, at least it will always be the expected type.  With the current issue, we could get many strange results, including (as here) unexpected type output.

The simplest solution to this is to strictly forbid binding shadowing, especially internal to a function.

Allowing internal binding shadowing by other means than using true closures would be quite complex as it would require the complexity of name mangling for re-bindings and keeping track of the validity of the mangled names in the generated JavaScript code.  Let's not go there!

**Comment by JoeyEremondi** [comment]
As far as I can tell, your code shouldn't compile, since f should have type
number->number and x has type String.

The so called pseudo type classes like number are pretty hacky, so I
wouldn't be surprised if this compiled because of a bug there.

**Comment by GordonBGood** [comment]
@JoeyEremondi, that's the point of the issue:  it does compile and it gives the wrong results when it compiles.

As to pseudo "super-types" like "number", it still compiles and runs to produce the wrong answer even when "f" is supplied with the following type signature:
``` elm
    f : Int -> Int
```
so it has nothing to do with super types.

This has to do with the compiler front end assuming that it is talking about the first value of "x", but the code generator is outputting the same binding "x" as the shadowed value (with a different type) as if JavaScript would know the difference, when of course it does not, in combination with that the Elm compiler does not issue closure functions (which have an execution cost as mentioned) assuming that it doesn't need to because bindings are immutable.

Shadowed bindings break that immutability, as does TCO'd loops due to their internal loop variables being mutated.

The second case isn't much of an issue as it is easy to work around by manually creating true closures when necessary, as mentioned; but this case is serious, as it breaks guarantied semantics.

It isn't as if we have to reuse binding names with a choice of gazillions to choose from, and we could make them much more descriptive than just "x" even to "x0" and "x1" (I believe I saw somewhen in a style guide that it is frowned upon to use one character binding names, or too short, or too non-descriptive).

As I said, the simplest and quickest fix for this is just to forbid binding shadowing, at least in the same scope, but maybe even of outer scopes if there are potential other problems there.  In this case, moving the topmost "let..in" into the outer (global) scope fixes the problem, as JavaScript does distinguish between variables of the same name in different scopes.

**Comment by jvoigtlaender** [comment]
In other words, @JoeyEremondi, look at the example again. The function f isn't applied to x, it is applied to 7. Which is of course a number. So your suggestion is wrong.

**Comment by evancz** [comment]
Shadowing is just not allowed in the next version, so my development build is showing the following error for your code:

```
-- SHADOWING ---------------------------------------------------------- temp.elm

The name `x` is first defined here:

11|     x = 42
        ^
But then it is defined AGAIN over here:

14|   let x = "7"
          ^
Think of a more helpful name for one of them and you should be all set!

Note: Linters advise against shadowing, so Elm makes “best practices” the
default. Read <https://elm-lang.org/hints/0.19.0/shadowing> for more details on
this choice.
```

So it is fixed one way or another!

**Comment by GordonBGood** [comment]
Not allowing shadowing is the preferred solution; glad it's going this way.

On Mar 7, 2018 07:52, "Evan Czaplicki" <notifications@github.com> wrote:

Shadowing is just not allowed in the next version, so my development build
is showing the following error for your code:

-- SHADOWING ---------------------------------------------------------- temp.elm

The name `x` is first defined here:

11|     x = 42
        ^
But then it is defined AGAIN over here:

14|   let x = "7"
          ^
Think of a more helpful name for one of them and you should be all set!

Note: Linters advise against shadowing, so Elm makes “best practices” the
default. Read <https://elm-lang.org/hints/0.19.0/shadowing> for more details on
this choice.

So it is fixed one way or another!

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/elm-lang/elm-compiler/issues/1564#issuecomment-370983325>,
or mute the thread
