### ISSUE TITLE
Proposal: local exposing

### ISSUE THREAD

**Issue by steinuil** [elm-lang/elm-compiler#1567]
When working with modules containing lots of different types and functions that could potentially clash with the ones defined in the current module and you don't really want to expose them all globally, I find that things tend to become very verbose.

I know you could just segregate the problem functions in another module and expose the stuff you need there, but then you'll have to worry about yet another module and it's just annoying.

OCaml [has syntax](https://caml.inria.fr/pub/docs/manual-ocaml/extn.html#sec224) for "opening" a module (i.e. exposing all its exported functions and types) locally to an expression:
```OCaml
let average x y =
    let open Int64 in
    x + y / of_int 2
```
Is there any interest in having something similar in Elm?

It could be its own thing and look like a let expression:
```Elm
f =
  expose (List(..)) in
    map negate [ 1, 2, 3, 4 ]

type alias Player =
  expose (Dict(Dict)) in
    { name : String
    , attributes : Dict
    }
```
Or maybe a special construct that can only be used in let expressions:
```Elm
f =
  let
    expose (List(..))
  in
    map negate [ 1, 2, 3, 4 ]
```
I know it's additional syntax and thus not a very welcome addition to the language, but I can't see a way to do this with existing syntax.

**Comment by mgold** [comment]
This is a topic for the [mailing list](https://groups.google.com/forum/#!forum/elm-discuss).

**Comment by steinuil** [comment]
Ah ok, I'll send it there then.
