### ISSUE TITLE
Another pattern matching space leak

### ISSUE THREAD

**Issue by danielbarter** [elm-lang/elm-compiler#1568]
Hi there,

I am working on a project and getting the error `elm-make: out of memory (requested 1048576 bytes)`. That is a lot of memory! [Here is a stripped down example which causes the issue](https://gist.github.com/danielbarter/7029fce98c8878c6fd9e717bc072ef22). I am using Linux and elm 0.18.

**Comment by danielbarter** [comment]
OK, so breaking the example up in to nested case expressions solves the issue. I'm sure you know about this issue already, so feel free to close.

**Comment by evancz** [comment]
I think this is a duplicate of #1362 which will be a lot nicer in 0.19. Sorry you are running into it for now!
