### ISSUE TITLE
Compiler should check for duplicates in record's property name

### ISSUE THREAD

**Issue by psyCodelist** [elm-lang/elm-compiler#1570]
In elm 18, you can create a record like this:

```elm
type alias State =
    { title : String
    , forms : Forms.State
    , forms : Forms.State
    }
```

this will work on all modern browsers except IE 11 and below. It will generate the following Javascript  run time error:

"Multiple Definitions of a Property Not Allowed in Strict Mode".

**Comment by decioferreira** [comment]
Just for reference, running the generated Javascript in this situation on "PhantomJS 2.1.1" will output: `SyntaxError: Unexpected token ','`

**Comment by evancz** [comment]
In my development build, I get the following error:

```
-- NAME CLASH --------------------------------------------------------- temp.elm

This record has multiple `forms` fields. One here:

6|     , forms : Forms.State
         ^^^^^
And another one here:

7|     , forms : Forms.State
         ^^^^^
How can I know which one you want? Rename one of them!
```

So it should be fixed in the next release. Thank you for the report!
