### ISSUE TITLE
Let expression indentation sensitivity

### ISSUE THREAD

**Issue by erizocosmico** [elm-lang/elm-compiler#1573]
According to the [syntax docs](http://elm-lang.org/docs/syntax) let expressions are indentation sensitive 

> Let-expressions are indentation sensitive, so each definition must align with the one above it.

I was trying the following in [elm-lang.org/try](http://elm-lang.org/try) and I was surprised it parsed (and worked).

```elm
foo = let
  bar = 
 5
 in
 5
```

I'm not sure if this is a bug in the parser that's not following the "spec" or the syntax documentation is outdated and let expressions are no longer indentation sensitive, but I thought it was important to raise the issue because either the parser or the documentation should be updated accordingly.

**Comment by itsgreggreg** [comment]
As I understand it, it's just the definitions that have to be aligned. Everything else can be sort of willy nilly as long as you're one column in.

```elm
import Html exposing (text)
foo = let
                    bar = 
 5
                    baz = 7
 in
 baz + bar 
main =
  text <| toString foo
```

**Comment by evancz** [comment]
In the next release, it will be required that each level of nesting is more indented than the last, so you won't be able to write the body of a definition before the name.

But yeah, the indentation is about aligning `bar` and `baz`, not their definitions.
