### ISSUE TITLE
Using `_Tuple` constructors results in runtime error

### ISSUE THREAD

**Issue by SelectricSimian** [elm-lang/elm-compiler#1574]
Elm version 0.18.0

If an Elm program tries to explicitly use the constructor `_Tuple2`, it will compile without error but will crash at runtime.

```elm
val = _Tuple2 "foo" "bar"
```

The Javascript error is that the variable `_Tuple2` does not exist.  It appears that the Elm compiler is generating JS for this situation as if it were a call to the nonexistent `_Tuple2` function, instead of a constructor application. (i.e., generating `A2(_Tuple2, "foo", "bar")` instead of `{ctor: '_Tuple2', _0: "foo", _1: "bar"}`)

**Comment by rtfeldman** [comment]
SSCCE: (this compiles and then throws a runtime exception)

```
module Main exposing (..)

import Html exposing (Html, text)

main : Html a
main =
    text (toString <| _Tuple2 "foo" "bar")
```

**Comment by evancz** [comment]
This does not parse in the 0.19 code I am working with. Thanks for the report!
