### ISSUE TITLE
Compiler should optimize toString calls with constant arguments

### ISSUE THREAD

**Issue by YetAnotherMinion** [elm-lang/elm-compiler#1578]
When I use a union type to represent CSS classes, I need to turn that union type label into a `String` to construct `VirtualDom` nodes. I would expect the compiler to recognize that when I write `  class <| toString SomeClassName` that it should be replaced with `class "SomeClassName"` in the compiled output because the function argument is constant.

## SSCCE
```elm
import Html exposing (beginnerProgram, div, text)                        
main =                                                                          
  beginnerProgram { model = 0, view = view, update = update }

view model =                                                                    
  div [] [ text <| toString NoOp ]                                              
                                                                                
type Msg = NoOp
update msg model =                                                              
  case msg of                                                                   
    NoOp ->                                                                     
      model 
```

Generated code insists on calling toString every time
```js
var _user$project$Main$NoOp = {ctor: 'NoOp'};                                  
var _user$project$Main$view = function (model) {                                
    return A2(                                                                  
        _elm_lang$html$Html$div,                                                
        {ctor: '[]'},                                                           
        {                                                                       
            ctor: '::',                                                         
            _0: _elm_lang$html$Html$text(                                       
                _elm_lang$core$Basics$toString(_user$project$Main$NoOp)),       
            _1: {ctor: '[]'}                                                    
        });                                                                     
};
```

`java -jar ~/bin/closure-compiler --language_out ECMASCRIPT5 --js foo.js --compilation_level SIMPLE --js_output_file bar.js`
The closure compiler fails to optimize the JS produced by elm compiler because the generated JS is too complicated. The long variable name for the type `NoOp` has been simplified to `Jb`, and `toString` has been renamed to `X`, but that is it. The function call still occurs.
```js
var Jb = {
ctor: 'NoOp'
},
/*...*/
view: function (a) {
return r(Ib, {
ctor: '[]'
}, {
ctor: '::',
_0: Gb(X(Jb)),
_1: {
ctor: '[]'
}
})
}
```

## Why this behavior is bad.
The google closure compiler cannot optimize objects that are passed into toString because toString uses an `in` expression (ex: `'property' in someobject`). Because the closure compiler will never change string literals, object properties cannot be renamed because the closure compiler does not understand the `in` expression refers to a property name. This means we can only use the SIMPLE level of optimization which does not rename properties with elm programs.

## Why the constant argument optimization is helpful
It is much easier to write a tool to deduplicate string literals by lifting the string into a variable than it is to parse the javascript into an AST and determine when functions have constant arguments.   A post processing tool like the google closure compiler has no prior knowledge of elm's `{ctor:"someString"}` or {_0: "something", _1: "something"}` format for types. Performing this optimization inside the elm compiler not only prevents us from having to construct an AST twice, but also makes available the type information directly.

## Version information
```bash
$ elm --version
0.18.0

Closure Compiler (http://github.com/google/closure-compiler)
Version: v20170124
Built on: 2017-01-27 11:44
```

### Note
I can implement this optimization.

**Comment by evancz** [comment]
This kind of thing can be achieved with optimizations like "constant propagation" that can do some reductions at compile time. To do this in a way that is actually healthy for the compiler is a large project though.

I'd prefer to close this because optimizations will only come as part of a larger project, and I don't think it makes sense to track a multi-week or multi-month project here, especially if it is not being worked on at the moment.
