### ISSUE TITLE
Unable to generalize a type variable. It is not unranked.

### ISSUE THREAD

**Issue by j-hotlink** [elm-lang/elm-compiler#1579]
Using Elm 0.18, running elm-reactor hosted inside a docker container

When visiting the file Test.elm, the Elm reactor responds with this message:

> elm-make: It looks like something went wrong with the type inference algorithm.
> 
> Unable to generalize a type variable. It is not unranked.
> 
> Please create a minimal example that triggers this problem and report it to
> <https://github.com/elm-lang/elm-compiler/issues>
> elm-make: thread blocked indefinitely in an MVar operation

Minimal reproducible file Test.elm is:

<pre>
import Http exposing ( .. )
import Json.Decode as Decode exposing( Decoder )

connect : ( a -> msg ) -> String -> Cmd msg
connect tagger url =
    Http.send ( tagger ( getConnectionRequest url ) )

getConnectionRequest : String -> Http.Request Bool
getConnectionRequest url =
    Http.get url decodeConnection

decodeConnection : Decoder Bool
decodeConnection =
    Decode.succeed True
</pre>

The code itself is likely incorrect / invalid (unverified), however the error message is unexpected.

**Comment by jvoigtlaender** [comment]
See https://github.com/elm-lang/elm-compiler/issues/1569

**Comment by evancz** [comment]
I am tracking this in #1613 to get a high-level view of what's going wrong here.

Thank you for the SSCCE!

**Comment by evancz** [comment]
Based on 4b25980d93ada12236c794f35570e197be82f787, this is now producing normal error messages:

![screen shot 2018-03-06 at 2 21 15 pm](https://user-images.githubusercontent.com/1658058/37061889-bfb12f4c-2149-11e8-94e8-adf9bb8dbaf4.png)

Thank you for the report!
