### ISSUE TITLE
number is not comparable

### ISSUE THREAD

**Issue by zwilias** [elm-lang/elm-compiler#1581]
## Fails

```elm
five : number
five =
    5

isSmallerThanFive : number -> Bool
isSmallerThanFive number =
    number < five
```

results in

```
-- TYPE MISMATCH ------------------------------------------ src/Basics/Extra.elm

The left argument of (<) is causing a type mismatch.

49|     number < five
        ^^^^^^
(<) is expecting the left argument to be a:

    comparable

But the left argument is:

    number

Hint: Only ints, floats, chars, strings, lists, and tuples are comparable.
```

## Alternatives that do work:

Flipping the args
```elm
five : number
five =
    5

isSmallerThanFive : number -> Bool
isSmallerThanFive number =
    five > number
```

Doing something with the arg first
```elm
five : number
five =
    5


isSmallerThanFive : number -> Bool
isSmallerThanFive number =
    (number + 0) < five
```

Inlining the other number (?)
```elm
isSmallerThanFive : number -> Bool
isSmallerThanFive number =
    let
        five : number
        five =
            5
    in
        number < five
```

**Comment by jvoigtlaender** [comment]
Isn't this a duplicate of https://github.com/elm-lang/elm-compiler/issues/1281, which is already recorded in https://github.com/elm-lang/elm-compiler/issues/1373?

**Comment by zwilias** [comment]
You're correct. Sorry for the dupe!

**Comment by evancz** [comment]
No need to be sorry @zwilias! As I outline in [this thread](https://www.reddit.com/r/elm/comments/628efv/avoiding_slowdown_when_using_the_debugger/), duplicate issues are always better than comments on existing issues.

Your [SSCCE](http://sscce.org/) looks clearer to me than the ones referenced by @jvoigtlaender, and I added it to the meta issue!

@jvoigtlaender, can you just note that it belongs in the meta issue? I feel like you often kind of passively aggressively suggest that the poster has done something wrong by creating a nice issue that is clear and helpfel.

**Comment by jvoigtlaender** [comment]
No passive aggression from my side.

**Comment by zwilias** [comment]
No passive agression or confrontation experienced on this side, I understand @jvoigtlaender is just triaging and happens to have an almost academical knowledge of open issues. Since dupes are preferred over comments, it makes sense to at least ensure they're cross-referenced.
