### ISSUE TITLE
 Unable to generalize a type variable. It is not unranked.

### ISSUE THREAD

**Issue by seanastephens** [elm-lang/elm-compiler#1582]
Using `elm-make 0.18 (Elm Platform 0.18.0)` on Ubuntu 14.04, running `elm-make test.elm` produces the following:

```
elm-make: It looks like something went wrong with the type inference algorithm.

Unable to generalize a type variable. It is not unranked.

Please create a minimal example that triggers this problem and report it to
<https://github.com/elm-lang/elm-compiler/issues>
elm-make: thread blocked indefinitely in an MVar operation
```

Here is `test.elm`, as small as I could make it.

```Elm
module Test exposing (..)


type alias T =
    Int


g : T -> List T
g =
    [ "Blah" ]


f : a
f =
    g 1
```

**Comment by jvoigtlaender** [comment]
This looks to be a smaller example of the problem reported also in https://github.com/elm-lang/elm-compiler/issues/1579. @evancz

**Comment by amigalemming** [comment]
I got this error, too, when using a type variable in a type signature, where the implementation required a specific type.

**Comment by evancz** [comment]
Tracking in #1613 to get a high-level picture of the problem. Thanks for the report!

**Comment by evancz** [comment]
Based on commit 4b25980d93ada12236c794f35570e197be82f787, I am now seeing the following error in my development build!

![screen shot 2018-03-06 at 1 39 40 pm](https://user-images.githubusercontent.com/1658058/37060007-dd89a69e-2143-11e8-8c49-a5601151ed5f.png)

> **Note:** You may see extra qualifiers on types in this error. That is part of the dev build, but should not appear in the final thing.
