### ISSUE TITLE
Unable to generalize a type variable. It is not unranked.

### ISSUE THREAD

**Issue by JonathanFraser** [elm-lang/elm-compiler#1595]
Elm version 0.18 on windows
[working example](https://pastebin.com/FNkE0Zgz)
[erroring example](https://pastebin.com/csrfK49X)

Attempting to compile the erroring example gives the title specified error. Correcting a true bug in the code (correctly wrapping and unwrapping context) gets rid of the error. The error from the compiler appears not at all related to the actual compile issue. 

Edit: excuse the import Model, I stripped the depenency on it but failed to delete it.

**Comment by evancz** [comment]
I am consolidating all the examples in #1613, so it is easier to find them all.

**Comment by evancz** [comment]
The unranked issue is resolved by 4b25980d93ada12236c794f35570e197be82f787, but there are other things going on I think. Will look harder.
