### ISSUE TITLE
Runtime Error: period in repository name in elm-package.json

### ISSUE THREAD

**Issue by mdgriffith** [elm-lang/elm-compiler#1597]
A project will build but fail at runtime with `Uncaught SyntaxError: Unexpected token .` if the repository name contains a period such as `https://github.com/mdgriffith/elm.style.git`

So, any project that uses this `elm-package.json`:

```json
{
    "version": "1.0.0",
    "summary": "The elm.style website",
    "repository": "https://github.com/mdgriffith/elm.style.git",
    "license": "BSD3",
    "source-directories": [
        "."
    ],
    "exposed-modules": [
    ],
    "dependencies": {
        "elm-lang/core": "5.0.0 <= v < 6.0.0",
        "elm-lang/html": "2.0.0 <= v < 3.0.0"
    },
    "elm-version": "0.18.0 <= v < 0.19.0"
}

```

## Versions

 * `elm` 0.18
 * __OS__: OSX 10.11.6, El Capitan
 * __Browser__: Chrome, Firefox

**Comment by evancz** [comment]
With 0.19 project names with dots will be ruled out much earlier, so it won't get to this point anymore. Thanks for the report!
