### ISSUE TITLE
Make it possible to refer to (* -> *) types

### ISSUE THREAD

**Issue by zwilias** [elm-lang/elm-compiler#1598]
The following examples compile without error:

### Alias missing type variable
```elm
type alias Foo = List
```
(I don't believe one cannot actually construct a value of that type)

### Function annotation missing type variable
```elm
foo : List -> String
foo _ = "foo"
```
(Function cannot be used)

## Expected:

I would expect an error along the lines of what you get for the following:

```elm
type alias Foo a = a
type alias Bar = Foo
```

```
Type Main.Foo has too few arguments.
Expecting 1, but got 0.
```

**Comment by amigalemming** [comment]
`List` is a type constructor and it is perfectly ok to have a type constructor synonym like `Foo`.

**Comment by zwilias** [comment]
@amigalemming Perhaps I'm missing something. What is the use or sense of referring to a non-nullary type constructor as if it were a nullary type constructor? Functions and aliases declared that way compile just fine, but cannot be used, or can they?

**Comment by amigalemming** [comment]
On Tue, 30 May 2017, Ilias Van Peer wrote:

> @amigalemming Perhaps I'm missing something. What is the use or sense of referring to a non-nullary type
> constructor as if it were a nullary type constructor? Functions and aliases declared that way compile just fine,
> but cannot be used, or can they?

They can be used in another type alias, like so:

type alias Bar = Foo String

or in a function:

f : Foo String -> String

E.g. you may want to give List an application specific name.

**Comment by zwilias** [comment]
Neither one of those examples compiles. 

Elm only lets you do that if you make an alias for the type constructor including its argument types. (i.e. `type alias Foo a = List a`)

**Comment by amigalemming** [comment]
On Tue, 30 May 2017, Ilias Van Peer wrote:

> Neither one of those examples compiles.

I see. I have not tried. Just inferring from how it works in Haskell. 
Functions containing a plain type constructor in the type signature should 
not be compilable. At first, I was uncertain what you meant with "function 
cannot be used".

**Comment by evancz** [comment]
I do not plan to make this possible. I think it is clearer to say `type alias Foo a = List a` instead, and I'm not sure what benefit you really get from leaving the type variable off.

**Comment by amigalemming** [comment]
On Wed, 1 Nov 2017, Evan Czaplicki wrote:

> I do not plan to make this possible. I think it is clearer to say type 
> alias Foo a = List a instead, and I'm not sure what benefit you really 
> get from leaving the type variable off.

Type constructor synonyms can be useful for types that have type 
constructors as arguments. E.g. consider the type-level constructor 
composition:

type Compose f g a = Compose (f (g a))

Then you can write 'Compose Foo Maybe' only if Foo is defined as type 
constructor (type alias Foo = List), but not if Foo is defined as type 
with parameters (type alias Foo a = List a).

**Comment by evancz** [comment]
Requests for higher-kinded polymorphism are logged in #1039. I understand the broader uses, but that does not seem to be relevant to the request by OP.

**Comment by evancz** [comment]
The cases listed by OP look like this in the development branch:

```
-- TOO FEW ARGS ------------------------------------------------------- temp.elm

The `List` type was given 0 arguments:

9| type alias Foo = List
                    ^^^^
But it needs 1 argument. What is missing? Are some parentheses misplaced?
```

```
-- TOO FEW ARGS ------------------------------------------------------- temp.elm

The `List` type was given 0 arguments:

9| foo : List -> String
         ^^^^
But it needs 1 argument. What is missing? Are some parentheses misplaced?
```

Kind errors like this are ruled out in the canonicalization phase now.
