### ISSUE TITLE
Unable to run JS code inside event handler (ports or native)

### ISSUE THREAD

**Issue by vankeisb** [elm-lang/elm-compiler#1599]
Hi !

(Sorry if this is not the appropriate place to file this bug. It's more a runtime problem than compilation.)

Both ports and native JS code seems to be executed outside of the event handler function, in a timeout. 

This can be a problem, as the browser doesn't allow everything to be done outside the handler for security reasons. We found this problem on Firefox, when using `document.execCommand('copy')`.

Eventually, we had to resort to `attribute "onclick" "javascript:thisIsUgly()"` for it to work. Hopefully, it worked in our scenario ("copy to clipboard" button), but it could be a problem in more complex use cases, and it seems like a real limitation. The only one we actually found in Elm, hence the bug report.

**Comment by evancz** [comment]
Tracking this general issue over at https://github.com/elm-lang/virtual-dom/issues/108

Thanks for the report!
