### ISSUE TITLE
Feature: Not equal to be /= or unicode ≠

### ISSUE THREAD

**Issue by donpdonp** [elm-lang/elm-compiler#1604]
After hitting the oddity of != not being available, then reading how /= likely represents the "written" math of equals with a slash, it'd be slick if elm would accept the unicode slash-equals.

**Comment by evancz** [comment]
I would rather not track feature request in issues. I agree it would be cool, but the better way to achieve this may be to use an editor that allows "ligatures" of certain symbols. I have seen folks with ligatures for `|>` and `->` and this seems like a reasonable addition to that set. I'd ask around on the Elm slack to learn more about this.
