### ISSUE TITLE
Type inference error with type variables in let

### ISSUE THREAD

**Issue by YusukeTakeuchi** [elm-lang/elm-compiler#1607]
I'm using Elm 0.18.
This code raises a type inference error. It compiles without the annotation of app or with that of id.

```elm
-- id : (Int -> a) -> Int -> a
id f =
  let
    app : Int -> a
    app v = f v
  in
    app

```

```
elm-make: It looks like something went wrong with the type inference algorithm.

Unable to generalize a type variable. It is not unranked.
```

**Comment by evancz** [comment]
Tracking in #1613 so it is easier to get an idea of what might be causing this.

Thanks for the great report!

**Comment by evancz** [comment]
Based on commit 4b25980d93ada12236c794f35570e197be82f787, this code is going through without errors on my development build!
