### ISSUE TITLE
Compiler Error: Unable to generalize a type variable. It is not unranked.

### ISSUE THREAD

**Issue by emblem** [elm-lang/elm-compiler#1609]
SSCCE

```
type alias A = {}

aFn : A -> ()
aFn a = ()
           
testFn : a -> ()
testFn a =
    let
        foo = aFn a
    in
        ()
```

Elm 0.18, Ubuntu 16.04.

Output:

```
elm-make Bug.elm --yes --warn --output\=elm.js
[                                                  ] - 0 / 1elm-make: It looks like something went wrong with the type inference algorithm.

Unable to generalize a type variable. It is not unranked.

Please create a minimal example that triggers this problem and report it to
<https://github.com/elm-lang/elm-compiler/issues>
elm-make: thread blocked indefinitely in an MVar operation

Elm-Compile exited abnormally with code 1 at Mon Jul  3 17:07:13
```

**Comment by evancz** [comment]
I am consolidating all the examples in #1613, so it is easier to find them all.

This example is great. Thank you!

**Comment by evancz** [comment]
Based on commit 4b25980d93ada12236c794f35570e197be82f787, I am now seeing the following error in my development build!

![screen shot 2018-03-06 at 1 37 43 pm](https://user-images.githubusercontent.com/1658058/37059926-98161dc2-2143-11e8-8d99-84ee5c0aeb1a.png)

> **Note:** You may see extra qualifiers on types in this error. That is part of the dev build, but should not appear in the final thing.
