### ISSUE TITLE
More module system bugs

### ISSUE THREAD

**Issue by netogallo** [elm-lang/elm-compiler#161]
I have three files Main.elm Mod/Foo.elm Mod/Bar.elm with the following contents:

Main.elm:

```haskell

import Mod.Bar(foo)

main = text foo
```

Mod/Bar.elm:

```haskell

module Mod.Bar(foo) where

import Mod.Foo(foo)
```

Mod/Foo.elm

```haskell
module Mod.Foo(foo) where

foo = toText "foo"
```

This program would work with Haskell, but Elm does not accept the file Bar.elm since it only has imports. I guess this should be changed. Now if we change the file Bar.elm to:

```haskell

module Mod.Bar(foo) where

import Mod.Foo(foo)

dummy = "dummy"
```

The program compiles but the output is undefined. Based on the Haskell like behavior, the foo function should get called, and if not, the compiler should at least throw an error. For this to work, Bar.elm has to be changed to:

```haskell
module Mod.Bar(foo) where

import Mod.Foo(foo)

foo = Mod.Foo.foo
dummy = "dummy"

```

I wanted to try fixing this issues, so I post here to make sure they are issues and that they should be fixed the way I propose.

**Comment by evancz** [comment]
Moving this to #931
