### ISSUE TITLE
Elm reactor cuts leftmost columns of long error messages

### ISSUE THREAD

**Issue by drathier** [elm-lang/elm-compiler#1617]
When running elm-reactor 0.18.0 in Safari 10.1.2 on OSX 10.11.6 with a syntax error on a very long line, the leftmost columns of the errors message gets cut off when using a small screen, while the rightmost columns end up outside of the right edge of the screen.

```
Detected errors in 1 module.


-- SYNTAX PROBLEM ------------------------------------------ ./src/Model/Box.elm

I ran into something unexpected when parsing your code!

89| {-| Disconnect two boxes from each other. The Slot in the `from` argument is the output of that box, and the Slot in the `to` argument is the input of the receiving box.
       ^
I am looking for one of the following things:

    whitespace
```

This is what it looks like when scrolling past the left/right/top side of the screen. The black background is 100% of the width/height of the screen in both images. As you can see, the rightmost columns are just off screen, while the leftmost are cut off completely.

![skarmavbild 2017-07-20 kl 18 16 08](https://user-images.githubusercontent.com/3695812/28427762-91ce8646-6d77-11e7-99e7-85e757283ebf.png)
![skarmavbild 2017-07-20 kl 18 16 57](https://user-images.githubusercontent.com/3695812/28427789-a435cd44-6d77-11e7-916c-96e29bd421dc.png)

**Comment by evancz** [comment]
I believe this is already reported in the elm-reactor repo. If you cannot find the report there, it may be worthwhile to open an issue there.
