### ISSUE TITLE
Non-descriptive error when encountering a typeclass mismatch

### ISSUE THREAD

**Issue by JonathanFraser** [elm-lang/elm-compiler#1619]
Example [code](https://ellie-app.com/3QMbpGBGkZqa1/2)

The problem here is that the user is trying to define a Set of items which are not comparable. This is of course not allowed. However, the error message given does not provide any indication of that. 

```
The right side of (|>) is causing a type mismatch.
(|>) is expecting the right side to be a:

Json.Decoder (List (List Selection)) -> a

But the right side is:

Json.Decoder (List (List Selection)) -> Json.Decoder (Set (List Selection))

Hint: With operators like (|>) I always check the left side first. If it seems
fine, I assume it is correct and check the right side. So the problem may be in
how the left and right arguments interact.
```

According to the error message the code appears to be correct.

**Comment by evancz** [comment]
I think this would be a better fit for https://github.com/elm-lang/error-message-catalog

Do you mind retargeting it there?

And can you put the code directly in the issue? If I'm changing the compiler I cannot test it in Ellie.
