### ISSUE TITLE
Feature: Or pattern in case .. of

### ISSUE THREAD

**Issue by qwfy** [elm-lang/elm-compiler#1620]
OCaml has this feature called "Or pattern", where

    match some_variable with
    | A | B | C -> some_value
    | D -> another_value

is the same with

    match some_variable with
    | A -> some_value
    | B -> some_value
    | C -> some_value
    | D -> another_value

It's handy when you have a large-ish sum type and you only interested in one or two of them. (The wildcard pattern would make exhaustive check useless). And it doesn't break the existing syntax.

**Comment by evancz** [comment]
I'm familiar with this feature in OCaml, and I understand the benefit for exhaustiveness checking.

I prefer not to track requests for language features in github issues, but I will consider this along with some other pattern matching ideas like `{ x = Just y }` so you can match inside fields.
