### ISSUE TITLE
Can't compile when multiple packages export same name modules

### ISSUE THREAD

**Issue by fdbeirao** [elm-lang/elm-compiler#1626]
I am using ELM Platform 0.18.0.

I am trying to create an application that will use both a `<canvas>` for arbitrary rendering and some HTML elements to feed information into the model.

`elm-graphics` provides great functions to deal with `<canvas>`.
`style-elements` provides a good abstraction on how to layout HTML elements.

These two concerns are not mutually exclusive: I am not going to build my entire application using `<canvas>`, and I want to be able to structure my (HTML) layout in a way that doesn't require so much depth in CSS knowledge.

Steps to reproduce:
```
mkdir SameNameModules
cd SameNameModules
elm package install evancz/elm-graphics
elm package install mdgriffith/style-elements
```

Write the following into a new file `main.elm`:
```
module Main exposing (main)

import Element

```

Once you run `elm make`, you will get the error:
```
I found multiple modules named 'Element'.

Module 'Main' is trying to import it.

Modules with that name were found in the following locations:

    package evancz/elm-graphics
    package mdgriffith/style-elements
```

I would suppose the solution would be to support namespaces when there are these kinds of clashes.

`elm-package.json` doesn't explicitly support this concept.

Enforcing the default namespace to be the user's github account, could only somewhat mitigate the problem. Imagine the case that the same user exposes two highly useful packages which end up exposing a module with a common name. This makes me think that a combination of the username + package name would be a good candidate for disambiguation.

### Happy path
No packages have naming clashes. Everything stays the same.

### Package clash scenario 1
I import two packages from two *different users*. These packages export modules with have the same names.

Proposed solution would be to use the username as a "namespace":

```
import evancz.Element as CanvasElements
import mdgriffith.Element as LayoutElements
```

### Package clash scenario 2
The *same user* has published two packages, which contain modules with the same name. 

Each package name is unique per user, so we can use the package name as a "namespace":
```
import package1.ConflictingModule as ModuleForX
import package2.ConflictingModule as ModuleForY
```

### Package clash scenario 3
This is a combination of scenario 1 and 2. Highly unlikely situation, yet not impossible. We import *three* packages, and they all export a module called `Element`. One of them relates to canvas, another relates to layout (fictitious package `htmllayout`) and the other relates to (let's say) music (fictitious package `music`). **Both the `htmllayout` and `music` packages come from the same author.** For this scenario, the import would look like this:

```
import evancz.Element as CanvasElements
import htmllayout.Element as HtmlElements
import music.Element as MusicElements
```

This is related to issue #1625

**Comment by evancz** [comment]
Thanks, now I refer to this in https://github.com/elm-lang/elm-compiler/issues/1625 so more details are available about why you wanted that combination.
