### ISSUE TITLE
Strings should use locale when comparing

### ISSUE THREAD

**Issue by perty** [elm-lang/elm-compiler#1627]
Strings are one of the types in Elm that are comparable. However, you can not really compare
strings if you do not know the locale. That is why other languages let you supply the locale when you compare strings.

E.g. in JavaScript:
‘abc’.localeCompare(‘def’, ‘sv’);

AFAIK it is not simple to write a custom comparing function that compares two strings with a given locale.

Here is an example of how this is a problem in Elm.

We have a list of strings:
`ex = ["östen" , "Arne", "Åke", "Göran", "Gunnar", "Ängel", "Östen", "arne"]`

When sorting them we get a weird result, given that the strings are Swedish names.

`List.sort ex`
`["Arne","Gunnar","Göran","arne","Ängel","Åke","Östen","östen"] : List String`

The lower case “a” (4th element) pops up in the middle and the name “Åke” is placed after “Ängel”, which is also incorrect.

My **suggestion** is that string should be an abstraction for strings with different locales, like number is an abstraction for integers and floats. Thus it would be possible to construct strings and give them a locale that would be used when handling them. The locale would be used when handling the strings. E.g. sorting and line breaking, both are locale dependent.

The challenge is how much you can control during compile time. Often you would like to determine the locale of a string in run-time. But how can the compiler know that you are nor comparing strings of different locales then? It is probably quite possible to do that. The compiler would only ensure that the strings are of the same locale but not know which locale. The locale could thus not be given as a string, like in JavaScript. It would need to be more controlled than that.

I am new to filing issues so please bear with me if this is not up to standard.

**Comment by perty** [comment]
The Swedish was of course just an example on how problematic this is. 

After considering this a bit more, I agree that it is probably too hard to solve in compile time.

**Comment by evancz** [comment]
Is there any language that works like you suggest? If there is no precedent, I'd be more confident closing it for now. (It will be possible to revisit if we ever have our own `String` implementation.)

**Comment by zwilias** [comment]
The "correct" order of strings depends on locale, not codepage/charset. 

Example:
- in Swedish, `ä` comes _before_ `z`
- in German, `ä` comes _after_ `z`

The default sorting (which we're currently doing) is just comparing unicode codepoints.

**Comment by perty** [comment]
It works fine in JavaScript, if you supply the locale, as said in the OP. All languages that I know of has an initial approach of just sorting using codepoints and then giving you an option to supply a locale to get a sorting that is useful for human consumption. In Java you create a Collator and supply it to the sort function.

`Collections.sort(words, Collator.getInstance(locale));`

So it is more like a bolt-on with libraries. Elm could do the same but I was intrigued by the idea of having the locale as a guide to interpret a string (the suggestion). Without locale, a string is just an array of codepoints.  There is more to this than sorting, of course . You can't do word or line breaks properly without knowing the locale. You don't know if you should print from right to left or vice versa, either.

**Comment by SwiftsNamesake** [comment]
JavaScript also has a devoted localised comparison method, as it turns out. Docs [here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/localeCompare#Sort_an_array).

**Comment by evancz** [comment]
It cannot be the default behavior. Elm gives the guarantee on functions of "same input, same output" and where the code is running cannot change that.

A viable API would be:

```elm
getLocale : Task Never Locale
String.compare : Maybe Locale -> Sting -> String -> Order
```

Is there a way to get the locale as data? Are there other things you'd want to use locale for?

**Comment by evancz** [comment]
I am going to close because this proposal is not viable right now.

That said, let's continue gathering information here. Figure out if the API I suggested is possible. If so, we can track it on the `elm-lang/core` repo. (Though in the end it probably would be in a separate package.)

**Comment by SwiftsNamesake** [comment]
@evancz Yes, I said the very same thing at the outset:

> It would also have the disadvantage of breaking referential transparency, which is obviously one of Elm's major selling points.

The OP also suggested closing, but for a different reason it seems.

Everyone seems to be in agreement regarding the original issue. Maybe we should close this one and open a separate one for locales specifically.

Your response indicates that there isn't any built in support for locales at the moment, so there's potentially a whole array of issues to hash out.

Thank you for bringing FP to the web, btw.
