### ISSUE TITLE
Module name collisions of this and external packages

### ISSUE THREAD

**Issue by nukisman** [elm-lang/elm-compiler#1628]
I have 3 implementations of memoization (module Memo):
Written by me in ./src/Memo.elm
From repository package jvoigtlaender/elm-memo
From repository package ktonon/elm-memo-pure

I wanted to compare performance of these implementation in current project but got the compiler error:
```elm
./src/Sandbox.elm
Module build failed: Error: Compiler process exited with error Compilation failed
I found multiple modules named 'Memo'.

Module 'Sandbox' is trying to import it.

Modules with that name were found in the following locations:

    directory ./src/Memo.elm
    package jvoigtlaender/elm-memo
    package ktonon/elm-memo-pure
```
Related issue: #1625

**Comment by quangv** [comment]
@nukisman can you use `as` ? (I'm new to elm so I probably do not understand the problem.)

**Comment by evancz** [comment]
Logged in #1625. Thanks for the report!
