### ISSUE TITLE
Unable to generalize a type variable. It is not unranked - From typed argument, to polymorphic, to typed

### ISSUE THREAD

**Issue by JoshSmithCode** [elm-lang/elm-compiler#1633]
This code works fine.
[working ellie](https://ellie-app.com/4498NqGCjX9a1/0)

This does not.
[busted ellie](https://ellie-app.com/4498NqGCjX9a1/1)

**Elm version 0.18**

The difference is in the polymorphic argument in `func2`'s annotation.
Going from a known type to a polymorphic type and back to a known type seems to cause an issue with the type inference algorithm.

> It looks like something went wrong with the type inference algorithm. 
Unable to generalize a type variable. It is not unranked.

**Note** - This only happens when the known type is a type alias, swapping `Person` for a `Bool` for example doesn't cause the issue.

This is most likely relevant to #1613

**Comment by evancz** [comment]
Tracking in #1613. Thanks for the report!

**Comment by evancz** [comment]
Based on commit 4b25980d93ada12236c794f35570e197be82f787, I am now seeing the following error in my development build!

![screen shot 2018-03-06 at 1 53 06 pm](https://user-images.githubusercontent.com/1658058/37060639-be03d496-2145-11e8-8603-0ec1df748a03.png)

> **Note:** You may see extra qualifiers on types in this error. That is part of the dev build, but should not appear in the final thing.
