### ISSUE TITLE
Inconsistent compiler behaviour, adding an identity function leading to different outcome

### ISSUE THREAD

**Issue by FRosner** [elm-lang/elm-compiler#1636]
### Problem

When a locally bound function and a global function have the same name `f`, then using it as `f ()` or `(identity f) ()` yields different results.

### Context

I was trying to implement an ADT representing a circular list. This is what I had so far:

```
module CircularList exposing (CircularList(..), get, next)


type CircularList a
    = CircularList { val : a, next : () -> CircularList a }


get : CircularList a -> a
get (CircularList { val, next }) =
    val


next : CircularList a -> CircularList a
next (CircularList { val, next }) =
    -- it doesn't work when I just do "next ()"???????
    (Debug.log "next" next) ()
```

It works as expected and the following test case is green:

```
test "get" <|
            \() ->
                let
                    s =
                        "bla"

                    a =
                        CircularList { val = s, next = \() -> a }
                in
                    Expect.equal s (CircularList.get (CircularList.next a))
```

However as soon as I remove the `Debug.log` and execute `next ()` directly the test never finishes. Looks like the identify call makes the compiler use the locally bound variable, while without, it takes the global function.

See [slack discussion](https://elmlang.slack.com/archives/C0CJ3SBBM/p1503786536000045) for more details.

### Environment

- Elm Version: 0.18.0
- NPM Version: 5.0.3
- OS: Mac OS Sierra 10.12.6

### Workround

Don't name the local variable the same as the global.

### Expected Behaviour

- The behaviour should be consistent whether I add identity or not
- The compiler should warn because I am shadowing the global name (or not)
- If the behaviour cannot be made consistent the code should not compile, forcing you to choose different names

**Comment by jvoigtlaender** [comment]
It seems related to https://github.com/elm-lang/elm-compiler/issues/1452

**Comment by evancz** [comment]
You cannot represent cyclic data structures in a language with only immutable values.

You need references, and laziness is a way of exposing references in a limited way.

If you want to learn to represent things that can have cycles (like graphs) I recommend reading https://evancz.gitbooks.io/functional-programming-in-elm/content/graphs/

**Comment by evancz** [comment]
I think I may not be understanding the problem you are seeing properly. Please create an http://sscce.org/ in a new issue that I can actually run if that is the case!

**Comment by FRosner** [comment]
Hi @evancz I am going to create an sscce right now. Thanks for the feedback.

I agree that you need laziness but that's what I get with `() -> CircularList a`, no?

**Comment by FRosner** [comment]
Actually I think that the SSCCE will boil down to #1452 as pointed out by @jvoigtlaender already. So I'm not going to create a duplicate of that one :)

**Comment by zwilias** [comment]
This typechecks, but the generator thinks it's a recursive function.

```elm
f : (() -> a) -> a
f f = f ()
```

This also typechecks, and works fine:

```elm
f : (() -> a) -> a
f f = (identity f) ()
```


In other words, when used as a top-level expression, it seems like the codegen doesn't see the parameter-binding and uses the global `f`, rather than the parameter `f`.
