### ISSUE TITLE
Yet another "Unable to generalize a type variable. It is not unranked."

### ISSUE THREAD

**Issue by ksmithbaylor** [elm-lang/elm-compiler#1638]
This is another instance of the error referenced in #1613. Using elm `0.18.0` on macOS `10.12.6`.

```elm
type alias SpecialInt =
    Int


toFloat : SpecialInt -> Float
toFloat m =
    -- Minimal implementation to satisfy the compiler
    42.0


divide : SpecialInt -> number -> SpecialInt
divide a b =
    ((toFloat a) / (toFloat b)) |> round
```

Changing the name of our user-defined `toFloat` function fixes the issue (gives a normal compiler error rather than a crash), as does changing the second argument type of `divide` to `Int` instead of `number`.

**Comment by evancz** [comment]
Added to #1613

**Comment by evancz** [comment]
Based on commit 4b25980d93ada12236c794f35570e197be82f787, I am now seeing the following error in my development build!

![screen shot 2018-03-06 at 1 43 29 pm](https://user-images.githubusercontent.com/1658058/37060189-6b6a28c6-2144-11e8-89a8-cba98fe7a9bd.png)

> **Note:** You may see extra qualifiers on types in this error. That is part of the dev build, but should not appear in the final thing.
