### ISSUE TITLE
Array.append causing mutation.

### ISSUE THREAD

**Issue by rtavenner** [elm-lang/elm-compiler#1641]
When this code is run, it displays `Array.fromList [(),()]` on the screen. It should display `Array.fromList [()]`. It appears that `single` is being mutated by the append operation.

```
import Html
import Array

single = Array.fromList [()]

_ = Array.append single (Array.fromList [()])

main = Html.text (toString single)
```

**Comment by zwilias** [comment]
There are [quite a few issues](https://github.com/elm-lang/core/issues?utf8=%E2%9C%93&q=array) with the current array implementation. These are known issues.

In 0.19, we'll have a new Array implementation. If you are blocked by this right now, you can install `Skinney/elm-array-exploration` and use it as a drop-in replacement: `import Array.Hamt as Array`
