### ISSUE TITLE
Type mismatch ambiguity

### ISSUE THREAD

**Issue by jatinderjit** [elm-lang/elm-compiler#1642]
Elm version: 0.18

```elm
module Test exposing (..)


type alias BaseConfig a =
    { a
        | id : Int
        , name : String
    }


type Model
    = StringField StringConfig


type alias StringConfig =
    BaseConfig
        { value : String
        }


getProperty : (BaseConfig a -> b) -> BaseConfig a -> b
getProperty fn config =
    fn config


property : (BaseConfig a -> b) -> Model -> b
property fn model =
    case model of
        StringField config ->
            getProperty fn config


id : Model -> Int
id =
    property .id


id2 : Model -> Int
id2 model =
    case model of
        StringField config ->
            getProperty .id config
```

This code fails  with the error:
```
The 2nd argument to function `getProperty` is causing a mismatch.

30|             getProperty fn config
                               ^^^^^^
Function `getProperty` is expecting the 2nd argument to be:

    BaseConfig a

But it is:

    StringConfig
```

If I comment out the `property` and `id` functions, the code works just fine.

My argument is that (almost) exact same thing works in the `id2` function.
The difference between `property` and `id2` is the 1st argument. But the raised error complains about the 2nd argument.

**Comment by zwilias** [comment]
This makes sense, as far as I can tell. If that were to compile, I could make a function

```
getSize : BaseConfig { size: Int } -> Int
```

and pass that to your `property`  function, which clearly wouldn't work.

The "magic" here is `getProperty` which restricts that `a` in its type-signature to be of the same type across the whole thing. Changing the type-signature of `property` to `(StringConfig -> b) -> Model -> b` should make the whole thing work properly.
