### ISSUE TITLE
Compiler freezes when annotating a weird self-referential type

### ISSUE THREAD

**Issue by nonpop** [elm-lang/elm-compiler#1643]
Trying to compile the following code causes the compiler (elm 0.18.0 on Archlinux) to freeze. If I remove the type annotation from idF it will produce an error message about a weird self-referential type, but with the annotation it just gets stuck.

```elm
module Test exposing (..)


type alias Focus b s =
    { get : b -> s
    , update : (s -> s) -> b -> b
    }


create : (b -> s) -> ((s -> s) -> b -> b) -> Focus b s
create get update =
    { get = get
    , update = update
    }


idF : Focus { r | id : a } a
idF =
    create .id (\f s -> { s | id = f })  -- should be { s | id = f s.id }
```

**Comment by evancz** [comment]
Development build captures it:

![screen shot 2018-03-06 at 3 31 49 pm](https://user-images.githubusercontent.com/1658058/37064874-8b52b464-2153-11e8-9e14-ad2f4f2788f7.png)

It is not pointing out the infiniteness in an ideal way, but it does not hang at least.
