### ISSUE TITLE
Elm compiler does not detect type error in recursive call for list length

### ISSUE THREAD

**Issue by pbv** [elm-lang/elm-compiler#1651]
The elm compiler accepts the following definition of list length which has a type error in the recursive call:

~~~
import Html exposing (text)

main =
  text (toString (len (List.range 1 9)))

len : List a -> Int
len xs = case xs of
   [] -> 0
   x :: xs -> 1  + len [xs] 
        -- should be type error: List a does not match List (List a) 
~~~

Using elm 0.18 this does not cause a type error and generates JS that fails at runtime with a maximum call stack size exceed.

**Comment by itsgreggreg** [comment]
I don't believe that is actually a type error. You're essentially calling a differently type `len` inside of `len` but it's going to return an `Int` and that's all the compiler cares about at that point. The compiler isn't going to guarantee that you are calling the same `list a` every time you call it within a recursive call. This is just a normal recursion implementation error.

**Comment by pbv** [comment]
OK, got it, Elm is allowing polymorphic recursion here. Somehow I though it would stick to Hindley-Milner only, but it make to allow more if I provide a type signature (it does complaint if I don't provide it because it can't do the inference).

**Comment by zwilias** [comment]
Indeed, this is soundly typed with polymorphic recursion 👍
