### ISSUE TITLE
Consider removing "Don't save code quality for later!" admonition 

### ISSUE THREAD

**Issue by pbiggar** [elm-lang/elm-compiler#1652]
I love that Elm focuses on really good error messages. As a result, I find that the "don't save code quality for later!" admonition that accompanies the "Module x is unused" warning to be out of place.

As the person working on my project, I am probably best at determining my priorities, and the compiler perhaps lacks the nuanced reasoning of what I'm trying to achieve now. Repeatedly being admonished by the compiler is annoying, but when the compiler is also wrong it is doubly annoying. It's also a little bit jarring - I'm thinking "I need to do X and Y" but then it pops into my head "Don't save code quality for later!".

I know Elm aims to be a user-friendly and beginner-friendly language, I believe that this is detrimental to those goals. Hope this is helpful.

Elm: 0.18.

**Comment by evancz** [comment]
Please include evidence of a case where this message does not make any sense. I cannot balance this case against all the others without knowing the actual situation. It should be in a new issue with everything necessary in the first post.
