### ISSUE TITLE
Any news?

### ISSUE THREAD

**Issue by bradacina** [elm-lang/elm-compiler#1654]
Hi guys,

It's been a quiet 2017. Very few commits, very few blog posts on the official website. Of course, I'm comparing the level of activity of 2017 to that of 2016.

Has there been a change in direction? Other real life priorities have popped up? Anything you can share with the community? What's the plan for 2018?

Regards,
Bo

**Comment by lukewestby** [comment]
@bradacina you can find regular updates on what's happening with development on the [elm-dev](https://groups.google.com/forum/#!forum/elm-dev) mailing list. as for new commits, changes to `elm-compiler` usually progress in branches other than `master`.

**Comment by bradacina** [comment]
Thank you for the info @lukewestby

**Comment by kachkaev** [comment]
Just chipping in to fix two links above:
*  https://elmlang.herokuapp.com/
* https://discourse.elm-lang.org/

(they were pointing to unexpected places at the time of writing)
