### ISSUE TITLE
thread blocked indefinitely in an MVar operation

### ISSUE THREAD

**Issue by h4ck3rm1k3** [elm-lang/elm-compiler#1655]
I was able to reproduce this, here is my entire build directory will all files https://github.com/h4ck3rm1k3/steem-graph just run elm-make. Installed on debian sid with nvm v9.

Running strace showed many of these:
32216 --- SIGVTALRM {si_signo=SIGVTALRM, si_code=SI_TIMER, si_timerid=0, si_overrun=0, si_value={int=0, ptr=NULL}} ---

What I did was install modules via elm-package and then rename them to try and work out conflicts where names conflict

elm-make: Could not find type constructor `SimpleGraph.Node` while checking types.
elm-make: thread blocked indefinitely in an MVar operation

**Comment by evancz** [comment]
We cannot provide support for errors caused by hand-editing package assets.

The issue about overlapping module names is known and we are tracking it elsewhere.
