### ISSUE TITLE
A qualified name in a record update gives a parsing error

### ISSUE THREAD

**Issue by nikita-volkov** [elm-lang/elm-compiler#1656]
E.g., the following will fail to parse

```elm
{ Slider.likert | highlighted = True }
```

with the following message:

```
I ran into something unexpected when parsing your code!
I am looking for one of the following things:
    a closing bracket '}'
    a lower case name
    whitespace
```

**Comment by mkwiatkowski** [comment]
Elm syntax only supports single-level updates. If you want to update a nested structure then this FAQ entry should help to solve your problem: http://faq.elm-community.org/#how-can-i-change-the-value-of-a-nested-field

If this is not what you are looking for then please post a full example of your code, preferably using https://ellie-app.com/ Feel free to also check out Elm's Slack, there are always helpful people there: http://elm-lang.org/community#slack

**Comment by zwilias** [comment]
For tracking purposes - this is the same issue as described in #635  and tracked in #1375.

Thanks for the report!

**Comment by mkwiatkowski** [comment]
Ah, misunderstood the issue, I somehow read `{ Slider.likert | highlighted = True }` as `{ slider.likert | highlighted = True }`. Sorry!

**Comment by evancz** [comment]
Thanks @zwilias for letting folks know what's up here.
