### ISSUE TITLE
Shadowing in extensible records

### ISSUE THREAD

**Issue by endlessoblivion** [elm-lang/elm-compiler#1660]
In Elm 0.18:

### [1] Gap between annotation & instantiation

Duplicate record properties are allowed in type annotations, but not in record instances:
```elm
a : { x : Int, x : () }
a = { x = () }
-- a = { x = 42, x = () } --> error: more than one field `x`
```
Note that here the **last** declared property wins.

Since Elm no longer has the feature of adding & removing record properties, it would feel much safer if declaring duplicate record properties was not allowed at all. (The properties retention makes sense only when combined with add- / remove- induced scoping.)

Related: #1570 (that one uses the same type for the duplicate property)

### [2] Inconsistent shadowing order
```elm
type alias A a = { a | x : () }

a : A { x : Int }
a = { x = () }
```
Note that this time, the **first** declared property wins.

It's not clear which one should win in this case, so again, it would feel more safe if this was not allowed at all in the first place.

### [3] Not constraining a type variable
```elm
type alias A a = { a | x : () }

f : A { x : a, y : a, z : a } -> ()
f { x } = x

_ = f { x = (), y = "", z = "" }
```
Here, `x : a` is ignored to the extent that it's not even taken into account for constraining the type variable `a`.

### ... while everything else works as expected

Even things like "fractal" records:
```elm
type alias A a = { a | x : a }

f : A { a | y : a } -> ()
f _ = ()

_ = f { x = { y = {} }, y = {} }
_ = f { x = { y = { z = "" }, z = "" }, y = { z = "" }, z = "" }
```

**Comment by evancz** [comment]
In my development build, I am getting the following error from the first example:

```
-- NAME CLASH --------------------------------------------------------- temp.elm

This record has multiple `x` fields.

4| a : { x : Int, x : () }
         ^        ^
How can I know which one you want? Rename one of them!
```

So it is disallowed, as was the intent!

I'm not really sure what choices or bugs are revealed in the other parts of the issue, so I am going to close. It seems like adding normal kind checking to fix #1661 will not resolve the possibility of duplicate fields. I'll add a note about it.
