### ISSUE TITLE
errors when extending records in invalid ways

### ISSUE THREAD

**Issue by endlessoblivion** [elm-lang/elm-compiler#1661]
In Elm 0.18:
```elm
type T = T {}
type alias A a = { a | x : () }

f : A T -> ()
f { x } = x
```
still results in:
```
elm-make: Used toSrcType on a type that is not well-formed
elm-make: thread blocked indefinitely in an MVar operation
```
despite [this commit for 0.16](https://github.com/elm-lang/elm-compiler/commit/a28acb21900535f3229e7ef924856b70298870c5) claiming a fix.

Related: #917

> **Note from Evan:** Issue #1660 points out that you can have problems when it is a record, but has duplicate fields. It seems like kind checking would have to have a bit of extra cleverness to catch that situation as well.

**Comment by evancz** [comment]
Tracking in https://github.com/elm-lang/elm-compiler/issues/1684

Thank you for the report!
