### ISSUE TITLE
compiler hangs on what's probably a self-referential type

### ISSUE THREAD

**Issue by robx** [elm-lang/elm-compiler#1662]
The naked function definition

    f = List.foldr (|>) 1

causes elm-make (`elm-make 0.18 (Elm Platform 0.18.0)`) to hang indefinitely.

(The new issue template references

    - Does the compiler hang?         See https://github.com/elm-lang/elm-compiler/issues/1240

but that seems to be outdated, following the thread leads to the suggestion in https://github.com/elm-lang/elm-compiler/issues/1231 to open a new issue.)

**Comment by MikeyBurkman** [comment]
Just ran into roughly this same issue. Brought my computer to its knees when elm-make was using 270% of my CPU :P

**Comment by evancz** [comment]
In my development build, I am seeing:

![screen shot 2018-03-06 at 3 27 45 pm](https://user-images.githubusercontent.com/1658058/37064715-f1fcc2be-2152-11e8-8288-cabcb494ca90.png)

The error is not perfect (e.g. one of those hints is weird) but I expect that to get fixed up before a public release. So at the very least, it is not a crash anymore!

Thanks for the report!
