### ISSUE TITLE
Bit Shaving: Recursive loops with case..of compiles with unrequired continue statement.

### ISSUE THREAD

**Issue by Skinney** [elm-lang/elm-compiler#1670]
When compiling recursive functions with case..of expressions, the outputed JS contains a label and continue statement which doesn't need to be there. This is not removed by uglify-js, meaning that this effects bundle size.

I think there is some savings to be had here.

Take, as an example, this Elm code:

```elm
example : Int -> String
example n =
    case n of
        1 ->
            "Big Number!"

        0 ->
            "Zero"

        _ ->
            example (n - 1)
```

Compile to JS:

```js
var _user$project$Main$example = function (n) {
	example:
	while (true) {
		var _p0 = n;
		switch (_p0) {
			case 1:
				return 'Big Number!';
			case 0:
				return 'Zero';
			default:
				var _v1 = n - 1;
				n = _v1;
				continue example;
		}
	}
};
```

Minify it (using `uglify-js -c -m`):

```js
function(t){t:for(;;)switch(t){case 1:return"Big Number!";case 0:return"Zero";default:t-=1;continue t}}
```

Since we're inside a loop, nothing bad would happen in this case if we simply remove the label and the continue statement. We do save 12 bytes however. Multiply this with every recursive function, and we get a not-insignificant size-saving.

**Comment by zwilias** [comment]
Note that occasionally, the labels are in fact required: complex `case..of` statements are also compiled to a labeled `do..while` loop to enable a sort of `goto default` approach.

The following code would (with the current compiler) compile to incorrect code with the labels for tail-recursive code removed:

```
weirdTailRec : Int -> String
weirdTailRec i =
    case (i, 1) of
        (1, 1) -> "hi"
        (2, 1) -> weirdTailRec (i + 1)
        _ -> "ho"
```

**Comment by evancz** [comment]
I think that it will be too complex to detect this in time for 0.19, so I am going to close this issue.

I think it may make sense to study the code gen of 0.19 at some point and collect a list of cases where we can do better. It may be possible to organize a batch of work around that.
