### ISSUE TITLE
Reserved JS kewords can be used as a record field but they are not defined through ports.

### ISSUE THREAD

**Issue by pietro909** [elm-lang/elm-compiler#1672]
I can create a record `{ static: "hello" }` and send it through a port. On the JS side, I receive `{ static: undefined }`. The Elm code doesn't fail because under the hood `static` became `$static`.

This applies also to other reserved words like `new`.

Example: https://ellie-app.com/3pQCzWTt5a1/3

This is a bug because:

1. ports are the official and only supported way to interoperate with JS
2. it causes runtime exceptions in the JS code (ie: `static.length`)
3. there's no clue or warning of this behavior, and it leads to very difficult debugging

**Comment by rtfeldman** [comment]
@pietro909 In case it helps, you can send `Json.Encode.Value` to ports, and do the encoding yourself with `Json.Encode` - this way there are no surprises!

(I realize that doesn't address the underlying issue you're reporting, but personally I prefer using `Json.Encode` with ports in general anyway - it's a bit more work up front, but I always know exactly what I'm getting on the other side.)

**Comment by pietro909** [comment]
Thank you @rtfeldman, this is exactly what I'm doing most of the time :-) and I find it better since I can write my unit tests for the decoders and if something breaks I discover it immediately.

It turns out also that this is related to #1548 and caused by #1510

What is the policy? Is better to close the issue in favour of the mentioned ones or the team prefers to keep them all?

**Comment by evancz** [comment]
It is better to keep them all. I prefer to have the problem stated different ways by different people. It provides more examples, and it means that you are not stuck with a poor quality issue if that happens to be the first one you get!

**Comment by evancz** [comment]
Tracking in #1685 now. Thank you for the report!
