### ISSUE TITLE
Special comments not allowed in some circumstances

### ISSUE THREAD

**Issue by schani** [elm-lang/elm-compiler#1678]
```elm
type alias Foo =
    {-| Could I put a special comment here, please? -}
    Float
```

If I remove the pipe, `|`, then this compiles, if not the compiler complains with

```
-- SYNTAX PROBLEM --------------------------------------------------------------

I ran into something unexpected when parsing your code!

3|     {-| Could I put a special comment here, please? -}
        ^
I am looking for one of the following things:

    "}"
    a lower case name
    whitespace
```

Elm 0.18.0

**Comment by evancz** [comment]
The `{-|` is specifically for documentation comments, which must appear in certain locations.

I think this is a good issue for https://github.com/elm-lang/error-message-catalog though. Sorry for the trouble in the meantime!

**Comment by evancz** [comment]
I have a feeling the 0.19 changes will make it better, but I'll likely circle back through the error message catalog to make sure when it's the right time.

**Comment by schani** [comment]
For the time being, is there a way to add documentation comments for record fields?  That’s what I was trying to do in the first place.

**Comment by evancz** [comment]
There is no special language feature for that. I just write about it in the normal documentation, sometimes with a bulleted list. I haven't felt like I needed anything fancier than that.
