### ISSUE TITLE
Cannot access fields on qualified records

### ISSUE THREAD

**Issue by Flecks1** [elm-lang/elm-compiler#1680]
I stumbled upon this bug a few times now. In some of the modules we use in our Elm applications, we have public records that are exposed. But I noticed that when you try to use these records in other modules using qualified names, the fields they contain are unaccessible. The compiler fires an error saying that the module 'MyModule.myRecord' cannot be found, as if it tries to evaluate everything that comes before the last dot as a module.

```
module MyModule exposing (myRecord)

type alias Record =
    { someProp : Int
    , someOtherProp : String
    }

myRecord : Record
myRecord =
    { someProp = 5
    , someOtherProp = "Yup"
    }
```

```
module MyOtherModule exposing (..)

import MyModule

someValue : Int
someValue =
    MyModule.myRecord.someProp -- This results in a compiler error

someValue_ : Int
someValue_ =
    let
        someRecord =
            MyModule.myRecord
    in
    someRecord.someProp -- This does not
```

```
Cannot find variable `MyModule.myRecord.someProp`.

No module called `MyModule.myRecord` has been imported.
```

I know exposing records of static values is probably a weird way to structure your code, and that this could be fixed by exposing the values in `myRecord` in a submodule to `MyModule` instead of exposing a record of those values, but shouldn't this still be possible?

I am using Elm 0.18.

**Comment by zwilias** [comment]
Thanks for the report!

This is [fixed in the new parser](https://github.com/elm-lang/elm-compiler/issues/520#issuecomment-267798164) which will be released as part of Elm 0.19
