### ISSUE TITLE
Probably erroneous code in library diffing

### ISSUE THREAD

**Issue by joonazan** [elm-lang/elm-compiler#1683]
https://github.com/elm-lang/elm-compiler/blob/master/builder/src/Deps/Diff.hs#L277

I think it should say that Number and Comparable are compatible, not Number and CompAppend. The same case is repeated twice.

Also, the function should be called compatible, not compatable.

**Comment by evancz** [comment]
Thanks! Fixed this in 32ff9501f8e6abc4df214b1112dee6d5008ce95f
