### ISSUE TITLE
Case statements with booleans 

### ISSUE THREAD

**Issue by tolgap** [elm-lang/elm-compiler#1703]
Case statements with booleans do not work. It tries to unwrap a boolean with `_n1.$ === 'True'`, but the variable `_n1` is already a boolean primitive: SSCCE https://staging.ellie-app.com/d78PLCpRfSa1/0

```elm
module Main exposing (main)

import Html

main =
    case True of
        True ->
            Html.text "True"
        False ->
            Html.text "False"

```

The ellie example should print `True`, but the output is `False`.

**Comment by evancz** [comment]
Thanks for the report! Fixed locally!
