### ISSUE TITLE
(10 ^ -1) is considered an Int type by compiler

### ISSUE THREAD

**Issue by harfangk** [elm-lang/elm-compiler#1704]
While (10 ^ -1) is displayed as number type, it seems to pass compiler checks for an Int.
This can be easily reproduced in REPL.
```
> n = 10 ^ -1
0.1 : number
> Basics.rem n 5
0.1 : Int
> Basics.rem 5 n
0.09999999999999973 : Int
> String.repeat n "string"
"" : String
> String.pad n 's' ""
"s" : String
> String.left n "Elm"
"" : String
> 
```
Same example in Ellie: https://ellie-app.com/qKWRjvzfSa1/1

**Comment by rtfeldman** [comment]
Thank you so much for reporting this @harfangk!

This is a `core` issue, so I'm going to close this `elm-compiler` issue in favor of an issue on that repository: https://github.com/elm-lang/elm-compiler/issues/1704
