### ISSUE TITLE
Bug: Elm.Native.Http never 'Waiting'

### ISSUE THREAD

**Issue by grotsev** [elm-lang/elm-compiler#173]
In http://elm-lang.org/edit/examples/Reactive/ZipCodes.elm while changing last zip code digit
 - 12123
 - 1212
 - 12124

response changes
 - {"city": "Nassau", "state": "New York", "country": "US"}
 - Enter a valid zip code, such as 12345 or 90210.
 - short period of old value {"city": "Nassau", "state": "New York", "country": "US"} instead of (image 16 16 "waiting.gif")
 - {"city": "New Baltimore", "state": "New York", "country": "US"}

Debug shows the 'Waiting' signal value has never fired.

**Comment by evancz** [comment]
This module was removed in 0.15
