### ISSUE TITLE
Zombie touches if "Alt" key pressed during dragging using mouse (MacOSX 10.8.4, Firefox 22)

### ISSUE THREAD

**Issue by codecurve** [elm-lang/elm-compiler#191]
If the "Alt" key is kept down while mouse dragging is started, stopped and restarted multiple times, "zombie" entries appear in the Touch.touches list.

To reproduce, just do multiple drags keeping Alt down the whole time in any of the Touches dragging demos, e.g. http://elm-lang.org/examples/Basic.elm

Only seems to be a problem with this specific configuration: MacOSX 10.8.4, Firefox 22.
MacOSX 10.8.4, using Google Chrome or Safari is fine, so I guess the workaround is obvious. Linux and Windows seem fine too.

**Comment by evancz** [comment]
I am trying to clean up the issues in this repo, so I am going through and closing a bunch of issues with ideas on how to get them done.

In this case, we should verify that the issue still manifests and if so, open an issue at https://github.com/elm-lang/core/issues
