### ISSUE TITLE
If WebSocket connection gets interrupted, it stays interrupted

### ISSUE THREAD

**Issue by ozataman** [elm-lang/elm-compiler#198]
There doesn't seem to be a strategy for error detection/recovery/re-connection here. A simple observation can be made by following these steps:

1. Start websocket server
2. Start Elm app containing a Signal with WebSocket.connect underneath
3. Shut down the websocket server
4. Keep observing the Elm app

which simply results in no more signals being emitted. 

Error recovery is important, especially for server-driven real-time apps. Perhaps we can add a reconnect flag, or better yet, a ReconnectStrategy type with finer grained options for re-establishing communication?

**Comment by evancz** [comment]
`WebSockets` has been moved outside of the core modules, so we resolved this problem by deleting all the code. The new approach uses `Tasks` so should not have the same fundamental API constraints.

Thanks for the report and sorry for the crazily long delay!

**Comment by mgold** [comment]
You can try [elm-socketio](https://github.com/mgold/elm-socketio) which _will_ reconnect and has some configurable error handling.
