### ISSUE TITLE
Elements in a flow down are jumping around when updated

### ISSUE THREAD

**Issue by deadfoxygrandpa** [elm-lang/elm-compiler#228]
I was designing a simple menu system and found that when I added a time signal for a fade in, the elements started bugging out and jumping around oddly. Without this quickly updating time signal, it still happens, but very rarely. I don't have any guesses as to what's causing it.

Problem example, cut down to show the bare minimum needed to reproduce it, as far as I can tell:
```
import Window
import Keyboard

menu (w, h) select t =
    container w h midLeft . flow down <| 
        map (\s -> (if (s == select) then color grey . container w 20 midLeft else id) . plainText <| s) 
            [ "new"
            , "resume"
            , "settings"
            , "quit"
            ]

step {x, y} (s, n) = 
    let ss = ["new", "resume", "settings", "quit"]
        n' = clamp 0 3 (n - y)
    in  (head . drop n' <| ss, n')
    
selected = foldp step ("new", 0) Keyboard.arrows

main = menu <~ Window.dimensions ~ (fst <~ selected) ~ (count <| fps 60)
```
You can view it here: http://share-elm.com/sprout/521c2544e4b098db14c54c13/view
You use the keyboard up/down arrow to select different options. Sometimes when you move, the text jumps around and gets bunched up, and the highlight bar doesn't extend very far to the right.

But if I take out the ```count <| fps 60``` the problem mostly goes away (but will still very rarely happen):
```
import Window
import Keyboard

menu (w, h) select t =
    container w h midLeft . flow down <| 
        map (\s -> (if (s == select) then color grey . container w 20 midLeft else id) . plainText <| s) 
            [ "new"
            , "resume"
            , "settings"
            , "quit"
            ]

step {x, y} (s, n) = 
    let ss = ["new", "resume", "settings", "quit"]
        n' = clamp 0 3 (n - y)
    in  (head . drop n' <| ss, n')
    
selected = foldp step ("new", 0) Keyboard.arrows

main = menu <~ Window.dimensions ~ (fst <~ selected) ~ (constant 0)
```
Which you can see in action here: http://share-elm.com/sprout/521c2676e4b098db14c54c15/view

**Comment by evancz** [comment]
I am trying to clean up the issues in this repo, so I am going through and closing a bunch of issues with ideas on how to get them done.

In this case, we should verify that the issue still manifests and if so, open an issue at https://github.com/elm-lang/core/issues
