### ISSUE TITLE
flow up changes element positions on signal change

### ISSUE THREAD

**Issue by deadfoxygrandpa** [elm-lang/elm-compiler#229]
When trying to center several items using ```container``` and ```flow up```, I found that the centering behavior is incorrect. The items become staggered and slanted instead of centered, as you can see here:
```
items = ["one", "two", "three"]

display x t = flow up <| map (container 500 19 midTop . plainText) x

main = display items <~ fps 1
```
The items will display correctly centered for 1 second, until the ```fps 1``` ticks and they stagger. The weirdest part is that this does NOT happen with ```flow down```:
```
items = ["one", "two", "three"]

display x t = flow down <| map (container 500 19 midTop . plainText) x

main = display items <~ fps 1
```
If you check that, nothing moves and everything is centered correctly.

I've looked at the library and don't see anything that seems like it could possibly cause this. So I also looked at the runtime, but nothing is jumping out at me there, either.

**Comment by evancz** [comment]
I am trying to clean up the issues in this repo, so I am going through and closing a bunch of issues with ideas on how to get them done.

In this case, we should verify that the issue still manifests and if so, open an issue at https://github.com/elm-lang/core/issues
