### ISSUE TITLE
Make record syntax more lenient

### ISSUE THREAD

**Issue by ytaras** [elm-lang/elm-compiler#231]
Consider this code:
```
point = {x = 1,y = 2, z=3}
-- Doesn't work
-- addingFewFields = { point | a = 4, b = 5 }
-- addAndReplace = { point | x = 1, a <- 4}
-- Works
replaceFewFields = { point | x <- 1, y <- 2 }
```
If I uncomment addingFewFields function, compilation fails with following message:
```
Parse error at (line 3, column 34):
unexpected ","
expecting digit, ".", whitespace, "-", basic term (4, x, 'c', etc.), infix operator (e.g. +, *, ||) or closing bracket '}'
```
Also, if I try to use record extensions and update at the same time, like in funciton addAndReplace, I get following error:
```
Parse error at (line 4, column 32):
unexpected ","
expecting digit, ".", whitespace, "-", basic term (4, x, 'c', etc.), infix operator (e.g. +, *, ||) or closing bracket '}'
```
It was tested using online code editor on a Elm site at 28 Aug 2013.

**Comment by evancz** [comment]
I just implemented #985 in the master branch. The overall lessons from having record extension at the syntax level has been that it does not come up in practice ever, and when it does, it can be done better in another way. This is what we have seen so far at least.
