### ISSUE TITLE
Numerical computations error with large numbers

### ISSUE THREAD

**Issue by rahulsidhu** [elm-lang/elm-compiler#264]
The following code outputs "True"

n : Int
n = 10000 + 10^20
m = 20000 + 10^20

main = asText (n==m)

http://share-elm.com/sprout/523b7892e4b00f123dfa61f9
Edit: It's the same in Javascript too

**Comment by evancz** [comment]
This should happen as the compiler gets better. Can't do it before then, and having the issue open forever will not get us there quicker. Thanks for the report!
