### ISSUE TITLE
add syntax for module reexport

### ISSUE THREAD

**Issue by seliopou** [elm-lang/elm-compiler#277]
It would be nice if you could export all the names from an import module in one go. For example if you had the module `Else`:

```haskell
module Else where

theNumberOne = 1
theNumberTwo = 2
```

And you imported it in another module called `Something`, I want a way to export all the names in `Else` all at once, like this:

```haskell
module Something
  ( module Else
  , theNumberThree
  ) where

import Else

theNumberThree = 3
```

Right now, you'd have to write the equivalent module like this:

```haskell
module Something
  ( theNumberOne
  , theNumberTwo
  , theNumberThree
  ) where

import Else

theNumberThree = 3
```

That's gonna get unmanageable as the number of exports in `Else` increases.

**Comment by evancz** [comment]
Centralizing all issues about reexports into #931
