### ISSUE TITLE
Collage makes covered input elements unreachable

### ISSUE THREAD

**Issue by VulumeCode** [elm-lang/elm-compiler#283]
Here it is demonstrated that an input element that's not in the first place in a collage is unreachable. It's also demonstrated that flow doesn't have this problem. I've tested it with hoverables (left) and customButtons (right)
http://share-elm.com/sprout/5252c33fe4b0d6a98b152f5e

Flow has other troubles but seems to be getting input detection right.

**Comment by evancz** [comment]
I believe this was fixed at some point with [the pointer-events property](https://developer.mozilla.org/en-US/docs/Web/CSS/pointer-events). Let's open a new issue over on [this repo](https://github.com/elm-lang/core) if there are still problems!
