### ISSUE TITLE
elm-doc: better error messages on ill-formatted documentation

### ISSUE THREAD

**Issue by seliopou** [elm-lang/elm-compiler#284]
If a source file contains no documentation markup, elm-doc will fail with a parse error. Here's an example:

```bash
$ elm-doc <(echo "module Test where")
```

When you pass elm-doc non-documented files that have comments in them, it reports odd line and column locations for the source of the error. Sometimes it reports the end of the file, but not always.

**Comment by evancz** [comment]
Track continued progress on #933
