### ISSUE TITLE
Sets aren't comparable

### ISSUE THREAD

**Issue by LiamGoodacre** [elm-lang/elm-compiler#310]
I was wanting a unionAll function:

~~~haskell
unionAll : Set (Set comparable) -> Set comparable
~~~

I went to define it as such:

~~~haskell
import Set as S

unionAll xs = S.foldl S.union S.empty xs

a = S.fromList [1, 2, 3]
b = S.fromList [3, 4, 5]
xs = S.fromList [a, b]

main = asText <| unionAll xs
~~~

Receiving the following compile error:

~~~
Type error on line 3:
Expecting something comparable such as an
Int, Float, Char, String, or a list or tuple of comparables.

        S.union

   Expected Type: S.Set comparable
     Actual Type: comparable
~~~

Compiled on [share-elm](http://www.share-elm.com/sprout/526cdd1ee4b03cf6e675ba3a) with `master/HEAD`

**Comment by evancz** [comment]
Closing in favor of #1008 which tracks a bunch of issues in this ballpark. Idea is that we centralize the feedback in one place so we can have a better answer.

**Comment by dustinfarris** [comment]
I was wanting to keep track of "collections" of data I am subscribing to over websockets.

e.g., I might be subscribed to channel name`friends::user:12345`

This is what I wanted:

```
type Collection
    = UserFriendsCollection String
    | SomeOtherCollection String
    | ...

type alias model =
    { collections : Set Collection
    , ...
    }
```

I am trying to hack out something using tuples, but a union type would have fit nicely here.

**Comment by robyoder** [comment]
I was trying to do the opposite of the OP. I wanted to make a function `powerSet`:

```haskell
powerSet : Set comparable -> Set (Set comparable)
```

The power set of a set is a common function of sets in mathematics, and it is semantically incorrect to represent that as a List or Array of Sets.

**Comment by robyoder** [comment]
Thinking about this more, I can't say I understand why Sets can only have comparable members. The only thing one needs to be able to do with members of a set is compare their equality, not their order. 

So I would approach this problem differently and say instead of allowing Sets themselves to be comparable, we could simply remove the constraint that Sets contain only comparable types.

**Comment by robyoder** [comment]
I posted about this on Discourse. https://discourse.elm-lang.org/t/why-must-set-members-be-comparable/3205/3 The answer makes sense, so I'm back to the OP's position. If a Set has a deterministic ordering of comparable elements, it should make sense for the set itself to be comparable, just like tuples of comparable types are also comparable.
