### ISSUE TITLE
Pattern Matching Identically Named Record Fields

### ISSUE THREAD

**Issue by duffey** [elm-lang/elm-compiler#366]
```haskell
main = let r = { x = "Problem?" } in plainText <| (\{x} {x} -> x) r r
```
produces ```Problem?```, which I didn't expect. I discovered this when writing something like
```haskell
main = let r = { x = "Problem?" } in plainText <| (\{x} {x'} -> x ++ x') r r
```
and the compiler forced me use the identifier ```x```. The workaround I am currently using is
```haskell
main = let r = { x = "Problem?" } in plainText <| (\{x} o -> x ++ o.x) r r
```

**Comment by evancz** [comment]
Closing in favor of #809 which, when fixed, will resolve this issues as well.
