### ISSUE TITLE
Markdown crops <iframe>

### ISSUE THREAD

**Issue by hoosierEE** [elm-lang/elm-compiler#371]
When embedding an `<iframe>` inside of a `[markdown|...|]` element, a parent `div` limits the size.
[Example showing both width and height cropped](http://share-elm.com/sprout/5295f5b5e4b06194fd2d291d)
[Example showing full width, but height still cropped](http://share-elm.com/sprout/5295f605e4b06194fd2d291e)
[Discussion](https://groups.google.com/forum/#!topic/elm-discuss/nOoPEpzETAU)

Snippet of the generated code, the offending `div` is the one setting the height to 189px:
```
<div style="padding: 0px; margin: 0px; width: 2112px; height: 189px;">
  <div style="padding:0;margin:0;text-align:left">
    <div style="height:0;width:0;">&nbsp;</div>
      <p><iframe id="fr" src="http://elm-lang.org" seamless="" width="100%" height="100%"></iframe></p>
    <div style="height:0;width:0;">&nbsp;</div>
  </div>
</div>
```
Also, if the `<iframe>` height is set to a fixed amount (e.g. larger than 189px) the parent div expands to fit.  Example [here](http://share-elm.com/sprout/5295f78ae4b06194fd2d2924).

Finally, [further experimentation](http://share-elm.com/sprout/5295f837e4b06194fd2d2925) suggests that the parent `div` is adding 20px above and below the markdown-containing `div`, and therefore if the height of the `<iframe>` is not explicitly stated it is assume to be 149px.

**Comment by evancz** [comment]
The `[markdown| ... |]` syntax is gone in favor of stuff like elm-html and elm-markdown which should avoid this issue.

**Comment by hoosierEE** [comment]
Ah, I should have closed this quite a while ago.  Thanks!

**Comment by evancz** [comment]
No worries, I was scanning through to see if there were any easy things or old issues! :)
