### ISSUE TITLE
Support type classes

### ISSUE THREAD

**Issue by techtangents** [elm-lang/elm-compiler#38]
As a driving example, the Dict class doesn't make sense without typeclasses. Right now, it's unclear how exactly the Dict implementation gets the "compare" function - it looks like duck typing.

Without type classes, passing in an Ord instance is preferable to duck typing.

e.g.
instead of:
singleton :: k -> v -> Dict k v

do this:
data Ordering = LT | EQ | GT
data Ord a = Ord (a -> Ordering)
singleton :: Ord k -> k -> v -> Dict k v

Alternatives include generalised implicit parameters.

I think, given Elm's Haskell heritage, Haskell-style type classes would be nice.

**Comment by viclib** [comment]
Same

**Comment by fosskers** [comment]
Purescript does.

**Comment by Fresheyeball** [comment]
So I learned at LambdaConf about the existence of elm-html and am now conflicted. Elm has everything I want in an interface system **except** typeclasses. Everything I want is here on the Elm side in terms of libraries and functionality, but no Monads, and very limited type level programming in general; which is what attracted me to PureScript in the first place.  Typeclasses need to be on the roadmap to compete with PureScript's future.

**Comment by unbalancedparentheses** [comment]
It would be really useful to have type classes. I don't know how difficult it's to add them but it would be really helpfull :D

**Comment by Apanatshka** [comment]
The current plan is that in the long term some type-class-like feature will be supported. It's currently low priority and will probably not replicate Haskell's exact solution because Haskell requires all kinds of extensions to use type classes for all the situations where you want them. It is more likely that implicit arguments will be borrowed from Agda, which in combination with Elm's records will be enough to emulate everything around type classes. Use your favourite search engine to find more information on the mailing list, or about Agda, or about a method in the blog post "Scrap your Type Classes" about how you can use records for emulating type classes.

**Comment by evancz** [comment]
@Apanatshka has described the state of the world quite well.

I'm gonna close this. The arguments for and against this (and the various alternatives) are understood at this point, and I am very skeptical that further discussion will reveal new information. It is conceivable that there is a theoretical break through revealing a 4th way of achieving these things, but I'll hear about that independent of this issue. This is obviously on my list of "features to think about" along with a bunch of other stuff.

If you feel compelled to comment on this issue more anyway, please look through the mailing list to get an idea of what has already been said (everything) and maybe watch [this](https://www.youtube.com/watch?v=oYk8CKH7OhE) to get a feel for how these decisions are made. The most relevant point there is that the *timing* of a feature is an important aspect in how the feature is used.

**Comment by evancz** [comment]
Alright, made a meta issue to track all type system extensions and describe the state of the world for folks interested in this topic.

**Comment by brainrape** [comment]
I found a clunky way to simulate existential types by wrapping the type parameter of a polymorphic type in an unexported type. The result is, you can only write polymorphic functions over the polymorphic type. If you try to write a function where you specify the type variable, it either won't compile, or you can never call it.
https://github.com/brainrape/elm-existential
