### ISSUE TITLE
Runtime Error On Circular Signal Reference

### ISSUE THREAD

**Issue by micmarsh** [elm-lang/elm-compiler#418]
I realize that this is probably a non-trivial fix and/or bad practice, but I'm designing a turn-based game that uses a different coordinate system depending on whose turn it is, and thought I was really clever using a gameState -> position -> gameState -> ... reference: https://github.com/micmarsh/xiangqi/blob/3e17891326de5eaebf4786bdd12078afb0a84af2/GameState.elm

Unsurprisingly, this throws "Cannot read property 'value' of undefined" at runtime. If it's possible to throw a compiler warning when this kind of thing happens, that would be great, but I figured it was good to let you know regardless.

Keep up the good work!

**Comment by evancz** [comment]
Centralize this into #873 which describes the viable fixes.
