### ISSUE TITLE
AST allows building of record update which doesn't parse

### ISSUE THREAD

**Issue by JoeyEremondi** [elm-lang/elm-compiler#450]
This is a very minor issue but I thought it should be on record somewhere.

The AST types for record update allow an arbitrary expression to be on the left hand side of the record update. When pretty-printed, this then doesn't parse because of the restrictions on what can be on the left hand side of a record update.

As a test file:

    module RecordExample where

    import SourceSyntax.Expression
    import SourceSyntax.Literal
    import SourceSyntax.Location
    import SourceSyntax.PrettyPrint

    import qualified SourceSyntax.Pattern as Pattern

    ee1 :: Expr
    ee1 = Literal $ IntNum 3

    e1 =  none $ ee1

    recExp = none $ Var "rec"

    funExp = none $ App (none $ Var "id") recExp

    update = Modify funExp [("x", e1)]

    main = do
      putStrLn $ show $ pretty update

Then in `cabal repl`

    :add RecordExample.hs 
    RecordExample.main

which gives output `{id rec | x <- 3}`.

I can't think of an easy way to fix this, other than making the pretty-printer convert these to let-expressions.
It's not a blocker for me, since it's pretty easy to convert everything to let expressions when constructing the AST, but I thought it should be noted that there were well-typed ASTs which didn't parse, through no fault of the pretty-printer.

**Comment by evancz** [comment]
It is unclear if we will make record syntax more flexible, and from the perspective of the compiler, this does not cause any issues and makes some code significantly easier. So we will revisit this when we think about record syntax.
