### ISSUE TITLE
Invalid JS generated with no warning on infinite self-reference

### ISSUE THREAD

**Issue by JoeyEremondi** [elm-lang/elm-compiler#454]
The following (deeply flawed) code compiles without warning/error, but when run in a webpage, a JavaScript type error is given.

    data Foo = Foo | Bar

    val : Foo
    val = 
      let
        x = 1
        y = 2
      in val

    fun : Foo -> Int
    fun x = case x of
      Foo -> 3
      Bar -> 4
      
    main = plainText (show (fun val))

Firefox prints `TypeError: x is undefined`. The same result happens in Stable and Head on [share-elm.com](http://share-elm.com/sprout/52da3acee4b06194fd2d413b).

Is this solvable or does detecting the problematic infinite loop reduce to solving the halting problem. Clearly val is in the namespace, since recursion is allowed for functions. But its definition is a tautology, val=val with no information.

Either way, it's a case in which invalid JS is generated.

**Comment by evancz** [comment]
Closing in favor of #873 which outlines the fix for this. Thanks for the report!
