### ISSUE TITLE
Type arguments not printed for some errors involving list and tuples.

### ISSUE THREAD

**Issue by JoeyEremondi** [elm-lang/elm-compiler#455]
Sorry to keep opening issues, but I've been writing a bunch of code and keep stumbling across them. This one is neither serious nor a regression, so it can wait until after 0.11.

When compiling the (incorrect) code `myConcat = [1,2,3] ++ (1,2)`, the following type error is given:

    Type error on line 1:

            [1,2,3] ++ ((1,2))
    
      Expected Type: _List
        Actual Type: (number)

I feel like it should read

    Type error on line 1:

            [1,2,3] ++ ((1,2))
    
      Expected Type: [number]
        Actual Type: (number, number)

Similar problems occur with 

    data Foo a = Foo a
    myConcat = [1,2,3] ++ (Foo 3)

I'll see if I can track down where in the source is causing this.

UPDATE:

The problem is not in the pretty printer, but in the values it is being given. In my first example, it's being asked to print `Data "_List" []` for the list type, and `Data "_Tuple" [number]` for the tuple type.

**Comment by evancz** [comment]
Yeah, the inferencer is able to work with types that have kind `* -> *` so that's what we are seeing here. Let's move this to https://github.com/evancz/error-message-catalog/issues with a nice code sample and a print out of the exact error message it gives.
