### ISSUE TITLE
Built-in Ports aren't TypeChecked

### ISSUE THREAD

**Issue by maxsnew** [elm-lang/elm-compiler#475]
The built-in ports are not typechecked. This breaks stuff at runtime:
```haskell
port stdout : Int
port stdout = 3

main = asText "sup"
```
crashes with `TypeError: ports.stdout.subscribe is not a function` since it tries to subscribe to something that's not a `Signal`.

**Comment by evancz** [comment]
I am trying to clean up the issues on these repos. My goal is for issues on repos like `elm-compiler` and `elm-repl` are about specific bugs. It is not working to manage proposals and stuff that requires changes to the language here, so I am devising a way of keeping track of all this stuff in a transparent way.

The idea is that it doesn't super matter where the proposal is opened, but we should collect related ideas in certain places so we can look at them as a collection of issues and find a coherent solution that addresses them all as much as possible. So I'm gonna close this and reference https://github.com/elm-lang/elm-plans/issues/17 which is collecting a bunch of port problems.

If there is more to say about this idea, we should continue on this thread. The fact that is closed is more about decluttering stuff!
