### ISSUE TITLE
Markdown Compilation Adds Extra Surrounding Divs

### ISSUE THREAD

**Issue by pseudonom** [elm-lang/elm-compiler#487]
Perhaps this is desired behavior that I somehow don't understand, but the Elm compiler seems to surround markdown blocks with extra divs like `<div style="height:0;width:0;">&nbsp;</div>`. In at least some cases, this produces undesirable behavior. An example is included below. Note how extra white space is included beyond the bottom of the table.

```haskell
main = flow down [ color red <| size 400 1000 empty
                 , size 400 100 table]
                 
table = [markdown|<table style="background-color: black; 
                  width: 100%; height: 100%"></table>|]
```

http://www.share-elm.com/sprout/52edfabee4b0f7cc0dd4d666

**Comment by evancz** [comment]
The `[markdown| ... ]` syntax is gone in favor of elm-html and elm-markdown which should not have these issues.
