### ISSUE TITLE
Feature Request: some way to detect mouse input on Collages

### ISSUE THREAD

**Issue by DR6** [elm-lang/elm-compiler#506]
I made an implementation of the Game of Life on Elm, but now it's very ugly because knowing which square the user clicks is hard. There are two reasons for this:

* Mouse input can only be detected relative to the Elm frame, not relative to any element: I had to make the corner of the collage and the corner of the webpage to coincide, which is good enough but will be inconvenient in some cases.

* The coordinate system the collage uses is very different to the coordinate system mouse input uses, and finding out where it's centered is specially hard.

I know that each system was chosen because of specific reasons, and changing them is not an option, but it would be nice if we could get something like:

    collageInput : Int -> Int -> [Form] -> (Element, Signal (Int,Int))

Where the coordinates were given according to the collage's coordinates. Something like that for elements in general would be cool, but I think it's specially important for Collages so that certain kinds of interactive apps could be done.

**Comment by evancz** [comment]
Closing in favor of #533 which links to where we should continue tracking this. Thanks for the report!
