### ISSUE TITLE
Clearer Errors on Keyword Use

### ISSUE THREAD

**Issue by pseudonom** [elm-lang/elm-compiler#513]
Right now, they can be pretty opaque.

http://www.share-elm.com/sprout/531d3407e4b0f7cc0dd4e2b9

**Comment by evancz** [comment]
I would love to do this! We are collecting a bunch of bad error messages at https://github.com/evancz/error-message-catalog/issues so we know where folks are feeling the most pain. This will help us see patterns and prioritize fixes. If the latest version of the compiler still sucks at your case, please report it there!

This may require a revamp of how parsing works in Elm, so it may not be possible to do this for a while though.
