### ISSUE TITLE
Loss of focus in text field with new input API

### ISSUE THREAD

**Issue by mg50** [elm-lang/elm-compiler#523]
See this gist: https://gist.github.com/mg50/9579575

It searches for list items that begin with the value of the text field. However, whenever typing into the field would change the number of list items displayed, the search field immediately loses focus.

**Comment by evancz** [comment]
For now, I'd recommend using elm-html which should not have this issue. If there are still issues, please rereport it on elm-lang/core or if you have troubles with the `Html` route, on evancz/elm-html.
