### ISSUE TITLE
Feature request: local coordinates for input within an element

### ISSUE THREAD

**Issue by skybrian** [elm-lang/elm-compiler#533]
The mouse and touch signals use a global coordinate system, making it awkward to convert to the local coordinate system used when drawing within a collage element. Converting from global to local coordinates could be quite tedious when a collage is nested in a complicated layout. Perhaps a collage could optionally take a handle where it can send mouse and touch events using local coordinates?

Examples: the "Track" and "Draw" examples do their own coordinate conversion, which is okay in the simple case.

More generally, perhaps it should be possible to use any Element as a local coordinate system for sending events to a handle, similar to the automatic coordinate system conversion that happens when receiving events in JavaScript.

Example: it should be possible to click on an image and get the coordinates where the click happened.

**Comment by evancz** [comment]
Still a good idea, mentioning https://github.com/elm-lang/core/issues/332 so we have all the `Graphics.*` ideas in one place and we clean up the issues in the compiler repo!

**Comment by jvoigtlaender** [comment]
Note that https://github.com/elm-lang/core/pull/307 contains an idea to address something like this.
