### ISSUE TITLE
Can't use expression as record to update

### ISSUE THREAD

**Issue by skybrian** [elm-lang/elm-compiler#537]
This doesn't work:

rec = {a = {b = 3}}

rec2 = {rec.a | b <- 4}

main = asText rec2

Parse error at (line 3, column 12):
unexpected "."
expecting whitespace, pattern or "="

The workaround I found is to use a let expression to declare a variable for rec.a.

**Comment by evancz** [comment]
Alright, I am closing in favor of https://github.com/elm-lang/elm-plans/issues/16 which will track a couple things along these lines. It's good to have them all in one place. Furthermore, I think it's not making sense to have proposals in the elm-compiler repo anymore, so I am laying the groundwork for doing this in a better way. For now, please let me manage elm-plans, no new stuff there!

If there is more to say about this, we should continue the discussion here, not in the elm-plans issue!

**Comment by mezuzza** [comment]
Oops, sorry. I looked there, but I guess I didn't parse the ticket properly. My bad.

**Comment by sfwc** [comment]
I wish for this frequently. What's the argument against it?
