### ISSUE TITLE
Flow right is flowing down in Firefox with new Fields

### ISSUE THREAD

**Issue by deadfoxygrandpa** [elm-lang/elm-compiler#541]
When aligning the new `Graphics.Input.Field` text fields with `flow right`, they are actually flowing down. This can be seen here, which shows the problem on Firefox, but works correctly on Chrome:

http://share-elm.com/sprout/5339695ae4b0e548f3686335

Similarly, `flow left` is the same as `flow up`

**Comment by pchiusano** [comment]
I encountered what seems like the same issue (Firefox ignoring styling on fields) here, against 0.14: http://share-elm.com/sprout/54a6abc1e4b05f9c59b24b99

```Elm
import Graphics.Input.Field as Field
import Color
import Signal
import Text

chan = Signal.channel Field.noContent

style1 : Field.Style
style1 =
  { padding = let s = Field.defaultStyle in s.padding
  , outline = { color = Color.red
              , width = Field.uniformly 3
              , radius = 0 }
  , highlight = Field.noHighlight
  , style = Text.defaultStyle }

main =
  let scene c = Field.field style1 (Signal.send chan) "w00t" c
  in Signal.map scene (Signal.subscribe chan)
```

**Comment by evancz** [comment]
I am trying to clean up the issues in this repo, so I am going through and closing a bunch of issues with ideas on how to get them done.

In this case, we should verify that the issue still manifests and if so, open an issue at https://github.com/elm-lang/core/issues and perhaps make a "Graphics" milestone or label so we can collect everything related to that in one place.
