### ISSUE TITLE
Feature request: Add signal with keyboard characters, not keycodes

### ISSUE THREAD

**Issue by jonashaag** [elm-lang/elm-compiler#565]
`Keyboard.lastPressed` and friends only give you the key *codes* of the pressed keys. A way to get the pressed *chars* would be very helpful. Otherwise, everyone who wants to implement some sort of text input would have to implement this conversion themselves (unnecessary work and error-prone, particularly with regard to shift/special keys).

I know there's `Graphics.Input.Field`, but it doesn't fit our usecase. (Thanks for fixing #563 anyway :-)

**Comment by evancz** [comment]
Adding to https://github.com/elm-lang/core/issues/322, thanks for the suggestion!
