### ISSUE TITLE
Char.fromCode should fail on non-character codes

### ISSUE THREAD

**Issue by jonashaag** [elm-lang/elm-compiler#566]
```
> import Char
> Char.fromCode 27
" : Char
```
Using `Char.fromCode` on a non-character keycode results in an "empty character" being returned. `Char.fromCode` should incorporate some way to handle these kind of errors in user code.

We also found out that the things that you get back from `Char.fromCode` aren't the same kind of characters that you get when typing a character literal:

```
> Char.fromCode 65
"A" : Char
> 'A'
'A' : Char
```

I don't think there's any issue with that, though :-)

**Comment by wetmore** [comment]
+1. There is some weirdness here. First of all, the empty character isn't actually returned; I'm not even sure such a thing exists, as you can't just construct a non-empty character via the literal `''`. For example the key code 18 corresponds to `alt` (weirdly, I get it in `Keyboard.presses` when I press `ctrl-r`). If you convert the result of `Char.fromCode 18` to a string and then compare it to the empty string, you'll get false:

````
> "" == (String.fromChar << Char.fromCode <| 18)
False : Bool
> String.isEmpty << String.fromChar << Char.fromCode <| 18
False : Bool
> String.length << String.fromChar << Char.fromCode <| 18
1 : Int
````

**Comment by evancz** [comment]
I don't think it is the right move to crash. There are some characters that do not have a visual representation, but I don't think that means `fromCode` should be changed.

I may be wrong about this, and if so, lets discuss it further on https://github.com/elm-lang/core/issues

Thanks for the issue!
