### ISSUE TITLE
Typography issue

### ISSUE THREAD

**Issue by yogsototh** [elm-lang/elm-compiler#569]
I would appreciated to have access to the "font-weight" CSS attribute. But I don't believe I have access to it. The same could be said about "line-height", "letter-spacing", "text-rendering", etc...

I understand that might make the Style datatype bigger, but typography is a complex thing and actual navigator rendering is unfortunately all we can use today.

A "LaTeX-like" system for typography would be incredible but I don't think our current browser are fast enough to support it correctly.

**Comment by evancz** [comment]
For now I'd recommend using `elm-html` for this kind of stuff. We may be breaking `Graphics.*` out of core at some point so we can experiment with doing things there more.
