### ISSUE TITLE
List Documentation Doesn't Describe Performance

### ISSUE THREAD

**Issue by maxsnew** [elm-lang/elm-compiler#594]
I'm working on making everything in the `List` module use constant stack space, but I noticed that none of the functions in the module describe their performance characteristics.

I can imagine this being very bad in some cases:
```haskell
head : [a] -> a
last : [a] -> a
```
A newbie might think these are both fast operations. A JS dev might think that `last` is constant time and `head` is O(n), when the reality is the opposite.

I think we should mention these but I don't know what kind of language to use/what we expect from users. Should we use big-O notation or terms like "constant time" and "linear time" or be more descriptive like "traverses the entire list"?

**Comment by evancz** [comment]
I am trying to make all the issues here directly about elm-compiler. This seems like a reasonable thing to add, so someone do a sample PR adding it to one function in `List` and we can go from there!
