### ISSUE TITLE
Can't use Module name prefix in record syntax.

### ISSUE THREAD

**Issue by jcollard** [elm-lang/elm-compiler#635]
Given a module:

```haskell
module Audio where

defaultTriggers = { timeupdate = False, ended = False }
```

An error occurs in another module when accessing defaultTriggers:

```haskell
module AudioTest where

import Audio

myTriggers = { Audio.defaultTriggers | timeupdate <- True }
```

The error is:

```
Parse error at (line X, column Y):
unexpected "A"
expecting whitespace, lower case variable or closing bracket '}'
```

It appears that it is expecting a lower case field name and doesn't know how to handle a field defined in another module.

The work around is to import `Audio(defaultTriggers)`.

**Comment by hoosierEE** [comment]
Another workaround, using a placeholder variable:

```elm
module AudioTest where

import Audio

placeholder = Audio.defaultTriggers
myTriggers = { placeholder | timeupdate <- True }
```

**Comment by evancz** [comment]
Alright, I am closing in favor of https://github.com/elm-lang/elm-plans/issues/16 which will track a couple things along these lines. It's good to have them all in one place. Furthermore, I think it's not making sense to have proposals in the elm-compiler repo anymore, so I am laying the groundwork for doing this in a better way. For now, please let me manage elm-plans, no new stuff there!

If there is more to say about this, we should continue the discussion here, not in the elm-plans issue!
