### ISSUE TITLE
Hot swap not working for image dimensions

### ISSUE THREAD

**Issue by ColonelJ** [elm-lang/elm-compiler#638]
In a simple example such as 'main = image 472 315 "/stack.jpg"' changing the image dimensions has no effect when using the hot swap feature.  (Tested on Firefox)  Note that it does seem to do hot swap for the actual image path.

**Comment by evancz** [comment]
Thanks for the report. Not sure if this is still true, but if so, please see if this has an open issuen on https://github.com/elm-lang/elm-lang.org/issues and if not, migrate this over there.
