### ISSUE TITLE
bad code gen for recursive, higher order functions

### ISSUE THREAD

**Issue by notnew** [elm-lang/elm-compiler#639]
Recursive functions aren't always compiled to javascript functions:

    fact = factHelp fact
    factHelp f n = if (n < 2) then n else n * f (n-1)

`fact` compiles to `var fact = factHelp(fact);`
and throws a runtime error since `fact` is undefined when it's passed to `factHelp`.

When the same function not written point free `fact' n = factHelp fact' n`,
it works as expected and compiles to:

     var fact$ = function (n) {
        return A2(factHelp,fact$,n);
     };

It's also a problem for partially applied point free functions `foo x = factHelp (foo x)`.  But in this case a `foo` becomes a function that takes 1 argument when it should take 2 and the stack is exhausted.  I think the correct behavior would be to use a variable's type to determine what arity javascript function is generated for the variable.

**Comment by evancz** [comment]
Centralize this into #873 which describes possible fixes.
