### ISSUE TITLE
Duplicate signals when using WebSocket library

### ISSUE THREAD

**Issue by jacknojo** [elm-lang/elm-compiler#643]
The following code demonstrates how sending a single message to a public echo websocket server results in two signals being triggered:

http://www.share-elm.com/sprout/5390b772e4b07afa6f981bac

I have verified with a local websocket server that only one string is recieved per click, so the second one must originate from within the elm runtime.

According to a poster (Jeff Smits) at https://groups.google.com/forum/#!topic/elm-discuss/_F6JtKARsuQ this is a bug, so I am posting it here.

**Comment by evancz** [comment]
The `WebSockets` library is no longer in core, this will be done with the `Task` API in a community library.
