### ISSUE TITLE
No Array.remove

### ISSUE THREAD

**Issue by maxsnew** [elm-lang/elm-compiler#646]
This is a pretty useful function `Array.remove : Int -> Array a -> Array a` that would match the function in Dict. I currently am using this definition to get around it using slice:
```haskell
remove : Int -> Array.Array a -> Array.Array a
remove n arr = Array.append (Array.slice 0 n arr) (Array.slice (n+1) (Array.length arr) arr)
```
but I don't know enough about the array library to know how much this could be improved by a manual implementation.

**Comment by evancz** [comment]
Adding to https://github.com/elm-lang/core/issues/322
