### ISSUE TITLE
Unsound type inference for extensible records

### ISSUE THREAD

**Issue by tomprimozic** [elm-lang/elm-compiler#656]
Hi! I recently tried implementing the type inference algorithm as described in Daan Leijen's paper Extensible records with scoped labels. I also implemented an optimized version, and knowing that Elm is based on the same research, I checked out how type inference is implemented for Elm. I think the implementation is wrong.

This is an example code that demonstrates the problems:

```elm
choose i x y = if i > 0 then x else y

test1 r s = choose 0 {r | a = 1} {s | b = True}

wrong1 = (test1 {x = 1.0, b = True} {a = 2.0}).x

test2 r = choose 1 {r | x = 1.0} {r | y = "AAA"}

wrong2 = test2 {x = 16.0, y = "bce"}

main = plainText (join " " ["a", show wrong1, "c", show wrong2, "e"])
```

In particular, the type of `test1` should be `{a | b : Bool} -> {a | a : number} -> {a | b : Bool, a : number}`, but Elm infers `{a | b : Bool} -> {b | a : number} -> {a | b : Bool, a : number}` (note the different row variable in the second argument) while typing `test2` should result in an error due to recursive row types.

I think the bug is in the implementation [`actuallyUnify`][1]. To solve the first issue, the extension row variables of `record1'` and `record2'` should not be distinct, but one and the same variable. To solve the second issue, after `unify' record1' ext2`, `ext1` (which must be a variable) has to be checked; if it is not unbound, it means that the types are recursive and should be rejected.

For comparison, you can check out [my implementation][2] (in OCaml).

[1]: https://github.com/elm-lang/Elm/blob/master/compiler/Type/Unify.hs#L189

[2]: https://github.com/tomprimozic/type-systems/blob/master/extensible_rows2/infer.ml#L127

**Comment by evancz** [comment]
Record extension no longer exists in the syntax of the master branch (though the type system works exactly the same). Will this issue be possible if there is no record extension?

**Comment by evancz** [comment]
Commit a28acb2 makes [the revision suggested by @tomprimozic](https://github.com/elm-lang/elm-compiler/blob/a28acb21900535f3229e7ef924856b70298870c5/src/Type/Unify.hs#L609-L615) from the very beginning.

I think this is resolved, but I'd like to wait to close until this gets merged into master.
