### ISSUE TITLE
Rotating forms created from shapes over time does not work.

### ISSUE THREAD

**Issue by phischu** [elm-lang/elm-compiler#665]
The following gives unexpected results in the online editor as well as when compiled and served with elm-server.

    blacksquare : Form
    blacksquare = filled black (square 400)

    yogi : Form
    yogi = toForm (image 200 200 "yogi.jpg")

    rotating : Form -> Time -> Form
    rotating form t = rotate (degrees (inMilliseconds t)) form

    canvas : Time -> Element
    canvas t = collage 500 500 [rotating blacksquare t,rotating yogi t]

    main : Signal Element
    main = lift canvas (every (20*millisecond))

While the yogi rotates the square does not. Other forms created from shapes (ngon, oval, rect, polygon) do not rotate either while other forms created from elements (with toForm) work fine.

**Comment by evancz** [comment]
Seems like @mgold resolved this one, thanks!

**Comment by jvoigtlaender** [comment]
Doesn't sound to me like the issue is really resolved. Max confirmed that of the two forms that both should rotate, only one does. I also just checked that the same is still the case, with the following slightly updated program:
```elm
import Graphics.Element exposing (..)
import Graphics.Collage exposing (..)
import Color exposing (..)
import Time exposing (..)
import Signal exposing (..)

blacksquare : Form
blacksquare = filled black (square 400)

yogi : Form
yogi = toForm (image 200 200 "imgs/yogi.jpg")

rotating : Form -> Time -> Form
rotating form t = rotate (degrees (inMilliseconds t)) form

canvas : Time -> Element
canvas t = collage 500 500 [rotating blacksquare t, rotating yogi t]

main : Signal Element
main = map canvas (every (20*millisecond))
```
Max's suspected explanation is that trigonometry functions on large inputs are buggy. Maybe that does need a fix?

**Comment by evancz** [comment]
I think he was saying that rotating from 120912000 degrees to 120913000 degrees is unlikely to produce smooth animations unless it happens to line up with your screens refresh rate or something weird. Our rotation stuff is just using typical JS functions as far as I know.

If I am misunderstanding, let's open an issue on core describing the particular inaccuracies.

**Comment by jvoigtlaender** [comment]
The funny thing with the above code, though, is that it's not a matter of smooth or non-smooth animations. Instead, there is no movement, of one of the two forms, *at all*. So maybe the explanation is that not only are the trigonometry functions "glitching", or whatever, when going from 120912000 degrees to 120913000 degrees, but instead it seems that above a certain number, maybe 120000000, all results will be constant. (All this, if @mgold's hunch about the trigonometry functions being responsible is correct.)

Plus, it is somewhat strange that only some rotations are affected, others not. So why is there no visual difference between 
* `rotate (degrees 120912000) (filled black (square 400))` and 
* `rotate (degrees 120913000) (filled black (square 400))`,

while there is between 
* `rotate (degrees 120912000) (toForm (image 200 200 "imgs/yogi.jpg"))` and 
* `rotate (degrees 120913000) (toForm (image 200 200 "imgs/yogi.jpg"))`?

**Comment by jvoigtlaender** [comment]
Moved over to https://github.com/elm-lang/core/issues/335.
