### ISSUE TITLE
Elm breaks in surf browser

### ISSUE THREAD

**Issue by recrag** [elm-lang/elm-compiler#676]
Using the surf browser (www.suckless.org) from under Linux, about half of the examples in the elm-lang.org site do not work.  For example, the games which utilize moving collage elements cannot run because the main window "shakes back and forth" as the fps is updated (the scrollbars on the right and bottom appear then disappear rapidly).  Second, the text fields all enter text reversed!  To get the zip code example working, one must enter the zipcode backwards!

What could be causing this?  Surf uses the same webkit library that chromium uses under Linux (the elm-lang examples work under chromium in Linux).  On debian you can download with apt-get install surf, but a never version is available from suckless.org.

Is there an easy workaround?

Thanks.

**Comment by evancz** [comment]
I need to consider browser marketshare when prioritizing fixes. I'm going to close this in favor of an issue about pinning down specific browsers that are supported or not. From there we can create milestones for any browsers we want to add support for and track progress.
