### ISSUE TITLE
Path/shape shadow function

### ISSUE THREAD

**Issue by andreywix** [elm-lang/elm-compiler#679]
It would be great if Elm supported a functionality for adding shadows to various objects in Graphics.Collage.

**Comment by evancz** [comment]
I agree that this would be a nice addition. For now I'd recommend trying to do it with `elm-svg`.

We are collecting a bunch of ideas along these lines in https://github.com/elm-lang/core/issues/322 and one of them is to break `Graphics.*` out into its own package so we can experiment more with these things https://github.com/elm-lang/core/issues/324
