### ISSUE TITLE
'undefined is not a function' when trying to reference a variable

### ISSUE THREAD

**Issue by theburningmonk** [elm-lang/elm-compiler#681]
In this line:
https://gist.github.com/theburningmonk/32aebb3d42eeb0d20fe1#file-gistfile1-txt-L191
if I try to reference `groundH` (defined towards the top) instead, I get an error:

    undefined is not a function
        Open the developer console for more details.

when I try to run the application, with both `elm-server` and the online editor.

**Comment by evancz** [comment]
Without a minimal reproduction I'm not sure how to resolve this. If it can be gotten down smaller please report it at https://github.com/elm-lang/core/issues
