### ISSUE TITLE
Can't Reexport Values

### ISSUE THREAD

**Issue by maxsnew** [elm-lang/elm-compiler#693]
Internal.elm
```haskell
module Internal (foo) where

foo = 3
```
Public.elm
```haskell
module Public (foo, bar) where
import Internal (..)
bar = 4
```
Main.elm
```haskell
module Main where
import Public (..)
main = asText <| foo + bar
```
Running
```
$ elm -m Main.elm
```
gives
```
[1 of 3] Compiling Internal            ( Internal.elm )
[2 of 3] Compiling Public              ( Public.elm )
Export Error: trying to export non-existent values: foo
```

so you can't re-export anything.

Re-exporting is extremely useful since it lets you separate the way the implementation is organized with the way people use your modules. For instance, in my `IO` library, I have two modules `IO.IO` which includes data structure definitions and the `IO` actions like `putStrLn, exit` while the `IO.Runner` module includes the code for the actual message passing over ports. Users of the library have to import both modules to use functions from them instead of me putting them all in some big `IO` module or something. The alternative is to just dump everything into one big file which is undesirable.

**Comment by evancz** [comment]
Moving this to #931
