### ISSUE TITLE
Close WebSocket on onbeforeunload

### ISSUE THREAD

**Issue by andreywix** [elm-lang/elm-compiler#708]
Hello,
I just noticed that different browsers react differently on refresh/close of a window respectively:

**Chrome:** ```ConnectionClosed``` / doesn't close
**Safari:** doesn't close / doesn't close
**Firefox:** ```ConnectionClosed``` / ```ConnectionClosed```

So, I was wondering if you could fix that behavior by adding something similar to this to Elm: 
http://stackoverflow.com/a/4818541/1544803

Thank you!

**Comment by evancz** [comment]
The `WebSockets` library no longer lives in core, so this will be handled by a community library.
