### ISSUE TITLE
Elm allows invalid JavaScript identifier names; runtime failure

### ISSUE THREAD

**Issue by jastice** [elm-lang/elm-compiler#710]
Elm allows identifier names such as `x²`, and uses them verbatim as JS variable names. However, because JS doesn't allow this name, it fails at runtime: `Uncaught SyntaxError: Unexpected token ILLEGAL`

I would expect Elm to either enforce the same identifier restrictions, or transform them at compilation (as it does with JavaScript reserved words).

[For reference: Post about legal characters in JS identifiers](http://mathiasbynens.be/notes/javascript-identifiers#valid-identifier-names)

**Comment by jastice** [comment]
Just confirmed issue as still existing in Elm 0.16. 
Specifically the `x²` identifier still causes a runtime error:

    SyntaxError: illegal character JavaScript.elm:6681:8

Most other invalid identifiers I have tried cause a (slightly confusing) compile error instead:

```
I ran into something unexpected when parsing your code!

13│ x🎃 = 23
     [31m^[0m
I am looking for one of the following things:

    a pattern
    an equals sign '='
    more letters in this name
    whitespace
```

**Comment by evancz** [comment]
Track in #1377

**Comment by cdeszaq** [comment]
1. If Elm truly intends not to be coupled to JS as it's kernel, defining Elm's set of valid characters as "the same as JS" seems antithetical to that intention.
2. Restricting the character set may add linguistic barriers to Elm. I understand that keeping the valid character set restricted reduces the surface area for possible problems, and prevents devs from shooting themselves in the foot with "creative" names, but is that level of safety worth the restriction on those who's language does not fit into the JS box?

**Comment by mgold** [comment]
It's always possible to expand the set of allowed characters later. The more urgent concern is if we're allowing a character that we don't like, which was the case with `'`.
