### ISSUE TITLE
Browser/Tab becomes unresponsive with multiple textured signal-dependent objects

### ISSUE THREAD

**Issue by jastice** [elm-lang/elm-compiler#724]
The following program causes the Chrome tab to become extremely unresponsive, while Firefox essentially locks up before even showing the scene. 

This only happens when 
* there are at least 2 objects in the collage 
* it depends on a signal
* they are textured

One object will run just fine even when I use `(fps 40)` instead of `Mouse.clicks`

```elm
import Mouse
import Graphics.Collage (..)
import Signal ((<~),foldp)
import Time (fps)

texture = "https://raw.githubusercontent.com/elm-lang/elm-lang.org/master/resources/book.jpg"

scene x = 
  let t1 = square 100 |> textured texture |> move (x,0)
      t2 = square 66 |> textured texture |> move (0,200-x)
  in collage 800 800 [t1,t2]

ticks = foldp (\click total -> total + 1) 0 Mouse.clicks
-- ticks = foldp (\click total -> total + 1) 0 (fps 40)
main = scene << toFloat <~ ticks
```

(updated for elm-platform 0.14.1, elm-reactor 0.3)

**Comment by evancz** [comment]
It looks like this has been reported in core in another form, so I am just going to mention https://github.com/elm-lang/core/issues/332 so we can look back and review if we caught this case. Thanks for the report!
