### ISSUE TITLE
Events outpacing elm's handler (Losing keystrokes on input field)

### ISSUE THREAD

**Issue by rehno-lindeque** [elm-lang/elm-compiler#727]
Sometimes when typing too fast while some heavy background processing is going on, an input field will lose some of its keystrokes. For instance, on my machine, typing `"abcd"` fast in http://library.elm-lang.org/catalog/elm-lang-Elm/0.12.3/ will result in `"acd"` displayed in the input box.

Reference threads:
* [real time search swallows typed characters](https://groups.google.com/forum/#!searchin/elm-discuss/diff$20dobi/elm-discuss/Lm-M-PPM2zQ/jQUsm9kcqkQJ)
* [Elm's input loses key strokes](https://groups.google.com/forum/#!topic/elm-discuss/7uylQZzbz4w)

**Comment by evancz** [comment]
Mentioning https://github.com/elm-lang/core/issues/332 so we can see all the `Graphics.*` issues in one place and so the compiler issues gets cleaned out and focused on compiler stuff.
