### ISSUE TITLE
documentation for "link" is wrong - compiler gives bad type info as error

### ISSUE THREAD

**Issue by KevinBrogan** [elm-lang/elm-compiler#743]
`test = link "http://elm-lang.org" ("Elm Website")`
`main = plainText ""`

> [1 of 1] Compiling Main                ( HelloWorld.elm )
> Type error on line 1, column 36 to 49:
> "Elm Website"
> 
> Expected Type: Element
> Actual Type: String

Okay, sorry I gave you a String, Let me give you an Element...

`test = link "http://elm-lang.org" (plainText "Elm Website")`
`main = plainText ""`

> *no error*

Alright, good... but the documentation says link wants a "Text" not an "Element"

`test = link "http://elm-lang.org" (toText "Elm Website")`
`main = plainText ""`

> [1 of 1] Compiling Main                ( HelloWorld.elm )
> Type error on line 1, column 36 to 42:
>         toText
> 
>    Expected Type: Text
>      Actual Type: Element

Okay this is getting weird. The actual type is now a text instead of an element, but the compiler is telling me that the expected type is the actual type and the actual type is the expected type...

So when things get weird, I start checking version numbers. I notice that when ElmServer is launched, it states that it's version is 0.11.0.1.

> Elm Server 0.11.0.1: Just refresh a page to recompile it!
> Listening on http://0.0.0.0:8000/

I don't know if the documentation changed, the api changed, or what. I used the Windows installer provided from https://www.dropbox.com/s/qzcm9yyve54ss1l/Elm-Platform-0.12.3.exe and it installed to "C:\Program Files (x86)\Elm Platform\0.12.3\bin\elm-server.exe", but the version number doesn't match.

So right now I don't know which of the three things is wrong. Am I running outdated software? If so does the new compiler get the type information correct? Is the documentation wrong?

**edit**

I checked the Elm version. It is 0.12.3. So Elm and Elm-Server have different versions...

I'm not sure if the elm-server delegates to elm or if it compiles on it's own so I manually compiled with elm, still getting the same errors.

The documentation is definitely wrong, and the compiler is outputting contradictory error information.

**Comment by evancz** [comment]
Sorry for the very slow response :(

I think the root issue here was that both `Text.link` and `Graphics.Element.link` were exported unqualified by default at the time you opened this issue. There was also a bug where we were not able to report ambiguous usages of imported variables, so it was just picking one of the `link` functions and going with that. I suspect this issue no longer exists, but if it does, definitely report it at https://github.com/elm-lang/core/issues or https://github.com/evancz/error-message-catalog/issues
