### ISSUE TITLE
bug with input events from within collage?

### ISSUE THREAD

**Issue by jvoigtlaender** [elm-lang/elm-compiler#747]
The following doesn't work as it supposedly should:

```haskell
import Graphics.Input (..)

i = input ()

foo = move (40,0) (toForm (clickable i.handle () <| asText "foo"))

counter = count i.signal

-- Given the above, clicking on the "foo" text should always increment the counter.

bar1 = toForm (asText "bar")
bar2 = outlined (solid black) (circle 5)

-- However, this doesn't work:

main = (\c -> flow down [ asText c
                        , collage 150 20 [foo, bar2]
                        ]) <~ counter

-- Strangely enough, after replacing [foo, bar2] by any of
-- [foo, bar1], [bar1, foo], [bar2, foo], it does work.
```
On mailing list: https://groups.google.com/d/msg/elm-discuss/zoe1KKLE4qA/UwmxMuNaibsJ

**Comment by evancz** [comment]
Not sure if this is still relevant, but I am trying to make all the issues here directly about elm-compiler. If you can reproduce this please open an issue or PR on elm-lang/core

Mentioning elm-lang/core#332 so folks can find this more easily.

**Comment by jvoigtlaender** [comment]
Yes, the issue is still relevant, I moved it over to https://github.com/elm-lang/core/issues/334.
