### ISSUE TITLE
takeWhile and dropWhile are Missing

### ISSUE THREAD

**Issue by maxsnew** [elm-lang/elm-compiler#752]
Just came across a case where I needed this. Looking https://github.com/elm-lang/Elm/pull/298 and https://github.com/elm-lang/Elm/pull/383 it looks like they're not added because you don't like the API?

I think these are 2 very useful and intuitive functions so why don't we just add them then.

**Comment by evancz** [comment]
Let's do stuff like this in a `list-extra` package, and talk about bringing them into core on the now-split out repo for that.
