### ISSUE TITLE
Firefox rerenders canvas even though nothing is modified in collage

### ISSUE THREAD

**Issue by andreywix** [elm-lang/elm-compiler#754]
Hi, I've been optimizing my program, and have been trying to use the feature where there are no dom rerendering (removing and adding) of canvas if none of the forms in collage are changed. I've had a great success in Webkit based browsers, however Firefox for some reason is ignoring the fact that nothing has changed.
Is it a bug or is it something you have no control of? Thank you!

**Comment by evancz** [comment]
Hey, sorry I did not get back to you on this.

If the issue you describe in your second posts still exists, definitely open a PR to https://github.com/elm-lang/core/ to fix it!

I'm not sure if the initial thing still is a problem. We do not do super smart diffs on collage at the moment. If you are still running into issues with this, I'd recommend asking folks on the elm-discuss mailing list about this and maybe opening an issue at https://github.com/elm-lang/core/issues describing what steps we can take to improve this.
