### ISSUE TITLE
Bad Error Message for qualified Operators

### ISSUE THREAD

**Issue by maxsnew** [elm-lang/elm-compiler#770]
When you use an operator that you have imported qualified, the error message tells you to just make it qualified, which doesn't work.

Example. Module 1:
```
module Operator where
x +++ y = "what"
```
```
module Main where

import Operator

main = plainText <| 1 +++ "huh"
```
you get the error message
```
Error on line 5, column 21 to 32:
Could not find variable '+++'.
Close matches include: Operator.+++
```
But that suggestion is obviously invalid since `Operator.+++` won't parse.
Should be easy to fix, probably just check in this error message if it's an operator and if so suggest importing the operator unqualified.

**Comment by evancz** [comment]
I think this should live on https://github.com/elm-lang/error-message-catalog/issues
