### ISSUE TITLE
Centering of elements with odd pixel width / height looks off

### ISSUE THREAD

**Issue by pchiusano** [elm-lang/elm-compiler#773]
http://share-elm.com/sprout/53fe3a0ee4b0d19703e96be3

I expect this code to generate a white square with a 1 pixel black border, as I'm adding an extra two pixels to the width and height and placing a white spacer in the center:

~~~ Haskell
import Window

main =
  let inner = color white (spacer 30 30)
      bordered = container (widthOf inner + 2) (heightOf inner + 2) middle inner
              |> color black
      layout (w,h) = container w h middle bordered
  in layout <~ Window.dimensions
~~~

Instead, I get, on Chrome:

![screen shot 2014-08-27 at 4 06 32 pm](https://cloud.githubusercontent.com/assets/11074/4066676/17ed1bd2-2e26-11e4-9e03-d41b7c82dd28.png)

This is latest Chrome build 36.0.1985.143. This is a Macbook Air with a non-retina display. [Specs](http://www.everymac.com/systems/apple/macbook-air/specs/macbook-air-core-i5-1.3-13-mid-2013-specs.html).

On Safari, there seems to be a similar issue, but it's not noticeable unless I zoom in:

![screen shot 2014-08-27 at 4 16 36 pm](https://cloud.githubusercontent.com/assets/11074/4066753/124e307a-2e27-11e4-9969-7f4f8a712a99.png)

And in Firefox, it looks like what I expect, even on zoom:

![screen shot 2014-08-27 at 4 15 59 pm](https://cloud.githubusercontent.com/assets/11074/4066746/01b1e0f4-2e27-11e4-921c-6ac2d5fc17d1.png)

**Comment by evancz** [comment]
Not sure if this is still relevant, but I am trying to make all the issues here directly about elm-compiler. If you can reproduce this please open an issue or PR on elm-lang/core

Mentioning elm-lang/core#332 so folks can find this more easily.
