### ISSUE TITLE
Graphics.Input.clickable does not work with 'layers'

### ISSUE THREAD

**Issue by openaki** [elm-lang/elm-compiler#775]
If multiple clickable elements are layered using 'layer' the signal value for the last element is delivered everywhere. This does not happen if the elements are 'flow'ed Down.

```
import Graphics.Input as Input

type State = {v : Int}
initState = {v = 0}

clickTest : Input.Input Int
clickTest = Input.input 0

display {v} = flow DDown [asText v, squareElem] 

step : Int -> State -> State
step n v = {v | v <- n}

main = lift display <| foldp step initState clickTest.signal

-- This works
-- squareElem = flow DDown squares

-- But this just shows 2 no matter where the mouse is clicked
squareElem = layers squares


squares =  
  zipWith (\n c -> Input.clickable clickTest.handle n (sq n c))
            [0..2] [lightGreen, lightBlue, lightRed]

sq n c = collage 500 500 [move (0, toFloat (60*n)) <| filled c <| square 50]

```

**Comment by evancz** [comment]
Not sure if this is still relevant, but I am trying to make all the issues here directly about elm-compiler. If you can reproduce this please open an issue or PR on elm-lang/core

Mentioning https://github.com/elm-lang/core/issues/332 so folks can find this more easily.
