### ISSUE TITLE
Elm Homebrew formula

### ISSUE THREAD

**Issue by peeb** [elm-lang/elm-compiler#776]
It would be good if users of Mac OS X could install Elm via the [Homebrew package manager](https://github.com/Homebrew/homebrew), like so:
```
$ brew install elm
```
It seems that this could be implemented as a so-called "bottled" homebrew package which would avoid the need to depend on the entire Haskell Platform and Cabal. Also, `elm-repl`'s dependency on Node.js could be managed by Homebrew.

I'd be happy to volunteer to do (and maintain) this work.

Thoughts?

**Comment by evancz** [comment]
Alright, I am going to close as an issue that it is not possible to address in this repo. I have seen some discussions about getting this kind of thing maintained since this issue, and I think we'd need to do it as part of elm-platform or ideally as an independently maintained thing.

**Comment by taoeffect** [comment]
So what's the verdict on this? Virtually all programming languages/platforms are installed via Homebrew on OS X since that makes clean upgrades and uninstalls possible, and it adds a level of security to the installation. .pkgs are discouraged.

**Comment by avh4** [comment]
A proper homebrew formula would be welcome, but the issue should be tracked in the elm-platform repo https://github.com/elm-lang/elm-platform instead of here.

**Comment by vtsatskin** [comment]
Elm can be installed using [Homebrew Cask](http://caskroom.io/):

```
brew cask install elm-platform
```

**Comment by harlantwood** [comment]
This is broken, at least for me, now:

```
==> Downloading http://install.elm-lang.org/Elm-Platform-0.18.pkg

curl: (6) Could not resolve host: install.elm-lang.org
Error: Download failed on Cask 'elm-platform' with message: Download failed: http://install.elm-lang.org/Elm-Platform-0.18.pkg
```
