### ISSUE TITLE
Prepending to arrays

### ISSUE THREAD

**Issue by JasonJAyalaP** [elm-lang/elm-compiler#784]
Arrays currently have no prepend feature. Could this be implemented with no performance cost?

**Comment by evancz** [comment]
The way arrays work is with a bunch of JS arrays of length 32. Sliding things down one may be fairly expensive, but we'd need to benchmark to know for sure.

In any case, if there is concrete action we should take on this, lets talk about it at https://github.com/elm-lang/core/issues
