### ISSUE TITLE
Not possible to remove the underline from links in Elm 0.13

### ISSUE THREAD

**Issue by grzegorzbalcerek** [elm-lang/elm-compiler#788]
The following program shows a link that is underlined:
import Text as T
main = T.toText "elm-lang.org" |> T.link "http://elm-lang.org" |> T.style T.defaultStyle |> centered
I would expect, that applying the defaultStyle to a link would remove the underline.

**Comment by evancz** [comment]
I'd recommend using `elm-html` for this for now. We may be doing this idea https://github.com/elm-lang/core/issues/324 which would mean we could do a lot more experimentation with the `Graphics` API.
