### ISSUE TITLE
Elm website page and iPad

### ISSUE THREAD

**Issue by rikvdkleij** [elm-lang/elm-compiler#794]
Hi,

I noticed when using my iPad and going to this page:
http://elm-lang.org/learn/What-is-FRP.elm
that particular page does not respond to clicks on links. Links on all other pages of the Elm website are okay.

When I click on link, it becomes active (turns red). `Mouse.position` is set but `Mouse.clicks` is not increased. Because it works on other devices I tried, it must be something weird. The click event is not "swallowed" because link turns red, but the reaction on click is "swallowed". It looks like it has something to do with the example code on this page.

Regards,
Rik

**Comment by evancz** [comment]
Thanks for the report! This should be "fixed" in the sense that page no longer exists in its initial form. Sorry for the slow response on this!
