### ISSUE TITLE
Input fields in container are not centered correctly

### ISSUE THREAD

**Issue by menelaos** [elm-lang/elm-compiler#800]
There seems to be a problem with the centering of input fields. 

http://share-elm.com/sprout/5429b8b4e4b017b21db2f699

    import Graphics.Input ( Input, input )
    import Graphics.Input.Field ( Content, noContent, field, defaultStyle, uniformly)

    queryInput : Input Content
    queryInput = input noContent

    queryField : Element
    queryField = field
        { defaultStyle | padding <- uniformly 15
                       , outline <- {color=red,width=uniformly 1,radius=4 }
        }
        queryInput.handle
        identity
        "Search"
        noContent

    bar : Element
    bar = color grey <| container 500 30 middle <| color green <| spacer 150 30

    main : Element
    main =
       flow down
           [ bar
           , color orange <| container 500 66 middle <| queryField
           , bar
           ]

As you can see, the input field is neither vertically nor horizontally centered.

**Comment by chrisberragan** [comment]
It looks like the elm-lang site uses a function called "center" to achieve this: http://elm-lang.org/edit/Elm.elm

```
center elem =
    container outer (heightOf elem) middle elem
```

**Comment by evancz** [comment]
Mentioning https://github.com/elm-lang/core/issues/332 so we can track all the `Graphics.*` issues in one place *and* clear out the issues on the compiler repo to be more focused. Thanks for the report!
