### ISSUE TITLE
Graphics.Input.Field.email - fails to update input signal

### ISSUE THREAD

**Issue by marklar** [elm-lang/elm-compiler#805]
The function is provided here:
+ https://github.com/elm-lang/Elm/blob/master/libraries/Graphics/Input/Field.elm#L162

The "email" field renders properly, but the signal of the Input provided for it doesn't update.

Example:

    import Graphics.Input as I
    import Graphics.Input.Field as F

    input = I.input F.noContent

    -- On the next line, change `F.email` to `F.field`, and the input.signal updates fine.
    field = F.email F.defaultStyle input.handle identity "Email" <~ input.signal

    page element value = flow down [ element, asText value ]

    main = page <~ field ~ input.signal

**Comment by evancz** [comment]
Closing because this API has changed. I am going to mention https://github.com/elm-lang/core/issues/332 in case this kind of thing is still an issue though!
