### ISSUE TITLE
Detect repeat argument names at compile time

### ISSUE THREAD

**Issue by rudi-c** [elm-lang/elm-compiler#809]
The following code

```elm
sum x x = x + x
mySum = sum 1 2
```

Generates the error

```
Uncaught SyntaxError: Strict mode function may not have duplicate parameter names
```

Which is good, except that the error message appears only in the console. Instead, the webpage only shows
```
Cannot read property 'make' of undefined
    Open the developer console for more details.
```

Which makes debugging really confusing.

**Comment by thSoft** [comment]
This has bit me multiple times! Also happens when declaring a local variable with the same name as an argument:

```elm
update action model =
  let result =
        (model, effects)
      (updatedSubmodel, effects) =
        Subcomponent.update action model.submodel
      model = -- should be updatedModel
        { model | submodel <- updatedSubmodel }
  in result
```

**Comment by Apanatshka** [comment]
I guess there are two parts to this:

1. shadowing allows you to define `model` again in the `let`. 
2. declarations can be recursive, so you can use `model` again in the right-hand side, but since this is a value, the recursive definition should be disallowed.

**Comment by jvoigtlaender** [comment]
Are the previous two comments really placed correctly in this issue here? Don't they belong to #829 / #1018 instead?

Look at the opening comment of this issue. It is about a very specific situation that is not what you (@thSoft and @Apanatshka) are talking about here.

**Comment by thSoft** [comment]
Sorry, you're right, @jvoigtlaender. Should I delete my comment?

**Comment by mgold** [comment]
As for the original issue, I remember seeing something similar. Can someone please verify that the issue exists in the 0.16 alpha?

**Comment by mgold** [comment]
It still exists in 0.16-alpha3. In the repl:
```
> sum x x = x + x
/<PATH SNIPPED>/repl-temp-000.js:6039
   var sum = F2(function (x,x) {    return x + x;});
                            ^

SyntaxError: Duplicate parameter name not allowed in this context
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:404:25)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:457:10)
    at startup (node.js:136:18)
    at node.js:972:3

```

**Comment by yblein** [comment]
Also the following code
```
sum x (x, y) = x + y
mySum = sum 1 (2, 3)
```
does *not* produce an error. Instead, mySum is equal to 5.
I guess this kind of multiple binding should be prevented too?

**Comment by mgold** [comment]
Yes, there is no sensible way to interpret that definition.
