### ISSUE TITLE
Unchecked range in Array.slice results in undefined value

### ISSUE THREAD

**Issue by nulldatamap** [elm-lang/elm-compiler#815]
For Arrays bigger than 32 elements all attempts to slice it from an index bigger or equal to it's size to another index bigger or equal to it's size it results in an `undefined` value being passed around resulting in an ugly crash.

I assume that this has to do with the fact that at 32 elements the array is split into a tree of arrays and the indices aren't handled properly. The `undefined` value comes from
```javascript
var sliced = sliceRight(to - (right > 0 ? a.lengths[right - 1] : 0), a.table[right]);
~~~~~~~ in Elm.Native.Array.sliceRight ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
```
Where the  `right` value is out of index ( which comes from `var right = getSlot(to, a);` )

This expression demonstrates the error:
```haskell
Array.slice 32 32 <| Array.repeat 32 0
```
Which will crash Elm with this error:
```
array is undefined
    Open the developer console for more details.
```

**Comment by evancz** [comment]
I am trying to clean up the issues in this repo. It looks like we should make sure that this is still a problem, and if so, migrate the report to https://github.com/elm-lang/core/issues or just fix the thing in a PR.
