### ISSUE TITLE
Allow partial application of types

### ISSUE THREAD

**Issue by pchiusano** [elm-lang/elm-compiler#819]
In 0.13: 

``` Elm
data Foo a = Foo a

type Blah = Foo

f : Blah Int -> Blah Int
f (Foo x) = Foo (x + 1)
```

This yields: `Type alias 'Main.Blah' expects 0 type arguments but was given 1`. I'd expect either a) an error pointing to the type alias, saying I've underapplied Foo, or b) my strong preference would be that it just works as written, as in Haskell, and analogous to how aliasing of values works.

[gist](http://share-elm.com/sprout/544a71b8e4b00800031fe243)

**Comment by evancz** [comment]
I don't have plans to do this, but I think https://github.com/elm-lang/elm-compiler/issues/1039 covers it well enough. If those kinds of extensions were added, it'd make sense to consider this as well.
