### ISSUE TITLE
problem generating human-readable names for "comparable" types

### ISSUE THREAD

**Issue by pchiusano** [elm-lang/elm-compiler#821]
I became curious about how to write a function that accepts multiple comparable values. First I decided to see what was inferred:

```Elm
> f x y p q = (x < y, p < q)
<function>
 : comparable -> comparable -> comparable -> comparable -> (Bool, Bool)
> f 1 2 "hi" "bye"
(True,False) : (Bool, Bool)
> f : comparable -> comparable -> comparable -> comparable -> (Bool,Bool)
```

That inferred signature can't be right though, since the same type variable is used throughout. In fact, if I give this as the annotation, I get a type error (as expected) when calling it with two distinct types.

Here's another example that somehow typechecks:

```
f : comparable -> comparable -> comparable1 -> comparable2 -> (Bool, Bool)
f x y p q = (x < y, p < q)

ex = f 1 2 "hi" "blah"
```

I don't really know what's going on here but it seems like something is buggy.

**Comment by evancz** [comment]
Alright, this is resolved on the `type-fixes` branch which I'm working on merging into master now. Here's what I'm seeing in the REPL:

```
$ elm-repl
---- elm repl 0.16.0 -----------------------------------------------------------
 :help for help, :exit to exit, more at <https://github.com/elm-lang/elm-repl>
--------------------------------------------------------------------------------
> f x y p q = (x < y, p < q)
<function>
    : comparable
      -> comparable -> comparable' -> comparable' -> ( Bool, Bool )
> f 1 2 "hi" "bye"
(True,False) : ( Bool, Bool )
> f
<function>
    : comparable
      -> comparable -> comparable' -> comparable' -> ( Bool, Bool )
> 
```

And the example program you gave is resulting in an error now as well.

Thanks for the report!
