### ISSUE TITLE
</script> in strings

### ISSUE THREAD

**Issue by nathan** [elm-lang/elm-compiler#822]
If you include the sequence `</script>` in a string or markdown literal, the compiler should escape it in the generated JavaScript. Otherwise, it gets interpreted by the browser as the end tag for the script.

```elm
main = asText "</script>"
```

```elm
main = asText [markdown|</script>|]
```

**Comment by evancz** [comment]
Thanks for the report, mentioning https://github.com/elm-lang/core/issues/332 so we can figure out how to fix this!
