### ISSUE TITLE
Module name collision in generated code

### ISSUE THREAD

**Issue by evancz** [elm-lang/elm-compiler#826]
As it is, each module is attached to Elm according to its name, so `Search.View` becomes `Elm.Search.View`.

This becomes problematic when there are many packages involved that may have modules with the same names. For example, if there's a private `Utils` module in `evancz/focus` and in `evancz/automaton`, the module that wins at runtime depends on what order things were compiled.

The solution is to use fully qualified names in generated code, so `Utils` would be `Elm.evancz.focus.Utils` or something like that.

**Comment by joaalto** [comment]
I just ran into a module name collision. I'm using [rluiten/elm-date-extra](http://package.elm-lang.org/packages/rluiten/elm-date-extra/3.0.0) in an hour reporting app I'm writing. Then I needed some UI components and decided to bring in [Elm-UI](https://github.com/gdotdesign/elm-ui). Unfortunately this doesn't work, as Elm-UI depends on [mgold/elm-date-format](http://package.elm-lang.org/packages/mgold/elm-date-format/1.1.3/), and both `elm-date-format` and `elm-date-extra` have a module called `Date.Format`:

```
I found multiple modules named 'Date.Format'.

Module 'Ui.DatePicker' is trying to import it.

Modules with that name were found in the following locations:

    package mgold/elm-date-format
    package rluiten/elm-date-extra
```

**Comment by evancz** [comment]
Whoo, resolved in 0.17!

**Comment by szagi3891** [comment]
how can use it?

**Comment by evancz** [comment]
To clarify, the initial issue was that if two packages have *private* modules with the same name, it used to cause problems. So if package `A` had a `Utils` module that **was not** exposed, and if package `B` had a `Utils` module that **was not** exposed, it would mess up.

Then someone posted about a separate issue, thinking this was tracking what he was worried about. That happens, and that is why I recommend always opening a *new* issue rather than piling on things that you think are your problem.
