### ISSUE TITLE
Make ports modular

### ISSUE THREAD

**Issue by thSoft** [elm-lang/elm-compiler#827]
If I define a port in a sub-module (i.e. not the module being compiled), I get the following error message:

    Port Error: ports may only appear in the main module, but
        sub-module Froggy.State declares the following port: load
        All ports must appear in module Froggy.Main

What is the rationale behind this? I'd like to define a port in a module I reuse, for example to support a custom input event source as a library.

**Comment by evancz** [comment]
Sorry for the no reply here.

The idea initially was that we weren't sure it'd be smart to use ports in this way. This would allow people to abuse ports as an FFI in ways that'd interact strangely with the module system. We have a more low-level FFI in the works that will address the root concern here more directly, so I am going to close this in favor of that.

Again, sorry to take so long!
