### ISSUE TITLE
Compiler Warnings

### ISSUE THREAD

**Issue by evancz** [elm-lang/elm-compiler#834]
It would be good to have compiler warnings for at least the following cases:

  * [x] incomplete pattern matches
  * [ ] variable shadowing
  * [x] missing top-level type signatures
  * [x] unused imports

If you were watching #829, follow this issue instead.

**Comment by mitchmindtree** [comment]
Just thought i'd give a :+1: to non-exhaustive pattern matches resulting in a compiler error! I just spent about an hour trying to determine the source of some strange runtime behaviour and it turned out to be two missing branches :bomb:

Also thought I'd mention Rust gives a compiler error for this also, has saved my feet from bullets many a time :dancer: :gun:

**Comment by gsingh93** [comment]
I'd also like compiler warnings for unused imports, and maybe unused variables/functions.

**Comment by Dobiasd** [comment]
Yes, this would be great. Sometimes I remove import after import manually to check with every step if it compiles, but sometimes I just do not have the nerves to do this. It gets especially tedious when it's not about whole modules but about a list of single function imported from a module.

**Comment by evancz** [comment]
:+1: to unused imports :)

**Comment by mitchmindtree** [comment]
Just lost a couple hours to an error before realising it was #829 :tired_face:  just thought I'd give this a bump!

**Comment by pythonesque** [comment]
This would be really, really, really, really nice.  It's the single biggest issue I have with Elm right now that isn't a bug.

**Comment by mgold** [comment]
There have been discussions on the mailing list, and the general consensus is to eliminate as many runtime errors as reasonably possible.

Like JavaScript, division by zero results in `Infinity`.

**Comment by evancz** [comment]
The compiler now has nice support for warnings throughout all phases, so adding this stuff is much more plausible. I have "unused imports" working, and we are working on "incomplete pattern matches" in #930

**Comment by mgold** [comment]
Another case for warning messages is shadowing using case expressions. From #948:
````elm
import Graphics.Element exposing (show)

type Foo = Bar Int
whatever = Bar 7

main = show <| case Bar 5 of
  Bar 3 -> "nope"
  whatever -> "hooray!"
  _ -> "something else"
````

This is always `"hooray!"` because `whatever` is a constraint-free identifier and _not_ equal to `Bar 7`.

**Comment by fernandezpablo85** [comment]
+1 to exhaustive pattern matching enforcement.

**Comment by evancz** [comment]
Alright, this is mostly done, so I am migrating us to #1018 which is about the specific warning that still needs to be done.

**Comment by jtarchie** [comment]
@evancz, how about unused assignments? For example if `let` defines a value, which is never used in the `in`.
