### ISSUE TITLE
elm-doc appears to cause package.elm-lang.org to fail

### ISSUE THREAD

**Issue by jcollard** [elm-lang/elm-compiler#840]
The following page does never loads: http://package.elm-lang.org/packages/jcollard/elm-playground/1.0.2/Playground-Input

Removing leading whitespace from elm-doc comments results in the documentation loading: http://package.elm-lang.org/packages/jcollard/elm-playground/1.0.3/Playground-Input

The diff of these two versions is here:
https://github.com/jcollard/elm-playground/compare/1.0.2...1.0.3

It seems that the elm-doc comments must not contain any leading whitespace. This seems fine but an error should be reported when attempting to publish.

Here is a gist containing the output of elm-doc on the files: https://gist.github.com/jcollard/539a4c4e0e4684b86285

**Comment by evancz** [comment]
Since `elm-doc` is no more and I have made the code to parse doc comments less clever, I am going to close this until we see it again with the new version of things. Let's reopen this if it can be reproduced!
