### ISSUE TITLE
Proposal: let } appear in column 0

### ISSUE THREAD

**Issue by rtfeldman** [elm-lang/elm-compiler#842]
Take a look at https://github.com/rtfeldman/dreamwriter/blob/75651371541a88a1d85504e70c7e41afd914eaae/Dreamwriter/Model.elm

Notice that `emptyState` at the bottom awkwardly has an extra level of indentation compared to the `type alias` above. It turns out this extra indentation is currently mandatory for record assignment.

If you attempt to do the "commas at the end of the line" style like this, the parser will let you do indentation "normally" in the case of `type alias` (as you can see earlier in the file), but if you try to use this style with record assignment (as with `emptyState`) and use "normal" indentation instead of awkward extra indentation, you get the following syntax error:

```bash
>> Error when compiling Dreamwriter.Model:
>> 
>> Parse error at (line 41, column 1):
>> unexpected "}"
>> expecting a newline or whitespace
Warning: Error when compiling Dreamwriter.Model:

Parse error at (line 41, column 1):
unexpected "}"
expecting a newline or whitespace
```

**Comment by evancz** [comment]
Alright, I am closing in favor of https://github.com/elm-lang/elm-plans/issues/16 which will track a couple things along these lines. It's good to have them all in one place. Furthermore, I think it's not making sense to have proposals in the elm-compiler repo anymore, so I am laying the groundwork for doing this in a better way. For now, please let me manage elm-plans, no new stuff there!

We should continue the discussion of this idea in this issue if more needs to be said (though it looks like it's pretty covered)
