### ISSUE TITLE
Compiler's state gets corrupted: Could not find type constructor '...' while checking types.

### ISSUE THREAD

**Issue by avh4** [elm-lang/elm-compiler#844]
With 0.14, I have been getting errors like the following sometimes when recompiling after making small changes to me code.

```
Error when compiling Outline.Document.Actions:

Could not find type constructor 'App.Command' while checking types.
```

After deleting the `*.elmo` and `*.elmi` files from `elm-stuff`, compilation succeeds with no problem.  I have seen this happen several times with different modules and type constructors.

**Comment by evancz** [comment]
I think https://github.com/elm-lang/elm-make/commit/2e3f17798e480df59a668cefb87746dea11ed1e7 and https://github.com/elm-lang/elm-make/commit/d6f4f569d4c48995f2b874c81a1738118430c1c5 should resolve the issues we are seeing here.

If you can build from source, please do and let me know. If you cannot, I'll have installers relatively soon so we can test with that.

**Comment by mitchmindtree** [comment]
Just thought I'd confirm, also getting this error in my top level file (main.elm):

```
Error in ./src/Character.elm:

Could not find type constructor 'Player.Action' while checking types.
```

- Using the mac installer from the 5th Jan
- Using elm-reactor
- `elm-reactor --version` gives `0.2`
- I have 6 files
- ./src/character.elm does not use or import `Player.Action` at all (the file's only 10 lines long)

@evancz If you could confirm here once the installers are updated that would be sweet :)

PS: absolutely loving Elm, thanks for sharing it with the world!

**Comment by avh4** [comment]
I can build from source, but probably won't have a chance to test it out until Saturday.

**Comment by evancz** [comment]
@mitchmindtree and @avh4, [the installer for Mac is ready](https://groups.google.com/forum/#!topic/elm-discuss/KHg-aeFvDN0). I am working on the Windows one.

**Comment by mitchmindtree** [comment]
:100: :+1:

**Comment by kasbah** [comment]
I had this issue on [my project](https://github.com/kasbah/mooltipass.hid-app/tree/0.7.1) when editing the file `src/background/DevicePacket.elm` and do not with latest elm-make built from source. 

Thanks very much! I think you can safely close this.

**Comment by avh4** [comment]
Yeah, I haven't seen this come up in a while.  Closing.

**Comment by evancz** [comment]
Great, thanks for the report!

**Comment by seanhess** [comment]
For anyone else who found this: I got this issue after refactoring. I moved a type into another file and the compiler became very confused. It's easy to work around though: just trash elm-stuff, reinstall packages, and run elm-make again. Not sure if there's any easier way to clear the compiler cache.

**Comment by domenkozar** [comment]
I just got this one today on Elm 0.17:

```
elm make src/Main.elm 
[                                                  ] - 0 / 8elm-make: Could not find type constructor `Urls.Page` while checking types.
elm-make: thread blocked indefinitely in an MVar operation
```

**Comment by neerone** [comment]
Today got this error too (Elm 0.17.1). It came after deleting some unneeded types in my project. It appears only with elm reactor (with elm make all just fine). I have fixed it by deleting elm-stuff folder and "elm make" it again. Now elm reactor works too.

**Comment by evancz** [comment]
I believe https://github.com/elm-lang/elm-make/commit/46ec85c0e8dc5f3427bde6e4f212b4f367ecbd07 will fix all this stuff. Once 0.18 comes out, we can revisit this if it comes up again.

**Comment by h4ck3rm1k3** [comment]
I was able to reproduce this,  here is my entire build directory will all files https://github.com/h4ck3rm1k3/steem-graph just run elm-make. Installed on debian sid with nvm v9.

Running strace showed many of these:
32216 --- SIGVTALRM {si_signo=SIGVTALRM, si_code=SI_TIMER, si_timerid=0, si_overrun=0, si_value={int=0, ptr=NULL}} ---

What I did was install modules via elm-package and then rename them to try and work out conflicts where names conflict

```
elm-make: Could not find type constructor `SimpleGraph.Node` while checking types.
elm-make: thread blocked indefinitely in an MVar operation
```
