### ISSUE TITLE
type errors for pattern match left-hand-sides lack line/column numbers

### ISSUE THREAD

**Issue by rntz** [elm-lang/elm-compiler#848]
The following code:

    module Bug2 where
    import String (toInt)
    foo : String -> Int
    foo x = case toInt x of
              Just y -> y
              Nothing -> 0

Produces the following error:

    Error in bug2.elm:

    Type mismatch between the following types:

            Result.Result String

            Maybe.Maybe

        It is related to the following expression:

            Maybe.Nothing

    Type mismatch between the following types:

            Result.Result String

            Maybe.Maybe

        It is related to the following expression:

            Maybe.Just y

This has no line number information, which would make this a hard problem to debug in a file of any significant size.

**Comment by evancz** [comment]
This is fixed in the warnings branch! Thanks for the report :)
