### ISSUE TITLE
"Maximum Call Stack Size Exceeded" when drawing randomly generated grid

### ISSUE THREAD

**Issue by sonnym** [elm-lang/elm-compiler#850]
Hey guys!

I was updating my Conway's Game of Life example to 0.14 (which is a great release, I must add!), and I ran into an interesting problem.  When the grid is a small size, everything works fine, but somewhere between 35 and 40 in Firefox and somewhere between 50 and 75 in Chromium, it just crashes with the following:

```
Uncaught RangeError: Maximum call stack size exceeded  
init compile:2752
Elm.fullscreen compile:2623
(anonymous function) compile:4601
```
This did at least force me to rewrite a terrible recursive function I wrote to ensure it was no my fault, but alas!  There is a gist here you can take a look at:  https://gist.github.com/sonnym/5d0314f6cb18fae0aa71

Thanks for all your hard work!

**Comment by evancz** [comment]
Okay, with TCE coming in the next release, I am going to close this one. Thanks for the report and figuring out exactly what was the root issue!
