### ISSUE TITLE
Canvas elements are blurry on high DPI (Retina) display

### ISSUE THREAD

**Issue by jameshfisher** [elm-lang/elm-compiler#855]
On my retina display, vector elements displayed in the canvas are blurry. [Apparently this can be fixed.](http://www.html5rocks.com/en/tutorials/canvas/hidpi/)

**Comment by evancz** [comment]
Thanks for the report! I believe this made it into a more recent version of `elm-lang/core` with https://github.com/elm-lang/core/pull/144 so things should be sharp now!
