### ISSUE TITLE
Elm.worker expects document to be available

### ISSUE THREAD

**Issue by sonnym** [elm-lang/elm-compiler#856]
Hey!

I have been working on creating a node module to allow transparently including elm code in a node application, but have run into an issue using the `Elm.worker` function on the compiled module.  Namely, it relies on the document object being present:
```
ReferenceError: document is not defined
    at init (/home/sonny/src/local/node-elm/test/fixtures/constant_port.js:1173:28)
    at Object.Elm.worker (/home/sonny/src/local/node-elm/test/fixtures/constant_port.js:1072:20)
```

When I pass in a document object created by `jsdom`, I end up getting the following error a few lines later, which is caused by an empty object being passed in rather than a DOM object:
```
TypeError: Object #<Object> has no method 'appendChild'
    at init (/home/sonny/src/local/node-elm/test/fixtures/constant_port.js:1186:27)
    at Object.Elm.worker (/home/sonny/src/local/node-elm/test/fixtures/constant_port.js:1072:20)
```

I have created a gist with the relevant elm source and the compiled output:  https://gist.github.com/sonnym/aad84421f8d604d63c5a

Please let me know if I can provide any further details!  Thanks!

**Comment by evancz** [comment]
I am working on getting things working on node, so we will resolve this issue as that becomes a first-class project. I am going to close this knowing that a lot of the module initialization stuff is going to change in this process. Thanks for reporting this!
