### ISSUE TITLE
Wrong HTML element disappears in state transition

### ISSUE THREAD

**Issue by jameshfisher** [elm-lang/elm-compiler#862]
### Steps to reproduce

Copy-paste the following program into http://elm-lang.org/try and hit compile:

```
import Color (blue)
import Graphics.Collage (toForm, move, collage)
import Graphics.Element (color, spacer, beside)
import Signal (foldp, map)
import Mouse (clicks)

b = color blue (spacer 20 20)
bb = toForm (beside b b)
main = map
  (\s -> collage 200 200 (if s then [move (0, 50) (toForm b), bb] else [bb]))
  (foldp (always not) True clicks)
```

Then repeatedly click the mouse in the right-hand pane.

### Expected behavior

The top-most square disappears and reappears when clicking the mouse.

### Actual behavior

The bottom-most rectangle disappears and reappears when clicking the mouse.

### Notes

I've reduced a much larger program down to this minimal one, but can't find a way to reduce it further. The bug appears to be an interaction between `Graphics.Element`, `Graphics.Collage`, and signals.

If I were to guess, I would say there is a problem with DOM diffing which causes removal of the wrong element.

A related bug can be found by changing `True` to `False` in the last line. Then the expected behavior is the same, but the actual behavior is that no DOM changes happen at all.

**Comment by etaque** [comment]
This bug is preventing me to enjoy the 0.14 experience, do you know any workaround?

**Comment by jwmerrill** [comment]
You can try changing this line

https://github.com/elm-lang/core/blob/9687580e6f7b012cdee712c2f14471b272c85488/src/Native/Graphics/Collage.js#L358

from 

```javascript
} else if (kid.getContext) {
```

to

```javascript
} else {
```

and let us know if this fixes your problem, and also if it causes any other regressions that you notice.

I can put up a PR that does this, but I don't really know how to test whether it will break something else with any certainty.

**Comment by etaque** [comment]
Great, this fixes the bug and I didn't notice any regressions !

**Comment by evancz** [comment]
Alright, just merged @jwmerrill's fix, so this should be resolved. Thanks for the report @jameshfisher, and thanks for the fix @jwmerrill!

**Comment by jameshfisher** [comment]
Wonderful! Thanks all!

**Comment by etaque** [comment]
Thanks! :+1: 
Will 0.14.1 incorporate this elm-core version?
