### ISSUE TITLE
Error while editing code loaded in debugger (invalid 'in' operand debuggedModule.main)

### ISSUE THREAD

**Issue by imeckler** [elm-lang/elm-compiler#866]
When I edit the module which is currently loaded in the debugger, I get the following error:
```
invalid 'in' operand debuggedModule.main
```
The error occurs here, at line 51 of `debugging-runtime.js`:
```js
  // make sure the signal graph is actually a signal & extract the visual model
  if ( !('recv' in debuggedModule.main) ) {
    debuggedModule.main = Elm.Signal.make(runtime).constant(debuggedModule.main);
  }
```

**Comment by louisch** [comment]
This is still a problem. An issue has been created over at the reactor page: https://github.com/elm-lang/elm-reactor/issues/65

**Comment by evancz** [comment]
This is resolved with the latest development version of elm-reactor, which should come out with 0.14.1 in the next few days. I am going to close for now.
