### ISSUE TITLE
rendering problem in firefox with input fields and flow right inside of flow down

### ISSUE THREAD

**Issue by Dobiasd** [elm-lang/elm-compiler#867]
The output of [this code](http://share-elm.com/sprout/54a288f0e4b05f9c59b249d7) (You have to manually select version 0.14 since share-elm.com seems to not save the version number.) is rendered correctly in Chrome but not in Firefox (see [screenshot](http://i.imgur.com/Qyyn236.png)).

**Comment by Dobiasd** [comment]
possible duplicate: https://github.com/elm-lang/elm-compiler/issues/541

**Comment by evancz** [comment]
Alright, added to meta issue https://github.com/elm-lang/core/issues/332 over on core, thanks for the report!
