### ISSUE TITLE
Weird errors with qualified names and record update syntax.

### ISSUE THREAD

**Issue by imeckler** [elm-lang/elm-compiler#871]
I found the following two errors associated with trying to update a record with a qualified name:
```elm
import Graphics.Input.Field
import Graphics.Input.Field(defaultStyle)

err1 = {defaultStyle | outline <- Graphics.Input.Field.defaultStyle.outline}
err2 =  {Graphics.Input.Field.defaultStyle | outline <- defaultStyle.outline}
```

Each of these separately produces a different error. The first produces the error
```
Could not find variable 'Graphics.Input.Field.defaultStyle.outline'.
```
and the second the error
```
Parse error at (line 5, column 4):
unexpected "G"
expecting whitespace, a newline, lower case variable or closing bracket '}'
```
(The line number in the parse error is wrong since this was just at the repl.)
Having everything unqualified, like
```elm
{defaultStyle | outline <- defaultStyle.outline}
```
works just fine.

**Comment by imeckler** [comment]
Duplicate of [635](https://github.com/elm-lang/elm-compiler/issues/635).

**Comment by evancz** [comment]
Awesome, thanks for digging around and finding that!
