### ISSUE TITLE
Confusing compiler error distant from actual error

### ISSUE THREAD

**Issue by danmane** [elm-lang/elm-compiler#882]
Suppose you have code like this:
```
1|  function a1 a2 = if 
2|    | a1 == a2 -> Nothing 
3|    | otherwise -> let x1 = somethingValid1
4|                       x2 = List.map (/= a2) somethingValid2 
5|                   in  somethingValid3 
```

There is a mistake in line 4, where `(\= a2)` should be `((\=) a2)`. However, the compiler spits out a warning for line 3 that the `|` is unexpected; expecting whitespace or end of input. It gives no hint that the error is actually on line 4 and makes this syntax error difficult to debug.

**Comment by evancz** [comment]
Thanks for reporting this! Do you mind migrating it to https://github.com/evancz/error-message-catalog/issues ? We are using that repo to log all of the crappy error messages so we can find patterns and fix a bunch at once!
