### ISSUE TITLE
elm-doc fails when not given a filename

### ISSUE THREAD

**Issue by mgold** [elm-lang/elm-compiler#886]
````shell
$ elm-doc
elm-doc-unwrapped: : openFile: does not exist (No such file or directory)
````
It would be nice if we detected this and either (1) used the files in elm-package.json, (2) used all *.elm files (perhaps recursively), or (3) threw a more helpful error message. I think (1) is the sensible thing but (3) would be a great improvement.

**Comment by mgold** [comment]
Ah crap, I meant to do this on elm-doc. Sorry everyone!

**Comment by mgold** [comment]
Oh no wait, elm-doc is part of this repo. *pretends nothing happened*

**Comment by mgold** [comment]
Thanks!

**Comment by evancz** [comment]
No problem! I fixed a very tough bug today, but it was obscure enough that no one had reported it! It felt unjust that it was so hard and there was nothing to close, so I went through and tried to fix some others too :)
