### ISSUE TITLE
elm-doc expects docs before imports

### ISSUE THREAD

**Issue by mgold** [elm-lang/elm-compiler#887]
````shell
$ elm-doc myFile.elm 
(line 3, column 1):
unexpected "i"
expecting module documentation comment or more whitespace
$ head myFile.elm
module myModule where

import Text
````
This happens if an import statement appears before a `{-|` token. elm-doc should either be robust to this (i.e. imports first is acceptable) or print a very specific error message.

**Comment by evancz** [comment]
Track this on the WIP issue
