### ISSUE TITLE
HTML buttons can't be clicked inside of elements

### ISSUE THREAD

**Issue by imeckler** [elm-lang/elm-compiler#890]
It seems like this issue might belong to evancz/elm-html, but I suspect it's related to whatever was changed to handle [this issue](https://github.com/elm-lang/elm-compiler/issues/747). In short, because something is setting pointer-events to none on element divs, HTML buttons cannot be clicked (unless you explicitly set "pointer-events" to "auto" in the HTML). Here's a small example.
```elm
import Graphics.Element(..)
import Html
import Html.Events(..)
import Text
import Color
import Signal

clickChan = Signal.channel ()

init : Element
init =
  flow inward
  [ flow down
    [ Text.fromString "Hi"
      |> Text.centered
    , Html.button [onClick (Signal.send clickChan ())] [Html.text "Go"]
      |> Html.toElement 100 50
    ]
  , container 500 500 middle empty |> color Color.white
  ]

main =
  Signal.foldp (\_ _ -> Text.plainText "You'll never see this") init
    (Signal.subscribe clickChan)
```
As mentioned, adding an attribute to the button setting pointer-events to "auto" resolves this.

**Comment by evancz** [comment]
Maybe `toElement` should set pointer-events to auto?

**Comment by imeckler** [comment]
Maybe, though it shouldn't do so unconditionally, but only if pointer-events hasn't been set explicitly. However I don't know enough about the referenced issue to say if this would have some unforeseen consequence.

**Comment by evancz** [comment]
Mentioning https://github.com/elm-lang/core/issues/332 so we can find this there and so we can clean up the issues in this repo.
