### ISSUE TITLE
characters --|> are not coonsidered a comment and they are interpreted as a variable

### ISSUE THREAD

**Issue by wighawag** [elm-lang/elm-compiler#894]
Error in Game.elm:
Error on line 58, column 14 to 224:
Could not find variable '--|>'.

**Comment by johnpmayer** [comment]
This is probably deliberate. There's probably a thread for this 2 years ago
on the mailing list (elm-discuss)

**Comment by mgold** [comment]
Technically they are interpreted as an infix operator. You could probably define this operator and use it just fine. If we did want to consider this a comment (I don't know if we do), either the comment parser needs to run before the tokenizer, or the regex should not assume spaces surrounding `--`, or something in that ballpark at least \*handwave\*.

**Comment by avh4** [comment]
There is currently inconsistency in how `--|>` is handled: sometimes it is seen as a comment, and other times it is seen as an infix operator.  Here are examples that illustrate this:

This example compiles and executes, and treats `--|>` as a comment
```elm
import Html
import Debug

main = "Hi"
  --|> Debug.log "text"
  |> Html.text
```

This example treats `--|>` as a an infix operator and does not compile:
```elm
import Html
import Debug

main = "Hi"
  |> Html.text
  --|> Debug.log "html"
```

**Comment by evancz** [comment]
Both of @avh4's examples work for me now on the master branch, so I *think* this is resolved. I believe this is connected to the changes I made to whitespace parsing a while ago.
