### ISSUE TITLE
Poor error message on parsing incorrect record update syntax

### ISSUE THREAD

**Issue by betaveros** [elm-lang/elm-compiler#896]
Code like

```
bar = { foo | a <- 1, b <- 2, oops, c <- 3, d <- 4 }
```

fails to parse with the quite confusing error message:

```
Parse error at (line 1, column 13):
unexpected "|"
expecting whitespace, a newline or "="
```

Looking at the source code I guess this occurs because the parser backtracks to the start of the bracket if it can't parse the whole content as record update syntax ( https://github.com/elm-lang/elm-compiler/blob/69a436680cc7d129ab8ec982a778b007e235c766/src/Parse/Expression.hs#L126 ) and it doesn't look too easy to fix, but I still thought I'd mention it because I spent a painfully long time looking at that error message completely mystified.

**Comment by evancz** [comment]
I am revamping the error reporting in the compiler. Right now, we actually point to the part that is messed up:

```
-- SYNTAX ERROR --------------------------------------- syntax/record-update.elm

Problem when parsing your code!

0| 
1| bar = { foo | a <- 1, b <- 2, oops, c <- 3, d <- 4 }
2|                                   ^

SysUnExpect: ","
SysUnExpect: ","
SysUnExpect: ","
SysUnExpect: ","
SysUnExpect: ","
SysUnExpect: ","
SysUnExpect: ","
SysUnExpect: ","
SysUnExpect: ","
UnExpect: 
UnExpect: whitespace
UnExpect: a newline
UnExpect: "<-"

```

I still need to properly display the raw error messages from the parser in a way that works for humans, but the point is that the error message now points to the problematic part, no extreme backtracking!
