### ISSUE TITLE
Runtime error with record extension

### ISSUE THREAD

**Issue by TheSeamau5** [elm-lang/elm-compiler#897]
```elm
d = {}
test = 
  { d | toString = toString }
```
causes the error in Chrome:

```
undefined is not a function


Open the developer console for more details.
```

and in Firefox:

```
values.slice is not a function


Open the developer console for more details.
```

When I snoop in the debugger, I find this:

![screen shot 2015-02-28 at 10 26 56 pm](https://cloud.githubusercontent.com/assets/3227869/6428405/0058c2dc-bf99-11e4-8296-efe94c3b36c8.png)

So, it seems that the `toString` is not a list. A check should probably be placed around `values`.

**Comment by TheSeamau5** [comment]
Just checked and this is still a bug today.

**Comment by evancz** [comment]
Can you show what the runtime representation of `{}` is?

**Comment by TheSeamau5** [comment]
Here, I managed to get to the exact point of the crash.

![screen shot 2015-08-06 at 2 43 55 am](https://cloud.githubusercontent.com/assets/3227869/9101944/12be0504-3be5-11e5-969f-c858e864a60c.png)


 I also took a screenshot of the states of the objects in the debugger.

![screen shot 2015-08-06 at 2 45 54 am](https://cloud.githubusercontent.com/assets/3227869/9101971/521e3ac0-3be5-11e5-8e1f-7b7057bae75a.png)

It seems that `{}` is just an object with a property that's an underscore with nothing in it.

**Comment by evancz** [comment]
So does `for (var key in obj)` work differently depending on which fields are in there? Like, will it always touch the `toString` property? Or only in certain circumstances? Maybe it's something freaky there.

Meta note: I don't super know what's going on in the screenshots you are giving, so I'll understand better if we can pin it down to objects that can be written in a code block and links to locations in elm-lang/core.

**Comment by TheSeamau5** [comment]
Aha! Check this out! Thanks to the chrome devtools that apparently I just discovered allows you to mess in the console with the variables currently in scope, I've found this

![screen shot 2015-08-06 at 2 50 01 am](https://cloud.githubusercontent.com/assets/3227869/9102061/fc55f21c-3be5-11e5-8969-86bef431a40c.png)

Looks like there are a certain number of properties accessible via the array syntax that are already taken. I've confirmed this because it turns out that this also causes the crash.

```elm
d = 
  {}

test = 
  { d | toLocaleString = "" }
```

Conclusion, you gotta treat these words like keywords in the compiler or change them somehow.

From that screenshot, I'm guessing that you have to special case 7 different strings that can't be generated on the JS side as record properties:

- constructor
- hasOwnProperty
- isPrototypeOf
- propertyIsEnumerable
- toLocaleString
- toString
- valueOf 

I confirm that they all cause the crash!

**Comment by evancz** [comment]
Yowzers, nice find!

Do you mind closing this issue and opening a new one that describes exactly what is going wrong in a concise way with a clear title. We probably just have to add these things to [here](https://github.com/elm-lang/elm-compiler/blob/master/src/Generate/JavaScript/Variable.hs#L48-L64).

**Comment by TheSeamau5** [comment]
Closed in favor of https://github.com/elm-lang/elm-compiler/issues/1010
