### ISSUE TITLE
Unable to pass tuple through port into Elm

### ISSUE THREAD

**Issue by sonnym** [elm-lang/elm-compiler#898]
If you try to initialize a port like the of the following definition with an empty array, the following error message is generated.

```shell
Elm: An error ocurred during processing
Error: Initialization Error on port 'messageIn':
Runtime error when sending values through a port.
Expecting an array but was given
[]
```

```elm
port messageIn : Signal ()
```

This may already be fixed with the upcoming changes to ports, but is present in 0.14.1.

**Comment by evancz** [comment]
Is this true for just unit values like `()` or for all tuples, stuff like `(Int,Int)` as well?

**Comment by sonnym** [comment]
I originally saw the problem with this port that is of type `((Int, Int), (Int, Int Int))` (a position and a color): https://github.com/sonnym/elm-expressway_doodle/blob/master/Doodle/Server.elm#L15

In my testing, I believe I also tried `(Int, Int)` with the same result.

**Comment by jvoigtlaender** [comment]
@sonnym, have you seen this problem in Elm 0.16?

**Comment by evancz** [comment]
Not sure if this is still relevant. Will close. Open a new issue with a http://sscce.org/ if it persists in 0.17
