### ISSUE TITLE
Shouldn't we tell which is the expected and which is the actual type on error messages.

### ISSUE THREAD

**Issue by viclib** [elm-lang/elm-compiler#899]
This is an Elm type error message:

    Type mismatch between the following types on line 17, column 18 to 28:

        Signal.Signal Int

        a -> Html.Html

    It is related to the following expression:

        numsSignal

It is not obvious to a newbie what he did wrong. I suggest the following format instead:

    On line 17, column 18 to 28, the expression:
        
        numsSignal

    has the type:

        Signal.Signal Int

    but it should have the type:

        a -> Html.Html

Does anyone agree?

**Comment by evancz** [comment]
Check the mailing list for discussions of expected vs actual. We had it for a long time, and it would get them mixed up. Having none has been much nicer than having it wrong sometimes. If it can be done, I don't have any problem with it though!

**Comment by viclib** [comment]
I should've expected that was already debated before. My bad. I'll check the list for the reasonings. Thanks!

**Comment by evancz** [comment]
No worries at all! It is just harder to do right than it sounds! Or maybe it's harder for *me* to do right :P

**Comment by evancz** [comment]
I'm gonna close this because of the recent error reporting overhaul. I think things are much better now.

We will also be doing more work on error messages this summer, so it may be possible to add expected/actual at some point, or at least assess if it is helpful to perceived error message quality.
