### ISSUE TITLE
Removing Signals

### ISSUE THREAD

**Issue by viclib** [elm-lang/elm-compiler#900]
That may sound like a terrible idea - maybe it is - but it is puzzling me so I want to hear your opinion on it. Note this is totally uninplementable without giantic refactorings so I'm not asking that at all. Just thoughts, really.

We all know Monads are great for keeping stateful computation isolated from the rest of the program in a purely functional language. They work on Haskell for many reasons. I just suspect those reasons don't apply to Elm, and the FRP's approach could work totally independent of Monads: we could just keep everything at the language level **completely pure** and allow values to be changed externally from JS. For example, consider the following program:

    external time : Double
    time = `Date.now()`

    ballPosition : Double
    ballPosition = sin time * 40
   
    main : Element
    main = circle 200 ballPosition blue

Here, `time` is defined externally by a JavaScript computation. Whenever it is changes, any element depending on it is changed too. Now, it sounds like "time" is stateful and could cause havoc, but it is actually not. For example, **referential transparency still holds**. Indeed, the language now is actually much more pure than before, since there is no state on the language level at all - not even inside monads. It might help if you think an Elm program as a function which receives its external variables and returns `main`.

But why would you do that?

Because that keeps our code much simpler and ridiculously easier to newbiews. Since `time`'s type now is just Double, you can use it anywhere without worrying about lifts, fmaps, which I can't overstate how confusing are for newbies. Even for the initiated, that will still make your code much more concise. For example, compare:

    external currentDate, url, lastTweet : String

    view : HTML
    view = div [] [div [] [text currentDate], div [] [text url], div [] [text lastTweet]]

Versus:

    currentDate, url, lastTweet : Signal String

    view : HTML
    view = Signal.map3 (\ currentDate, url, lastTweet →  div [] [div [] [text currentDate], div [] [text url], div [] [text lastTweet]]) currentDate url lastTweet

I doubt anyone would have trouble understanding the first one. Now, the second... well, good luck explaining lifts, maps. As much as Elm has made things easier, there is still "monad understanding" entry wall on the language right now for anyone who wants to use it properly. Trust me - every single time I explain Elm to a friend, I can see him hitting that wall.

The only reason I see not to take this approach is that it sounds scary that "mutable" values aren't tagged on the type level anymore - but if that is what you are thinking, please, just tell me: what is the "Signal" type protecting us from, that this approach would make us vulnerable? Adding a "pure" and an "impure" value together? But we already do that! Signals are already exactly the same thing; they are already stateful. The only difference is that they are awkward to use.

**Comment by evancz** [comment]
Do you mind retargeting this suggestion to elm-discuss? This is roughly the idea of "automatic lifting" to signals as used in FrTime which comes with it's own set of trade offs. Folks on the list will be able to talk through this in much more detail!

Also, Elm does not have `lift` or `fmap` or monadic signals, and I feel somewhat that this suggestion conflates Elm an Haskell in a weird way. Ask the list though, they can give more detail!

**Comment by viclib** [comment]
No problems... my bad again :(

**Comment by evancz** [comment]
No worries at all! I should probably try to get folks on the mailing list more inclined towards discussion in issues like this, but the culture is not like that at this moment. Next time I'll tell them to come here instead!

**Comment by viclib** [comment]
Okay! Done! You're the fastest repo manager ever. Wish I could star more times! :)

**Comment by evancz** [comment]
Haha, you caught me on a good day, but thanks for saying so! :)

Is it okay to close this for now, potentially reopening after the list discussion?

**Comment by viclib** [comment]
Of course, delete if possible...?
