### ISSUE TITLE
Proposal: require spaces between numbers and variables

### ISSUE THREAD

**Issue by jvoigtlaender** [elm-lang/elm-compiler#901]
I was very suprised that this is *not* rejected by the compiler:
```elm
mport Graphics.Element (..)
import Text (..)

r = 10

main : Element
main =
  f 3r

f _ _ = plainText "Hello, World!"
```
(Turns out GHC also accepts stuff like `f 3r`, interpreting it as `f 3 r`. Doesn't mean it's necessarily a good idea. For beginners just getting into "spaced function application" syntax, this might be quite confusing.)

**Comment by rtfeldman** [comment]
Agreed. If I ever do this, it's because I messed up; as such, I'd appreciate the compiler saving me from myself as usual. ;)

**Comment by evancz** [comment]
Tracking in #1374

**Comment by evancz** [comment]
This is fixed by the new parser. Here's the updated SSCCE, and resulting error:

```elm
import Html exposing (..)

r = 10

f _ _ = text "Hello, World!"

main = f 3r
```

![screen shot 2016-12-17 at 7 50 53 pm](https://cloud.githubusercontent.com/assets/1658058/21290915/2c2a8184-c492-11e6-802f-83b7abb115c6.png)

Thanks for the report!
