### ISSUE TITLE
record updates don't work with module names

### ISSUE THREAD

**Issue by echatav** [elm-lang/elm-compiler#904]
If you import a module qualified then record updates fail because upper case is disallowed.

```
import Text
boldStyle = {Text.defaultStyle | bold <- True}

> unexpected "T"
> expecting whitespace, a newline, lower case variable or closing bracket '}'
```

**Comment by sindikat** [comment]
I confirm, the below doesn't work:

    import Graphics.Collage as C
    line = { C.defaultLine | width <- 10 }

while this works:

    import Graphics.Collage as C exposing (defaultLine)
    line = { defaultLine | width <- 10 }

**Comment by evancz** [comment]
Closing as a duplicate of #635 which is being tracked at https://github.com/elm-lang/elm-plans/issues/16

Thanks for the report!
