### ISSUE TITLE
Proposal: String Interpolation

### ISSUE THREAD

**Issue by rtfeldman** [elm-lang/elm-compiler#905]
[String interpolation](http://en.wikipedia.org/wiki/String_interpolation) is incredibly desirable when building UIs. It would be great if Elm had it!
## Proposed Implementation

**1.** New interpolation syntax is introduced for `"` and `"""` strings:

``` elm
"There are {{length hobbitList}} hobbits."
"""There are {{length hobbitList}} hobbits."""

-- both desugar to the following:
"There are " ++ (toString (length hobbitList)) ++ " hobbits."
```

**2.** Extra whitespace surrounding the expression inside the `{{ }}` is ignored; the following are equivalent:

``` elm
"There are {{numHobbits}} hobbits."
"There are {{ numHobbits }} hobbits."
"""There are {{numHobbits}} hobbits."""
"""There are {{ numHobbits }} hobbits."""
"There are " ++ (toString numHobbits) ++ " hobbits."
```

**3.** When you do not want interpolation, you can escape with a backslash like so:

``` elm
"There are \{{length hobbitList}} hobbits."
"""There are \{{length hobbitList}} hobbits."""

-- both desugar to the same string without the backslashes; no interpolation is performed.
```

**4.** Aside from the escaping noted above, there would be no special syntax for a "noninterpolated string" for [these reasons](https://github.com/elm-lang/elm-compiler/issues/905#issuecomment-89046859).

**5.** `toString` is changed such that when it is given a `String`, it just returns the argument it was given. (Currently it would wrap that argument in quotation marks.)
## Background

There are a bunch of [examples of how this is done in various languages](http://en.wikipedia.org/wiki/String_interpolation#Examples) on Wikipedia. Here are some different ways we could make the following Elm code more concise using String interpolation.

(Note: I'm assuming `toString` is changed to be the identity function when given a String.)

**[Elm](http://package.elm-lang.org/packages/elm-lang/core/1.1.1/String)**:

``` elm
"There are " ++ (toString (length hobbitList)) ++ " hobbits."
```

**[Mustache](https://mustache.github.io/mustache.5.html)/[Handlebars](http://handlebarsjs.com/)**:

``` handlebars
"There are {{length hobbitList}} hobbits."
```

**[Ruby](https://rubymonk.com/learning/books/1-ruby-primer/chapters/5-strings/lessons/31-string-basics)/[CoffeeScript](http://coffeescript.org/#strings)/[Elixir](http://elixir-lang.org/getting-started/basic-types.html#strings):**

``` ruby
"There are #{length hobbitList} hobbits."
```

**[Perl](http://perlmaven.com/quoted-interpolated-and-escaped-strings-in-perl)/[PHP](http://php.net/manual/en/language.types.string.php#language.types.string.parsing.simple)/[Dart](https://www.dartlang.org/docs/dart-up-and-running/ch02.html)/[Haxe](http://haxe.org/manual/lf-string-interpolation.html)/[ES6 JavaScript](http://updates.html5rocks.com/2015/01/ES6-Template-Strings)**:

``` dart
"There are ${length hobbitList} hobbits."
```

**[Swift](https://developer.apple.com/library/ios/documentation/Swift/Conceptual/Swift_Programming_Language/StringsAndCharacters.html#//apple_ref/doc/uid/TP40014097-CH7-ID292)**:

``` swift
"There are \(length hobbitList) hobbits."
```

**[Boo](http://boo.codehaus.org/String+Interpolation)**:

``` boo
"There are $(length hobbitList) hobbits."
```

**[Scala](http://docs.scala-lang.org/overviews/core/string-interpolation.html):**

``` scala
s"There are ${length hobbitList} hobbits."
```

**[C#](https://roslyn.codeplex.com/discussions/570614):**

``` c#
$"There are {length hobbitList} hobbits."
```

**Comment by TheSeamau5** [comment]
I think that this paired with the markdown library could be amazing.

Perhaps it would be nice to see what syntax would clash neither with Elm nor with Markdown.

Remember that curly braces are used in Elm for records and record updates, and we might want to use these inside the interpolation. Elm also has lambdas that we may want to evaluate (or pass to `List.map` inside the interpolation). And then, there is all the special syntax in Markdown..

I don't know if it's worth the pain, but we could in theory have nested string interpolation (if inside the interpolation you're trying to concatenate different strings). 

This is a random example to illustrate what I mean:

```elm
welcomeMessage = Markdown.toHtml
"""
##Welcome $(user.title ? "" ) $(user.name)

- Checking account : *£ $(user.checking.total)*
- Savings account : *£ $(user.savings.total)*

### Withdrawals
Date | Location | Total
---- | -------- | -----
$( String.lines <|
List.map (\w -> "$( w.date )  |  $( w.location ) | £ $( w.total ) ) user.withdrawals
)

"""
```

Where user is of the type :

```elm
type alias User = 
 { title : Maybe String
 , name : String
 , checking : { total : Float }
 , savings : { total : Float }
 , withdrawals : List { date : Date, location : String, total : Float}
 }
```

Which should hopefully produce something like this:

## Welcome Mr. Bond

- Checking account : *£1,000,000*
- Savings account : *£0*

Date | Location | Total
---- | -------- | -----
23/03/15 | Omega Watch at Omega Store, London, United Kingdom | £5,000
24/03/15 | Martini (Shaken not stirred) at Casino Royale, Montenegro | £300

**Comment by rtfeldman** [comment]
I think the barrier to adding sugar to the language should be very high, but in UI development in particular it comes up a ton that you want to concatenate three strings, the middle of which is often the result of a call to `toString`.

I mention this because I think this motivating use case should drive the design of the syntax. If you were to graph the distribution of how interpolation is used, I'm pretty sure expressions involving record literals would be among the most extremely rare edge cases in the list. So it's probably not worth designing around, beyond the basic "it's supported if you want to." :smile: 

That said, agree that avoiding clashes with Markdown would be wise!

**Comment by rtfeldman** [comment]
With that in mind, I'm liking the Handlebars option best.

Consider:

```handlebars
welcomeMessage = Markdown.toHtml
"""
##Welcome {{user.title ? ""}} {{user.name}}

- Checking account : *£ {{user.checking.total}}*
- Savings account : *£ {{user.savings.total}}*

### Withdrawals
Date | Location | Total
---- | -------- | -----
{{ String.lines <|
List.map (\w -> "{{ w.date }}  |  {{ w.location }} | £ {{ w.total }}") user.withdrawals
}}

"""
```

**Comment by evancz** [comment]
I think the double curly braces work well in a big chunk (although seeing a multiline thing in a string is barfy, just make a let-expression!) but I am curious to see more examples of "typical scenarios".

Lets try to find the type of one line things that'd probably benefit most. Maybe you two have examples in code you have written? That'd be perfect.

I am sort of drawn to the C# version as well, perhaps irrationally, and I think examples will sort this out :)

**Comment by rtfeldman** [comment]
Sure! Here are three examples from Dreamwriter rewritten various different ways.

### Example 1

https://github.com/rtfeldman/dreamwriter/blob/master/Component/Editor.elm#L59

```elm
div [id "doc-word-count"] [text <| (pluralize "word" wordCount) ++ " saved"]
```
```elm
div [id "doc-word-count"] [text "{{pluralize "word" wordCount}} saved"]
```
```elm
div [id "doc-word-count"] [text "{pluralize "word" wordCount} saved"]
```
```elm
div [id "doc-word-count"] [text "#{pluralize "word" wordCount} saved"]
```
```elm
div [id "doc-word-count"] [text "${pluralize "word" wordCount} saved"]
```
```elm
div [id "doc-word-count"] [text "\(pluralize "word" wordCount) saved"]
```

### Example 2

https://github.com/rtfeldman/dreamwriter/blob/master/Component/Editor.elm#L88
```elm
else (withCommas quantity) ++ " " ++ noun ++ "s"
```
```elm
else "{{withCommas quantity}} {{noun}}s"
```
```elm
else "{withCommas quantity} {noun}s"
```
```elm
else "#{withCommas quantity} #{noun}s"
```
```elm
else "${withCommas quantity} ${noun}s"
```
```elm
else "\(withCommas quantity) \(noun)s"
```


### Example 3

https://github.com/rtfeldman/dreamwriter/blob/master/Component/Editor.elm#L80

```elm
prefix ++ "," ++ (String.right 3 <| toString num)
```
```elm
"{{prefix}}, {{String.right 3 <| toString num}}"
```
```elm
"{prefix}, {String.right 3 <| toString num}"
```
```elm
"#{prefix}, #{String.right 3 <| toString num}"
```
```elm
"${prefix}, ${String.right 3 <| toString num}"
```
```elm
"\(prefix), \(String.right 3 <| toString num)"
```

**Comment by TheSeamau5** [comment]
I put the nested interpolation as a contrived example to push the idea to its limits. Obviously, this would be considered bad style, ideally, you'd do something like this:

``` elm
welcomeMessage user = 
  let makeRow elem = " {{ elem.date }} | {{ elem.location }} | £ {{ elem.total }} "
      makeTable list =  """
        Date | Location | Total
        ---- | -------- | -----
        {{ String.lines <| List.map makeRow list }}
      """
  in Markdown.toHtml """
        ##Welcome {{user.title ? ""}} {{user.name}}

        - Checking account : *£ {{user.checking.total}}*
        - Savings account : *£ {{user.savings.total}}*

        ### Withdrawals
        {{ makeTable user.withdrawals }}
     """
```

(Don't mind the indentation too much, it's really for clarity)

**Comment by TheSeamau5** [comment]
As for examples, just check out the whole `Shader` folder in `GraphicsEngine`. There's a file called [`Boilerplate.elm`](https://github.com/TheSeamau5/GraphicsEngine/blob/master/Engine/Shader/Boilerplate.elm) that's filled with helper functions to help do some string concatenation.

Here's an example:

```elm
commonShaderBoilerplate : String
commonShaderBoilerplate =
  materialPropertyStructTypeDefinition ++ newLine ++ newLine ++
  materialStructTypeDefinition         ++ newLine ++ newLine ++
  lightStructTypeDefinition            ++ newLine ++ newLine ++
  uniformDeclarations                  ++ newLine ++ newLine ++
  setupLight                           ++ newLine ++ newLine ++
  setupMaterial                        ++ newLine ++ newLine ++
  libraryVariables                     ++ newLine ++ newLine ++
  libraryFunctions
```

Which could be reduced to 

```elm
commonShaderBoilerplate : String
commonShaderBoilerplate = """ 
   {{ materialPropertyStructTypeDefinition }}
   {{ materialStructTypeDefinition }}
   {{ lightStructTypeDefinition }}
   {{ uniformDeclarations }}
   {{ setupLight }} 
   {{ setupMaterial }}
   {{ libraryVariables }}
   {{ libraryFunctions }}
""" 
```

I think it's more straightforward than having all those newlines

**Comment by rtfeldman** [comment]
I didn't realize this, but [ES6 will actually use `${}`](http://updates.html5rocks.com/2015/01/ES6-Template-Strings) - making that syntax easily the most common.

It's not my favorite, but for what it's worth, it seems to be super common.

**Comment by evancz** [comment]
I think what js does is data like any other language. What are the downsides of double curly?

Does the overlap with templating matter? Let's think that through. Pretend Elm is the server, and we want to generate some stuff statically?

Why does everyone do an ugly asymmetrical one? (Besides C#) Is it logical or historical?

**Comment by TheSeamau5** [comment]
I like the double curly personally. I assume the other languages do the asymmetric stuff to not clash with other syntax in the language or something. But I think that the double mustache syntax sticks out nicely.

**Comment by rtfeldman** [comment]
I think it's historical...I've never heard an argument that it's better on
its own merits.

I'm not worried about template clashes. Almost always you're either loading
those from a file (in which case Elm doesn't parse it, so it's moot) or
it's a big multiline thing where you'd probably want to use a different
quoting method anyway - for example, to avoid clashes on quotation marks.

Also, find/replace "{{" with "\{{" would be a quick and reliable escaping
operation if worst came to worst.

**Comment by evancz** [comment]
I'm interested in the details in case we are missing something. I was asking for someone to do the research and figure it out. It's not about opinions right now.

**Comment by evancz** [comment]
Sorry, that was harsh! I figure we should at least do a search to figure out who did it first and if there are design discussions out there. Maybe it's from perl, that'd be interesting to know!

**Comment by rtfeldman** [comment]
Ah, sure. Makes sense!

A concrete drawback of `${}` and `#{}` that I've encountered is their implication on text editors.

When I try to type `"The # of questions"` in a Sublime CoffeeScript editor, I get as far as `"The #` at which point autocomplete helpfully jumps in with `"The #{}` and I have to delete the curlies. As you can imagine, this is even more annoying with `$` instead of `#`, especially when dealing with USD currency.

Yes, I can turn off that autocomplete feature (or bug plugin authors to only close the curly instead of opening it too), but a syntax less conducive to false positives renders this moot.

**Comment by TheSeamau5** [comment]
Plus, who doesn't like symmetry? 

Lists have square brackets
Lisps have parentheses

There's value to making it nice and simple. There would be no need to remember "What's the character I put in before the curly? Is it a `$` or a `#`?"


We could alternatively just make it one curly:

```elm
declareConstVariable variableType variableName initialValue = 
  "const { variableType } { variableName } = { initialValue };" 
```

It kinda reminds me of the whole templating/binding stuff in JS. I think (although you guys should probably correct me on this one) that the convention goes: 2 curlies for two-way data binding, 1 curly for one-way data binding. 

If you pass in `Signals` to `declateConstVariable` instead of just strings (using `Signal.map3` of course) then you end up with one-way data-binding.

**Comment by mgold** [comment]
I'm worried a single curly would be too commonly used unescaped. But, I honestly can't think of a non-code use for it. Double curly is fine.

**Comment by evancz** [comment]
I tend to write curly braces in code blocks, which I tend to do as triple quoted strings for the Elm websites and such. I can imagine it being *extremely* annoying in that case. The whole point of the triple quoted strings is that things tend to work out really nicely.

**Comment by rtfeldman** [comment]
Double curlies would still be fine for that use case though, yeah?

**Comment by evancz** [comment]
Yeah, I can't remember ever writing double curly braces organically :)

**Comment by bsummer4** [comment]
Just want to point out that most languages with string interpolation have a separate syntax for interpolated strings. I think this is really important to avoid accidental uses.

    Coffeescript: '#{asdf}' vs "#{asdf}"
    es6: "${asdf}" vs `${asdf}`

**Comment by evancz** [comment]
@bsummer4, what about all the languages @rtfeldman mentioned?

In JS I assume this is so that the whole internet does not break, though I don't see the rational in CoffeeScript. I'd guess that languages that had this feature from the start do not have special quotes?

**Comment by rtfeldman** [comment]
@evancz Perl, Ruby, and CoffeeScript all use single-quoted strings to mean "no interpolation" but in my experience mainly what this approach serves to do is to litter codebases with inconsistent usages of string syntax.

Pretty much the only use case (read: *literally* the only use case I've ever encountered) for putting interpolation syntax in a string that you don't want to actually be interpolated is when you're doing something like documenting the string interpolation feature.

I think Elm's existing `"""` (which I assume would continue to be non-interpolated) string style covers this much better than single-quote strings or backtick-strings, because nobody will casually substitute those for normal double-quote strings and cause stylistic inconsistencies.

**Comment by evancz** [comment]
Interesting, I had assumed all strings would have the interpolation feature. You would do something like `"{\0{"` if you wanted to write two curly braces in a row.

Is it valuable to rule out code like some of @TheSeamau5's examples of bigger chunks with interpolation? Or is the idea that that is not the common case and maybe should be done some other way?

**Comment by evancz** [comment]
I'm actually pretty into the idea that `"""` is not interpolated. The theory would be, "hey, don't you want to use a proper pretty printing library for this kind of thing" and we can always add it later if people are annoyed.

**Comment by rtfeldman** [comment]
Oh, I'd just assumed `"""` would be non-interpolated; I wasn't trying to advocate for or against. :smile: 

The following would be [consistent with how CoffeeScript handles these quote styles](http://stackoverflow.com/questions/8608292/how-to-escape-string-interpolation-in-coffeescript) with regards to whether or not they are interpolated:

`"There are {{length hobbitList}} hobbits."` - interpolated
`"""There are {{length hobbitList}} hobbits."""` - interpolated
`'''There are {{length hobbitList}} hobbits.'''` - NOT interpolated

Additionally, CoffeeScript offers single-quote (as opposed to 3x single quote) non-interpolated strings, which I do think leads to far more badness than usefulness.

**Comment by evancz** [comment]
Let's advocate for or against! :P

I think it's a bit weird to use `'c'` for characters and `'''hello'''` for strings. Seems very inconsistent to me. I'd go for something like this:

`"There are {{length hobbitList}} hobbits."` - interpolated
`"""There are {{length hobbitList}} hobbits."""` - interpolated
`'"""There are \{{length hobbitList}} hobbits.""` - NOT interpolated

You can just "escape" a curly brace and it won't count anymore.

**Comment by rtfeldman** [comment]
That sounds good to me! I assume escaping would be supported for normal `"`
strings as well?

**Comment by evancz** [comment]
Yeah, for sure.

**Comment by bsummer4** [comment]
@evancz, @rtfeldman: I updated the list of examples in my previous comment. I really think that string interpolation and string literals are separate concepts and deserve distinct syntax.

All of the languages that I can think of outside of the perl family make the distinction very explicit.

**Comment by rtfeldman** [comment]
I agree that those languages do, but of course that doesn't imply that they are correct to do so. :smiley: 

My position is:

1. The most common use case is to want interpolation to be available.
2. The most common case should not require extra work; for example, the `s` in Scala's `s"some {{interpolated}} string"` is undesirable.
2. The cost of extra syntax (as opposed to escaping) is that it introduces ambiguity about which style you should use. I've seen lots of code bases where single-quote (uninterpolated) strings and double-quote (interpolated) strings are intermingled, and in every case I can remember, double-quote would have been fine. In fact, changing them from single-quoted to double-quoted because I want to introduce interpolation is an annoyingly common chore I find myself doing in these languages. (I don't know why so many people reach for single quotes unnecessarily, but empirically it's widespread.)
3. If you always have to escape, you will clearly only use it when it is warranted, so this downside never materializes.
4. Wanting to disregard interpolation in a string literal is an extremely uncommon edge case, and as such, having to escape is an extremely uncommon inconvenience.

I think this would be an improvement over the approaches of the languages mentioned earlier.

**Comment by evancz** [comment]
@bsummer4, thanks, that is really useful info!

I can see the argument that as a reader of code, it'd be good to have a marker at the beginning that says, "hey, watch out for interpolation here." I'm not saying I buy it, but I think it makes sense.

I think in a lot of cases, the syntax is different because it is done with macros or something. I think the scala one uses their macro system? Haskell's is using Template Haskell. Rust does it [with macros](http://stackoverflow.com/questions/21324657/does-rust-support-ruby-like-string-interpolation) apparently as well.

Assuming this whole "Elm with macros" becomes a thing, I could imagine doing this with `@"hello {{name}}"` or something. I'm not saying I like that, but rather, I'm suggesting a theory of why so many languages have special syntax and what that could mean for Elm.

Maybe doing it with macros is the unfortunate version?

**Comment by rtfeldman** [comment]
I think it is, yeah. Inasmuch as strings are just (in some languages) nice sugar for lists of characters, interpolation is just a low-friction way to make that sugar even nicer for a very common use case.

**Comment by evancz** [comment]
Here's [a nice write up](https://mail.mozilla.org/pipermail/rust-dev/2012-February/001346.html) from the Rust mailing list about different options.

**Comment by evancz** [comment]
I think the point they make on the Rust list about using {{ }} as an attack vector is interesting. I feel like the issue after this one is, "how can I construct a URL that escapes stuff?"

```elm
"http://example.com/user/{{name}}"
```

And now someone is like "how can I get spaces to turn into + signs?" What do we say to them? "Just be sure to call `Http.uriEncode`?"

```elm
"http://example.com/user/{{ uriEncode name }}"
```

Is that satisfactory? Is this gonna be any more or less error prone than the existing situation?

Thinking about macro world, maybe there'll be a time when you can write this:

```elm
@url "http://example.com/user{{name}}"
```

And it will do a bit of extra expanding to add in the `uriEncode` call?

**Comment by rtfeldman** [comment]
`"http://example.com/user/{{ uriEncode name }}"` is what I'd always expected to do.

I think constructing Strings that have validity constraints (e.g. URLs, regular expressions, JSON, XML...) is an orthogonal concern to interpolation, which only coincidentally can make those easier to build.

I don't follow the attack vector argument in a language that doesn't have `eval` - how would an attack like that work?

**Comment by evancz** [comment]
I guess you could put bad stuff in a URL and it'd look like you were making calls from a safe domain. Like, someone unwisely puts user input directly into a string, and an attacker just fills in that user input with some malicious thing, and everyone thinks they are not violating cross origin policy. Does this sound plausible? Do any of these approaches protect against this kind of thing? Am I misunderstanding the point the Rust guy was making?

**Comment by rtfeldman** [comment]
That's certainly a plausible attack vector, but it seems like that's just a general "working with Strings" hazard. In other words, it's the same vector regardless of whether you're using concatenation or interpolation.

Just to make sure I'm on the same page, which exact comment on the Rust thread were you referring to?

**Comment by evancz** [comment]
[This message](https://mail.mozilla.org/pipermail/rust-dev/2012-February/001346.html) has some points about "code injection vectors" and how easy it is to use it for translations. I don't think I understand these points fully though.

**Comment by rtfeldman** [comment]
Oh! The explanation above the pros/cons section sheds some light on that:

> In this case, the format string contains an expression shim, which **fully evaluates** its expressions in the context of the surrounding code. **It's possible to call any expression construct in the format string.**

Emphasis mine. In other words, the interpolated string actually gets `eval`'d.

This seems like a terrible idea. Let's not do that, and then there's no attack vector.

**Comment by evancz** [comment]
I suspected that was what they were saying, but I couldn't believe that was the chosen behavior. Okay, so that is not really a relevant concern. I still wonder about the translation point though...

Also, I guess we should share this on the list at some point!

**Comment by rtfeldman** [comment]
I took that to mean that in i18n implementation you'd delegate a lot of interpolated values to third parties (because your team of programmers wouldn't be writing the copy for that), at which point the eval would become a serious risk.

...which, again, I mean, argh. D:

**Comment by skybrian** [comment]
The usual shorthand for this is "XSS attack". This is probably the most common security flaw in web apps and internally Google requires autoescaping for HTML template libraries because it's too easy to forget otherwise. Using a text template library to generate HTML isn't a good idea. There are probably similar issues for Markdown.

In Go, there are separate libraries for text templates and HTML templates. HTML templates do context-aware autoescaping, so putting a template variable in an href attribute is handled differently than putting between HTML tags.

This is an area where type checking is quite useful. A string containing trusted or sanitized HTML (which shouldn't be double-escaped) should be a different type from a string containing untrusted user input. It would be a pity for Elm to be strict about type checking in other ways and then be loose about strings where it really matters.

**Comment by rtfeldman** [comment]
Using a type-checker to stop XSS is a good discussion to have, but really belongs in a separate issue. This is just a discussion of String interpolation, and guarding against XSS is orthogonal to concatenation versus interpolation; rather, it's a discussion of whether a plain String is the right tool for certain jobs. :smiley:

**Comment by hoosierEE** [comment]
What is being sugared?  I assume it's this:

    ++ toString(expr) ++

Which, if the dollar-sign-double-curly syntax wins, would become this:

    ${{ expr }}

Can we clarify in what contexts this would be possible (double quotes, triple-double quotes, etc.)?

**Comment by rtfeldman** [comment]
@hoosierEE I have updated the original post with the current proposal, which is based on the iteration in this discussion. Does that clear things up?

**Comment by hoosierEE** [comment]
@rtfeldman totally clear now, thanks!

**Comment by laszlopandy** [comment]
One thing I think is missing from this discussion is how to do translations.
For translated strings, you need:
 * positional arguments (so other languages can change the order of the arguments) and
 * runtime format parsing (because I believe people would rather load language specific json files at runtime, than integrate their translation workflow into their Elm build).

Because translation formatting is done at runtime, the proposal is quite separate from this proposal, which does everything at compile time. But for the sake of Elm developers, I think we should have an idea of what runtime formatted strings will look like so their syntax can be consistent with this proposal.

**Comment by rtfeldman** [comment]
@laszlopandy I agree that i18n is orthogonal to this, but not following why the one should necessarily influence the other. Could you post a code snippet to illustrate?

**Comment by krainboltgreene** [comment]
Outside source, with no inherent value, but I love `{{value}}` syntax. I wish more languages chose it.

**Comment by dennisreimann** [comment]
Came here looking for how to do string interpolation in Elm. After reading this issue (and other ones across the Elm repos) I just wanted to say how nice it is to read discussions like this, because it ensures me that Elm is well worth learning and that it has a friendly community that's trying to shape the language nicely. :+1:

**Comment by rchrdnsh** [comment]
I personally want to put in my vote for either single or double curlies. Never have been a fan of currency symbols in code, myself. Also, soon looking forward to this...i personally experience many bugs concentrating strings with variables, so this will be awesome, IMHO :-)

**Comment by rchrdnsh** [comment]
This one for me:

`div [id "doc-word-count"] [text "{pluralize "word" wordCount} saved"]`

is my fav, syntaxtually speaking :-)

**Comment by crazymykl** [comment]
Although I dislike the symmetry (and double closing delimiter) of `{{foo}}`, it seems I am outvoted. Interpolation is still a killer feature.

**Comment by rchrdnsh** [comment]
why do you dislike the symmetry @crazymykl? Just curious :-)

**Comment by crazymykl** [comment]
I like the sigil to denote "do a thing", and then a pair of delimiters indicating what the scope of the thing is.

**Comment by rchrdnsh** [comment]
hmmmm...seems reasonable, but do you think that this context requires a sigil to clarify it's purpose?

**Comment by evancz** [comment]
As a rule, I do not want to track feature requests in issues. You end up closing good ideas, keeping open so-so ideas, etc. and in the end it just makes it harder to focus on bugs that need to be fixed. 

Furthermore, the general policy for right now is to focus on things that **cannot be done** over things that **could be done better**.

So I am going to close, but we can always refer back if/when this gets bumped into focus!
