### ISSUE TITLE
Issue with Array.append

### ISSUE THREAD

**Issue by jheiling** [elm-lang/elm-compiler#906]
There still seems to be an issue with Array.append:

I have the following functions for creating a jagged array and turning it into a regular array:

    initialize : Int -> Int -> (Int -> Int -> a) -> Array(Array a)
    initialize l1 l2 f = Array.initialize l1 (\i1 -> Array.initialize l2 (f i1))
    
    toArray : Array(Array a) -> Array a
    toArray = Array.foldl (\ys rs -> Array.append rs ys) Array.empty

If I just call

    xs = initialize 3 3 (,)

it works as expected and xs is

    Array.fromList [Array.fromList [(0,0),(0,1),(0,2)],Array.fromList [(1,0),(1,1),(1,2)],Array.fromList [(2,0),(2,1),(2,2)]]

But if I call

    xs' = toArray xs

later, xs will be

    Array.fromList [Array.fromList [(0,0),(0,1),(0,2),(1,0),(1,1),(1,2),(2,0),(2,1),(2,2)],Array.fromList [(1,0),(1,1),(1,2)],Array.fromList [(2,0),(2,1),(2,2)]]

afterwards.

**Comment by evancz** [comment]
Also, can you reopen this on the `elm-lang/core` repo? I do not think the bug would be in the compiler. 

When you open it there can you address these things:

  * When you say "still" what are you referring to exactly?
  * Can you also share a minimal example that clearly demonstrates the bug? Ideally one that we can pop into elm-lang.org/try and see easily. The prose explanation is good, but it means we have to reconstruct the code you are talking about in our minds.

**Comment by jheiling** [comment]
Done!
Sorry for opening the issue in the wrong repo, it's 3 in the morning.
