### ISSUE TITLE
Got "the notify function has been called synchronously" error

### ISSUE THREAD

**Issue by mkoconnor** [elm-lang/elm-compiler#909]
Hello, I just started using Elm a couple of days ago and got this error "The notify function has been called synchronously" when using elm-reactor.  The error message said to report this issue, so I'm doing so.

Unfortunately, I'm new enough to elm that I don't know what information would be helpful.  I put the source code here: https://gist.github.com/mkoconnor/2856465fcbb79c1d3edf (it's a polygon-drawer currently).  I've been running it with elm-reactor on a Mac and the output of `elm-reactor --version` is "0.3".

Let me know if there's any more information I can provide that would be helpful.

**Comment by aforemny** [comment]
This seems to be caused by line 94

    let model = { model | next <- update.cursor } in

If you replace it with

    let model' = { model | next <- update.cursor } in

and replace the occurences of ```model``` with ```model'```` it seems to work.

I believe a more minimal example is this https://gist.github.com/aforemny/4453833423b63b482a02.

**Comment by evancz** [comment]
Ah, this looks like a repeat of #873 that is manifesting in a weird way. Thanks for the report @mkoconnor and @aforemny for getting it down smaller so it was easy to see the root problem!
