### ISSUE TITLE
"input is undefined" runtime error when using WebSockets

### ISSUE THREAD

**Issue by onnoowl** [elm-lang/elm-compiler#910]
I'm trying to set up a simple example using WebSockets in Elm, but I keep getting the run time error "input is undefined". The console does not give me any line number in my elm file or anything like that.
This seems like this is an issue with Elm's WebSockets... If I'm doing something wrong, please let me know.

I was trying to use WebSockets in a large project, and I kept getting the error "a is undefined", so I decided to make this small example to try and isolate the problem.

I wrote some code that receives messages containing numbers from the websocket. It increments the numbers, and then sends the new numbers back out over the web socket. The server does the same thing, sending back the number incremented by 1 to the client.

Here is the elm code: https://gist.github.com/onnoowl/2540996b2ac55002d773

I tested the server side, and it's working fine, so I definitely do not think that the server is causing the issue.

When I tried the code in Firefox, I get "input is undefined". When I run it in Chrome, I get "Cannot read property 'kids' of undefined". In Chrome, upon looking at the stack trace it seems that when the code goes to run, input is undefined. Is this a bug with the WebSocket library?

I'm very new to using Elm, so I'd appreciate any help/advice on using websockets.

**Comment by onnoowl** [comment]
I'm going to close this issue, and post it on the core repository instead.

**Comment by evancz** [comment]
Hey, sorry for the trouble. The `WebSockets` library is not fully featured as is, so we are doing a revamp of the general approach in 0.15. We are typically recommending that people do any websockets stuff with [ports](http://elm-lang.org/learn/Ports.elm) until we get a proper implementation done.

**Comment by onnoowl** [comment]
Ok, thanks.
When do you think 0.15 will be released?

Also, is there any way to embed javascript inside elm?
Or do I need to make an HTML document that embeds my elm code?

**Comment by evancz** [comment]
I'm hoping for the next week or so, but it's not going to have a websockets library out of the box. It will be possible to create a good one though. So I'd still go for ports right now.

No embedding of JS directly, mainly so that code can stay more platform independent in the long run. So the second one. Same with CSS for now.
