### ISSUE TITLE
Listing of Difficult-to-understand Compiler Errors

### ISSUE THREAD

**Issue by rtfeldman** [elm-lang/elm-compiler#911]
As discussed in [this post](https://groups.google.com/d/msg/elm-discuss/0gVxiYZj2Vk/6wZZnHlMnQAJ), here is an issue for posting compiler error messages anyone finds confusing. The first step to on the road to a better compiler is identifying problem areas!

**Comment by rtfeldman** [comment]
This can be reproduced by checking out [this commit](https://github.com/rtfeldman/dreamwriter/commit/ded5e9a5d3ac7aa0ea15ab3dbf8a5590de7240dc) and building using Elm 0.14. (Following the instructions in the README should work, or alternatively I'd expect just trying to compile App.elm ought to give this compilation error.)

```
Error in App.elm:

Type mismatch between the following types on line 214, column 39 to 60:

        String

        ()

    It is related to the following expression:

        {locals | update = pageUpdate} Use --force to continue.
```

[The fix for this error](https://github.com/rtfeldman/dreamwriter/commit/6f751d9faa738a02972439fd99b1c4613fb08e65) turned out to be related to `locals`, but given the vagueness of the message, I was fortunate to have known how I'd most recently changed that structure (I'd mistakenly added `openNoteId : LocalChannel ()` when I should have added `openNoteId : LocalChannel Identifier`).

If that knowledge hadn't been fresh in my memory, this would have taken much longer to track down!

**Comment by mgold** [comment]
Here's one:
````
> (//)
<function> : Int -> Int -> Int
> 3 // 2.0

Error in repl-temp-000.elm:

Type mismatch between the following types on line 3, column 3 to 11:

        Char.KeyCode

        Time.Time

    It is related to the following expression:

        3 // 2.0
````

This is a **0.15 regression** inasmuch that 0.14 reports Int and Float.

**Comment by evancz** [comment]
I started the [error message catalog](https://github.com/evancz/error-message-catalog) for this kind of stuff, so I'm gonna close this.

@rtfeldman , if you can get your example down smaller (gist sized) I think there are some plausible improvements to record updates. I need more data to really know the implications of those changes though. Maybe do a PR to the new repo if you have a chance in the next year or so :P
