### ISSUE TITLE
Specifying Source Character Encoding

### ISSUE THREAD

**Issue by donutcho** [elm-lang/elm-compiler#914]
I apologize for my poor English.
Searched with filter "is:issue is:open encoding" -> Result: 0
Also this is called "RFE" issue?

Requiring this: 
    `elm make --encoding UTF-8 a.elm --output b.html`
And also if "elm make" default character encoding is set to UTF-8, it is better for me (and other 2 bytes character language users maybe). 
 
Current case: 
1. On ja-jp Windows platform, default character encoding is "Shift-JIS (CP932)".
2. Writes/Saves an Elm source file with "UTF-8" encoding. According to output HTML file is UTF-8. 
3. "elm make" try to compile source file with default character encoding (Shift-JIS).
4. Result: hGetContents: invalid argument (invalid byte sequence)

As long as using only non ja-jp chareters with UTF-8, no error occurred. 

By the way, I heard that "mkTextEncoding function in System.IO module can set an encoding".

**Comment by donutcho** [comment]
Pastes the source contains ja-jp character: 
```
import Graphics.Element exposing (..)

main : Element
main = show "私"
```

**Comment by rtfeldman** [comment]
@donutcho We ran into this recently (the `hGetContents` error) and it looks like you can specify source encoding with an environment variable like so:

```bash
LANG=en_US.UTF-8 elm-make a.elm
```

Maybe this would resolve your issue without the need for an `--encoding` flag?

**Comment by laszlopandy** [comment]
Can anyone reproduce this issue on OSX, or maybe on a Linux VM? I would like to attempt fixing this for good but I don't have a windows machine which I can set to Japanese, and so far I can't reproduce it on OSX, even if I force LANG to some other encoding.

**Comment by rtfeldman** [comment]
I have never seen it on OS X. We encountered it on Jenkins running on a Linux box, but it's not in an environment I can easily export to a VM for reproducing locally.

**Comment by donutcho** [comment]
Many thanks for the specific feedbacks! For now, I'm following rtfeldman/node-elm-compiler#3 and elm-lang/elm-make#20.
