### ISSUE TITLE
elm-doc should error on non-exported name in @docs

### ISSUE THREAD

**Issue by Apanatshka** [elm-lang/elm-compiler#915]
Right now it just happily generates documentation when you use un-exported names in a `@docs` tag, and a package author who unwittingly publishes his/her package only finds out by looking through the docs and finding:
```
There is some problem with the docs for 'forgot-to-export-this-name-trollolol', please inform the package author.
```

**Comment by mgold** [comment]
This should be done before elm-package accepts a revision. Good catch.

**Comment by evancz** [comment]
Track this on the WIP issue
