### ISSUE TITLE
Signal.merge Behavior for First Element

### ISSUE THREAD

**Issue by DavidHarrison** [elm-lang/elm-compiler#919]
I am running into issues using merge (specifically using Signal.Extra.foldp'), where the first element of a merged signal is not an expected value. The following:
```elm
import Graphics.Element exposing (Element, show)
import Time exposing (every, second)
import Signal exposing ((<~), merge)

type MyADT = Value1 | Value2

showMyADT : MyADT -> String
showMyADT adt = case adt of
    Value1 -> "Value 1"
    Value2 -> "Value 2"

main : Signal Element
main =
    let value = Value1
        fun = showMyADT
        sig = (always value) <~ every second
    in show << fun <~ merge sig sig
```
gives the error:
`Cannot read property 'ctor' of undefined`

Changing `fun` to `identity` will not fail, however the first value will be `<internal structure>`.
Changing `value` to `1` and `fun` to `(\x -> x + 1)` will similarly not fail, but start with `NaN`.

**Comment by evancz** [comment]
I believe https://github.com/elm-lang/core/pull/228 resolves your issue, and I'll be doing a patch to elm-lang/core to release this. Thanks for the report!

**Comment by evancz** [comment]
Okay, 2.0.1 of elm-lang/core should be out. If you can reproduce this issue, please open an issue on the elm-lang/core repo!

**Comment by DavidHarrison** [comment]
2.0.1 works great, thanks!
