### ISSUE TITLE
Confusion with dependencies

### ISSUE THREAD

**Issue by TheSeamau5** [elm-lang/elm-compiler#920]
So, I made a package called `elm-shrink` that exposed a single module called `Shrink` in a file called `Shrink.elm`. This package uses tons of private functions which are all placed in a seperate file: `Utils.elm`.

The file hierarchy in elm-shrink looks like this: 

```
elm-shrink
|
|__ src
    |
    |__ Shrink.elm
    |
    |__ Utils.elm
```

And the import in `Shrink.elm` goes like this:

```elm
module Shrink where

....

import Utils exposing (..)

...
```

And the `elm-package.json` file only exposes `Shrink` since `Utils` is "private":

```json

{
    "version": "1.0.0",
    "summary": "Library for authoring shrinking strategies",
    "repository": "https://github.com/TheSeamau5/elm-shrink.git",
    "license": "BSD3",
    "source-directories": [
        "src"
    ],
    "exposed-modules": [
      "Shrink"
    ],
    "dependencies": {
        "elm-lang/core": "2.0.0 <= v < 3.0.0"
    },
    "elm-version": "0.15.0 <= v < 0.16.0"
}
```

But when I try to use it, as in by importing the package and calling elm-reactor, I get this error:

```
Error in package TheSeamau5/elm-shrink 1.0.0 in module Shrink:

Error on line 66, column 30 to 39:
Could not find variable 'seriesInt'.


This error is probably due to bad version bounds. You should definitely
inform the maintainer of TheSeamau5/elm-shrink to get this fixed.

In the meantime, you can attempt to get rid of the problematic dependency by
modifying elm-stuff/exact-dependencies.json, though that is not a long term
solution.
```

Where `seriesInt` is one of those "private" functions in the Utils file. 

Is this a bug? If so, what's the workaround? If not, what am I doing wrong?

You can find the github repo for `elm-shrink` here : https://github.com/TheSeamau5/elm-shrink
Or you can get it from elm-package here : http://package.elm-lang.org/packages/TheSeamau5/elm-shrink/1.0.0

**Comment by TheSeamau5** [comment]
I solved it by removing the `Utils.elm` file, putting all of its contents in `Shrink.elm` and then expliciting all of the exports. The problem is that were I to add files to elm-shrink, I couldn't re-use those private functions within the package

**Comment by evancz** [comment]
Can you create a minimal reproducible example? The info here is enough to show me that something is weird, but not enough to easily reproduce it or localize the issue.

**Comment by evancz** [comment]
I'm not sure how to reproduce or act on this, so I am going to close. If you can get it down smaller, please open an issue about it on elm-package or elm-reactor depending on the exact details!
