### ISSUE TITLE
Proposal: private keyword

### ISSUE THREAD

**Issue by TheSeamau5** [elm-lang/elm-compiler#923]
It's often the case that I forget to export certain functions. As soon as I define one single measly private function, I have to manually list all of the functions I am exporting. When my module has many public functions and few private ones (often the case), I often forget to list all the public ones in the module declaration. It's tedious and error-prone.

Instead, I'd like to qualify the private functions as such. I know which functions are private, even while I'm authoring them and adding that one "keyword" is nothing compared to actually forgetting to export a public function. 

This feature could look like this:

```elm
map : (a -> b) -> List a -> List b
map f list = 
  trampoline (map' f list [])


private map' : (a -> b) -> List a -> List b -> Trampoline (List b)
private map' f list accum = case list of
  [] -> Done accum
  x :: xs ->
    Continue (\() -> map' f xs (accum ++ [f x]))
```

Variants of this feature can be found in multiple programming languages

### Scala

Example taken from scala docs: http://docs.scala-lang.org/style/declarations.html

```scala
private def foo(x: Int = 6, y: Int = 7) = x + y
```

### Clojure

Note: there is no explicit notion of private in clojure but you can make function invisible outside a given namespace using the appropriate macro or metadata

Taken from : https://github.com/bbatsov/clojure-style-guide

```clj
(defn- private-fun [] ...)

(def ^:private private-var ...)
```

### Dart

As stated in the [dart-lang docs](https://www.dartlang.org/docs/dart-up-and-running/ch02.html#important-concepts), Dart doesn't have a `private` keyword but instead considers identifiers that start with an underscore to be private to is library.

```dart
// This is private
_sum(x, y) => x + y;

// This is public
sum(x,y) => x + y;
```

### Typescript

Typescript does the exact opposite of what I am proposing and I thought that this is a valid reason to include it early in the discussion. Rather than mark explicitly what you want to hide, you make explicitly what you want to export.

Example from Typescript Handbook : http://www.typescriptlang.org/Handbook#modules

```ts
import validation = require('./Validation');
var lettersRegexp = /^[A-Za-z]+$/;
export class LettersOnlyValidator implements validation.StringValidator {
    isAcceptable(s: string) {
        return lettersRegexp.test(s);
    }
}
```

The pros of this approach: 

1. The is a symmetry between the `import` keyword and the `export` keyword. Symmetry is always nice.
2. The export keyword can lend itself nicely to the idea of re-exporting entire modules from other modules. 

Example:

```elm
module Math where

export Math.Arithmetic
export Math.Calculus
export Math.LinearAlgebra
```

While this is not a proposal or a discussion about re-exporting modules or how that would work, it's interesting to note that `export` makes the language open to such a feature in the future.

The cons of this approach:

1. It's tedious. It's exactly what is done today except you mark these functions public at the site where they are defined as opposed to all the way at the top of the file.
2. Making functions public is not the default. This is an unnecessary drag that can make things needlessly hard for beginners.

**Comment by mgold** [comment]
+1 for the idea. This is definitely an improvement over listing everything at the top, and by default, everything is public. I really like how the proposed syntax mirrors `port` as something affixed to the definition (and annotation).

A few edge cases to watch out for in during implementation:
* let-bound functions cannot be declared private (they already are)
* private ports should be disallowed (probably)
* private functions should not be allowed in Main, or unmoduled code

**Comment by TheSeamau5** [comment]
Nice catch, those are valuable edge cases. 

Yeah, only top-level functions/constants should be public. 
As for Main, I don't think it's worth the trouble to disallow it. 
Private ports... I have no idea what that would mean. Maybe a way of offering a Signal-based API in Elm as opposed to Task-based one? I dunno, sounds weird.

Anyways, the idea of a private keyword just comes from the frustration of having forgotten to export something in another package for the umpteenth bazillionth time and then having to go to that package, actually export it, go to the terminal, elm package publish, oh I gotta bump, etc... etc... etc...

Especially a package like `elm-random-extra`, it's super hard to keep track of all this stuff. I basically treat it as like a dropbox of generators and combinators. Whenever I have a new super useful random generator, I put it there.

The worst is if I ever add a private function to the `Random.Char` submodule: https://github.com/TheSeamau5/elm-random-extra/blob/master/src/Random/Char.elm

Just look at that behemoth. There's no way I'm not gonna forget one of those generators in the module declaration.

**Comment by Apanatshka** [comment]
Interesting idea. Right now I'm mostly annoyed by the fragile syntax in the export list. But I've also been bitten by forgetting to import. I guess excluding some things it a nice solution. 

I'm not completely sure about the keyword. It's long, and it looks sort of :confused: . Adding an underscore to the front the name always seemed a bit ad-hoc to me, but it's lightweight and rather elegant in how it shows that it's a private function at every use site too. 
I'm not even sure what I'm voting for here.

**Comment by Apanatshka** [comment]
Oh, I'd like to add another language to the list:

# C++

C++ has private *sections* inside classes. This restricts you from putting a private function "physically close" to the public function that uses it, but removes a lot of typing and visual overhead. 

```cpp
class SomeClass {
  public:
    int a;
    void method();

  private:
    int b;
    int method2();
    int method3();
};
```

**Comment by TheSeamau5** [comment]
I guess you could translate the C++ example to like a private block or something:

```elm
private {

sum x y = x + y

mul x y = x * y

}

div x y = x / y
```

where `div` would be public and `sum` and `mul` would be private. I guess there's less visual noise in this case

**Comment by Apanatshka** [comment]
Someone's going on Santa's naughty list; suggesting curly braces to delimit something in Elm, smh. 
```elm
div x y = x / y

private section --either indentation or just don't allow to switch back to public definitions
  sum x y = x + y

  mul x y = x *y
```

**Comment by TheSeamau5** [comment]
Lol. Well I couldn't think of something less intrusive. If you're going with indentation, why not something like C++?

```elm
div x y = x / y

private : 
  sum x y = x + y
  mul x y = x * y
```

The colon thing makes it look a bit like Python, but I guess that's not a bad language to seek inspiration from.

**Comment by mgold** [comment]
I'm still moderately in favor of `private funName x = ...` because it mirrors `port` declarations. Like `exposing`, the extra typing could be a good thing, because you shouldn't have too many private functions.

**Comment by TheSeamau5** [comment]
Umm... I've bumped into cases where there are way more private functions than public ones. For example, if you have a submodule that wants to provide a single Html components but needs tons of helpers (like, a few for the styles, a few for all those div containers, etc...). That's one case where it gets tedious.

**Comment by evancz** [comment]
I recall a discussion on the mailing list about this. One of the tensions with any system is "public-by-default sucks when everything is private" and "private-by-default sucks when everything is public".

The theory is that by default we are in public-by-default mode. When you want to get more serious about code quality, you can switch into private-by-default mode by explicitly listing what is exported. This is nice in that someone browsing your code immediately knows what is exposed without browsing hundreds of lines of code. It's all at the top.

For @TheSeamau5's specific case of missing exports, I can't say I have ever had this problem. With all the code I have written, it tends to start out public-by-default, and then I close it down. When that happens I can use `elm-package diff` to see exactly what I am removing from the public API. In your case, you can make your code expose everything for a bit, and `elm-package diff` will tell you everything you are adding.

**Comment by evancz** [comment]
As a final note, I never ever publish anything without first running `elm-package diff` so I can review my changes. Are there things I forgot to expose? Are there changes I forgot I made that I don't want to expose anymore? It's super easy to assess these questions now.

**Comment by imeckler** [comment]
[Idris](http://docs.idris-lang.org/en/latest/tutorial/modules.html?highlight=public#export-modifiers) lets you annotate top level decls with `public`, `private`, or `abstract` (this latter not really being applicable in Elm's case for value decls, but certainly for types). On top of this, you can change the default access level by putting `%access ACCESS_LEVEL` at the top of your module.

**Comment by Apanatshka** [comment]
I don't think we should hold on to the idea of manually keeping a list of exports up to date at the top of the file, just so some day someone can have a bit of convenience in reading the code without needing a tool to find a list of exported functions. I mean, you can look at the docs of the module. Or use an Elm-specific tool, or a sed-script for all I care. 
Has anyone here ever read a Haskell module and thought, wow this list of exported functions is really handy? I almost never look at imports/exports of programs, and I'm not bothered by the public/private annotations in OO languages. Because I can text-search any file, and usually have nice tools handy that give me an overview of the file. 

As for the `elm-package diff` workflow: that's useful to know Evan. That sounds like an ok solution. But not a great one! That's an extra manual step that you need to remember to do instead of being automated somehow. And that tip isn't documented anywhere (that I've seen). I think that's the least we can do, maybe add it to the console output of `elm-package publish`? Like: "Have you checked your list of exported functions? Just abort this operation and run `elm-package diff` to see what's changed. "

**Comment by mkolosick** [comment]
One of the ideas about private by default is that it requires you to actively decide what you want to expose in your API. That way you don't accidentally leave something in there and have users rely on something that should have been private.

**Comment by evancz** [comment]
There are a number of ideas that address this in different ways. One I like is to change module declarations to be like this:

```elm
module MyThing exposing (..)
```

So no more `where` as a keyword there. I have a list of the different options of how to address the root concern here, so I am going to close this issue in favor of that.

Thanks for the proposal!
