### ISSUE TITLE
Proposal: allow fully qualified modules (author/package/Module) in imports for potential dissambiguation

### ISSUE THREAD

**Issue by TheSeamau5** [elm-lang/elm-compiler#935]
This may become a problem with all the `extra` modules where the names clash. 

In the case modules have the same name, it would be nice to be able to prefix the module names by the author names too. For example:

```elm
import A/List.Extra
import B/List.Extra
```

This allows the user to use multiple modules that share the same name. The problem then may be in accessing fields. We may require the user of the module to alias these things in order to use them (in order not to have the slash in the code).

```elm
import A/List.Extra as AList
import B/List.Extra as BList


x = AList.foo

y = BList.foo
```

We may want to shy away from allowing the following:

```elm
import A/List.Extra
import B/List.Extra

x = A/List.Extra.foo

y = B/List.Extra.foo
```

Because the author name is not forced to start with a capital letter.

```elm
import evancz/Html
```

So, the user would have to alias this for sanity:

```elm
import evancz/Html as Html

```

**Comment by Apanatshka** [comment]
Have you run into this problem yet? I haven't seen any overlapping `-extra` packages yet. 
How is this conflict resolved at the moment? Is it just impossible to depend on two packages that use the same module names?
How does Haskell resolve this? They don't use package author names, not that I've seen anyway. IIRC they just merge the modules? Is that a sane approach to resolving this?

(Basically having the author name in your code sounds like a bad idea to me. But I don't really have the bandwidth to think about why, because I'm just context-switching from long compile times at work to write short messages, so it's just a gut feeling).

**Comment by TheSeamau5** [comment]
I haven't run into this problem either currently. We can try. I'll try to publish a fake `-extra` library with a function that has the same name as another package of the same name but has a different type. 

The thing about this functionality is that it's supposed to be rare. (hence the extra boilerplate. It shouldn't be fun to use for a reason) Another option would be to simply ban these things. Like, you cannot publish a package with the same name. (Beware of race conditions with this one). This could be the best option as hopefully the `extra` libraries get integrated into the core library.

**Comment by Apanatshka** [comment]
I like that idea, let's be conservative and ban it for now :+1:

**Comment by manleyjster** [comment]
npm just implemented something very similar to this - not at the language level, but at the package index level: see http://blog.npmjs.org/post/116936804365/solving-npms-hard-problem-naming-packages

**Comment by evancz** [comment]
I think this makes sense, but I don't want a bunch of proposals sitting around in this repo. I think we'll add this someday and it is on my personal list of additions. In the meantime, I'd like to see if folks run into this kind of thing for now.

**Comment by TheSeamau5** [comment]
First instance of someone running into this problem: https://github.com/elm-lang/elm-compiler/issues/1043
