### ISSUE TITLE
Proposal: Compact error messages

### ISSUE THREAD

**Issue by Apanatshka** [elm-lang/elm-compiler#936]
Power users who prefer to use the command line error messages of the compiler may want to have more compact error messages for easily glancing. It would be great if this was somehow supported. Either by the compiler itself or have an easy way for another tool to influence the error messages, e.g. based on JSON output of the compiler errors that's been planned for editor integration. 

Use case: It may be a natural iteration of write code sloppily, run compiler, recognise obvious errors in a glance, fix, repeat. An error like the following is great if you have never seen an error message before, but if you've seen many and many like this there is redundant information:
```
-- TYPE MISMATCH -------------------------------------------------------------- 

This argument is causing a type mismatch.

Looks like a record is missing the field 'errors'

15| 
16|        view { username = "", password = "" } 
17|             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

To be more specific, as I infer all the types, I am seeing a conflict between
this type:

    { b |
          password : String
        , errors : { a |   password : String, username : String }
        , username : String
        }

and this type:

    { password : String, username : String }

```

I would minimize this to a more compact:
```
16:8-16:44 (record missing field 'errors')
    { b | password : String
        , errors : { a | password : String, username : String }
        , username : String }
 /= { password : String, username : String }

```
So only line/column instead of the actual code, a more terse hint, more compactly printed type, and type mismatch is simply denoted with `/=`.

**Comment by mgold** [comment]
Or maybe even a `≠`?

This sounds good down the line, but it's possible to tweak the existing wording without needing a separate compact mode.

**Comment by Apanatshka** [comment]
I'm not a power user atm, so it's not a must-have for me either. But if it isn't added in the next release, it would be nice to at least keep this in mind for the future and design for it. I don't think tweaking the existing wording will be enough for power users.

**Comment by evancz** [comment]
Things are more compact in the latest version. Is this addressed enough, or do you want it even more compact?

**Comment by Apanatshka** [comment]
Can you post the new version? It'll probably still be too expansive for power users.

**Comment by evancz** [comment]
Not sure what code produced that message, maybe add a link to a gist of that in the initial report? The new stuff is available in the online editor now.

**Comment by Apanatshka** [comment]
I can't find the original code either :( I used the missing field example from the error-message-catalog to view the new message in the online editor. It's not compact enough for power users. 

My proposal is to have a flag for messages with minimal line/column, minimal text hint and the two types and don't match. (See also original post)

**Comment by evancz** [comment]
I think this belongs in the error-message-catalog, let's move this over there. Open an issue that has a code snippet and the output of the compiler. Then describe the sort of thing you'd be into.

The long term answer may be writing wrappers that eat the JSON output and do whatever they want to do, so there may never be "explicit" support for this.

**Comment by Apanatshka** [comment]
Ok, this is now in [error-message-catalog issue #41](https://github.com/elm-lang/error-message-catalog/issues/41).
