### ISSUE TITLE
Regression: Empty List confuses typechecker

### ISSUE THREAD

**Issue by TheSeamau5** [elm-lang/elm-compiler#937]
Currently, in Elm, this code:

```elm
import Graphics.Element exposing (show)

x = "h" ++ []

main = show x
```

yields this error message:

```
Type mismatch between the following types on line 4, column 5 to 14:

       String

       List a

   It is related to the following expression:

       "h" ++ []
```

But, after the new warnings work, you don't get a type error and instead get this result:

```
"h[object Object]"
```

**Comment by evancz** [comment]
Thanks for the report, this blocks the release of the new messages!

I spent a while looking into this yesterday and could not figure it out. Are you able to figure out when the break was introduced? My theory was that changing `Type.Constrain.Expression` for binops and application was the root, but I was unable to substantiate that. I did not try reverting those changes directly though...

It may be too deep in compiler world, but any help on this would be much appreciated!

**Comment by evancz** [comment]
cc @JoeyEremondi

**Comment by TheSeamau5** [comment]
Hmmm... I'm unfortunately not so well versed in compiler theory and the Elm compiler in general. But, I'm wondering, is it possible for you to add this piece of code as a unit test and go back commit by commit until you find it?


Also, it seems that this problem affects all "typeclassy" things. By this I mean that "comparable" is also affected:

```elm
import Graphics.Element exposing (show)

x = [] < 1

main = show x
```

in the warnings release yields:

```
True
```

when it currently yields:

```
Type mismatch between the following types on line 10, column 5 to 11:

       List comparable

       number

   Looks like something besides an Int or Float is being used as a number.
   It is related to the following expression:

       [] < 1

```

The "True" comes from Javascript's weirdness. Cuz, you know, the empty list is obviously less than 1. 

I don't know if it helps, but if I put anything in that empty list I get an error:

```
-- TYPE MISMATCH -------------------------------------------------------------- 

The right argument of (<) is causing a type mismatch.

2| 
3|     [2] < 1
4|           ^

To be more specific, as I infer all the types, I am seeing a conflict between
this type:

    List number

and this type:

    number

```

**Claim : I think this is caused by the fact that the typechecker assumes it's a "comparable" too soon.**

Here's evidence for this claim.

This code:

```elm
import Graphics.Element exposing (show)

y : List Int
y = []

x = y < 1

main = show x
```

yields this error: 

```
-- TYPE MISMATCH -------------------------------------------------------------- 

The right argument of (<) is causing a type mismatch.

5| 
6|     y < 1
7|         ^

To be more specific, as I infer all the types, I am seeing a conflict between
this type:

    List Int

and this type:

    number
```

But if you comment out the type annotation for "y", it'll run and return "True".


Furthermore, it is not due to the fact that the type parameter of the list was not "specialized" (as in, `List a`) because this yields an error.

```elm
import Graphics.Element exposing (show)

y : List a
y = []

x = y < 1

main = show x
```

yields:

```
-- TYPE MISMATCH -------------------------------------------------------------- 

The right argument of (<) is causing a type mismatch.

5| 
6|     y < 1
7|         ^

To be more specific, as I infer all the types, I am seeing a conflict between
this type:

    List comparable

and this type:

    number

```


Now, finally, here's what I think is the smoking gun:

```elm
import Graphics.Element exposing (show)

y : comparable
y = []

x = y < 1

main = show x
```

yields

```
True
```

As in, it compiles. It shouldn't.

**Comment by evancz** [comment]
This is good detective work! It seems like the only value that can sneak through is an empty list. Is this the case?

**Comment by mgold** [comment]
Nice detective work. Just so you know, you can run `git bisect` to find where a bug was introduced.

**Comment by TheSeamau5** [comment]
Thanks.

It looks like it. Although, it's worth pointing out that it doesn't just happen for the empty list alone. It even happens with tuples of the empty list.

```elm
import Graphics.Element exposing (show)

y = (1,2)

z = ([],[])

x = y < z

main = show x
```

yields:

```
False
```



By the way, I didn't know you added heterogeneous collections to Elm ;)

```elm
import Graphics.Element exposing (show)

x : List comparable
x = [1 , [], 2, []]


main = show x
```

yields:

```
[1,[],2,[]]
```


Or, even more hilarious:

```elm
import Graphics.Element exposing (show)

x : List comparable
x = [([],[]), ([],2), ("peekaboo", []), []]


main = show x
```

```
[([],[]),([],2),("peekaboo",[]),[]]
```


I tried instead using `Nothing` and all sorts of types and I don't get the error. It has to involve the empty list. It's fun, it's like the empty list is some kind of joker type or an any type. This is the weird thing, it only works on the empty list. I wonder if it's due to the fact that you're special casing lists in the compiler. Unlike the [`Maybe` type which seems to be defined in Elm](https://github.com/elm-lang/core/blob/master/src/Maybe.elm), the [`List` type is not](https://github.com/elm-lang/core/blob/master/src/List.elm). I wonder if that has anything to do with it.

**Comment by TheSeamau5** [comment]
Looks like it has nothing to do with typeclassy things. It's just the empty list that's confusing the typechecker.

Evidence:

```elm
import Graphics.Element exposing (show)

type Tree a = Empty | Node a (Tree a)

x = Node 3 (Node [] Empty)

main = show x
```


```
Node 3 (Node [] Empty)
```


Again, I don't know much about compilers. But, [it looks like you're special casing lists for some reason when previously you didn't.](https://github.com/elm-lang/elm-compiler/commit/37a568714d68617bc9022117c71f43e1c113d116)

**Comment by evancz** [comment]
This should be fixed on http://elm-lang.org:1234/try

Thanks for the great detective work!

**Comment by TheSeamau5** [comment]
No problem. I got lucky in finding the commit. :D  

Anyways, I'm super glad that got fixed.
