### ISSUE TITLE
Support where clauses

### ISSUE THREAD

**Issue by polux** [elm-lang/elm-compiler#938]
[Things not in Elm](http://elm-lang.org/learn/Syntax.elm#things-not-in-elm) specifies that Elm doesn't  *currently* support `where` clauses. That's the thing I'm missing the most from Haskell when programming in Elm. I've searched through the open and closed issues and couldn't find any that tracks this particular feature.

The word "currently" makes it sound like this might be supported one day. Is it something that you would indeed consider?

**Comment by jvoigtlaender** [comment]
Oh, you must have overlooked this: #621. Discussion ongoing between some of us.

**Comment by polux** [comment]
Thanks! It's probably the quotes around 'where' which mislead github's search feature.

Closing this bug then.
