### ISSUE TITLE
0.15->master regression in infinite type detection

### ISSUE THREAD

**Issue by mgold** [elm-lang/elm-compiler#939]
````elm
f (x::xs) = xs::x
````

This code (yay minimal examples) is detected as an infinite type in 0.15 but not in the editor on the special port. There, this code causes the server to send an empty response - presumably this code crashes the master branch compiler.

**Comment by TheSeamau5** [comment]
This code does it too
```elm
f x = x f
```

**Comment by mgold** [comment]
This one is still fine: `type alias Foo = {foo : Foo}`

So only some infinite types?

**Comment by TheSeamau5** [comment]
Maybe it has to do with type inference as opposed to just a unification bug.
