### ISSUE TITLE
Dicts can not be passed through ports

### ISSUE THREAD

**Issue by lachenmayer** [elm-lang/elm-compiler#940]
A JavaScript object (ie. `{"foo": 1, "bar": 53, "baz": 52}`) can sometimes contain arbitrary and/or dynamic keys, and can thus not be turned into a record.

JS objects should be accessible through a port of type `Dict String a`.

See motivation here https://groups.google.com/forum/#!topic/elm-discuss/hdOBmFaQq1E

**Comment by evancz** [comment]
Makes sense, thanks for the report!

I am collecting all issues like this in https://github.com/elm-lang/elm-plans/issues/17, so we can keep track of them all.

In the meantime you can have a `Json.Value` go through the port and use [`Json.Decode.dict`](http://package.elm-lang.org/packages/elm-lang/core/2.1.0/Json-Decode#dict) to extract things from it.
