### ISSUE TITLE
Reactor: Oops! Imports message had poor html

### ISSUE THREAD

**Issue by raould** [elm-lang/elm-compiler#943]
no address is visible -- it is *in*visible -- in the rendered error page. looking at the source it is because there is no "a href" around the "http" for the link.

Error in Hello.elm:
Error on line 29, column 29 to 45:
Could not find variable 'Window.dimensions.width'.
Looks like the prefix 'Window.dimensions' is not in scope. Is it spelled correctly?
Is it imported correctly?
You can read about how imports work at the following address:
<here is where it should be, but it doesn't render, because of poor html>

**Comment by mgold** [comment]
I actually just encountered this as well. The DOM contains:
````html
<http: elm-lang.org="" learn="" syntax.elm#modules=""><br><br></http:>
````

Minimal example to reproduce is `x = Foo`. It renders fine in the repl but not in the browser.

**Comment by Apanatshka** [comment]
So the actual issue is that the text isn't html-escaped before it's inserted.

**Comment by evancz** [comment]
It sounds like this is specific to `elm-reactor` so I am going to close it here. Should be migrated to https://github.com/elm-lang/elm-reactor/issues and it may be fixed thanks to @vilterp's ongoing work over there!
