### ISSUE TITLE
No data constructor for record types using another type constructor

### ISSUE THREAD

**Issue by thSoft** [elm-lang/elm-compiler#944]
[This snippet](http://share-elm.com/sprout/55665960e4b06aacf0e89f7f) should compile, as well as [this one](http://share-elm.com/sprout/556659d2e4b06aacf0e89f81).

**Comment by evancz** [comment]
That is not currently supported, it is only based on aliasing a record directly.

In the future we may have a different mechanism for creating these constructors. Either way, this issue is a known "we should find a better way" thing and should be getting some attention in the future.

**Comment by kommen** [comment]
I just ran into that as well. Any issue/mailing list thread where this is discussed?
