### ISSUE TITLE
elm-make: TODO:occurs (This expression is leading me to infer an infinite type)

### ISSUE THREAD

**Issue by avh4** [elm-lang/elm-compiler#947]
I have a case where I get this error
```
## ERRORS in Example.elm #######################################################

-- INFINITE TYPE --------------------------------------------------- Example.elm

This expression is leading me to infer an infinite type.

elm-make: TODO:occurs
```

Here is as much as I've been able to simplify the example:

```elm
-- Some stubs for things that can't be imported in try-elm
type alias Test = ()
type alias Investigator a = ()
suite : String -> List Test -> Test
suite _ _ = ()
test : String -> Test -> Test
test _ _ = ()
assertEqual : a -> a -> Test
assertEqual _ _ = ()
check : String -> (a -> b) -> (a -> b) -> Investigator a -> Test
check _ _ _ _ = ()

item what = { description = what, last = Nothing }

model = { active = item "initial" }

active m = m |> .active

foo what m = 
    let next = item what
    in
        { m | active <- { next | last <- Just m.active } }
bar what m = m -- { m | active <- item what }

forAll s list a b i = suite s <| List.map (\x -> check s (a x) (b x) i) list

all = suite "Main"
    [ model
        |> foo "foo"
        |> active
        |> .last
        |> Maybe.map .description
        |> assertEqual (Just "initial")
        |> test "foo remembers last"
    , forAll "changing active"
        [foo, bar]
        (\f s -> model |> f s |> active |> .description)
        (\f s -> s)
        ()
    ]
```

There are many seemingly-trivial changes I can make to the code that will cause it to successfully compile.

**Comment by evancz** [comment]
I just synced some changes that should fix this. What message do you get with the latest versions of things?

**Comment by avh4** [comment]
The situation is much improved, though I don't understand if it's entirely correct.  I now get at least an informative message for the case given above, but changing the `bar = ...` line slightly gives results that I don't understand, and one case leads the compiler to never finish:

With `bar what m = { m | active <- m.active }` or `bar what m = m` (the original example):
```
## ERRORS in Error.elm #########################################################

-- INFINITE TYPE ----------------------------------------------------- Error.elm

I am inferring weird self-referential type for 'foo'

19| foo what m = 
    ^^^
The bit of the type that is self-referential looks like this:

    a = { last : Maybe { a |   description : String } }

The cause is often that the usage of 'foo' is flipped around.

Maybe you are inserting a data structure into an element? Maybe you are giving
a function to an argument? Either way, something is probably backwards!

Try breaking the code related to 'foo' into smaller pieces.
Give each piece a name and try to write down its type.


Detected errors in 1 module.
```

With `bar what m = { m | active <- item what}`:  It compiles successfully.  (And I don't understand how this resolves when the former example doesn't, but maybe this is actually correct?)

With `bar what m = { m | somethingElse <- m.active }`: It maxes out all CPUs and never completes.

**Comment by avh4** [comment]
The example of `bar what m = { m | somethingElse <- m.active }` seems like it might be the same as #832 and #885.

The original case now has an informative error message, so I'm going to close this.

**Comment by evancz** [comment]
Yeah, I think it's another case of those two issues. Essentially, the `occurs` check is not happening aggressively enough. I tried to put it in a certain place to save some CPU cycles. cc @JoeyEremondi in case this is something that can be figured out this summer!

**Comment by JoeyEremondi** [comment]
Yeah, I was running into some interesting issues with this before. I'll
definitely take a look at it as I'm playing with the typechecker.

**Comment by evancz** [comment]
I'm taking my cues from [The Essence of ML Type Inference](http://gallium.inria.fr/~fpottier/publis/emlti-final.pdf) which says on page 439 that:

> As suggested above, it is almost the same for finite and regular tree models; only one rule, which implements the occurs check, must be removed in the latter case. In other words, the algorithm works with possibly cyclic data structures and does not rely in an essential way on the occurs check.

Which does not match our observations :) It seems that I am misinterpreting how the S-Check rule should be used. There appear to be some real performance concerns about running it too much (i.e. on every unification) but this paper specifies how you can use the occurs check less frequently and I must be misunderstanding it.
