### ISSUE TITLE
Constructors cannot be used as infix ops

### ISSUE THREAD

**Issue by jvoigtlaender** [elm-lang/elm-compiler#950]
In the presence of
```elm
type D = C Int Int

c = C
```
the expression ``3 `C` 4`` is rejected by the parser, whereas ``3 `c` 4`` is accepted.

I think this has to do with [this line](https://github.com/elm-lang/elm-compiler/blob/0.15/src/Parse/Helpers.hs#L110) and [this definition](https://github.com/elm-lang/elm-compiler/blob/0.15/src/Parse/Helpers.hs#L75-L78).

(In Haskell, ``3 `C` 4`` would be perfectly okay.)

**Comment by Heimdell** [comment]
Analoguos thing with the fields - except they can't be composed of operator symbols (#966).

**Comment by jvoigtlaender** [comment]
I don't think the two issues are related (in terms of what causes them).

**Comment by evancz** [comment]
Track in #1375

**Comment by lydell** [comment]
As far as I understand backticks are removed from the next version, so there's no need tracking this in #1375 any longer, is it? :)
