### ISSUE TITLE
Type checker error in case expressions

### ISSUE THREAD

**Issue by jvoigtlaender** [elm-lang/elm-compiler#952]
While this code:
```elm
import Html exposing (text)

x : Int
x = 5

main = case x of x -> text "hello"
```
may not be good style, it is surprising that it leads to a compiler error: `Could not find 'x' when solving type constraints.`

**Comment by evancz** [comment]
I am pretty surprised by this error. @jvoigtlaender and @mgold, are there any other cases that trigger this that could help pin down the root cause?

@manleyjster, do you think this is related to [your message](https://groups.google.com/d/msg/elm-dev/n7m305JIdy8/T6C9779LVbUJ) about canonical names on elm-dev?

**Comment by jvoigtlaender** [comment]
The error seems to depend on several factors coming together. At the least:
* a `case`-expression in which a pattern uses a variable that shadows the thing being pattern matched
* the thing being pattern matched on is a top-level entity

For example, this code has the problem:
```elm
import Graphics.Element exposing (show)

type D = D Int

d : D
d = D 5

main = case d of D d -> show "hello"
```
while this very similar code does not:
```elm
import Graphics.Element exposing (show)

type D = D Int

d : D
d = D 5

main = f d

f d = case d of D d -> show "hello"
```
The only real difference between these pieces of code is that in the second case the `d` in `case d of D d -> ...` is a local variable, not the top-level `d`. And in the original problem in the first comment here the `x` also was a top-level entity, then pattern-matched on directly, with a branch which contains `x` as a pattern variable.

So, some interaction of top-level entities with environment extension while type-checking the branches of a `case`?

**Comment by evancz** [comment]
Track in #1373

**Comment by jvoigtlaender** [comment]
This old error is not actually specific to `case` alone. New issue https://github.com/elm-lang/elm-compiler/issues/1425 appears to be the same error but in additional situations, including when no `case`, but lambda-binding, is present.

**Comment by jvoigtlaender** [comment]
Probably the reference to https://github.com/elm-lang/elm-compiler/issues/952 in the opening comment of meta-issue https://github.com/elm-lang/elm-compiler/issues/1373 should be replaced by https://github.com/elm-lang/elm-compiler/issues/1425.

**Comment by evancz** [comment]
Local shadowing will not be allowed with 0.19, so whatever is happening here, it will stop happening.

Thanks for the report!

**Comment by evancz** [comment]
Output of development build is:

```
-- SHADOWING ---------------------------------------------------------- temp.elm

The name `x` is first defined here:

5| x = 5
   ^
But then it is defined AGAIN over here:

7| main = case x of x -> text "hello"
                    ^
Think of a more helpful name for one of them and you should be all set!

Note: Linters advise against shadowing, so Elm makes “best practices” the
default. Read <https://elm-lang.org/hints/0.19.0/shadowing> for more details on
this choice.
```

So it is fixed one way or another!
