### ISSUE TITLE
Feature request: emit compiled JS to stdout

### ISSUE THREAD

**Issue by rtfeldman** [elm-lang/elm-compiler#961]
Right now it's a bit annoying to build Elm integrations because the compiler can only write to files. When we want the compiled JS to be immediately consumed elsewhere (e.g. by Sprockets or Node), we end up writing a temporary file, reading it in, and then deleting it afterwards.

It would be cleaner if we could instead just consume the output directly and send it along to the next process in the pipeline, without having to deal with a throwaway file along the way.

Something like an `--output-to-stdout` flag would be great!

**Comment by evancz** [comment]
It seems like [this](http://stackoverflow.com/a/7757228/2038647) could work for now, but I think this is a reasonable request.

**Comment by rtfeldman** [comment]
Hrm...like so? Doesn't seem to work.

```bash
$ elm-make --output >(echo) Test.elm 

Compiled 1 file                                                     
elm-make: /dev/fd/63: hClose: resource vanished (Broken pipe)
```

**Comment by mgold** [comment]
What if `elm-make --output=stdout` was supported?

**Comment by RGBboy** [comment]
This would be fantastic. I was just about to request the same thing. This feature would open up the doors to do more interesting things with the compiled source, similar to what browserify does with node modules.

One idea I had was to write a little node module that would transform the output to work within node.

**Comment by evancz** [comment]
This should be migrated to `elm-make`, but otherwise, it seems okay to me!

**Comment by adit-hotstar** [comment]
> It seems like [this](http://stackoverflow.com/a/7757228/2038647) could work for now, but I think this is a reasonable request.

That seems like a very reasonable thing to support. However, when I try it I get the following error.

```
This flag was given a bad value:

    --output=/dev/fd/12

I need a valid <output-file> value. For example:

    --output=elm.js
    --output=index.html
    --output=/dev/null
```

Is `/dev/null` the only device you support? Is it not all right for the file type to be a named pipe?

---

Anyway, I really don't understand the following reasoning.

> We decided offline not to go for this. Rough reasoning is: it's not worth it to make the command line interface so much fancier. It will hurt beginners and help experts, but experts can do what they need to do anyway.

How will adding an `--stdout` option hurt beginner experience?

**Comment by rlefevre** [comment]
Just accepting `/dev/stdout` in addition to `/dev/null` would do it at least on Linux:
```
$ elm make --output=/dev/stdout  src/Main.elm
```
For now, it returns:
```
This flag was given a bad value:

    --output=/dev/stdout

I need a valid <output-file> value. For example:

    --output=elm.js
    --output=index.html
    --output=/dev/null
```

A workround is to create a symbolic link to `/dev/stdout` ending by `.js`:
```
$ ln -s /dev/stdout stdout.js
$ $ elm make --output=stdout.js  src/Main.elm
```

**Comment by pravdomil** [comment]
Can we reopen the issue?
