### ISSUE TITLE
Parsing issue with record destructuring in case statement

### ISSUE THREAD

**Issue by Apanatshka** [elm-lang/elm-compiler#962]
As discussed on the mailing list: https://groups.google.com/d/topic/elm-discuss/w9fjpRwPZH4/discussion

Minimal example:

```
foo = case {x=1} of
  {x} -> x == 1
```

Expected behaviour: accepted as correct program. 
Actual behaviour: parse error on line of the record pattern `{x}`.

**Comment by mgold** [comment]
Wait, how would this work? You know at _compile-time_ whether the record has an _x_ field, and therefore it's always the first case. This seems like a loss of orthogonality, compared to let:
````elm
bar =
  let {x} = {x = 1}
  in x == 1
````

Case statements should be used for case analysis. If there's only one case, use another construct.

**Comment by Apanatshka** [comment]
See the discussion on the mailing list. Yes you can use a `let`, but pattern matching is usually associated with `case`. Not being able to match a simple pattern like a record in a `case` would be a strange gotcha.

**Comment by mgold** [comment]
I saw the discussion on the mailing list. I still think it's weird.

**Comment by Apanatshka** [comment]
Weirder than a syntax error like it is now?
I prefer a non-fragile syntax and warnings or something.

**Comment by mgold** [comment]
Maybe we should have a nice warning that says use a `let` instead?

**Comment by evancz** [comment]
This seems to be fine in master now. I suspect this is because I took out the curly brace syntax for `case` expressions, but I'm not certain. In any case,

> Expected behaviour: accepted as correct program.

is what happens now!
