### ISSUE TITLE
Make error messages more compact, remove blank lines

### ISSUE THREAD

**Issue by raould** [elm-lang/elm-compiler#963]
I appreciate the attempts to make the errors helpful!

I would like to suggest what I think would further improve the messages:

The blank lines don't really help, my $0.02 is that I would prefer not to have blank lines emitted. It just ends up making the error message too long. e.g. I like a big font and it is annoying that the message doesn't fit in the half-screen emacs buffer due to the blank lines. Removing them and it fits.

(Same goes for the repl.)

**Comment by Apanatshka** [comment]
This is a duplicate of #936.

**Comment by raould** [comment]
ok
