### ISSUE TITLE
Unexpected parse results using lambdas between infix operators

### ISSUE THREAD

**Issue by mindphaze** [elm-lang/elm-compiler#967]
The following code compiles but it does not get parsed as expected:
```elm
login model =
    Http.fromJson Decode.string 
        (Http.send Http.defaultSettings
            { verb = "POST"
            , headers = [("Content-Type", "application/json")]
            , url = loginUrl
            , body = Http.string ""
            })
    `andThen` \resp -> Signal.send actions.address (PostMessage "Thanks for logging in.")
    `onError` \err -> Signal.send actions.address (PostMessage "Something went wrong.")
```
What it actually gets parsed as is more like the following:
```elm
login model =
    Http.fromJson Decode.string 
        (Http.send Http.defaultSettings
            { verb = "POST"
            , headers = [("Content-Type", "application/json")]
            , url = loginUrl
            , body = Http.string ""
            })
    `andThen` (\resp -> Signal.send actions.address (PostMessage "Thanks for logging in.")
                        `onError` (\err -> Signal.send actions.address (PostMessage "Something went wrong.")))



```

**Comment by ThomasWeiser** [comment]
I think this is the intended behaviour.
See the section “More Chaining” in http://elm-lang.org/guide/reactivity:

      An anonymous function includes everything after the arrow

**Comment by mgold** [comment]
I always put parens around my lambdas, which would solve this.

**Comment by Apanatshka** [comment]
Sure, and the compiler used to not accept lambdas without parens around them. 
Now it does, which is nice, but we'll need to look into what behaviour is desired...

**Comment by mgold** [comment]
Sure, but would any change that fixes this also cause `f = \x -> x + 2` to become `f = (\x -> x) + 2` and type error?

**Comment by Apanatshka** [comment]
I think Haskell does it in a way that's different and more intuitive than Elm currently does. And Haskell accepts `f = \x -> x + 2` just fine :)
It's only a matter of requiring something following the `->` on a new line to be indented more than the line with the `\` to be considered part of the lambda body. Then the following two will be different:

```elm
login model =
    Http.fromJson Decode.string 
        (Http.send Http.defaultSettings
            { verb = "POST"
            , headers = [("Content-Type", "application/json")]
            , url = loginUrl
            , body = Http.string ""
            })
    `andThen` \resp -> Signal.send actions.address (PostMessage "Thanks for logging in.")
        `onError` \err -> Signal.send actions.address (PostMessage "Something went wrong.")
```

This would be an `andThen` of the `Http.fromJson` and (the `onError` of the first `Signal.send` and the `\err -> ...`). 

```elm
login model =
    Http.fromJson Decode.string 
        (Http.send Http.defaultSettings
            { verb = "POST"
            , headers = [("Content-Type", "application/json")]
            , url = loginUrl
            , body = Http.string ""
            })
    `andThen` \resp -> Signal.send actions.address (PostMessage "Thanks for logging in.")
    `onError` \err -> Signal.send actions.address (PostMessage "Something went wrong.")
```

But this would be the `onError` of (the `andThen` of the `Http.fromJson` and `\resp -> ...`) and the `\err -> ...`

**Comment by jvoigtlaender** [comment]
I think the sane thing to do here would be to follow what Haskell does. They've been programming with lambdas a long time already.

Jeff [indicated on the mailing list](https://groups.google.com/d/msg/elm-discuss/3ZYgfqPE0Vw/vqWfhBw7UqsJ) that there is some difference in parsing between Haskell and Elm here. But it is not clear enough to me from that thread what the exact difference is. Can we see a simple example of the same lambda-involving-but-parentheses-less code currently being parsed differently by Haskell and Elm? As it stands, I'm not yet convinced there is such code.

**Comment by jvoigtlaender** [comment]
Ah, Jeff, I didn't see your comment before posting mine. Are you sure your interpretation of what Haskell does is correct? How did you test that? I doubt that Haskell does anything like requiring "a new line to be indented more than the line with the \ to be considered part of the lambda body".

**Comment by Apanatshka** [comment]
I have no official source that that's the rule.. I just messed around in ghci with `set +m` and `:{`/`:}` to get multi-line commands. But now as I try to reproduce what I did on another computer, it seems to give me different results. So I don't know what's going on anymore :neutral_face:

**Comment by evancz** [comment]
My understanding is that OCaml and Haskell (and any other ML-family language I have seen) do it the same as Elm. @Apanatshka, if you can share a valid Haskell file that demonstrates otherwise, we can talk about that. If not, let's close this issue.

**Comment by mindphaze** [comment]
Thanks @ThomasWeiser, I had seen that before but didn't make the connection that that was what was happening.

**Comment by Apanatshka** [comment]
@evancz I don't think I'm going to find an example, I think I just messed up when I first tried to find something different in Haskell. 
Ah, I just found [in the Haskell 98 Report](https://www.haskell.org/onlinereport/syntax-iso.html) that let and lambda body adhered to the "maximal munch" (longest match) rule. So **I was wrong**, Elm does things like Haskell does.

Can we please get a warning in the docs of `onError` though? This will be a gotcha of the lambda style of programming.

**Comment by evancz** [comment]
Yeah, for sure, I have been bitten by the `onError` thing as well. I have actually considered removing that function in favor of something like this:

```elm
recoverWith : (e -> Task e' a) -> Task e a -> Task e' a
```

Such that it does not follow the same pattern and you have to do it first. This way you'd just not get yourself into this situation. Perhaps that'll end up being better?

**Comment by Apanatshka** [comment]
That sounds like a good idea. Easiest thing would be to just add it, but you can also make a breaking change and replace `onError` with it.
