### ISSUE TITLE
Proposal: recursive record punning

### ISSUE THREAD

**Issue by Heimdell** [elm-lang/elm-compiler#969]
For now, if I have

```elm
type alias Game = { player: Point, level: Level }
type alias Point = { x: Int, y: Int }
```
and I do 
```elm
drawGame {{x, y}, level} = show "p" 
```
I get an error
```
I am looking for one of the following things:

    a lower case name
    whitespace
```
but if I do 
```elm
drawGame {player, level} = show "p" 
```
it compiles just fine.

I propose allowing of the 
```elm
drawGame {{x, y}, level} = show "p" 
```
form. There should be no ambiguility in that.

**Comment by TheSeamau5** [comment]
Question:

Suppose you have:

```elm
type alias Entity = 
   { position : { x : Float, y : Float }
   , velocity : { x : Float , y : Float }
   }
```

and you have a function like 

```elm
drawEntity {{x,y}} = 
   circle 20
   |> filled red
   |> move (x,y)
```

What would `x` and `y` be? The position x's and y's or the velocity x's and y's?

**Comment by Heimdell** [comment]
You are right.

**Comment by Apanatshka** [comment]
There's still an unambiguous way to introduce this by reusing the `as` pattern:

```elm
drawGame {{x, y} as player, level} = show "p" 
```

```elm
drawEntity {{x,y} as position} = 
   circle 20
   |> filled red
   |> move (x,y)
```

But then it's not short and sweet any more :confused:

**Comment by karldray** [comment]
Or it could mirror record creation syntax:

drawEntity {position={x,y}} = ...

**Comment by TheSeamau5** [comment]
I had thought of this before, but on further reflection it sounds like an anti-pattern. It discourages the use of the dot-notation, which I think makes things more legible.

```elm
drawEntity {{x,y} as position} = 
   circle 20
   |> filled red
   |> move (x,y)
```

vs.

```elm
drawEntity {position} = 
   circle 20
   |> filled red
   |> move (position.x, position.y)
```

or even better

```elm
drawEntity entity = 
   circle 20
   |> filled red
   |> move (entity.position.x, entity.position.y)
```
