### ISSUE TITLE
Simple error reports aren't sent as json with the "report=json" flag

### ISSUE THREAD

**Issue by ajhager** [elm-lang/elm-compiler#971]
The program below is one of a handful of errors that get passed straight through even when providing "--report=json" to elm-make.

```elm
module Main where

import Html Fexposing (..)

main : Html
main = text "Test"
```

**Comment by evancz** [comment]
This is actually an elm-make issue. elm-make needs to parse the imports to crawl all the necessary modules, so it does that before the real compilation phase. Currently, if it fails, it kind of bails out I guess.

Do you mind reopening this on that repo?

**Comment by ajhager** [comment]
Sure. cc elm-lang/elm-make#26
