### ISSUE TITLE
Proposal: Commas Work Like Semicolons

### ISSUE THREAD

**Issue by rtfeldman** [elm-lang/elm-compiler#979]
This is based on @Apanatshka's [comment on the Optional Commas proposal](https://github.com/elm-lang/elm-compiler/issues/978#issuecomment-118437011). It essentially says that commas in Elm should work like semicolons do in other languages, such as in Ruby or in Haskell's `do` notation—that is, they are used as a separator only in single-line cases, and in multiline cases newlines are the separator instead. This proposal is simpler but less backwards-compatible than optional commas.

Here is TodoMVC with and without the proposed change:

[Current TodoMVC](https://gist.github.com/rtfeldman/4682d081daab74ec185f)
[TodoMVC with proposed change](https://gist.github.com/rtfeldman/26fe87e2908e03e2322c)

## Proposed Implementation

**1.** Multiline terms are delimited by newlines **instead of** commas. This is a breaking change.

Examples:

```elm
-- equivalent to:
-- { x = 1, y = 5 }
{
  x = 1
  y = 5
}

-- equivalent to:
-- [label [class "login-field"] [text "username:"], input [name "username"] [], button [] [text "Submit"]]
[
  label [class "login-field"] [text "username:"]
  input [name "username"] []
  button [] [text "Submit"]
]

-- equivalent to:
-- (x, y, z)
(
  x
  y
  z
)

-- equivalent to:
-- type alias Bounds = { width : Int, height : Int }
type alias Bounds = {
  width : Int
  height : Int
}

-- equivalent to:
-- module Foo (bar, baz, qux) where
module Foo (
    bar
    baz
    qux
  ) where

-- equivalent to { point | x <- point.x + 1, y <- point.y + 1 }
{ point | x <- point.x + 1
          y <- point.y + 1 }
```

**2.** Commas become delimiters for single-line terms only.

Comma-delimited terms that begin and end on a single line work as they currently do. Examples:

```elm
[firstThing, secondThing, thirdThing]

{ x = 1, y = 5 }

(x, y, z)

type alias Bounds = { width : Int, height : Int }

module Foo (bar, baz, qux) where
```

**3.** To remove ambiguity, function application across multiple lines now requires indentation. This is a breaking change.

```elm
-- still compiles
foo 1 2 3

-- still compiles
foo
  1 2 3

-- no longer compiles
foo
1 2 3
```

**4.** The preceding rule implies that all elements in a multiline term must be at the same indentation level.

For example:

```elm
-- still compiles
[
  label [class "login-field"] [text "username:"]
  input [name "username"] []
  button [] [text "Submit"]
]

-- does not compile, because this is attempting to pass 3 extra arguments to `input`
-- (namely `button`, `[]`, and `[text "Submit"]`)
[
  label [class "login-field"] [text "username:"]
  input [name "username"] []
    button [] [text "Submit"]
]

-- compiles to the equivalent of (3, 4, 5)
(
  3
  4
  5
)

-- does not compile, because this is attempting to call 3 as if it were a function,
-- passing 4 as an argument. 
(
  3
    4
  5
)
```

**5.** Commas may not be used to delimit multiline terms.

```elm
-- compiles
[foo, bar, baz]

-- compiles
[
  foo
  bar
  baz
]

-- does not compile
[
  foo, bar
  baz
]
```

## Motivation
To avoid duplication, please see the original [Optional Commas proposal](https://github.com/elm-lang/elm-compiler/issues/978) for motivation. All the same motivating reasons apply here as well.

**Comment by mgold** [comment]
I like this proposal a lot better than the previous one, since it means we can still write `[1,3,5]` one-liners. Would the same approach work for union types? Like so:

```elm
type myUnion = Foo | Bar
    Qux Int Int String
    Norb Float String Char
````

As has been said, I like the pipe for union types as evocative of EBNF or an "or" (and the similarity between bitwise or and set union). I really dislike it for multiway if though, and would love to see that dropped.

**Comment by Apanatshka** [comment]
This is definitely better than the previous one. But these examples still make me uncomfortable:

```
-- compiles to the equivalent of (3, 4, 5)
(
  3
  4
  5
)

-- does not compile, because this is attempting to call 3 as if it were a function,
-- passing 4 as an argument. 
(
  3
    4
  5
)
```

1. The tuple like that looks very weird :pensive: I'm particularly uncomfortable with this because you usually use round brackets for grouping of expressions. With commas it's clear that it's a tuple instead of a grouping for priority of expressions. I really don't like this :worried: 
2. I can imagine names instead of numbers which would make the second example be correct. And it looks like you can make mistakes there as easily as in CoffeeScript :disappointed: The type-system will help you out is most cases I guess. But I remember making indentation errors in Python that left me with hard to track down bugs. If this proposal opens the door for any of those, I'm against :neutral_face:

**Comment by rtfeldman** [comment]
> I'm particularly uncomfortable with this because you usually use round brackets for grouping of expressions. With commas it's clear that it's a tuple instead of a grouping for priority of expressions.

Hm...I don't follow. When you group expressions with parentheses in Elm, they are always necessarily nested, yeah? Like, you would never have something like this:

```elm
(
  expr1
  expr2
  expr3
)
```

I guess I don't follow what the code would look like that becomes confused with tuples here. Did you have a particular example in mind?

> The tuple like that looks very weird

Multiline tuples look weird in general...I mentioned it as a clarification for what would happen if you wanted to do one, but there's a reason you don't see them in the wild very often. :smile: 

Actually I can't personally think of a time I've ever seen one, regardless of comma styles.

> I can imagine names instead of numbers which would make the second example be correct.

That's true of all function application in Elm, not just this proposal. :wink: 

Example:

```elm
--compiles
foo bar baz

-- does not compile
3 4 5
```

**Comment by rtfeldman** [comment]
> I remember making indentation errors in Python that left me with hard to track down bugs.

This cuts both ways though. I spend **much** more time tracking down syntax bugs in Elm than I do in CoffeeScript, because the latter is much friendlier to rearranging code.

Specifically, very often I want to move a line of rendering code from one place to another. When I do, I can’t just cut/paste the relevant lines of code; instead, I have to cut/paste and then fix commas. Whenever I forget to fix commas, or when I accidentally fix them incorrectly, I lose even more time because the resulting error isn’t “you forgot a comma,” but rather something that will several minutes later cause me to smack my forehead and add a comma.

This isn't just me either. When I did an Elm workshop (20ish people in attendance) at LambdaConf, when someone couldn't get something to compile, the second most common solution was "you need to add a comma." (The most common solution was "restart elm-reactor" but that's obviously unrelated here.)

**Comment by rtfeldman** [comment]
Put another way: my experience has been that the UX of reading and editing a language with newlines-over-commas syntax is nicer than the UX of reading and editing a language with mandatory commas. :smiley: 

Also worth noting that the only hard-to-track-down bugs I've ever gotten were around long conditionals...and I can't recall any that would have bitten me if (1) each conditional required an `else`, (2) each conditional were exactly one expression instead of arbitrarily many statements, and espeically (3) I had a type-checker that told me when my conditional branches were returning different types (yeah 0.15.1! :smile_cat: )

So while I completely understand why that Pythonic experience would give you pause, it's definitely something I've considered and do not think is a cause for concern in Elm's case.

**Comment by Apanatshka** [comment]
You argue for this change convincingly. I guess I'm being too conservative, but I'm not completely convinced yet. Let's talk it over on Wednesday :)

**Comment by rtfeldman** [comment]
:+1: Sounds good to me! :smiley:

**Comment by zeckalpha** [comment]
I think this would add confusion for beginners, particularly those already getting used to the lack of parentheses in function calls. Also, I would imagine this would make for some confusing error messages, particularly with regard to the difference between:

~~~
(
  expr1
  expr2
  expr3
)
~~~

And:

~~~
(
  expr1
    expr2
    expr3
)
~~~

**Comment by rtfeldman** [comment]
I think the massive popularity of CoffeeScript (it even ships by default with Rails!) is an important point to remember. It suggests that neither paren-free function application nor comma-free delimiting (CoffeeScript has both, and actually takes significant whitespace substantially further) are too much for a mainstream JS audience.

Also, keep in mind that you're going to get a surprising compiler error no matter what if you mistakenly write this:

```elm
(
  expr1
  expr2
  expr3
)
```

Today you'll either get a type error saying you passed too many arguments to whatever function kicks off `expr1`, or a syntax error saying `unexpected expr2` if `expr1` is something like an `if` expression instead of a function call.

In the world of this proposal, instead you get a type mismatch between Tuple3 and whatever you thought you'd be getting - presumably the type of `expr3`.

Relevantly, the latter scenario is more conducive to a helpful compiler error message ("Did you realize you were creating a Tuple here?") because it will consistently be a type error regarding a Tuple rather than sometimes a type error and sometimes a syntax error.

**Comment by zeckalpha** [comment]
CoffeeScript doesn't curry by default, however, so function application without parentheses looks like `f a, b`. The example they give on their website: `console.log sys.inspect object` -> `console.log(sys.inspect(object));` would be more like `console.log(sys.inspect, object);` in Elm.

**Comment by rtfeldman** [comment]
Sure, but `foo bar baz` is a perfectly valid thing to write in both Elm and CoffeeScript; they just do different things. :smiley:

**Comment by mgold** [comment]
I like `[foo bar]` as an example of how Elm treats whitespace as function application, and Clojure treats it as  a delimiter. That snippet can also mean function application in Ruby, if `self.foo` is defined and takes one argument.

**Comment by rehno-lindeque** [comment]
There doesn't appear to be any examples of record update syntax?

**Comment by mgold** [comment]
[Here](http://elm-lang.org/docs/syntax#records)?

**Comment by rtfeldman** [comment]
@rehno-lindeque Added an example to the end of the first code snippet, thanks!

**Comment by zeckalpha** [comment]
Richard Feldman writes:

> Sure, but `foo bar baz` is a perfectly valid thing to write in both Elm and CoffeeScript; they just do different things. :smiley:
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/elm-lang/elm-compiler/issues/979#issuecomment-119235577

I just wanted to point out that they do different things, so the
argument that mainstream language X does it, so we can, too, doesn't
quite hold.

--
Kyle Marek-Spartz

**Comment by rtfeldman** [comment]
But that's an argument against currying by default, not newlines-over-commas; it is already the case that `foo bar baz` works differently in Elm than it does in CoffeeScript.

In contrast, this proposal substitutes newlines for commas in very much the same way you can in CoffeeScript. The following code gives you an list of 3 items in either CoffeeScript or in this proposal:

```elm
[
  foo
  bar
  baz
]
```

(Technically an Array in CoffeeScript and a List in Elm, but otherwise they do the same thing.)

**Comment by rtfeldman** [comment]
To catch this thread up with a mailing list discussion, here is TodoMVC with and without the proposed change:

[Current TodoMVC](https://gist.github.com/rtfeldman/4682d081daab74ec185f)
[TodoMVC with proposed change](https://gist.github.com/rtfeldman/26fe87e2908e03e2322c)

**Comment by dnalot** [comment]
I can't see anything wrong with the new proposal and it drastically improves DSLs. I'm on board 👍

**Comment by Apanatshka** [comment]
Just FYI: I [forked](https://gist.github.com/Apanatshka/0736d8fc324ce8043a38) Richard's TodoMVC gist and wrote something in similar style but with operators instead of whitespace so it already works in Elm. You get stuff like:

```elm
( []
  :< foo
  :< bar
  :< baz
)
```

**Comment by dnalot** [comment]
When @rtfeldman proposed this I asked myself, why bother? I asked him, why not trailing commas; to which he asked, why not leading commas. In either case they'd be janky if not mandatory, leading me to wonder if they present semantic value. Commas make it visually unambiguous that we're not applying functions. This was actually a [concrete issue](https://github.com/gkz/LiveScript/issues/50) using [LiveScript](http://livescript.net) (which I enjoyed even if janky). Except with Elm, square brackets conspicuously do that.

CoffeeScript is the most prominent case of significant whitespace and optional commas I'm aware of. I strongly prefer it to Python in experience. I googled a thoughtful [syntax critique](http://ceronman.com/2012/09/17/coffeescript-less-typing-bad-readability/), but none of his criticisms applied to Elm.

What draws me most to this proposal is that Haskell's record syntax has always looked annoying to me, akin to double-colon type annotations. Reading an article [comparing rank-2 poly to type classes](http://www.haskellforall.com/2012/05/scrap-your-type-classes.html), I realized what makes type classes _appear_ preferable is primarily lack of commas:
```haskell
-- using Elm whitespace conventions

-- rank-2 monad works more better
monad'Maybe :: MonadI Maybe
monad'Maybe = MonadI
    { _return = Just
    , _bind = \m f -> case m of
        Nothing -> Nothing
        Just x  -> f x
    }

-- type class monad looks more better
instance Monad Maybe where
    return = Just
    m >>= f = case m of
        Nothing -> Nothing
        Just x  -> f x
```
The reason I think syntax proposals are being expressed is because syntax is the surface API of a language. Elm is already awesome at balancing the beam between minimal, effective, and intuitive syntax. They're are perhaps more practical issues moving forward like asynchrony and tooling. But both open issues seem fundamentally motivated by code readability. Just my two cents in case Richard missed anything.

Enjoying learning from so many brilliant minds!

**Comment by evancz** [comment]
I talked with @rtfeldman offline about this.

I think https://github.com/elm-lang/elm-plans/issues/2 is a far less controversial way to accomplish the root goal of "copy code around easily in a style that is familiar". It even does a better job on the "style that is familiar" part :)

One thing I really don't want to do is "fight the comma wars". We have lots of battles to fight between types and immutability and managed effects, adding something like this to the list seems like a bad mistake. I personally quite like the leading comma stuff, but in the spirit of "don't fight the comma wars" I don't think it makes sense to be in the business of making people go that route.

@rtfeldman, okay to close this in favor of the trailing commas proposal?

**Comment by rtfeldman** [comment]
:+1:
