### ISSUE TITLE
Integer counting list comprehensions do not work backward

### ISSUE THREAD

**Issue by rhaps0dy** [elm-lang/elm-compiler#982]
Is this intended behavior, or is the full integer list comprehension not implemented yet?
In case this is intended, maybe it would be good to remove the base case.

For example, [1..5] works, but [5,4..1] does not, and neither does [1,4..16].

**Comment by evancz** [comment]
Cases like that are not supported for now. I wanted to keep the syntax relatively simple. I don't see this getting in to the next release or two, but it seems like a reasonable idea, so lets revisit this at a later time. At that time, lets also figure out exactly which languages have features like this and how it works in each of those settings and why.
