### ISSUE TITLE
Proposal: Deprecate Tuples

### ISSUE THREAD

**Issue by rtfeldman** [elm-lang/elm-compiler#986]
In the spirit of https://github.com/elm-lang/elm-compiler/issues/985, I'd like to make the case for deprecating and then removing tuples from Elm. The short version is this:

*Tuples introduce significant complexity and learning curve to the language, but contribute only minor and rare convenience over records.*

Drawbacks of tuples:
* They are not Google-friendly at all if you have a question about them and don't know what they're called (`"in elm how do you access the first thing in the parentheses"`)
* They contribute to Elm's alienness for JavaScripters; `foo (bar, baz)` looks more like familiar JS function application than `foo bar baz`, which is how you actually apply functions in Elm.
* They're less self-documenting than records
* They make it harder to visually parse what parentheses do. Both `foo (bar, baz)` and `foo (bar baz)` are perfectly reasonable things to write, but the existence of tuples mean they do wildly different things. Likewise, in type signatures, `String -> Foo -> Maybe (Bar, Baz)` compared to `String -> Foo -> Maybe (Bar Baz)` - the `,` is easy to miss and makes a tremendous difference.
* They contribute to less clear APIs. Consider how [`Dict.toList`](http://package.elm-lang.org/packages/elm-lang/core/2.1.0/Dict#toList) and [`Dict.fromList`](http://package.elm-lang.org/packages/elm-lang/core/2.1.0/Dict#fromList) could look if tuples did not exist and `Dict` used records instead:

```elm
type alias Entry comparable v = { key : comparable, value : v }

-- Instead of toList
toEntries : Dict comparable v -> List (Dict.Entry comparable v)

-- Instead of fromList
fromEntries : List (Dict.Entry comparable v) -> Dict comparable v
```

Instead of using `Dict.fromList (List.map2 (,) keys values)`
you would call `Dict.fromEntries (List.map2 Dict.Entry keys values)`, which seems significantly clearer.

Isn't this just a nicer API? If so, isn't it the API one would naturally write if tuples were not available?

What tuples offer that records do not:
* A "points-free-esque" way to avoid naming things
* It's a natural way to express `(x, y)` coordinates (although `{ x = x, y = y }` is hardly unclear)
* The `(,)` function, which is not general for records and instead requires a `type alias` (e.g. `Dict.Entry` over `(,)`) - arguably not a bad thing, though.

**Comment by Apanatshka** [comment]
:+1: I've thought these same things too. 

Two notes:

1. Although `zip : (List a, List b) -> List (a,b)` is fairly easy to replace by a specific record constructor and `map2`, `unzip : List (a,b) -> (List a, List b)` is not generally replaceable in a nice way. 
I usually use `unzip` after a `map` of a function that returns multiple things. That function would now have to create an ad-hoc record, preferably with nice field names, and then I'd need to `map` field getters twice. I'm not sure if that's too much overhead. 

2. The `curry`/`uncurry` functions will be lost :(

**Comment by mgold** [comment]
Whoa there, one change at a time.

I'm not sure tuples are too alien given the Python has them. And they do make some things really convenient. Although with record pattern matching, this is lessened at the call site.

Let's look at some examples from the standard library:
```elm
-- Json.Encode
object : List ( String, Value ) -> Value
object : List { key : String, value : Value } -> Value

--Json.Decode
keyValuePairs : Decoder a -> Decoder (List ( String, a ))
keyValuePairs : Decoder a -> Decoder (List { key : String, value : a })

-- Mouse
position : Signal ( Int, Int )
position : Signal {x : Int, y : Int}
```

Honestly, it's six of one, half dozen of the other.

**Comment by rtfeldman** [comment]
@dnalot and @evancz pointed out that in the absence of tuples, people will introduce custom infix operators to get the same conciseness.

That seems like a worse outcome than first-class tuple support, and this is definitely the consensus syntax for tuples if the language is going to support them first-class.

I'm convinced. I'll close this.

**Comment by AnthonyJacob** [comment]
Did you consider replacing tuple by `type Pair a b = Pair a b`?

**Comment by Erudition** [comment]
> @dnalot and @evancz pointed out that in the absence of tuples, people will introduce custom infix operators to get the same conciseness.

Well, that is no longer a relevant objection, as custom infix operators are no longer allowed.

Time to revisit this proposal?

**Comment by ShalokShalom** [comment]
As a suggestion: If you depreciate them, clearly explain to complete newcomers to programming, why and how naming record types in general. I often stumble above code, that uses very similar type names for their record fields and I have still zero ideas why we should use different ones in the first place.
