### ISSUE TITLE
Compiler error says undefined documentation when the value is not even defined

### ISSUE THREAD

**Issue by Apanatshka** [elm-lang/elm-compiler#988]
My [signal-extra library (version 5.1.1)](http://package.elm-lang.org/packages/Apanatshka/elm-signal-extra/5.1.1/) has `filterMap` mentioned in the documentations `@docs`. But it was dropped since the core `Signal` module now has it. I just forgot to remove the name in the `@docs`. The compiler pointed me to the problem, but the message is a slightly off. The documentation is undefined because the whole definition is missing :grinning:

**Comment by evancz** [comment]
Can you share the error that is produced? Perhaps with a minimal reproduction as a gist?

**Comment by mgold** [comment]
I can repro with:

```elm
module Test where

{-|
@docs thing
-}
```

The error says "SYNTAX PROBLEM" and "I ran into something unexpected when parsing your code!". Defining `thing` results in no errors. I think the issue is to have a better error message, "You declared docs for `thing` but didn't define it`, rather than a syntax error.

**Comment by Apanatshka** [comment]
@mgold, that's a different error.

@evancz sorry, forgot to paste that in:

```
-- UNDEFINED DOCUMENTATION ------------------------------ ./src/Signal/Extra.elm

Your module documentation includes `filterMap` which is not exported.

 2|>{-| Utility functions that aren't in the `Signal` module from
 3|>`elm-lang/core`. 
 4|>
 5|># Flipped fancy map
 6|>@docs (~>)
 7|>
 8|># Zipping and unzipping
 9|>For those too lazy to write a record or union type.  
10|>@docs zip, zip3, zip4, unzip, unzip3, unzip4
11|>
12|># Stateful
13|>@docs foldp', foldps, foldps', runBuffer, runBuffer', delayRound
14|>
15|># Switching
16|>@docs switchWhen,switchSample
17|>
18|># Filters
19|>@docs keepIf,keepWhen,sampleWhen,keepThen,keepWhenI,filter,filterMap
20|>
21|># Combining
22|>@docs fairMerge, combine, mapMany, applyMany
23|>-}

Is it misspelled? Should it be exported?
```

I guess the last part hints at that it may not be defined? I only saw that part just now. Having to scroll past the whole doc comment makes me inattentive. So there's two things here:

1. The compiler should be able to easily go the extra step and look for misspelled and undefined names. 
2. The whole doc comment is distracting and bloating the error message, making me (and people like me) miss the hints at the end. But I think that complaint is in another issue as well?

**Comment by evancz** [comment]
Can you move this to error-message-catalog?

I knew this error was too long when I implemented it, but it was unclear how to make it smaller and I knew only a small set of people would ever see it.

When you open the new issue, describe the problem and include a copy of the existing message in the root issue. Then in the comments of the issue, suggest concrete changes that can be made to the message to improve it. Essentially take the existing message and rewrite it how you want to see what would be a better way. Seems like it could be done as a PR once we get to that point.

**Comment by Apanatshka** [comment]
[Done](https://github.com/evancz/error-message-catalog/issues/20). Does that mean this issue should be closed?

**Comment by evancz** [comment]
Yeah, I think it makes sense to try to keep the issues here more for bugs and specific trackers for improvements.
