### ISSUE TITLE
Pure elm Task and Port runtime error.

### ISSUE THREAD

**Issue by Fresheyeball** [elm-lang/elm-compiler#989]
```elm
createKey : Signal (Task x ())
createKey = let
  create : Task x ()
  create = Signal.send (.address input) Create
  g : Bool -> Maybe (Task x ())
  g b = if b then Just create else Nothing
  in Signal.filterMap g create Keyboard.enter

port run : Signal (Task x ())
port run = createKey
```

Causes an error at runtime.

**Comment by mgold** [comment]
What's the rest of the program? I can't reproduce. Using the following and then the code provided.

```elm
import Task exposing (Task)
import Keyboard

type Key = Create
input = Signal.mailbox Create
```

**Comment by Fresheyeball** [comment]
https://github.com/fresheyeball/elm-students

**Comment by Fresheyeball** [comment]
Where you able to reproduce it from my repo?

**Comment by mgold** [comment]
Sorry haven't had the chance. Maybe if you got it down to one file?

**Comment by Fresheyeball** [comment]
So I've been trying to get this down to one file. And Ive learned that the error only occurs in the reactor, with debug.

**Comment by Fresheyeball** [comment]
Should I move this issue? Or is elm-compiler the right place?

**Comment by mgold** [comment]
Possibly, but if you can get the error down to one file that crashes the debugger, that may be useful.

**Comment by rtfeldman** [comment]
@vilterp - can you reproduce on the current version of elm-reactor you're working on?

**Comment by Fresheyeball** [comment]
I will get this fully reproduced asap

**Comment by Fresheyeball** [comment]
Ok, this reproduces easily:

```elm
module Main where

import Graphics.Element exposing (..)
import Signal exposing (..)
import Task exposing (..)
import Keyboard

type Input = Input

input : Mailbox Input
input =
  mailbox Input

createKey : Signal (Task x ())
createKey = let
  create : Task x ()
  create = Signal.send (.address input) Input
  in Signal.filterMap
    (\b -> if b then Just create else Nothing)
    create
    Keyboard.enter

port run : Signal (Task x ())
port run = createKey

main : Signal Element
main = show <~ input.signal
```

**Comment by evancz** [comment]
Awesome, thanks for crushing this down! Do you mind sharing this code snippet on elm-reactor so we can track it there?

I'd also be curious if the recent fix to tasks https://github.com/elm-lang/core/pull/304 helps.

**Comment by Fresheyeball** [comment]
Pardon my ignorance. But how do I share on elm reactor?

**Comment by mgold** [comment]
https://github.com/elm-lang/elm-reactor/issues/new

**Comment by Fresheyeball** [comment]
Done. https://github.com/elm-lang/elm-reactor/issues/137
