### ISSUE TITLE
Non-exhaustive pattern match in multi-way-if expression.

### ISSUE THREAD

**Issue by pdamoc** [elm-lang/elm-compiler#992]
This throws a **Runtime error**. It should probably be a compiler error. 
```elm
import Graphics.Element exposing (..)


crash x = if 
  | x == 1 -> 1 
  
  
main = show <| crash 3
```  
The issue is present in Elm Platform 0.15

**Comment by mgold** [comment]
There is new `if` syntax being discussed at elm-lang/elm-plans#3 and elm-lang/elm-plans#6. This would make patterns without an `else` either harder or impossible to write.

Actually verifying exhaustive pattern matching is hard (someone had a proof that is was NP-complete somewhere), even if it's confined to `case` statements. For example, the heuristic "if you do case on a union type, you either need every type or an underscore at the end" fails to catch
```elm
evil x =
    case x of
        Just 1 -> "It's one"
        Nothing -> "It's not defined"
```
This has a runtime error on `Just 2`. I'm fairly certain Standard ML does not allow pattern matching on numbers, which is a very handy thing to do in Elm, so it may have had an easier time proving exhaustiveness. Similarly, it's hard to determine that (using today's syntax)
```elm
if | key == 0 -> n+1
   | key < 0 -> n-1
   | key > 0 -> n
```
_is_ exhaustive.

You're welcome to keep the discussion going but it may be better suited for the issues I linked at the top.

**Comment by dnalot** [comment]
Just occurred to me pattern matching on numbers seems like an implicit guard. Maybe I'm wrong. In any case when equality is involved, perhaps we could check for `Just x'`.

**Comment by evancz** [comment]
I believe it is the halting problem to prove that: given set of conditions, one will definitely be true. You can do other things though :)

Between the upcoming detection of incomplete pattern matches and the potential for removing multi-way-ifs specifically because of this issue, I think it makes sense to close this for now as a known issue.

Thanks for the report!
