### ISSUE TITLE
Module docs expect an @docs declaration to be last

### ISSUE THREAD

**Issue by mgold** [elm-lang/elm-compiler#993]
From the [mailing list](https://groups.google.com/d/msg/elm-discuss/1RP56kcQ0xc/DMJRDnPEWM4J), a bug involving parsing module documentation. If any text follows the last `@docs` line, the compiler rejects the documentation, claiming it does not document functions that are in fact documented.

Minimal example to reproduce:
```elm
module WebAudio where

{-|
@docs AudioContext
THIS LINE CAUSES THE PROBLEM - remove it to see for yourself.
-}


{-| Some docs here.
-}
type AudioContext = AudioContext | DefaultContext
```
This will compile fine, until you list `"WebAudio"` as an exposed module in `elm-package.json`. Then you get this error:

```
## ERRORS in webaudio.elm ######################################################

-- MISSING DOCUMENTATION ------------------------------------------ webaudio.elm

Your module exports `AudioContext` but it is not in the module documentation.

3|>{-|
4|>@docs AudioContext
5|>THIS LINE CAUSES THE PROBLEM - remove it to see for yourself.
6|>-}

It needs to be listed in the module documentation.
Learn how at <http://package.elm-lang.org/help/documentation-format>
```

As you can see on line 4, `AudioContext` is indeed documented. Removing line 5, as claimed, causes a correct compilation. This strongly appears to be undesired behavior.

**Comment by evancz** [comment]
Probably a bug in [this code](https://github.com/elm-lang/elm-compiler/blob/master/src/Docs/Check.hs#L128-L145), seems like it could be a simple PR.

**Comment by mgold** [comment]
My Haskell isn't that great, but just from studying the code it appears to be correct. Someone else feel free to take it.

**Comment by dnalot** [comment]
We should enumerate the issues @evancz identifies as low-hanging fruit within [Elm Plans](https://github.com/elm-lang/elm-plans) for would-be contributors? Even gamify it by mentioning their closed issue #s in the release notes.

**Comment by mgold** [comment]
I'd be up for that.

**Comment by dnalot** [comment]
Rad. Piping in on the Roadmap is on my todo. I want to try re-export first.

**Comment by evancz** [comment]
Don't try re-export. Adding language features needs more review than fixing stuff like this.

**Comment by dnalot** [comment]
* try using union of unions to work around other Max's concern

**Comment by rehno-lindeque** [comment]
I would love to have this fix cherry-picked for Elm 0.15.1, I think I might be running into this issue while trying to update [Elm.Html.Shorthand](http://package.elm-lang.org/packages/circuithub/elm-html-shorthand/9.0.0/Html-Shorthand) at the moment

**Comment by evancz** [comment]
Can you work around it by moving things around a bit? Sounds like the docs can be shuffled to work?

**Comment by rehno-lindeque** [comment]
Actually, I quickly did the compile via Elm 15.0 instead, so that's ok! I can continue publishing it via 15.0 for now.
