### ISSUE TITLE
crash when field `package` goes through inbound port

### ISSUE THREAD

**Issue by JustusAdam** [elm-lang/elm-compiler#994]
Exact error message 

> undefined is not an object (evaluating '_v0.summary')
>
>
> Open the developer console for more details.

[Minimal code I could produce that would cause the error](https://github.com/JustusAdam/package-bug)

This only happens when the initial model came through a port.

If an equivalent model is defined in elm itself it works just fine (see repository)

I am not sure it has something to do with the field called 'package' but changing the name of the field to something else fixes the problem.

**Comment by evancz** [comment]
Is it fair to summarize this as "sending a record with field `package` through a port causes a crash"?

If so, can we get the example down smaller? Or can we refine the summary? Maybe the field must be in the outermost record, but it does not matter if it is in a subrecord? What does the relevant generated code look like?

**Comment by JustusAdam** [comment]
I have tested a little more:
- The data at package key does not need to be complex, aka a record, I tried it with a String and that didn't work either.
- The reason it crashes is that instead of returning whatever was at that package key it returns `undefined`. (Or at least that's what it prints if you print is)
- It is not limited to keys of the outer record, that same happens in sub records.

I've simplified the code for the example with the String at the package key in the `subrecords` branch.

**Comment by mgold** [comment]
So if I understand this correctly,
```elm
port doesNotWork : { package : Int }
port doesNotWork = { package = 5 }

port works : { packag : Int }
port works = { packag = 5 }
```

This implies that `package` should be added to this list of reserved words. If the misspelled `packag` doesn't work either, then the bug is completely different. What happens with this code?
```elm
port package : Int
port package = 5
```

**Comment by JustusAdam** [comment]
No @mgold, read the original code I submitted. All of these work. In pure Elm there's no problem at all with using `package` as a record field name.

The only instance where it doesn't work, is if the data itself is a JavaScript object and comes **through** a port. (Again, look at the original code). 

Aka

```elm
port works : { package : Int }
port works = { package = 5 }
```
works without fail

but 

```elm
port externalPort = { package : Int }
```
and
```javascript
Elm.fullscreen(Elm.ModuleName, { externalPort: { package: 3}});
```

**Comment by mgold** [comment]
Ah, sorry about that. For incoming ports, it works if you misspell it as `packag` or whatever?

**Comment by JustusAdam** [comment]
Yes.

**Comment by evancz** [comment]
Can we try to find out why JS is doing this? What browser are you using? Is it only a node.js thing? Is there some doc describing this behavior?

**Comment by JustusAdam** [comment]
Tested it with Firefox, Safari, Chrome and Phantomjs. All display the same behaviour.

**Comment by evancz** [comment]
Seems like we can merge this with #1010. In that case we built a list of known reserved words based on some JS docs. What is the documentation here so we can understand *why* package is reserved?

Once we find that, maybe we can merge with the other issue.

**Comment by JustusAdam** [comment]
Well, it is a slightly different issue since #1010 causes runtime crashes even when defined within Elm, whereas this particular issue only occurs if the object was instantiated in javascript directly.

**Comment by JustusAdam** [comment]
Also the object can be evaluated in JavaScript itself. (I tested this just now)

**Comment by evancz** [comment]
Is this still true in 0.17? If so, can we reopen with all the crucial information from the comments here consolidated in a clear way.
