### ISSUE TITLE
A more robust BuildFromSource strategy using sandbox sources

### ISSUE THREAD

**Issue by rehno-lindeque** [elm-lang/elm-compiler#995]
Currently `runhaskell BuildFromSource.hs 0.15.1` is failing due to a conflicting dependency with `elm-compiler`:

```
Resolving dependencies...
cabal: Could not resolve dependencies:
trying: elm-package-0.5.1 (user goal)
trying: elm-compiler-0.15.1/installed-138... (user goal)
next goal: aeson (user goal)
rejecting: aeson-0.8.1.1/installed-07f... (conflict: aeson =>
vector==0.11.0.0/installed-0e7..., elm-package => vector>=0.10 && <0.11)
rejecting: aeson-0.9.0.1, 0.9.0.0, 0.8.1.1, 0.8.1.0, 0.8.0.2, 0.7.0.6,
0.7.0.4, 0.6.2.1, 0.6.2.0, 0.6.1.0, 0.6.0.2, 0.6.0.1, 0.6.0.0, 0.5.0.0,
0.4.0.1, 0.4.0.0, 0.3.2.14, 0.3.2.13, 0.3.2.12, 0.3.2.11, 0.3.2.10, 0.3.2.9,
0.3.2.8, 0.3.2.7, 0.3.2.6, 0.3.2.5, 0.3.2.4, 0.3.2.3, 0.3.2.2, 0.3.2.1,
0.3.2.0, 0.3.1.1, 0.3.1.0, 0.3.0.0, 0.2.0.0, 0.1.0.0, 0.8.0.1, 0.8.0.0,
0.7.0.5, 0.7.0.3, 0.7.0.2, 0.7.0.1, 0.7.0.0 (conflict: elm-compiler =>
aeson==0.8.1.1/installed-07f...)
```

I'd like to propose a more robust alternative that gets out of cabal's way and lets the constraint solver do its job. This is how I fixed my build:

```bash
rm -rf .cabal-sandbox/
cabal sandbox init

# Add each of the sub-directories as a sandbox source
cabal sandbox add-source elm-compiler/ elm-make/ elm-repl/ elm-package/ elm-reactor/

# Install all of the packages together so that cabal can resolve transient dependencies
cabal install --bindir=../bin elm-compiler elm-make elm-repl elm-package elm-reactor
```

That's it, super simple! Would you accept a PR that does this? If the sandbox sources aren't desirable for some reason it's easy to remove them afterward:

```bash
cabal sandbox delete-source elm-compiler/ elm-make/ elm-repl/ elm-package/ elm-reactor/
```

**Comment by evancz** [comment]
Seems reasonable to me. I don't know about source directories like this, but if this means all the constraints get solved at once it seems good to me.

Are there any potential downsides to this? Like, if everything is a source directory, could we accidentally be building with modules from other repos?

**Comment by rehno-lindeque** [comment]
> Are there any potential downsides to this?

The only downside I can think of is that the sandbox-sources are sort of circular in a sense. This only matters if you're actively developing code and sharing the same sandbox for all the packages the same way that `BuildFromSource.hs` does. Then every package is a "sandbox source" for every other package and it detects when a dependency needs to be rebuilt... I've found it a tad bit confusing.

> Like, if everything is a source directory, could we accidentally be building with modules from other repos?

I'm not 100% sure what you mean by this I'm afraid: only the repos directly specified will be built from source. The constraint trick here is actually `cabal install elm-compiler elm-make elm-repl elm-package elm-reactor`, the sandbox sources trick is actually only so that building from master will work (technically the repos are not required at all, you can install into the sandbox directly from hackage!).

**Comment by evancz** [comment]
I think the next step is to open a PR against elm-platform that does this, otherwise I'm not sure I'll be able to get to it. I am trying this new thing where I am more aggressive about closing issues, so I am going to close this and see what happens!

**Comment by rehno-lindeque** [comment]
I have a nasty habit of forgetting about issues I opened :) I'll try my best to remember to send you one!
