### ISSUE TITLE
Comment {-| ... -} at top of file causes parser to fail

### ISSUE THREAD

**Issue by WillSewell** [elm-lang/elm-compiler#996]
In elm 0.15.1 try and compile Test.elm

```elm
{-| xyz -}
module Test where
f = 5
```
It will produce the error

```
I ran into something unexpected when parsing your code!

2| module Test where
         ^
I am looking for one of the following things:

    a value definition
```

Removing the pipe will work; i.e.

```elm
{- xyz -}
module Test where
f = 5
```

It is not an issue in Elm 0.15

**Comment by evancz** [comment]
Why are you putting a documentation comment above the `module` declaration? In Elm [they go below](http://package.elm-lang.org/help/documentation-format#documenting-a-module).

This might be a good candidate for https://github.com/evancz/error-message-catalog especially if there are other cases where this happens.

**Comment by WillSewell** [comment]
I see. I will switch them over. Thanks.

I had them in there since elm 0.14 and must have assumed that was the correct location to put them. On upgrading to 15.1 I did find the error messages rather misleading.

**Comment by evancz** [comment]
I'm gonna close this one because there are no immediate action items we can track. Def report this on error message catalog though, this is a really confusing message considering the problem!
